src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cred_Cycle__c</fullName>
        <label>Cred Cycle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <externalId>true</externalId>
        <label>Prov ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Provider_Identification__c.object
<CustomObject>
    <description>Provider Identification Object contains the Issued Identification types and numbers of the provider like License,NPI, Medicare etc</description>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Issu_Ident_Nmbr__c</fullName>
        <externalId>true</externalId>
        <label>Identification Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_PI_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Identification</relationshipLabel>
        <relationshipName>Provider_Identification</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Identification</label>
    <nameField>
        <displayFormat>PI-{0}</displayFormat>
        <label>Provider Identification Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Identification</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Provider_Tax_Id__c.object
<CustomObject>
    <description>Provider Tax Identification Object  shows how and where billing is done.</description>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Prov_Name_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Tax Identifications</relationshipLabel>
        <relationshipName>Provider_Tax_Identifications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider Tax Identification</label>
    <nameField>
        <displayFormat>PTI-{0}</displayFormat>
        <label>Prov Tax Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Tax Identifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ETL_Report_Config_Data__mdt.object
<CustomObject>
    <description>Used to strore the config data which is used to send the report when ETL Load the data in the MCC Data Object</description>
    <fields>
        <fullName>Active_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>when the check box is checked we send out the email to the particular address</description>
        <label>Active Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Destination_Org__c</fullName>
        <description>Used to store the Origination URL</description>
        <label>Destination_Org</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <description>Used to capture the email Address</description>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <description>Used to store the File Type</description>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onboarding Cred Mass Status Update</fullName>
                    <default>true</default>
                    <label>Onboarding Cred Mass Status Update</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <description>Used to store the plan ID</description>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                    <default>true</default>
                    <label>IL1</label>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Accounts__c</fullName>
        <description>Number of accounts where provder id is not null and needs to exclude this year, the code in ETLReportingNotification will sum up the values this year values and others</description>
        <label>Total Accounts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ETL Report Config Data</label>
    <pluralLabel>ETL Report Config Datas</pluralLabel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>MCC_Case_Origin__c</fullName>
        <label>MCC Case Origin</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/MCC_Data_Object__c.object
<CustomObject>
    <description>Intermediate object for Mass Case Creation and Death File.</description>
    <fields>
        <fullName>Cred_Cycle__c</fullName>
        <label>Cred Cycle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Count__c</fullName>
        <description>This field will hold the count the no rows processed within the mass file uploads ( Tx Recruitment, Il Roaster , Mass case closure and mass Cred status update)</description>
        <label>File Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MCC_File_Id__c</fullName>
        <label>File Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Type__c</fullName>
        <label>File Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Load_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Load Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MCC_Plan_ID__c</fullName>
        <description>For all loads</description>
        <label>Plan ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Prov_ID__c</fullName>
        <description>For Death and TX Data</description>
        <label>Provider ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Mass Case Creation Record</label>
    <nameField>
        <displayFormat>MCC-{0000}</displayFormat>
        <label>MCC Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Case Creation Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MassCreationDataObjectQuery.cls
global class MassCreationDataObjectQuery {
    
    
    /*
     * Author :Ashok N
     * Date : 12/23/2018
     * Business Purpouse : To query the case records to get the Plan ID
     */
  public Map<Id,Case> getCaseQueryRecord(set<Id> SetCaseId) 
  {
      Map<Id,Case> Map_CaseQuery=new Map<Id,Case>([Select Id,CaseNumber,status,Plan_ID__c ,ParentId,MCC_Record_Name__c,Project_Number__c,Grouping_ID__c,Comments from case where 
                                                   ID IN :SetCaseId]);
      return Map_CaseQuery;
  }
    
  /*
     * Author :Ashok N
     * Date : 12/23/2018
     * Business Purpouse : To query the case records to get the Plan ID
     */
  public List<Case> getlistOfCaseQueryRecord(List<string> listCaseNum) 
  {
      List<Case> listCaseQuery=new list<Case>([Select Id,CaseNumber,status,Plan_ID__c ,ParentId,MCC_Record_Name__c,Project_Number__c,Grouping_ID__c,Comments from case where 
                                                   CaseNumber IN :listCaseNum]);
      return listCaseQuery;
  }
    
    /*
     * Author :Ashok N
     * Date : 12/23/2018
     * Business Purpouse : To query the case records to get the Plan ID
     */
  public List<Case> getlistOfCaseQueryRecords(List<Id> listCaseId) 
  {
      List<Case> listCaseQuery=new list<Case>([Select Id,CaseNumber,status,Plan_ID__c ,ParentId,MCC_Record_Name__c,Project_Number__c,Grouping_ID__c,Comments from case where 
                                                   Id IN :listCaseId]);
      return listCaseQuery;
  }
    
    
    
    /*
     * Author :Ashok N
     * Date : 1/14/2019
     * Business Purpouse : To query the caseID from the caseNumber 
     */
  public Map<Id,Case> getCaseQueryRecordID(set<String> SetCaseNumber) 
  {
      Map<Id,Case> Map_CaseQuery=new Map<Id,Case>([Select Id,CaseNumber,status,Plan_ID__c ,ParentId,MCC_Record_Name__c,Project_Number__c,Grouping_ID__c,Comments from case where 
                                                   caseNumber IN :SetCaseNumber]);
      return Map_CaseQuery;
  }
    
    
    /*
     * Author :Ashok N
     * Date : 1/29/2019
     * Business Purpouse : To query the caseID from the caseNumber 
     */
  public Map<Id,Case> getCaseQueryCredCycle(set<Id> SetCaseID) 
  {
      Map<Id,Case> Map_CaseQuery=new Map<Id,Case>([Select Id,CaseNumber,status,Plan_ID__c ,ParentId,MCC_Record_Name__c,Project_Number__c,Grouping_ID__c,Comments from case where 
                                                   ID IN :SetCaseId AND Cred_Cycle__c='I']);
      return Map_CaseQuery;
  }
    
    
  /*
   * 
   */
    
    public Map<Id,MCC_Data_Object__c> getMCCDataObject(Set<ID> Set_MCCRecordId)
    {
        Map<Id,MCC_Data_Object__c> Map_MCCDataObjectQuery=new Map<Id,MCC_Data_Object__c>([select Id,MCC_File_Type__c,MCC_File_Id__c,
                                                                                          MCC_Load_Status__c,MCC_Prov_ID__c,File_Count__c,
                                                                                          Name,MCC_Plan_ID__c
                                                                                          from MCC_Data_Object__c 
                                                                                          where Id IN :Set_MCCRecordId]);
       return Map_MCCDataObjectQuery;
    }
    
    /*
     * 
     */
    
    public Map<Id,Group> getGroupQuery(String Queue ,String DeveloperName, Set<String> AssingeId)
    {
        Map<Id,Group> Map_GroupQuery= new Map<Id,Group>([SELECT Id, Name,developerName FROM Group WHERE type =:Queue 
                                                         and (developerName =:DeveloperName OR NAME IN :AssingeId )]);
        return Map_GroupQuery;
    }
    
    /*
     * 
     * 
     */
    public Map<Id,Case> getCaseProjectNumber(Set<String> ProjectNumber)
    {
        Map<Id,case> getCaseProjectNumber= new Map<Id,Case>([SELECT Id, Project_Number__c,ParentId FROM CASE 
                                                             where Project_Number__c IN :ProjectNumber AND IsClosed !=true ]);
        return getCaseProjectNumber;
    }
    /*
     * 
     * Author :U393129
     * Date : 12/26/2018
     * Business Purpouse : To get the recordType When we insert the process the records to MCC_Data_object
     * Ver : 1.0  
*/
     
    
    public Map<Id,RecordType> getRecordType(String SobjectType)
    {
      Map<Id,RecordType> RecordTypeQuery = new Map<Id,RecordType>([Select Id,developerName,Name,sobjectType from RecordType where
                                                                   SobjectType=:SobjectType ]);
      return RecordTypeQuery;
    }
    
 
    
/*
     * 
     * Author :U393129
     * Date : 12/26/2018
     * Business Purpouse : To Query the records from CM_Provider_Tax_Id
     * Ver : 1.0  
*/
    
    public Map<id,CM_Provider_Tax_Id__c> getCM_ProviderTaxId(Set<String> TaxIdSet)
    {
        Map<Id, CM_Provider_Tax_Id__c> Map_CM_ProviderTaxIDQuery=new Map<Id,CM_Provider_Tax_Id__c>([select id, CM_PTI_Prov_Name_From__c,  CM_PTI_Tax_Id__c from CM_Provider_Tax_Id__c where CM_PTI_Tax_Id__c IN :TaxIdSet ]);
        return Map_CM_ProviderTaxIDQuery;
    }
    
    
    /*
     * 
     * Author :U393129
     * Date : 12/26/2018
     * Business Purpouse : To Query the records from CM_Provider_Tax_Id
     * Ver : 1.0  
*/
    
    public Map<id,CM_Provider_Identification__c> getCMProviderIdentification(Set<String> NPIIdSet)
    {
        Map<Id, CM_Provider_Identification__c> Map_ProviderIdentification=new Map<Id,CM_Provider_Identification__c>([select id, CM_PI_Prov__c, CM_Issu_Ident_Nmbr__c from CM_Provider_Identification__c where  CM_Issu_Ident_Nmbr__c In: NPIIdSet ]);
        return Map_ProviderIdentification;
    }
    
    
    /*
    * 
    * Author :U393129
    * Date : 12/28/2018
    * Business Purpouse : To Query the Account records by using the Prov_ID__c
    * Ver : 1.0  
    */
    
    public Map<id,Account> getAccount(Set<String> SetProviderID)
    {
        Map<Id, Account> Map_Account=new Map<Id,Account>([select id, Prov_ID__c,CM_Corporate_Entity_Code__c,RecordtypeId,RecordType.developerName,Name  from  
                                                          Account where  Prov_ID__c In: SetProviderID ]);
        return Map_Account;
    }
    
    
    
    
     /*
    * 
    * Author :U393129
    * Date : 1/15/2019
    * Business Purpouse : To Query the Prov_ID__c from the ID 
    * Ver : 1.0  
    */
    
    public Map<id,Account> getAccountID(Set<ID> Set_AccountId)
    {
        Map<Id, Account> Map_Account=new Map<Id,Account>([select id, Prov_ID__c,CM_Corporate_Entity_Code__c,RecordtypeId,RecordType.developerName,Name  
                                                          from  Account where  ID IN: Set_AccountId ]);
        return Map_Account;
    }
    
    
    /*
    * 
    * Author :U393129
    * Date : 1/15/2019
    * Business Purpouse : To Query the Prov_ID__c from the ID 
    * Ver : 1.0  
    */
    
    public List<Account> getCredAccount(List<string> listProvId)
    {
        List<Account> listAccount=new List<Account>([select id, Prov_ID__c,CM_Corporate_Entity_Code__c,RecordtypeId,RecordType.developerName,Name  
                                                          from  Account where  Prov_ID__c IN: listProvId ]);
        return listAccount;
    }
    
    
      /*
    * 
    * Author :U393129
    * Date : 1/15/2019
    * Business Purpouse : To Query the Prov_ID__c from the ID 
    * Ver : 1.0  
    */
    
    public List<Account> getCredAccounts(List<Id> listAcctId)
    {
        List<Account> listAccount=new List<Account>([select id, Prov_ID__c,CM_Corporate_Entity_Code__c,RecordtypeId,RecordType.developerName,Name  
                                                          from  Account where  Id IN: listAcctId ]);
        return listAccount;
    }
    
    
    
    
    /*
* 
* Author :U393129
* Date : 12/28/2018
* Business Purpouse : To Query the User Record from User
* Ver : 1.0  
*/
    public Map<Id,User> getUser(Set<String> SetOfEmployeeIds)
    {
        Map<Id,User> Map_User= new Map<Id,User>
            ([Select Id,employeeNumber From User where employeeNumber In: SetOfEmployeeIds]);
        return Map_User;
        
    }
    
    
      /*
* 
* Author :U393129
* Date : 12/28/2018
* Business Purpouse : To Query the records from Case by using Grouping_ID__c
* Ver : 1.0  
*/
    public Map<Id,Case> getCaseGroupValues(Set<String> SetGroupingID)
    {
        Map<Id,Case> Map_CaseGroupValues= new Map<Id,Case>
            ([SeLECT Id, Grouping_ID__c, Project_Number__c,ParentId FROM Case WHERE Grouping_ID__c IN: SetGroupingID AND
              IsClosed !=true]);
         return Map_CaseGroupValues;
        
    }
    
    
         /*
* 
* Author :Ashok N
* Date : 12/28/2018
* Business Purpouse : To Query the records from Case by using Grouping_ID__c
* Ver : 1.0  
*/
    public Map<Id,GlobalSettings__c> getGlobalCustomSetting()
    {
        Map<Id,GlobalSettings__c> Map_GlobalSettings= new Map<Id,GlobalSettings__c>
            ([SeLECT Id, MCC_Case_Origin__c,Name, PFFileRecieved__c FROM GlobalSettings__c]);
         return Map_GlobalSettings;
        
    }

             /*
* 
* Author :Ashok N
* Date : 2/28/2019
* Business Purpouse : To Query the records user records
* Ver : 1.0  
*/
    
  public map<Id,User> getUserDetails(Set<Id> Set_UserId)
  {
     Map<Id,User> Map_User= new Map<Id,User>
            ([Select Id,employeeNumber,Alias From User where Id In: Set_UserId]);
        return Map_User; 
  }

    
                 /*
* 
* Author :Ashok N
* Date : 3/04/2019
* Business Purpouse : To Query the reports 
* Ver : 1.0  
*/
    
  public map<Id,Report> getReportName()
  {
     Map<Id,Report> Map_Report= new Map<Id,Report>([Select Id,DeveloperName From Report]);
     return Map_Report; 
  }
    
                     /*
* 
* Author :Ashok N
* Date : 3/06/2019
* Business Purpouse : To Query the reports 
* Ver : 1.0  
*/
    
  public map<Id,ETL_Report_Config_Data__mdt> getETLReprotConfigData(Set<String> Set_MCCFileType)
  {
      Map<Id,ETL_Report_Config_Data__mdt> ETL_Report_Config_Data= new Map<Id,ETL_Report_Config_Data__mdt>
          ([select Id,Email_Address__c,Destination_Org__c,Active_Email__c,File_Type__c,Plan_Id__c,Total_Accounts__c from ETL_Report_Config_Data__mdt where 
            File_Type__c IN : Set_MCCFileType]);
      return ETL_Report_Config_Data; 
  }
    
}