src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Acceptable_Plan_Ids__c</fullName>
        <label>Acceptable Plan Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>MCC trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/MCC_Data_Object__c.object
<CustomObject>
    <description>Intermediate object for Mass Case Creation and Death File.</description>
    <fields>
        <fullName>File_Count__c</fullName>
        <description>This field will hold the count the no rows processed within the mass file uploads ( Tx Recruitment, Il Roaster , Mass case closure and mass Cred status update)</description>
        <label>File Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>MCC_Data_Object</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Status__c</fullName>
        <label>Case Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Id__c</fullName>
        <label>File Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Type__c</fullName>
        <label>File Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Grouping_ID__c</fullName>
        <description>TX Specific</description>
        <label>Grouping ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Plan_ID__c</fullName>
        <description>For all loads</description>
        <label>Plan ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MCC_Project_Number__c</fullName>
        <description>TX Specific</description>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Prov_ID__c</fullName>
        <description>For Death and TX Data</description>
        <label>Provider ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Mass Case Creation Record</label>
    <nameField>
        <displayFormat>MCC-{0000}</displayFormat>
        <label>MCC Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Case Creation Records</pluralLabel>
    <recordTypes>
        <fullName>Roster</fullName>
        <active>true</active>
        <description>Roster</description>
        <label>Roster</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MCCProcessFlagUpdateBatchTest.cls
@isTest
public class MCCProcessFlagUpdateBatchTest {

    static testmethod void finishMethod_NetworkRecruitment(){
    
        GlobalSettings__c gs = new GlobalSettings__c();
        gs.Name = 'PFFileRecieved';
        gs.Record_Type_Names__c = 'CRM;';
        gs.MCC_trigger_switch__c    =   false;
        gs.Acceptable_Plan_Ids__c   =   'IL1,MT1,NM1,OK1,TX1';    
        insert gs;
        
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'IL1'); 
        insert acct;  
        
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='TX1';
        insert cs; 
                
        
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Roster'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test003';
        mcc.MCC_Grouping_ID__c = 'G003';
        mcc.MCC_File_Type__c = 'Onboarding Cred Mass Status Update';  
        mcc.MCC_Case_Status__c = 'Cred Denied'; 
        mcc.MCC_Case_Status__c = 'New';   
        mcc.MCC_Plan_ID__c = 'IL1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File003';
        mcc.File_Count__c  = 1.0;
        mcc.MCC_Case_Id__c  =cs.id;                
        insert mcc; 
        
        List<MCC_Data_Object__c> mccObjList = [SELECT Name FROM MCC_Data_Object__c limit 5];
        set<String> mccNameSet = new Set<String>();
        if(mccObjList!=null && mccObjList.size()>0){ 
            for(MCC_Data_Object__c mccO:mccObjList){
                mccNameSet.add(mccO.Name);
            }
            system.debug('*****************'+mccObjList);
            system.debug('*****************'+mccNameSet);        
            Test.startTest();
                MCCProcessFlagUpdateBatch  bt = new MCCProcessFlagUpdateBatch(mccNameSet);
                Database.executeBatch( bt );
           Test.stopTest();
       } 
    }
    

}