src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <externalId>true</externalId>
        <label>NPI</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Affiliations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name (Entity / Individual)</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Affiliated_Provider_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliated Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Affiliations</label>
    <nameField>
        <displayFormat>A{0}</displayFormat>
        <label>Affiliation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <recordTypes>
        <fullName>Affiliation</fullName>
        <active>true</active>
        <label>Affiliation for PPW</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_SPL_Addr__c.object
<CustomObject>
    <description>Service &amp; Payee Location Address Object based on PFIN Number</description>
    <fields>
        <fullName>Bill_PFIN__c</fullName>
        <description>Part of 40kpfin user stories.</description>
        <label>Bill PFIN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Add_Line_2__c</fullName>
        <description>Address Line 2</description>
        <inlineHelpText>Address Line 2</inlineHelpText>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Addr_Line_1__c</fullName>
        <description>Address Line 1</description>
        <inlineHelpText>Address Line 1</inlineHelpText>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Addr_Type__c</fullName>
        <description>Provider Address Usage Type</description>
        <inlineHelpText>Provider Address Usage Type</inlineHelpText>
        <label>Address Usage Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Capitation</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Directory</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Credentialing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CM_SPL_City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Email__c</fullName>
        <description>Email</description>
        <inlineHelpText>Email</inlineHelpText>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Fax_No__c</fullName>
        <label>Fax Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Mobile_No__c</fullName>
        <description>Mobile Phone Number</description>
        <inlineHelpText>Phone Number</inlineHelpText>
        <label>Phone Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_PFIN_No__c</fullName>
        <label>PFIN Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service &amp; Payee Location Address</relationshipLabel>
        <relationshipName>Account_Tax_Addresses_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_SPL_State__c</fullName>
        <description>State</description>
        <inlineHelpText>State</inlineHelpText>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CM_SPL_Zip_CD__c</fullName>
        <description>Zip Code</description>
        <inlineHelpText>Zip Code</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Service &amp; Payee Location Address</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Address Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service &amp; Payee Location Address</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/classes/DataUtility.cls
public class DataUtility {
public static void insertTestData()
    {
        GlobalSettings__c gs  =  new GlobalSettings__c();
        gs.name         =  'PFFileRecieved';
        gs.PFFileRecieved__c  =  false;
        gs.Record_Type_Names__c  =  'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        Id entityId,physicianId,personID,rolodexId;
        for(RecordType newRecordType:[Select Id,Name From RecordType Where Name='Entity Account' OR Name='Physician' OR Name='Rolodex' OR Name='Rolodex Affiliation'])
        {
            if(newRecordType.Name=='Entity Account')
            {
                entityId=newRecordType.Id;
            }
            if(newRecordType.Name=='Rolodex')
            {
                personID=newRecordType.Id;
            }
            if(newRecordType.Name=='Rolodex Affiliation')
            {
                rolodexId=newRecordType.Id;
            }
            else
            {
                physicianId=newRecordtype.Id;
            }
        } 
        Account newAccount = new Account();       
        newAccount.Name='Test Account';
        newAccount.CM_Corporate_Entity_Code__c='IL1';
        newAccount.RecordTypeId=entityId;
        insert newAccount;
        
        
        Account physicianDr = new Account();
        physicianDr.firstName='Saravana';
        physicianDr.lastName='Bharathi';
        physicianDr.CM_Corporate_Entity_Code__c='IL1';
        physicianDr.RecordTypeId=physicianId;
        physicianDr.Phone = '9185512503';
        physicianDr.personemail = 'test@abc.com';
        physicianDr.NPI__c = '1234567890';
        physicianDr.Tax_Id__c = '123456789';
        insert physicianDr;
        
        Account personAcc = new Account();
        personAcc.firstName='Test Account Per';
        personAcc.lastName='personAcc';
        personAcc.CM_Corporate_Entity_Code__c='IL1';
        personAcc.RecordTypeId=personID;
        personAcc.personemail = 'test@abc.com';
        personAcc.Phone = '9185512503';
        personAcc.NPI__c = '1234567890';
        personAcc.Tax_Id__c = '123456789';
        insert personAcc;
        
        Account affiliatedAccount = new Account();
        affiliatedAccount.Name='Test Affiliated Account';
        affiliatedAccount.CM_Corporate_Entity_Code__c='IL1';
        affiliatedAccount.RecordTypeId=entityId;
        insert affiliatedAccount;

        
        List<Affiliations__c> listOfAffiliations = new List<Affiliations__c>();
        Affiliations__c newAffiliation = new Affiliations__c ();
        newAffiliation.RecordTypeId = rolodexId;
        newAffiliation.CM_Affiliated_Provider_Name__c=affiliatedAccount.Id;
        newAffiliation.Account__c=newAccount.Id;
        listOfAffiliations.add(newAffiliation);
        
        newAffiliation = new Affiliations__c();
        newAffiliation.RecordTypeId = rolodexId;
        newAffiliation.CM_Affiliated_Provider_Name__c=personAcc.Id;
        newAffiliation.Account__c=newAccount.Id;
        listOfAffiliations.add(newAffiliation);
        
        newAffiliation = new Affiliations__c();
        newAffiliation.RecordTypeId = rolodexId;
        newAffiliation.CM_Affiliated_Provider_Name__c=physicianDr.Id;
        newAffiliation.Account__c=newAccount.Id;
        listOfAffiliations.add(newAffiliation);
        insert listOfAffiliations;
        
        List<CM_SPL_Addr__c> listOfAddress = new List<CM_SPL_Addr__c>();
        CM_SPL_Addr__c billPfin = new CM_SPL_Addr__c ();
        billPfin.CM_SPL_PFIN_No__c='BillPfin';
        billPfin.Bill_PFIN__c='BillPfin';
        billPfin.CM_SPL_Prov__c=newAccount.Id;
        billPfin.CM_SPL_Addr_Type__c='Billing';
        listOfAddress.add(billPfin);
        
        CM_SPL_Addr__c nonbillPfin = new CM_SPL_Addr__c();
        nonbillPfin.CM_SPL_PFIN_No__c='NonBillPfin';
        nonbillPfin.Bill_PFIN__c='BillPfin';
        nonbillPfin.CM_SPL_Prov__c=newAccount.Id;
        nonbillPfin.CM_SPL_Addr_Type__c='Service';
        listOfAddress.add(nonbillPfin);
        
        CM_SPL_Addr__c affiliatedNonBillPfin = new CM_SPL_Addr__c();
        affiliatedNonBillPfin.CM_SPL_PFIN_No__c='AffiliatedPfin';
        affiliatedNonBillPfin.Bill_PFIN__c='BillPfin';
        affiliatedNonBillPfin.CM_SPL_Prov__c=affiliatedAccount.Id;
        affiliatedNonBillPfin.CM_SPL_Addr_Type__c='Billing';
        listOfAddress.add(affiliatedNonBillPfin);
        
         CM_SPL_Addr__c billingAddress = new CM_SPL_Addr__c();
        billingAddress.CM_SPL_Addr_Line_1__c='Test add1';
        billingAddress.CM_SPL_Add_Line_2__c='Test add2';
        billingAddress.CM_SPL_City__c ='test city';
        billingAddress.CM_SPL_State__c='test state';
        billingAddress.CM_SPL_Zip_CD__c='234234';
        billingAddress.CM_SPL_Mobile_No__c='1234565435';
        billingAddress.CM_SPL_Email__c='abc@dc.com';
        billingAddress.CM_SPL_Fax_No__c='fax12345';
        billingAddress.CM_SPL_Addr_Type__c='Billing';
        billingAddress.CM_SPL_PFIN_No__c='BillPfin';
        billingAddress.Bill_PFIN__c='BillPfin';
        billingAddress.CM_SPL_Prov__c=personAcc.Id;        
        listOfAddress.add(billingAddress);
        
        CM_SPL_Addr__c serviceLocationAddress = new CM_SPL_Addr__c();
        serviceLocationAddress.CM_SPL_Addr_Line_1__c='Test add1';
        serviceLocationAddress.CM_SPL_Add_Line_2__c='Test add2';
        serviceLocationAddress.CM_SPL_City__c ='test city';
        serviceLocationAddress.CM_SPL_State__c='test state';
        serviceLocationAddress.CM_SPL_Zip_CD__c='234234';
        serviceLocationAddress.CM_SPL_Mobile_No__c='1234565435';
        serviceLocationAddress.CM_SPL_Email__c='abc@dc.com';
        serviceLocationAddress.CM_SPL_Fax_No__c='fax12345';
        serviceLocationAddress.CM_SPL_Addr_Type__c='Service';
        serviceLocationAddress.CM_SPL_PFIN_No__c='BillPfin';
        serviceLocationAddress.Bill_PFIN__c='BillPfin';
        affiliatedNonBillPfin.CM_SPL_Prov__c=physicianDr.Id;        
        listOfAddress.add(serviceLocationAddress);
        
        
        
          CM_SPL_Addr__c credentialingAddress = new CM_SPL_Addr__c();
        credentialingAddress.CM_SPL_Addr_Line_1__c='Test add1';
        credentialingAddress.CM_SPL_Add_Line_2__c='Test add2';
        credentialingAddress.CM_SPL_City__c ='test city';
        credentialingAddress.CM_SPL_State__c='test state';
        credentialingAddress.CM_SPL_Zip_CD__c='234234';
        credentialingAddress.CM_SPL_Mobile_No__c='1234565435';
        credentialingAddress.CM_SPL_Email__c='abc@dc.com';
        credentialingAddress.CM_SPL_Fax_No__c='fax12345';
        credentialingAddress.CM_SPL_Addr_Type__c='Credentialing';
        credentialingAddress.CM_SPL_PFIN_No__c='BillPfin';
        credentialingAddress.Bill_PFIN__c='BillPfin';
        affiliatedNonBillPfin.CM_SPL_Prov__c=affiliatedAccount.Id;        
        listOfAddress.add(credentialingAddress);
        
         CM_SPL_Addr__c adminAddress = new CM_SPL_Addr__c();
        adminAddress.CM_SPL_Addr_Line_1__c='Test add1';
        adminAddress.CM_SPL_Add_Line_2__c='Test add2';
        adminAddress.CM_SPL_City__c ='test city';
        adminAddress.CM_SPL_State__c='test state';
        adminAddress.CM_SPL_Zip_CD__c='234234';
        adminAddress.CM_SPL_Mobile_No__c='1234565435';
        adminAddress.CM_SPL_Email__c='abc@dc.com';
        adminAddress.CM_SPL_Fax_No__c='fax12345';
        adminAddress.CM_SPL_Addr_Type__c='Administration';
        adminAddress.CM_SPL_PFIN_No__c='BillPfin';
        adminAddress.Bill_PFIN__c='BillPfin';
        affiliatedNonBillPfin.CM_SPL_Prov__c=physicianDr.Id;        
        listOfAddress.add(adminAddress);
       
        
        
        insert listOfAddress;
    }
}