src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Rolodex_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rolodex To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rolodex</relationshipLabel>
        <relationshipName>Rolodex</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours_of_Operation__c</fullName>
        <label>Hours of Operation</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Affiliations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name (Entity / Individual)</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Affiliated_Provider_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliated Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Affiliations</label>
    <nameField>
        <displayFormat>A{0}</displayFormat>
        <label>Affiliation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <recordTypes>
        <fullName>Affiliation</fullName>
        <active>true</active>
        <label>Affiliation for PPW</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Hours_of_Operation__c.object
<CustomObject>
    <fields>
        <fullName>CM_HoO_Service_Payee_Location_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service &amp; Payee Location Address</label>
        <referenceTo>CM_SPL_Addr__c</referenceTo>
        <relationshipLabel>Hours of Operation</relationshipLabel>
        <relationshipName>Hours_of_Operation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hours of Operation</label>
    <nameField>
        <displayFormat>HO-{0}</displayFormat>
        <label>Hours of Operation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hours of Operation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Network__c.object
<CustomObject>
    <fields>
        <fullName>CM_Network__c</fullName>
        <label>Network</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Service_Payee_Location_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service &amp; Payee Location Address</label>
        <referenceTo>CM_SPL_Addr__c</referenceTo>
        <relationshipLabel>Networks</relationshipLabel>
        <relationshipName>Networks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Network</label>
    <nameField>
        <displayFormat>NI-{0}</displayFormat>
        <label>Network Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Networks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Provider_Identification__c.object
<CustomObject>
    <description>Provider Identification Object contains the Issued Identification types and numbers of the provider like License,NPI, Medicare etc</description>
    <fields>
        <fullName>CM_PI_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Identification</relationshipLabel>
        <relationshipName>Provider_Identification</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Identification</label>
    <nameField>
        <displayFormat>PI-{0}</displayFormat>
        <label>Provider Identification Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Identification</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Provider_Tax_Id__c.object
<CustomObject>
    <description>Provider Tax Identification Object  shows how and where billing is done.</description>
    <fields>
        <fullName>CM_PTI_Prov_Id_End_Date__c</fullName>
        <label>Tax End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Prov_Id_Start_Date__c</fullName>
        <label>Tax Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Prov_Name_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Tax Identifications</relationshipLabel>
        <relationshipName>Provider_Tax_Identifications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Prov_Name_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliated To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Tax Identifications</relationshipLabel>
        <relationshipName>Provider_Tax_Identifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Tax_Shared_Ind__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Shared Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Tax_Type__c</fullName>
        <label>Tax Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Provider Tax Identification</label>
    <nameField>
        <displayFormat>PTI-{0}</displayFormat>
        <label>Prov Tax Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Tax Identifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Specialty__c.object
<CustomObject>
    <description>Speciality</description>
    <fields>
        <fullName>CM_SP_Acc_Tax_Addr__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Tax Address Identifier</description>
        <inlineHelpText>Account Tax Address Identifier</inlineHelpText>
        <label>Provider Tax Address Identifier</label>
        <referenceTo>CM_SPL_Addr__c</referenceTo>
        <relationshipName>Specialties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_SP_Board_CD__c</fullName>
        <label>Board Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SP_Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_SP_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_SP_Network__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Network</label>
        <referenceTo>CM_Network__c</referenceTo>
        <relationshipLabel>Specialty</relationshipLabel>
        <relationshipName>Specialty</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_SP_Prov_Type__c</fullName>
        <label>Provider Type Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SP_Provi_Type_CD__c</fullName>
        <label>Provider Type Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SP_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Provider Lookup Relationship</description>
        <inlineHelpText>Provider</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Specialties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_SP_Specialty_CD__c</fullName>
        <label>Specialty Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SP_Specialty__c</fullName>
        <description>Specialty</description>
        <inlineHelpText>Specialty</inlineHelpText>
        <label>Specialty</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SP_SubSpec_CD__c</fullName>
        <label>SubSpecialty Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Specialty</label>
    <nameField>
        <displayFormat>SN-{0}</displayFormat>
        <label>Specialty Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specialty</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_SPL_Addr__c.object
<CustomObject>
    <description>Service &amp; Payee Location Address Object based on PFIN Number</description>
    <fields>
        <fullName>CM_SPL_Prov_Tax_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Tax Identification</label>
        <referenceTo>CM_Provider_Tax_Id__c</referenceTo>
        <relationshipLabel>Service &amp; Payee Location Address</relationshipLabel>
        <relationshipName>Service_Payee_Location_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service &amp; Payee Location Address</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Address Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service &amp; Payee Location Address</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Web2Case__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Web2Case Custom Object Values to store and retrieve</description>
    <fields>
        <fullName>CaseObjectValues__c</fullName>
        <label>CaseObjectValues</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Web2Case</label>
</CustomObject>

src/classes/ProviderDetails_Extended.cls
/****************************************************************
@Author      : Provider Intake team 
@Date        : 06/22/2017
@Description : This calss used to display broader view of Account 
details along with related objects records
******************************************************************/
public class ProviderDetails_Extended
{
    public Id accountId;
    public String numberOfRecordsToShow 									{ get; set; }    
    public set<Id>	provTaxIdentSet	=	new Set<Id>();
    public set<Id>  networkIds		=	new Set<Id>();
    
    
    public Map<Id,CM_Provider_Tax_Id__c> provIndentificationMap;
    public List<Affiliations__c>		affiliationsList					{ get; set; }
    public List<CM_Specialty__c>		specialityList						{ get; set; }
    public List<Account>				rolodexAccountsList					{ get; set; }
    public List<Case>					caseList							{ get; set; }
    public List<CM_Provider_Identification__c> provIdentificationList		{ get; set; }
    public List<CM_Provider_Tax_Id__c>	provTaxIdentificationList			{ get; set;	}
    public List<providerTaxIdenWrapper> listProvTaxIdentWrapper				{ get; set; }
    Public List<Account> accountList    									{ get; set; }
    Public Map<Id,List<CM_Specialty__c>> spltyWithNetworkIdsMap				{ get; set; }
    public Map<Id,List<CM_SPL_Addr__c>> spltyAddrMap 						{ get; set; }
    public Map<Id,List<CM_Specialty__c>> splAddressIdWithNtwrkSpltyMap_1    { get; set; }
    public static Boolean isSpeciality	{ get; set; }
    
    public ProviderDetails_Extended()
    {
        listProvTaxIdentWrapper 			= 	new List<providerTaxIdenWrapper>();
        splAddressIdWithNtwrkSpltyMap_1  	=	new Map<Id,List<CM_Specialty__c>>();
        spltyAddrMap						=	new Map<Id,List<CM_SPL_Addr__c>>();
        accountId   						=   ApexPages.currentPage().getParameters().get('Id');
        isSpeciality						=	false;
        intializeData();
    }
    
    public void intializeData()
    {
        /*
`* Account information results *
`	 */
        String acctQueryString      =   'SELECT Parent.Name,RecordType.name,' + Utils.getObjectFieldList('Account') +' FROM Account WHERE Id =:accountId';
        accountList                 =   (List<Account>)Database.query( acctQueryString );
        
        /*
* Provider information results 
*/
        String provIndentificationStr	=	'SELECT ' + Utils.getObjectFieldList('CM_Provider_Identification__c') +' FROM CM_Provider_Identification__c WHERE CM_PI_Prov__c=:accountId';
        provIdentificationList			=	(List<CM_Provider_Identification__c>)Database.query( provIndentificationStr );
        
        /*
* Provider Tax Identification results 
*/
        provIndentificationMap	=	new Map<Id,CM_Provider_Tax_Id__c>([Select Id,Name,CM_PTI_Tax_Id__c,CM_PTI_Tax_Shared_Ind__c,
                                                                       CM_PTI_Prov_Name_From__c,CM_PTI_Prov_Id_Start_Date__c,CM_PTI_Prov_Id_End_Date__c,
                                                                       CM_PTI_Tax_Type__c FROM CM_Provider_Tax_Id__c WHERE CM_PTI_Prov_Name_To__c=:accountId or  CM_PTI_Prov_Name_From__c=:accountId ]);
        System.debug('provIndentificationMap===>>>'+provIndentificationMap.size());
        for(Id provTaxId : provIndentificationMap.keySet() )
        {
            provTaxIdentSet.add( provTaxId );
        }
        if(!provIndentificationMap.isEmpty())
            populateProvTaxIdenData( provIndentificationMap );
        
        /*
* Affiliation results
*/	
        String affiliationStr	=	'SELECT '+ Utils.getObjectFieldList('Affiliations__c') +' FROM Affiliations__c WHERE Account__c =:accountId or CM_Affiliated_Provider_Name__c=:accountId';
        affiliationsList		=	(List<Affiliations__c>)Database.query( affiliationStr );
        
        /*
* Speciality results
*/	
        String specialityStr	=	'SELECT '+ Utils.getObjectFieldList('CM_Specialty__c') +' FROM CM_Specialty__c WHERE CM_SP_Provider__c =:accountId';
        specialityList			=	(List<CM_Specialty__c>)Database.query( specialityStr );
        
        /*
* Rolodex Account results
*/
        String rolodexAcctQueryStr	=	'SELECT '+ Utils.getObjectFieldList('Account') +' FROM Account WHERE CM_Rolodex_Account__c =:accountId';
        rolodexAccountsList			=	(List<Account>)Database.query( rolodexAcctQueryStr );
        /*
* Cases associated with either Entity or with Physician accounts
*/
        String caseQueryString		=	'SELECT '+ Utils.getObjectFieldList('Case') +' FROM Case WHERE 	Case_Entity__c =:accountId OR AccountId=:accountId';
        caseList					=	(List<Case>)Database.query( caseQueryString );
        /*
* Get custom settings for pagination
*/
        Web2Case__c cs_numberOfRecordsToShow = (Web2Case__c.getValues('NumberOfRecordsToShow'));
        
        if (cs_numberOfRecordsToShow !=null){
            this.numberOfRecordsToShow = cs_numberOfRecordsToShow.CaseObjectValues__c;	               
        } 
        else{
            this.numberOfRecordsToShow = '5';
        }        
        
    }
    
    public void populateProvTaxIdenData( Map<Id,CM_Provider_Tax_Id__c> provTaxIdenMap )
    {
        
        String queryString 	= 'SELECT ' + Utils.getObjectFieldList('CM_SPL_Addr__c')
            +',(SELECT '+ Utils.getObjectFieldList('CM_Specialty__c')+' FROM Specialties__r)'
            +',(SELECT '+ Utils.getObjectFieldList('CM_Network__c')+' FROM Networks1__r)'
            +',(SELECT '+ Utils.getObjectFieldList('CM_Hours_of_Operation__c')+' FROM Hours_of_Operation__r)'
            +' FROM CM_SPL_Addr__c where CM_SPL_Prov_Tax_ID__c IN : provTaxIdentSet'; 
        
        
        List<CM_SPL_Addr__c> spltyAddrList		=	(List<CM_SPL_Addr__c>)Database.query( queryString );
        Set<Id> serviceAndPayeeLocationSet		=	new Set<Id>();   
        if(!spltyAddrList.isEmpty())
        {
            for( CM_SPL_Addr__c spltyRecord : spltyAddrList )
            {  
                serviceAndPayeeLocationSet.add( spltyRecord.Id );
                if(!spltyAddrMap.containsKey( spltyRecord.CM_SPL_Prov_Tax_ID__c ) )
                {
                    System.debug('spltyRecord.CM_SPL_Prov_Tax_ID__c===>>>'+spltyRecord.CM_SPL_Prov_Tax_ID__c);
                    spltyAddrMap.put( spltyRecord.CM_SPL_Prov_Tax_ID__c, new List<CM_SPL_Addr__c>() );
                }
                spltyAddrMap.get( spltyRecord.CM_SPL_Prov_Tax_ID__c ).add( spltyRecord ); 
            }
        }
        
        /**** Specality records associated with Newworks ****/
        String networksQueryString 					=	'SELECT '+Utils.getObjectFieldList('CM_Network__c')+' FROM CM_Network__c WHERE CM_Service_Payee_Location_Address__c IN : serviceAndPayeeLocationSet';
        List<CM_Network__c>	netwrokList				=	(List<CM_Network__c>)Database.query( networksQueryString );
        
        for( CM_Network__c network : netwrokList )
        {
            networkIds.add( network.Id );
        }
        
        List<CM_Specialty__c> networkSpecialityList = new  List<CM_Specialty__c>();
        If(!networkIds.isEmpty())
        {
            networkSpecialityList = [Select Id,Name,CM_SP_Board_CD__c,Corporate_Entity_Code__c,CM_SP_Provi_Type_CD__c,CM_SP_Specialty__c,CM_SP_Specialty_CD__c,
                                     CM_SP_Effective_Date__c,	CM_SP_End_Date__c,CM_SP_Network__c,CM_SP_Acc_Tax_Addr__c,CM_SP_Prov_Type__c,CM_SP_SubSpec_CD__c,
                                     CM_SP_Provider__c FROM CM_Specialty__c WHERE CM_SP_Network__c IN : networkIds];   
        }        
                
        if(!networkSpecialityList.isEmpty()){
            for(CM_Specialty__c speciality : networkSpecialityList)
            {
                if(!splAddressIdWithNtwrkSpltyMap_1.containsKey( speciality.CM_SP_Network__c ) )
                {
                    splAddressIdWithNtwrkSpltyMap_1.put(speciality.CM_SP_Network__c, new List<CM_Specialty__c>());
                }
                splAddressIdWithNtwrkSpltyMap_1.get(speciality.CM_SP_Network__c ).add(speciality);
            }
            
        }						
        
        if(networkIds.size()>0)
        {
            for(Id tempId : networkIds)
            {
                if( !splAddressIdWithNtwrkSpltyMap_1.containsKey(tempId))
                {
                    splAddressIdWithNtwrkSpltyMap_1.put(tempId, new List<CM_Specialty__c>() );
                }
            }
        }
        
        if(!splAddressIdWithNtwrkSpltyMap_1.isEmpty())
        {
            isSpeciality = true;
        }
        
        
        
        if(!provTaxIdenMap.isEmpty())
        {
            for( Id provTaxId : provTaxIdenMap.keySet()) 
            {
                if( spltyAddrMap.containsKey( provTaxId ) )
                {
                    System.debug(spltyAddrMap.get( provTaxId ));
                    listProvTaxIdentWrapper.add( new providerTaxIdenWrapper( provTaxIdenMap.get( provTaxId ), spltyAddrMap.get( provTaxId )));
                }else{
                    listProvTaxIdentWrapper.add( new providerTaxIdenWrapper( provTaxIdenMap.get( provTaxId ),new List<CM_SPL_Addr__c>() ) );
                }
            } 
        }
    }
    
    public pageReference prevPage()
    {
        String backwardUrl = '/'+accountId;
        return (new PageReference( backwardUrl ).setRedirect(true));
    }
    
    
    /************* Inner Calss ********************/
    public class providerTaxIdenWrapper
    {
        public CM_Provider_Tax_Id__c 			provTaxIden	{ get; set; }
        public List<CM_SPL_Addr__c> 			spAddrList	{ get; set; }
        
        public providerTaxIdenWrapper( CM_Provider_Tax_Id__c  provTaxIden, List<CM_SPL_Addr__c>  spAddrList )
        {
            this.provTaxIden	=	provTaxIden;
            this.spAddrList		=	spAddrList;
        }
    }
}