src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_SPL_Addr__c.object
<CustomObject>
    <description>Service &amp; Payee Location Address Object based on PFIN Number</description>
    <fields>
        <fullName>Bill_PFIN__c</fullName>
        <description>Part of 40kpfin user stories.</description>
        <label>Bill PFIN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_County__c</fullName>
        <description>County</description>
        <inlineHelpText>County</inlineHelpText>
        <label>County</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_PFIN_No__c</fullName>
        <label>PFIN Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service &amp; Payee Location Address</relationshipLabel>
        <relationshipName>Account_Tax_Addresses_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service &amp; Payee Location Address</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Address Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service &amp; Payee Location Address</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Affiliation_Trigger_Switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Affiliation Trigger Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Case_Origin_Values__c</fullName>
        <label>CRM Case Origin Values</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Case_Status_fields__c</fullName>
        <label>CRM Case Status fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/classes/LtngCtrlCRMCase_test.cls
/*
 * Used to test the mobile version of CRM Case Creation 
*/
@isTest
public class LtngCtrlCRMCase_test {   
    
     @testSetup static void prepareData() {
         GlobalSettings__c gs    =   new GlobalSettings__c();
            gs.name                 =   'PFFileRecieved';
            gs.PFFileRecieved__c    =   false;
            gs.Affiliation_Trigger_Switch__c =   false;
         	gs.CRM_Case_Origin_Values__c = 'Email,Fax,In Person,Internal,Mass Case Creation,Others,Phone,Webex,Written';
         	gs.CRM_Case_Status_fields__c = 'New,In Progress,Waiting for Internal Response,Waiting for External Response,Closed';
            gs.Record_Type_Names__c = 'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
         insert gs;
         	
         Account acc = TestClassData.CreateAccount();
         CM_SPL_Addr__c spl = new CM_SPL_Addr__c();
         spl.CM_SPL_PFIN_No__c = '1234567890';         
         spl.CM_County__c      = 'Orange';
         spl.Bill_PFIN__c      = '1234567890';
         spl.CM_SPL_Prov__c    = acc.id;
         spl.CM_Corporate_Entity_Code__c = 'IL1';
         insert spl;
         spl = new CM_SPL_Addr__c();
         spl.CM_SPL_PFIN_No__c = '1234567890';         
         spl.CM_County__c      = 'Orange';
         spl.Bill_PFIN__c      = '1234567890';
         spl.CM_SPL_Prov__c    = acc.id;
         spl.CM_Corporate_Entity_Code__c = 'IL1';
         insert spl;
     }
    @isTest
    static void test_LtngCtrlCRMCase(){  
        Account acc = [select id from account limit 1];
        list<CM_SPL_Addr__c> spl = [select id,CM_SPL_PFIN_No__c from CM_SPL_Addr__c];
        case c = new case();
        c.Status = 'New';
        c.AccountId = acc.Id;
        c.Priority = 'Low';
            c.Origin = 'Email';
            c.Email_Address_Submitter__c = 'l@l.com';
            c.Corporate_received_date__c = date.valueof('2018-10-11');
        sobject parId;
        sobject contId;
        
        LtngCtrlCRMCase.getInitial(acc.Id,'Case');
        LtngCtrlCRMCase.getPFINS(acc.Id);
        LtngCtrlCRMCase.savedata(c,spl,acc.Id,null,null);
        case c2 = new case();
        LtngCtrlCRMCase.getselectOptions(c2,'Origin');
        LtngCtrlCRMCase.getselectOptions(c2,'Outcome__c');
        LtngCtrlCRMCase.getselectOptions(c2,'Status');
        LtngCtrlCRMCase.getselectOptions(c2,'CRM_Types__c');
        LtngCtrlCRMCase.getselectOptions(c2,'Type');
        LtngCtrlCRMCase.getDependentMap(c2,'CRM_Types__c','Outcome__c');
        
    }
}