src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Acceptable_Plan_Ids__c</fullName>
        <label>Acceptable Plan Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>MCC trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/MCC_Data_Object__c.object
<CustomObject>
    <description>Intermediate object for Mass Case Creation and Death File.</description>
    <fields>
        <fullName>MCC_Case_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>MCC_Data_Object</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Status__c</fullName>
        <label>Case Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Type__c</fullName>
        <label>Case Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Id__c</fullName>
        <label>File Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Type__c</fullName>
        <label>File Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Grouping_ID__c</fullName>
        <description>TX Specific</description>
        <label>Grouping ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Plan_ID__c</fullName>
        <description>For all loads</description>
        <label>Plan ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MCC_Project_Number__c</fullName>
        <description>TX Specific</description>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Prov_ID__c</fullName>
        <description>For Death and TX Data</description>
        <label>Provider ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Mass Case Creation Record</label>
    <nameField>
        <displayFormat>MCC-{0000}</displayFormat>
        <label>MCC Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Case Creation Records</pluralLabel>
    <recordTypes>
        <fullName>Roster</fullName>
        <active>true</active>
        <description>Roster</description>
        <label>Roster</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MCC_Report_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>MCC success/failure reporting email recipients</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mass Case Creation Reporting Users</label>
</CustomObject>

src/classes/MCCLoadStatusUpdateBatch_Test.cls
/**************************************************************************************************
Apex Class Name  : MCCLoadStatusUpdateBatch_Test
Version          : 1.0  
Functionality    : Test class for MCCLoadStatusUpdateBatch
Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                  
* Saravana Bharathi           05/21/2018              PPN-16156
  SethuRaman                  06/05/2018              PPN-17298
***************************************************************************************************/
@isTest
public class MCCLoadStatusUpdateBatch_Test 
{
     @testSetup static void prepareData() {
         
         GlobalSettings__c gs = new GlobalSettings__c();
        gs.Name = 'PFFileRecieved';
        gs.Record_Type_Names__c = 'CRM;';  
        gs.Acceptable_Plan_Ids__c   =   'IL1,MT1,NM1,OK1,TX1'; 
        gs.MCC_trigger_switch__c    =   false;
        insert gs;
         
         List<MCC_Report_Users__c> mccUsersList =  new List<MCC_Report_Users__c>();
        
        MCC_Report_Users__c objreportUser=new MCC_Report_Users__c();           
        objreportUser.Email__c='test@bcbsil.com';
        objreportUser.name='test user';
        objreportUser.Plan_Id__c='TX1';
        
    mccUsersList.add(objreportUser);
        
        MCC_Report_Users__c objreportUser1=new MCC_Report_Users__c();           
        objreportUser1.Email__c='test1@bcbsil.com';
        objreportUser1.name='test user1';
        objreportUser1.Plan_Id__c='IL1';
        
        mccUsersList.add(objreportUser1);
        
        MCC_Report_Users__c objreportUser2=new MCC_Report_Users__c();           
        objreportUser2.Email__c='test2@bcbsil.com';
        objreportUser2.name='test user2';
        objreportUser2.Plan_Id__c='MT1';
        mccUsersList.add(objreportUser2);
        
        MCC_Report_Users__c objreportUser3=new MCC_Report_Users__c();           
        objreportUser3.Email__c='test3@bcbsil.com';
        objreportUser3.name='test user3';
        objreportUser3.Plan_Id__c='OK1';
        
        mccUsersList.add(objreportUser3);
        
         MCC_Report_Users__c objreportUser4 = new MCC_Report_Users__c();           
        objreportUser4.Email__c='test4@bcbsil.com';
        objreportUser4.name='test user4';
        objreportUser4.Plan_Id__c='NM1';
         mccUsersList.add(objreportUser4);
        
        insert mccUsersList;
     }
    
   
   static testmethod void finishMethod_OnboardingCredMassStatusUpdate()
    {
       
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'TX1'); 
        insert acct;
        
      
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='TX1';
        insert cs;
             
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Roster'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test003';
        mcc.MCC_Grouping_ID__c = 'G003';
        mcc.MCC_Case_Type__c = 'CRM';
        mcc.MCC_File_Type__c = 'Onboarding Cred Mass Status Update';  
        mcc.MCC_Case_Status__c = 'New';   
        mcc.MCC_Plan_ID__c = 'TX1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File003';
        mcc.MCC_Case_Id__c  =cs.id; 
          insert mcc; 
         
         List<case> caseList = [Select Id,MCC_Record_Name__c from Case limit 5];    
         List<MCC_Data_Object__c > mccList = [Select Id,Name from MCC_Data_Object__c where Id=:mcc.Id];       
         
         if(caseList!=null && caseList.size()>0){
         
         for(Case cas:caseList){
             if(mccList!=null && mccList.size()>0){
                 cas.MCC_Record_Name__c = mccList[0].Name;
             }         
         }         
         
         update caseList;
         system.debug('*****************'+caseList);
               
        
            Test.startTest();
            MCCLoadStatusUpdateBatch bt = new MCCLoadStatusUpdateBatch(caseList);
            Database.executeBatch( bt );
            Test.stopTest(); 
       }
        
   }
   
    static testmethod void finishMethod_onBoardingCredRequestType()
    {
       
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'TX1'); 
        insert acct;
        
      
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='TX1';
        cs.status ='New';
        insert cs;
             
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Roster'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test003';
        mcc.MCC_Grouping_ID__c = 'G003';
        mcc.MCC_Case_Type__c = 'CRM';
        mcc.MCC_File_Type__c = 'onBoardingCredRequestType';  
        mcc.MCC_Case_Status__c = 'New';   
        mcc.MCC_Plan_ID__c = 'TX1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File003';
        mcc.MCC_Case_Id__c  =cs.id; 
          insert mcc; 
         
         List<case> caseList = [Select Id,MCC_Record_Name__c,status from Case limit 5];    
         List<MCC_Data_Object__c > mccList = [Select Id,Name from MCC_Data_Object__c where Id=:mcc.Id];       
         
         if(caseList!=null && caseList.size()>0){
         
         for(Case cas:caseList){
             if(mccList!=null && mccList.size()>0){
                 cas.MCC_Record_Name__c = mccList[0].Name;
                 cas.Status = 'New';
             }
         }         
         
         update caseList;
         system.debug('*****************'+caseList);
               
        
            Test.startTest();
            MCCLoadStatusUpdateBatch bt = new MCCLoadStatusUpdateBatch(caseList);
            Database.executeBatch( bt );
            Test.stopTest(); 
       }
        
   }
   
   static testmethod void finishMethod_ADCMassStatus()
    {
       
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'TX1'); 
        insert acct;
        
      
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='TX1';
        cs.status ='New';
        insert cs;
             
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Roster'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test003';
        mcc.MCC_Grouping_ID__c = 'G003';
        mcc.MCC_Case_Type__c = 'CRM';
        mcc.MCC_File_Type__c = 'ADC Mass Status';  
        mcc.MCC_Case_Status__c = 'New';   
        mcc.MCC_Plan_ID__c = 'TX1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File003';
        mcc.MCC_Case_Id__c  =cs.id; 
          insert mcc; 
         
         List<case> caseList = [Select Id,MCC_Record_Name__c,status from Case limit 5];    
         List<MCC_Data_Object__c > mccList = [Select Id,Name from MCC_Data_Object__c where Id=:mcc.Id];       
         
         if(caseList!=null && caseList.size()>0){
         
         for(Case cas:caseList){
             if(mccList!=null && mccList.size()>0){
                 cas.MCC_Record_Name__c = mccList[0].Name;
             }
         }         
         
         update caseList;
         system.debug('*****************'+caseList);
               
        
            Test.startTest();
            MCCLoadStatusUpdateBatch bt = new MCCLoadStatusUpdateBatch(caseList);
            Database.executeBatch( bt );
            Test.stopTest(); 
       }
        
   }
}