src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <externalId>true</externalId>
        <label>NPI</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Type__c</fullName>
        <label>Organization Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Entity_Account</fullName>
        <active>true</active>
        <description>Business Entities (not People).  Hospitals, Clinics, Groups, Locations, Facilities, etc</description>
        <label>Entity Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Master_Entity_Account</fullName>
        <active>true</active>
        <label>Master Entity Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Affiliations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name (Entity / Individual)</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Affiliated_Provider_Tax_Id__c</fullName>
        <label>Affiliated Provider Tax Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Affiliation_Type__c</fullName>
        <label>Affiliation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCSYSP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CM_Affiliated_Provider_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliated Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Affiliations</label>
    <nameField>
        <displayFormat>A{0}</displayFormat>
        <label>Affiliation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/classes/RolodexAffiliationControllerTest.cls
@isTest
public class RolodexAffiliationControllerTest 
{
   @isTest static void createRolodexAffiliation()
   {
       GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        gs.name                 =   'PFFileRecieved';
        insert gs;
       
       List<RecordType> recTypeList = [Select Id,DeveloperName,Name from RecordType where sObjectType='Account'];
       Map<String,RecordType> recTypeMap  = new Map<String,RecordType>();
       
       for(RecordType recType : recTypeList )
       {
           recTypeMap.put(recType.DeveloperName,recType);
       }     
      Account rolodexAcct = new Account( lastname			=	'test rolodex',
                                  recordTypeId 	= 	recTypeMap.get('Rolodex').Id,
                                  CM_Corporate_Entity_Code__c	=	'IL1',
                                  PersonEmail = 'testemail@email.com',
                                  Tax_Id__c='123456789',
                                  NPI__c='1234567890',
                                  Phone = '9185512503'
                                );
     insert rolodexAcct;
     Account entityAcct = new Account( Name			=	'test Entity',
                                  recordTypeId 	= 	recTypeMap.get('Entity_Account').Id,
                                  CM_Corporate_Entity_Code__c	=	'IL1',
                                  Class__c			=	'C'
                                  );
      
     insert entityAcct;
     Account masterEntityAcct = new Account( Name			=	'test Master Entity',
                                  recordTypeId 	= 	recTypeMap.get('Master_Entity_Account').Id,
                                  CM_Corporate_Entity_Code__c	=	'IL1',
                                  	Organization_Type__c		=	'HCSYS'
                                );
    insert masterEntityAcct;
    Account physicianAcct1 = new Account( LastName			=	'test Physician1',
                                  recordTypeId 	= 	recTypeMap.get('Physician').Id,
                                  CM_Corporate_Entity_Code__c	=	'IL1'
                                );
   insert physicianAcct1;
   Account physicianAcct2 = new Account( LastName			=	'test Physician2',
                                  recordTypeId 	= 	recTypeMap.get('Physician').Id,
                                  CM_Corporate_Entity_Code__c	=	'IL1'
                                  
                                );
    insert physicianAcct2;
       
    Affiliations__c afft1 = new Affiliations__c( Account__c = masterEntityAcct.id,
                                                 Affiliated_Provider_Tax_Id__c = '264562522',
                                                Affiliation_Type__c	=	'HCSYSP',
                                                CM_Affiliated_Provider_Name__c = physicianAcct1.Id
    											);
     insert afft1;
    
    Test.startTest();
    PageReference pageRef = Page.RolodexAffiliationPage;
	Test.setCurrentPage(pageRef);
    RolodexAffiliationController controller = new RolodexAffiliationController();
 	ApexPages.currentPage().getParameters().put('planId',rolodexAcct.CM_Corporate_Entity_Code__c);
    ApexPages.currentPage().getParameters().put('from','Account');   
    ApexPages.currentPage().getParameters().put('isEditPage','false'); 
    ApexPages.currentPage().getParameters().put('id',rolodexAcct.Id);   
    Test.stopTest();
    controller.displayRolldownAction();
    controller.saveAffiliationAction();
    controller.saveAndNewAffiliationAction();
    controller.cancelAction();
    controller.refreshPage();
       
   }
}