src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Entity_Account</fullName>
        <active>true</active>
        <description>Business Entities (not People).  Hospitals, Clinics, Groups, Locations, Facilities, etc</description>
        <label>Entity Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Master_Entity_Account</fullName>
        <active>true</active>
        <label>Master Entity Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Affiliations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name (Entity / Individual)</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Affiliated_to_Service_PFIN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up relationship with Service and Payee location. Introduced as part of PPN-16597</description>
        <label>Affiliated to PFIN</label>
        <referenceTo>CM_SPL_Addr__c</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Affiliations</label>
    <nameField>
        <displayFormat>A{0}</displayFormat>
        <label>Affiliation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <recordTypes>
        <fullName>Affiliation</fullName>
        <active>true</active>
        <label>Affiliation for PPW</label>
    </recordTypes>
    <recordTypes>
        <fullName>Master_Entity</fullName>
        <active>true</active>
        <label>Master Entity Affiliation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_SPL_Addr__c.object
<CustomObject>
    <description>Service &amp; Payee Location Address Object based on PFIN Number</description>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_PFIN_No__c</fullName>
        <label>PFIN Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service &amp; Payee Location Address</relationshipLabel>
        <relationshipName>Account_Tax_Addresses_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service &amp; Payee Location Address</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Address Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service &amp; Payee Location Address</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRM_Case_Status_fields__c</fullName>
        <label>CRM Case Status fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CRM_Case_record_Type_Id__c</fullName>
        <label>CRM_Case_record_Type_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Master_Record_Type_Id__c</fullName>
        <label>CRM Master Record Type Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseComment_Trigger_Switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>CaseComment Trigger Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Attachment_Trigger_Switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Case Attachment Trigger Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Physician</fullName>
        <active>true</active>
        <label>Physician</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rolodex</fullName>
        <active>true</active>
        <description>non-physician individuals</description>
        <label>Rolodex</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCRMCaseCreationController.cls
/*
* TThis is the test class for CRMCaseCreationController1.apxc
* Developer: Travis Self
*/
@isTest
public class TestCRMCaseCreationController {
    
    static Case controlCase, emailCase;
    static Account personAccount, entityAccount, meAccountWithAff, meAccountNoAff;
    static CM_SPL_Addr__c servicePay1, servicePay2;
    static List<Account> testAccounts;
    static List<CM_SPL_Addr__c> servPayeeLocations;
    static String planId = 'IL1';
    static Boolean runSaveAction	= true;
    
    // Custom settings record needed for CRM Case Creation
    @testSetup static void prepareData() {
        GlobalSettings__c gs					=	new GlobalSettings__c();
        gs.name 								=	'PFFileRecieved';
        gs.PFFileRecieved__c					=	false;
        gs.Record_Type_Names__c					=	'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        gs.CRM_Case_Status_fields__c			=	'New,In Progress,Waiting for Internal Response,Waiting for External Response,Closed';
        gs.CRM_Master_Record_Type_Id__c			=	[SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'Master_CRM_Case_Data'].Id;
        gs.CRM_Case_record_Type_Id__c			=	[SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'CRM'].Id;
        gs.Account_trigger_switch__c    		=   false;
        gs.Case_Attachment_Trigger_Switch__c 	= 	false;
        gs.CaseComment_Trigger_Switch__c     	= 	false;
        insert gs;
	}
    
    // New CRM cases can be created from:
    // 1. Physician Accounts
    // 2. Entity Accounts
    // 3. Master Entity Accounts
    // 5. Rolodex Accounts
    // 5. Email recordtype cases
    // 6. Service & Payee locations
    // 7. Rolodex Accounts
    static void createTestData() {
        
        testAccounts 		= new List<Account>();
        servPayeeLocations	= new List<CM_SPL_Addr__c>();
       
        personAccount 								= new Account();
        personAccount.LastName 						= 'Test Account';  
        personAccount.CM_Corporate_Entity_Code__c 	= planId;
        personAccount.RecordTypeId					= [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'Physician'].Id;
        testAccounts.add(personAccount);
        
        entityAccount 								= new Account();
        entityAccount.Name 							= 'Test Account';  
        entityAccount.CM_Corporate_Entity_Code__c 	= planId;
        entityAccount.RecordTypeId					= [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'Entity_Account'].Id;
        testAccounts.add(entityAccount);
        
        // Master Entity Account with no affiliations, and therefore there will be no associated pfins
        meAccountNoAff 								= new Account();
        meAccountNoAff.Name 						= 'Test Account';  
        meAccountNoAff.CM_Corporate_Entity_Code__c 	= planId;
        meAccountNoAff.RecordTypeId					= [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'Master_Entity_Account'].Id;
        testAccounts.add(meAccountNoAff);
        
        // Master Entity Account with 1 affiliation
        meAccountWithAff 								= new Account();
        meAccountWithAff.Name 							= 'Test Account';  
        meAccountWithAff.CM_Corporate_Entity_Code__c 	= planId;
        meAccountWithAff.RecordTypeId					= meAccountNoAff.RecordTypeId;
        testAccounts.add(meAccountWithAff);
        
        insert testAccounts;
        
        servicePay1 							= new CM_SPL_Addr__c();
        servicePay1.CM_SPL_PFIN_No__c 			= '123456';
        servicePay1.CM_SPL_Prov__c 				= personAccount.Id;
        servicePay1.CM_Corporate_Entity_Code__c	= planId;
        servPayeeLocations.add(servicePay1);
        
        servicePay2 = new CM_SPL_Addr__c();
        servicePay2.CM_SPL_PFIN_No__c 			= '654321';
        servicePay2.CM_SPL_Prov__c 				= personAccount.Id;
        servicePay2.CM_Corporate_Entity_Code__c	= planId;
        servPayeeLocations.add(servicePay2);
        
        insert servPayeeLocations;
        
        // Affiliation attached to Master Entity Account
        Affiliations__c	aff 				= new Affiliations__c();
        aff.Account__c						= meAccountWithAff.Id;
        aff.Affiliated_to_Service_PFIN__c 	= servicePay1.id;
        aff.CM_Corporate_Entity_Code__c		= planId;
        aff.RecordTypeId					= [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName like 'Master_Entity%' AND SObjectType='Affiliations__c'].Id;
        insert aff;
        
        // Email case
        emailCase 				= new Case();
        emailCase.accountId		= personAccount.id;
        emailCase.Plan_ID__c	= planId;
        emailCase.Origin		= 'Email';
        emailCase.Status		= 'New';
        emailCase.RecordTypeId	= [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'Email' AND SObjectType='Case'].Id;
        emailCase.OwnerId		= UserInfo.getUserId();
        insert emailCase;
    }
    
    
    static testMethod void crmTestMethod()
    {
        
        createTestData();
        
        Test.startTest();
        	
        	crmCreationFromPhysAccount();
        	crmCreationFromEntityAccount();
        	crmCreationFromMasterEntityAccount();
        	crmCreationFromCase();
        	crmCreationFromServicePayee();
                        
        Test.stopTest();
        
        System.assertEquals(1, [SELECT count() FROM Case WHERE recordtypeid=: GlobalSettings__c.getValues('PFFileRecieved').CRM_Master_Record_Type_Id__c]);
        //System.assertEquals(3, [SELECT count() FROM Case WHERE recordtypeid=: GlobalSettings__c.getValues('PFFileRecieved').CRM_Case_record_Type_Id__c]);
    }
    
    // CRM Case Creation launched from Account
    static void crmCreationFromPhysAccount() {
        
        controlCase 				= new Case();
        controlCase.Plan_ID__c 		= planId;
        
        PageReference pageRef = Page.CRMCaseCreationPage;
        
        pageRef.getParameters().put('accountId', personAccount.id );
        pageRef.getParameters().put('planId', planId);
        pageRef.getParameters().put('from','Account');
        pageRef.getParameters().put('inConsole','true');
        
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(controlCase);
        CRMCaseCreationController1 CCC 	= new CRMCaseCreationController1(sc);
        
        List<SelectOption> tempList = CCC.crmRequestTypes;
        
        CCC.caseRec.Origin = 'Phone';
        CCC.selectedCrmTypes = '["AIM - RQI","ANSI 5010"]';
        CCC.selectedCrmTypesToController();
        
        for(Integer i=0; i<CCC.caseWrapList.size(); i++) {
            
            CCC.caseWrapList[i].caseRec.Status			= 'New';
            CCC.caseWrapList[i].caseRec.CRM_Comments__c	= 'Test comments...';
            CCC.caseWrapList[i].caseRec.Priority		= 'High';
            CCC.lookupValue								= CCC.caseWrapList[i].caseRec.CRM_Types__c;
            CCC.fieldName								= 'Priority';
            CCC.fieldValue								= CCC.caseWrapList[i].caseRec.Priority;
        }
        
        CCC.selectedCrmTypes = '["AIM - RQI","ANSI 5010","Annual Provider Training"]';
        
        CCC.updateSelectedCrmTypes();
        CCC.selectedCrmTypesToController();
        
        CCC.caseWrapList[CCC.caseWrapList.size()-1].caseRec.Status			= 'New';
        CCC.caseWrapList[CCC.caseWrapList.size()-1].caseRec.CRM_Comments__c	= 'Test comments...';
        CCC.caseWrapList[CCC.caseWrapList.size()-1].caseRec.Priority		= 'High';
        
        for(Integer i=0; i<CCC.allPfins.size(); i++) {
            
            CCC.allPfins[i].selected = true;
            
        }
        
        CCC.addPFINS	= '333';
        
        CCC.getPossibleCaseOwnersByUser();
        CCC.getPossibleCaseOwnersByQueue();
        
        CCC.saveAndCloneAction();
        
        Id newlyCreatedMasterCase = [SELECT Id FROM Case WHERE RecordType.DeveloperName = 'Master_CRM_Case_Data' LIMIT 1].Id;
        List<Case> newlyCreatedCRMCases = [SELECT Id FROM Case WHERE parentId =: newlyCreatedMasterCase];
        CCC.setMasterCaseStatus(newlyCreatedMasterCase, newlyCreatedCRMCases);
        
        // After Save & Clone is clicked, set new values for Account and Case Entity to test pfin table method
        CCC.caseRec.AccountId 		= personAccount.Id;
        CCC.caseRec.Case_Entity__c 	= entityAccount.Id;
        CCC.caseRec.Origin			= 'Phone';
        
        CCC.populatePfins();
        
        // Master Entity Account with 1 affiliation
        CCC.caseRec.Case_Entity__c 	= meAccountWithAff.Id;
        
        CCC.populatePfins();
        
        // Master Entity Account with no affiliations
        CCC.caseRec.Case_Entity__c 	= meAccountNoAff.Id;
        
        CCC.populatePfins();
        
        CCC.cancelAction();
        
        //CCC.saveAndNewAction();	
        
        //CCC.saveAction();
        
    }
    
    // CRM Case Creation launched from Entity Account
    static void crmCreationFromEntityAccount() {
        
        controlCase 				= new Case();
        controlCase.Plan_ID__c 		= planId;
        
        PageReference pageRef = Page.CRMCaseCreationPage;
        
        pageRef.getParameters().put('accountId', entityAccount.id );
        pageRef.getParameters().put('planId', planId);
        pageRef.getParameters().put('from','Account');
        pageRef.getParameters().put('inConsole','true');
        
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(controlCase);
        CRMCaseCreationController1 CCC 	= new CRMCaseCreationController1(sc);
    }
    
    // CRM Case Creation launched from Master Entity Account
    static void crmCreationFromMasterEntityAccount() {
        
        controlCase 				= new Case();
        controlCase.Plan_ID__c 		= planId;
        
        PageReference pageRef = Page.CRMCaseCreationPage;
        
        pageRef.getParameters().put('accountId', meAccountWithAff.id );
        pageRef.getParameters().put('planId', planId);
        pageRef.getParameters().put('from','Account');
        pageRef.getParameters().put('inConsole','true');
        
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(controlCase);
        CRMCaseCreationController1 CCC 	= new CRMCaseCreationController1(sc);
    }
    
    // CRM Case Creation launched from Case
    static void crmCreationFromCase() {
        
        controlCase 				= new Case();
        controlCase.Plan_ID__c 		= planId;
        
        PageReference pageRef = Page.CRMCaseCreationPage;
        
        pageRef.getParameters().put('parentId', String.valueOf(emailCase.id) );
        pageRef.getParameters().put('accountId', String.valueOf(emailCase.accountId) );
        //pageRef.getParameters().put('caseEntityId', '' );
        pageRef.getParameters().put('planId', planId );
        pageRef.getParameters().put('Origin', String.valueOf(emailCase.Origin) );
        pageRef.getParameters().put('from','Case');
        pageRef.getParameters().put('inConsole','true');
        
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(controlCase);
        CRMCaseCreationController1 CCC 	= new CRMCaseCreationController1(sc);
        
        CCC.cancelAction();
    }
    
    // CRM Case Creation launched from a service & payee location address
    static void crmCreationFromServicePayee() {
        
        controlCase 				= new Case();
        controlCase.Plan_ID__c 		= planId;
        
        PageReference pageRef = Page.CRMCaseCreationPage;
        
        pageRef.getParameters().put('accountId', String.valueOf(servicePay1.CM_SPL_Prov__c) );
        pageRef.getParameters().put('planId', planId );
        pageRef.getParameters().put('pfinNumber', String.valueOf(servicePay1.CM_SPL_PFIN_No__c) );
        pageRef.getParameters().put('from','ServiceAndPayee');
        pageRef.getParameters().put('inConsole','true');
        
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(controlCase);
        CRMCaseCreationController1 CCC 	= new CRMCaseCreationController1(sc);
        
        CCC.cancelAction();
    }
}