src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cred_Status_Date__c</fullName>
        <description>Cred Status Date</description>
        <label>Cred Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cred_Status__c</fullName>
        <description>This field created part of PPN-25402. This field will hold the group credentialing case status</description>
        <label>Cred Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Mapping_Settings__mdt.object
<CustomObject>
    <description>This custom metadata object has been created part of PPN-41295. It holds the Case status value and the mapping text and it will be displayed under the NPI search results display page</description>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <label>Actual Value</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mapping_value__c</fullName>
        <label>Mapping value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Case Mapping Settings</label>
    <pluralLabel>Case Mapping Settings</pluralLabel>
</CustomObject>

src/objects/CM_Provider_Identification__c.object
<CustomObject>
    <description>Provider Identification Object contains the Issued Identification types and numbers of the provider like License,NPI, Medicare etc</description>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Issu_Ident_Nmbr__c</fullName>
        <externalId>true</externalId>
        <label>Identification Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_PI_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Identification</relationshipLabel>
        <relationshipName>Provider_Identification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Prvdr_Iden_Typ_Cd__c</fullName>
        <label>Identification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NPI</fullName>
                </value>
                <value>
                    <fullName>Govt. ID</fullName>
                </value>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Identification</label>
    <nameField>
        <displayFormat>PI-{0}</displayFormat>
        <label>Provider Identification Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Identification</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Public_search_history_tracking__c.object
<CustomObject>
    <fields>
        <fullName>Cred_Status_Date_Displayed__c</fullName>
        <label>Cred Status Date Displayed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cred_Status__c</fullName>
        <label>Cred Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI_Number__c</fullName>
        <label>NPI Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Displayed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Displayed</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Public_search_history_tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Search_Date_and_Time__c</fullName>
        <label>Search Date and Time</label>
        <type>DateTime</type>
    </fields>
    <label>Public Search History Tracking</label>
    <nameField>
        <displayFormat>PSH-{00000}</displayFormat>
        <label>Public search history tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Search History Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CredentialingStatusCheck.cls
/*
-------------------------------------------------------------------------------
 Developer                   Date                   Description
----------------------------------------------------------------------------- 
 Ashok N                    5/29/2019                PPN-40802
 Sreekanth K                06/13/2019               PPN-41295
*/

public  class CredentialingStatusCheck {
   
    /*
    * @author       :   Ashok Nettem
    * @date         :   06/05/2019
    * @description  :
    * ver           :   1.0 
    * Param         :   Input will take the License_Number and return the wrapperclass
    * @JIRA Stories :   PPN-40802
    * ver           :   1.1 
    * Description   :   Part of the PPN-41295, introduced logic to swapping of Cred status and
                        Plan id is with business provided text
    * @JIRA Stories :   PPN-41295
    */
    @AuraEnabled 
    public static CredentialingStatusWrapper getProviderDetailsByLicenseNumber(String License_Number)
    {
        system.debug('License_NumberInnerclass=== '+License_Number);
        CredentialingStatusWrapper CredentialingStatus                      =   new CredentialingStatusWrapper();
        List<String> ListProviderId                                         =   new List<String>();
        Map<Id,CM_Provider_Identification__c> MapCM_Provider_Identification =   new Map<Id,CM_Provider_Identification__c>(
                                                                                    [select Id ,CM_PI_Prov__c from CM_Provider_Identification__c 
                                                                                     where CM_Prvdr_Iden_Typ_Cd__c='License' AND  CM_Issu_Ident_Nmbr__c=: License_Number
                                                                                    ]);
        
        system.debug('MapCM_Provider_Identification===>> '+MapCM_Provider_Identification.size());
        List<Account> ListAccountProviderId                                 =   new List<Account>();
        
        if(MapCM_Provider_Identification.size()>1)
        {
            CredentialingStatus.NoProviderId                           =   ' More than one results found '+License_Number+ ' Please search with NPI Number ';
        }else if(MapCM_Provider_Identification.size()==0 || MapCM_Provider_Identification.isempty())
        {
            //Apex Add the message No provider id records is found.
            CredentialingStatus.NoProviderId                                =   ' License  '+License_Number+'  was not found. Please try searching by NPI or contact your appropriate state below for further information.';
        }else if(MapCM_Provider_Identification.size()==1)
        {
            for(CM_Provider_Identification__c CM_Provider_Identification :MapCM_Provider_Identification.values())
            {
                ListProviderId.add(CM_Provider_Identification.CM_PI_Prov__c);
            }
        }
        System.debug('ListProviderId====>>>>'+ListProviderId);
        
        if(ListProviderId.size()>0)
        {
             Map<String,String> caseSettingsMap         =   getCredStatusMappingValue(); 
             Integer statusValidateCount                =   0;
             List<Public_search_history_tracking__c> trackingHistoryList    =   new List<Public_search_history_tracking__c>();
            
            for( Account provRecord : [Select Id,Cred_Status__c,Name,CM_Corporate_Entity_Code__c,Cred_Status_Date__c from 
                                                     Account where Id IN:ListProviderId Order BY Cred_Status_Date__c DESC ] )
            {
                if(!String.isEmpty(provRecord.Cred_Status__c))
                {
                 /*
                  * Converting status to lowercase as the cred status updated through ftp
                  * is in uppercase and through onbroding flow updated status in lower case
                  */
                 String tempProviderStatusStr   = provRecord.Cred_Status__c.toLowerCase();
                 String tempCorpEntityStr       = provRecord.CM_Corporate_Entity_Code__c;   
                
                if(caseSettingsMap.containsKey( tempProviderStatusStr ))
                {
                    provRecord.CM_Corporate_Entity_Code__c          =   caseSettingsMap.containsKey( provRecord.CM_Corporate_Entity_Code__c )?caseSettingsMap.get( provRecord.CM_Corporate_Entity_Code__c ) : provRecord.CM_Corporate_Entity_Code__c;
                    System.debug('CaseSettings 222====>>>'+caseSettingsMap.get( tempProviderStatusStr.toLowerCase() ));
                    provRecord.Cred_Status__c                       =   caseSettingsMap.get( tempProviderStatusStr.toLowerCase() );
                    provRecord.CM_Corporate_Entity_Code__c          =   caseSettingsMap.get( tempCorpEntityStr.toLowerCase() );
                    ListAccountProviderId.add( provRecord );
                    
                    /*
                     * Insert tracking history
                     */
                    Public_search_history_tracking__c trackingRecord    =   new Public_search_history_tracking__c();
                    trackingRecord.Provider_Displayed__c                =   provRecord.Id;
                    trackingRecord.Search_Date_and_Time__c              =   System.now();
                    trackingRecord.Cred_Status__c                       =   provRecord.Cred_Status__c ;
                    System.debug(provRecord.Cred_Status__c+'License Search status ====>>>>'+caseSettingsMap.get( provRecord.Cred_Status__c ));
                    System.debug('License Search status ====>>>>'+trackingRecord.Cred_Status__c);
                    trackingRecord.Cred_Status_Date_Displayed__c        =   provRecord.Cred_Status_Date__c;
                    trackingRecord.License_Number__c                    =   License_Number;
                    trackingHistoryList.add( trackingRecord );
                }else{
                    statusValidateCount++;
                }
              }
            }
            if(!ListAccountProviderId.isEmpty() && statusValidateCount == 0 )
            {
                CredentialingStatus.ListAccounts    =   ListAccountProviderId;
                CredentialingStatus.LicenseNumber   =   'Entered License Number '+License_Number;
                try{
                    insert trackingHistoryList;
                }catch(Exception e){
                    System.debug('trackingHistoryList===>>>'+e.getMessage());
                }
            }else{
                CredentialingStatus.NoProviderId                                =   'No Results found for entered License Number  '+License_Number+'  Please enter NPI Number or contact your appropriate state below for further information ';
            }
        }
        system.debug('CredentialingStatus=== >>> '+CredentialingStatus);
        return CredentialingStatus;
    }
    
    /*
    * @author       :   Ashok Nettem
    * @date         :   06/05/2019
    * @description  :
    * ver           :   1.0 
    * Param         :   Input will take the NPI_Number and return the wrapperclass
    * @JIRA Stories :   PPN-40802
    * ver           :   1.1 
    * Description   :   Part of the PPN-41295, introduced logic to swapping of Cred status and
                        Plan id is with business provided text
    * @JIRA Stories :   PPN-41295
    */
    @AuraEnabled 
    public static CredentialingStatusWrapper getProviderDetailsByNPINumber(String NPI_Number)
    {
        CredentialingStatusWrapper CredentialingStatus                      =   new CredentialingStatusWrapper();
        List<String> ListProviderId                                         =   new List<String>();
        List<Account> ListAccountProviderId                                =   new List<Account>();
        
        Map<Id,CM_Provider_Identification__c> MapCM_Provider_Identification =   new Map<Id,CM_Provider_Identification__c>([select Id ,CM_PI_Prov__c from 
                                                                                    CM_Provider_Identification__c where CM_Prvdr_Iden_Typ_Cd__c='NPI' AND  
                                                                                    CM_Issu_Ident_Nmbr__c=: NPI_Number]);
       
        if( MapCM_Provider_Identification.size()==0 )
        {
            //Apex Add the message No provider id records is found.
            CredentialingStatus.NoProviderId='NPI  '+  NPI_Number  +' was not found Please try searching by License number or contact your appropriate state below for further information';
        }else
        {
            for(CM_Provider_Identification__c CM_Provider_Identification :MapCM_Provider_Identification.values())
            {
                ListProviderId.add(CM_Provider_Identification.CM_PI_Prov__c);
            }
        }
        
        if(ListProviderId.size()>0)
        {
            Map<String,String> caseSettingsMap          =   getCredStatusMappingValue();
            Integer statusValidateCount                 =   0;
            List<Public_search_history_tracking__c> trackingHistoryList =   new List<Public_search_history_tracking__c>();
            
            for( Account provRecord : [Select Id,Cred_Status__c,Name,CM_Corporate_Entity_Code__c,Cred_Status_Date__c from 
                                       Account where Id IN:ListProviderId Order BY Cred_Status_Date__c DESC] )
            {
                if(!String.isEmpty(provRecord.Cred_Status__c))
                {
                    /*
                      * Converting status to lowercase as the cred status updated through ftp
                      * is in uppercase and through onbroding flow updated status in lower case
                      */
                    String tempProviderStatusStr1    =   provRecord.Cred_Status__c.toLowerCase();
                    String tempCorpEntityStr        =    provRecord.CM_Corporate_Entity_Code__c;
                    for(String str : caseSettingsMap.keySet()){
                        System.debug(tempProviderStatusStr1+'str===>>>>'+str);
                        if(Str.trim()==tempProviderStatusStr1.trim()){
                            System.debug('Inside str===>>>>'+str);
                        }
                    }
                    if(caseSettingsMap.containsKey( tempProviderStatusStr1 ))
                    {
                        
                        provRecord.CM_Corporate_Entity_Code__c          =   caseSettingsMap.containsKey( provRecord.CM_Corporate_Entity_Code__c )?caseSettingsMap.get( provRecord.CM_Corporate_Entity_Code__c ) : provRecord.CM_Corporate_Entity_Code__c;
                        System.debug('CaseSettings 111====>>>'+caseSettingsMap.get( tempProviderStatusStr1));
                        provRecord.Cred_Status__c                       =   caseSettingsMap.get( tempProviderStatusStr1 );
                        provRecord.CM_Corporate_Entity_Code__c          =   caseSettingsMap.get( tempCorpEntityStr.toLowerCase() );
                        ListAccountProviderId.add( provRecord );
                        
                        /*
                         * Insert tracking history
                         */
                        Public_search_history_tracking__c trackingRecord    =   new Public_search_history_tracking__c();
                        trackingRecord.Provider_Displayed__c                =   provRecord.Id;
                        trackingRecord.Search_Date_and_Time__c              =   System.now();
                        trackingRecord.Cred_Status__c                       =   provRecord.Cred_Status__c ; 
                        System.debug('NPI Search status ====>>>>'+trackingRecord.Cred_Status__c);
                        trackingRecord.Cred_Status_Date_Displayed__c        =   provRecord.Cred_Status_Date__c;
                        trackingrecord.NPI_Number__c                        =   NPI_Number;
                        trackingHistoryList.add( trackingRecord );
                    }else{
                        statusValidateCount++;
                    }
              }
            }
            if( !ListAccountProviderId.isEmpty() && statusValidateCount == 0 )
            {
                CredentialingStatus.ListAccounts    =   ListAccountProviderId;
                CredentialingStatus.LicenseNumber   =   'Entered NPI Number '+NPI_Number;
                
             try{
                    insert trackingHistoryList;
                }catch(Exception e){
                    System.debug('trackingHistoryList===>>>'+e.getMessage());
                }
            }else{
                CredentialingStatus.NoProviderId='No Results found for entered NPI Number '+  NPI_Number  +'  Please enter License Number or contact your appropriate state below for further information';
            }
        }
        return CredentialingStatus;
    }
    
  /*
    * @author       :   Sreekanth K
    * @date         :   06/05/2019
    * @description  :   This function to provide the making value for the cred status on the Account
    * ver           :   1.0 
    * Param         :
    * @JIRA Stories :   PPN-41295
    */
    @AuraEnabled 
    public static Map<String,String> getCredStatusMappingValue( )
    {
       Map<String,String> caseSettingsMap                       =   new Map<String,String>();
        List<Case_Mapping_Settings__mdt> CredStatusMetadataList =   [Select Actual_Value__c,Mapping_value__c,Id 
                                                                    from Case_Mapping_Settings__mdt];
       String   tempString  =   '';
        
        if( !CredStatusMetadataList.isEmpty() )
        {
            for( Case_Mapping_Settings__mdt record : CredStatusMetadataList )
            {
                tempString = record.Actual_Value__c;
                System.debug('Actaul Value===>>>>>'+tempString.toLowerCase());
                caseSettingsMap.put( tempString.toLowerCase() , record.Mapping_value__c );
            }
        } 
        
        return caseSettingsMap;
    }     
    /*
    * @author       : Ashok Nettem
    * @date         : 06/05/2019
    * @description  :Wrapping the account and other values and sending as the respone
    * ver           :1.0 
    * Param         :
    * @JIRA Stories : PPN-40802
    */
    public class CredentialingStatusWrapper{
       
        @AuraEnabled
        public List<Account> ListAccounts{get;set;}
        @AuraEnabled
        public String MutipleProviderId{get;set;}
        @AuraEnabled
        public String NoProviderId{get;set;}
        @AuraEnabled
        public String LicenseNumber{get;set;}
        @AuraEnabled
        public String NPINumber{get;set;}
        
    }
    
    
}