src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percent_of_Covered_Charges__c</fullName>
        <label>Percent of Covered Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Networks__c</fullName>
        <label>Provider Networks</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL BlueCare Direct HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Select PPO Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Blue FocusCare HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Precision HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Broad PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL HMO of Illinois Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicaid Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL MMAI Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Focus Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Options Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Closed Plan Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT HealthLink Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Point of Service Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Traditional Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Community HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicaid Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PAR Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM POS Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>OK BCBS Medicare Advantage HMO Provider network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Service_Type__c</fullName>
        <label>Provider Service Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dialysis</fullName>
                </value>
                <value>
                    <fullName>Home Health</fullName>
                </value>
                <value>
                    <fullName>Hospice</fullName>
                </value>
                <value>
                    <fullName>SNF</fullName>
                </value>
                <value>
                    <fullName>ASC</fullName>
                </value>
                <value>
                    <fullName>Air Ambulance</fullName>
                </value>
                <value>
                    <fullName>Autism Agency</fullName>
                </value>
                <value>
                    <fullName>Birthing Center</fullName>
                </value>
                <value>
                    <fullName>DME</fullName>
                </value>
                <value>
                    <fullName>DME w/ Power Mobility</fullName>
                </value>
                <value>
                    <fullName>DME w/o Power Mobility</fullName>
                </value>
                <value>
                    <fullName>Health Screening Vendor</fullName>
                </value>
                <value>
                    <fullName>Home Infusion</fullName>
                </value>
                <value>
                    <fullName>Lab and Imaging</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                </value>
                <value>
                    <fullName>Sleep Facility</fullName>
                </value>
                <value>
                    <fullName>Home Health and Hospice</fullName>
                </value>
                <value>
                    <fullName>Ambulance</fullName>
                </value>
                <value>
                    <fullName>Facility -Acute Care</fullName>
                </value>
                <value>
                    <fullName>Psych</fullName>
                </value>
                <value>
                    <fullName>RTC</fullName>
                </value>
                <value>
                    <fullName>Facility-Behavioral Health</fullName>
                </value>
                <value>
                    <fullName>Facility-Rehab</fullName>
                </value>
                <value>
                    <fullName>Facility-LTAC</fullName>
                </value>
                <value>
                    <fullName>MG-Anesthesia</fullName>
                </value>
                <value>
                    <fullName>MG-Behavioral</fullName>
                </value>
                <value>
                    <fullName>MG-Chiropractic</fullName>
                </value>
                <value>
                    <fullName>MG-PCP</fullName>
                </value>
                <value>
                    <fullName>Prof-Anesthesia</fullName>
                </value>
                <value>
                    <fullName>Prof-Behavioral</fullName>
                </value>
                <value>
                    <fullName>Prof-HCP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>ASC</fullName>
        <active>true</active>
        <label>ASC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Facility</fullName>
        <active>true</active>
        <label>Facility</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_size__c</fullName>
        <label>List size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <recordTypes>
        <fullName>Network</fullName>
        <active>true</active>
        <label>Network</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CLM_Oklahoma_ReimbursmentHandler_Test.cls
@isTest
public class CLM_Oklahoma_ReimbursmentHandler_Test {
    static testMethod void testData() {
  
      GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
      Account acc= new Account();
      acc.Name               = 'Test Account CLM_Plan_OK';  
      acc.CM_Corporate_Entity_Code__c   = 'OK1';
      acc.RecordTypeId          = [SELECT Id, Name FROM RecordType WHERE Name = 'Entity Account'].Id;
      insert acc;
      
      Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
      
      list<Apttus__APTS_Agreement__c> agrmtList=new list<Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> oldMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> newMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      
  
     
        user u=[select Id from user where userrole.Name in ('CLM Oklahoma' ,'Oklahoma Supervisor') AND user.IsActive = true limit 1];
      
      Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c=acc.Id;
      agrmt.OwnerId=u.Id;
      agrmt.Plan__c='Oklahoma';
      agrmt.Provider_Networks__c='OK BCBS Medicare Advantage HMO Provider network; OK BCBS Medicare Advantage PPO Provider network';
      agrmt.recordtypeId=professionalRecordTypeId ;
      agrmt.Provider_Service_Type__c= null;
      agrmt.Percent_of_Covered_Charges__c= 10;
     
      agrmtList.add(agrmt);
      
      Apttus__APTS_Agreement__c agrmt2=new Apttus__APTS_Agreement__c();
      agrmt2.Apttus__Account__c=acc.Id;
      agrmt2.OwnerId=u.Id;
      agrmt2.Plan__c='Oklahoma';
      
      agrmt2.Provider_Networks__c='OK BCBS Medicare Advantage HMO Provider network; OK BCBS Medicare Advantage PPO Provider network';
       
      agrmt2.recordtypeId=professionalRecordTypeId ;
      agrmt2.Provider_Service_Type__c='Prof-HCP;Prof-PCP';
      agrmt2.Percent_of_Covered_Charges__c= 10;
      agrmtList.add(agrmt2);
      
      
      
      insert agrmtList;
      agrmt.Provider_Service_Type__c=  'Prof-HCP';
      update agrmt;
      agrmt2.Provider_Service_Type__c=  null;
      update agrmt2;
      
      oldMapAgrmt.put(agrmt2.Id,agrmt2);
      oldMapAgrmt.put(agrmt.Id,agrmt);
      newMapAgrmt.put(agrmt2.Id,agrmt2);
      newMapAgrmt.put(agrmt.Id,agrmt);
     
      Test.startTest();
      CLM_Oklahoma_ReimbursementHandler.beforeUpdate(agrmtList,oldMapAgrmt,newMapAgrmt);
      Test.stopTest();
  }
    
    static testMethod void testData2() {
  
      GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
      Account acc= new Account();
      acc.Name               = 'Test Account CLM_Plan_OK';  
      acc.CM_Corporate_Entity_Code__c   = 'OK1';
      acc.RecordTypeId          = [SELECT Id, Name FROM RecordType WHERE Name = 'Entity Account'].Id;
      insert acc;
      
      Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Medical Group').getRecordTypeId();
       
      list<Apttus__APTS_Agreement__c> agrmtList=new list<Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> oldMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> newMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      
       user u=[select Id from user where userrole.Name in ('CLM Oklahoma' ,'Oklahoma Supervisor') AND user.IsActive = true limit 1];
      
        
      Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c=acc.Id;
      agrmt.OwnerId=u.Id;
      agrmt.Plan__c='Oklahoma';
      agrmt.Provider_Networks__c=  'OK BCBS Medicare Advantage HMO Provider network ; OK BCBS Medicare Advantage PPO Provider network';
      agrmt.recordtypeId=professionalRecordTypeId ;
      agrmt.Provider_Service_Type__c= null;
      agrmt.Percent_of_Covered_Charges__c= 10;
     
      agrmtList.add(agrmt);
      
      Apttus__APTS_Agreement__c agrmt2=new Apttus__APTS_Agreement__c();
      agrmt2.Apttus__Account__c=acc.Id;
      agrmt2.OwnerId=u.Id;
      agrmt2.Plan__c='Oklahoma';
      agrmt2.Provider_Networks__c= 'OK BCBS Medicare Advantage HMO Provider network ;OK BCBS Medicare Advantage PPO Provider network';
      agrmt2.recordtypeId=professionalRecordTypeId ;
      agrmt2.Provider_Service_Type__c='Speech Therapist;Chiropractor';
      agrmt2.Percent_of_Covered_Charges__c= 10;
      agrmtList.add(agrmt2);
      
      
      
      insert agrmtList;
      agrmt.Provider_Service_Type__c=  'Speech Therapist;Chiropractor';
      update agrmt;
      agrmt2.Provider_Service_Type__c=  null;
      update agrmt2;
      
      oldMapAgrmt.put(agrmt2.Id,agrmt2);
      oldMapAgrmt.put(agrmt.Id,agrmt);
      newMapAgrmt.put(agrmt2.Id,agrmt2);
      newMapAgrmt.put(agrmt.Id,agrmt);
      
      Test.startTest();
      CLM_Oklahoma_ReimbursementHandler.beforeUpdate(agrmtList,oldMapAgrmt,newMapAgrmt);
      Test.stopTest();
  }
    
    static testMethod void testData3() {
  
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
      Account acc= new Account();
      acc.Name               = 'Test Account CLM_Plan_OK';  
      acc.CM_Corporate_Entity_Code__c   = 'OK1';
      acc.RecordTypeId          = [SELECT Id, Name FROM RecordType WHERE Name = 'Entity Account'].Id;
      insert acc;
      
      Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Facility').getRecordTypeId();
       
      list<Apttus__APTS_Agreement__c> agrmtList=new list<Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> oldMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> newMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
       
     user u=[select Id from user where userrole.Name in ('CLM Oklahoma' ,'Oklahoma Supervisor') AND user.IsActive = true limit 1];
      
      
      Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c=acc.Id;
      agrmt.OwnerId=u.Id;
      agrmt.Plan__c='Oklahoma';
      agrmt.Provider_Networks__c='OK BCBS Medicare Advantage HMO Provider network; OK BCBS Medicare Advantage PPO Provider network; OK Blue Advantage PPO Provider Network; OK Blue Choice PPO Provider Network;OK Blue Preferred PPO Provider Network;OK BlueLincs HMO Provider Network;OK BlueTraditional Provider Network;OK Blue Plan65 Select Provider Network';
      agrmt.recordtypeId=professionalRecordTypeId ;
      agrmt.Provider_Service_Type__c= null;
      agrmt.Percent_of_Covered_Charges__c= 10;
     
      agrmtList.add(agrmt);
      
      Apttus__APTS_Agreement__c agrmt2=new Apttus__APTS_Agreement__c();
      agrmt2.Apttus__Account__c=acc.Id;
      agrmt2.OwnerId=u.Id;
      agrmt2.Plan__c='Oklahoma';
      agrmt2.Provider_Networks__c=  'OK BCBS Medicare Advantage HMO Provider network; OK BCBS Medicare Advantage PPO Provider network; OK Blue Advantage PPO Provider Network; OK Blue Choice PPO Provider Network;OK Blue Preferred PPO Provider Network;OK BlueLincs HMO Provider Network;OK BlueTraditional Provider Network;OK Blue Plan65 Select Provider Network';
      agrmt2.recordtypeId=professionalRecordTypeId ;
      agrmt2.Provider_Service_Type__c='Facility-LTAC;Psych;RTC;Facility -Acute Care';
      agrmt2.Percent_of_Covered_Charges__c= 10;
      agrmtList.add(agrmt2);
      
      
      
      insert agrmtList;
      agrmt.Provider_Service_Type__c='Facility-LTAC;Psych;RTC;Facility -Acute Care';
      update agrmt;
      agrmt2.Provider_Service_Type__c=  null;
      update agrmt2;
      
      oldMapAgrmt.put(agrmt2.Id,agrmt2);
      oldMapAgrmt.put(agrmt.Id,agrmt);
      newMapAgrmt.put(agrmt2.Id,agrmt2);
      newMapAgrmt.put(agrmt.Id,agrmt);
     
      
      Test.startTest();
      CLM_Oklahoma_ReimbursementHandler.beforeUpdate(agrmtList,oldMapAgrmt,newMapAgrmt);
      Test.stopTest();
  }
 
    
    static testMethod void testData4() {
  
      GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
      Account acc= new Account();
      acc.Name               = 'Test Account CLM_Plan_OK';  
      acc.CM_Corporate_Entity_Code__c   = 'OK1';
      acc.RecordTypeId          = [SELECT Id, Name FROM RecordType WHERE Name = 'Entity Account'].Id;
      insert acc;
      
      Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Non-ASC Ancillary').getRecordTypeId();
       
      list<Apttus__APTS_Agreement__c> agrmtList=new list<Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> oldMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> newMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      
      user u=[select Id from user where userrole.Name in ('CLM Oklahoma' ,'Oklahoma Supervisor') AND user.IsActive = true limit 1];
            
      Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c=acc.Id;
      agrmt.OwnerId=u.Id;
      agrmt.Plan__c='Oklahoma';
      agrmt.Provider_Networks__c=  'OK BCBS Medicare Advantage HMO Provider network; OK BCBS Medicare Advantage PPO Provider network; OK Blue Advantage PPO Provider Network; OK Blue Choice PPO Provider Network;OK Blue Preferred PPO Provider Network;OK BlueLincs HMO Provider Network;OK BlueTraditional Provider Network;OK Blue Plan65 Select Provider Network';
      agrmt.recordtypeId=professionalRecordTypeId ;
      agrmt.Provider_Service_Type__c= null;
      agrmt.Percent_of_Covered_Charges__c= 10;
     
      agrmtList.add(agrmt);
      
      Apttus__APTS_Agreement__c agrmt2=new Apttus__APTS_Agreement__c();
      agrmt2.Apttus__Account__c=acc.Id;
      agrmt2.OwnerId=u.Id;
      agrmt2.Plan__c='Oklahoma';
      agrmt2.Provider_Networks__c=  'OK BCBS Medicare Advantage HMO Provider network; OK BCBS Medicare Advantage PPO Provider network; OK Blue Advantage PPO Provider Network; OK Blue Choice PPO Provider Network;OK Blue Preferred PPO Provider Network;OK BlueLincs HMO Provider Network;OK BlueTraditional Provider Network;OK Blue Plan65 Select Provider Network';
      agrmt2.recordtypeId=professionalRecordTypeId ;
      agrmt2.Provider_Service_Type__c='DME;SNF;Lab';
      agrmt2.Percent_of_Covered_Charges__c= 10;
      agrmtList.add(agrmt2);
      
      
      
      insert agrmtList;
      agrmt.Provider_Service_Type__c='DME;SNF;Lab';
      update agrmt;
      agrmt2.Provider_Service_Type__c=  null;
      update agrmt2;
      
      oldMapAgrmt.put(agrmt2.Id,agrmt2);
      oldMapAgrmt.put(agrmt.Id,agrmt);
      newMapAgrmt.put(agrmt2.Id,agrmt2);
      newMapAgrmt.put(agrmt.Id,agrmt);
     
      Test.startTest();
      CLM_Oklahoma_ReimbursementHandler.beforeUpdate(agrmtList,oldMapAgrmt,newMapAgrmt);
      Test.stopTest();
  }
        static testMethod void testData5() {
  
      GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
      Account acc= new Account();
      acc.Name               = 'Test Account CLM_Plan_OK1';  
      acc.CM_Corporate_Entity_Code__c   = 'OK1';
      acc.RecordTypeId          = [SELECT Id, Name FROM RecordType WHERE Name = 'Entity Account'].Id;
      insert acc;
      
      Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
       
      list<Apttus__APTS_Agreement__c> agrmtList=new list<Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> oldMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> newMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
           
                 
  user u=[select Id from user where userrole.Name in ('CLM Oklahoma' ,'Oklahoma Supervisor') AND user.IsActive = true limit 1];
      
      Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c=acc.Id;
      agrmt.OwnerId=u.Id;
      agrmt.Plan__c='Oklahoma';
      agrmt.Provider_Networks__c=  null;
      agrmt.recordtypeId=professionalRecordTypeId ;
      //agrmt.Percent_of_Covered_Charges__c= 10;
     
      agrmtList.add(agrmt);
      
      Apttus__APTS_Agreement__c agrmt2=new Apttus__APTS_Agreement__c();
      agrmt2.Apttus__Account__c=acc.Id;
      agrmt2.OwnerId=u.Id;
      agrmt2.Plan__c='Oklahoma';
      agrmt2.Provider_Networks__c= 'OK BCBS Medicare Advantage HMO Provider network';
      agrmt2.recordtypeId=professionalRecordTypeId ;
      agrmt2.Percent_of_Covered_Charges__c= 10;
      agrmtList.add(agrmt2);
      
      
      
      insert agrmtList;
      
      
      
      oldMapAgrmt.put(agrmt2.Id,agrmt2);
      oldMapAgrmt.put(agrmt.Id,agrmt);
      newMapAgrmt.put(agrmt2.Id,agrmt2);
      newMapAgrmt.put(agrmt.Id,agrmt);
      
      Test.startTest();
      CLM_Oklahoma_ReimbursementHandler.beforeUpdate(agrmtList,oldMapAgrmt,newMapAgrmt);
      Test.stopTest();
  }
  
}