src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Entity_Account</fullName>
        <active>true</active>
        <description>Business Entities (not People).  Hospitals, Clinics, Groups, Locations, Facilities, etc</description>
        <label>Entity Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Master_Entity_Account</fullName>
        <active>true</active>
        <label>Master Entity Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Affiliations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name (Entity / Individual)</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Affiliated_Provider_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliated Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Affiliation_Code_Description__c</fullName>
        <label>Affiliation Code Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Affiliation End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Converted to multi-select picklist as part of PPN-18792</description>
        <label>Role(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Assistant</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Associate General Counsel</fullName>
                </value>
                <value>
                    <fullName>Biller</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Billing Clerk</fullName>
                </value>
                <value>
                    <fullName>Billing Manager</fullName>
                </value>
                <value>
                    <fullName>Billing Practice Manager</fullName>
                </value>
                <value>
                    <fullName>Billings Clinic</fullName>
                </value>
                <value>
                    <fullName>Business Manager</fullName>
                </value>
                <value>
                    <fullName>Business Office Manager</fullName>
                </value>
                <value>
                    <fullName>CAO</fullName>
                </value>
                <value>
                    <fullName>Case Management</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CEO interim</fullName>
                </value>
                <value>
                    <fullName>Chief Dev Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Medical Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Operating Officer</fullName>
                </value>
                <value>
                    <fullName>Clinic Biller</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Credentialing</fullName>
                </value>
                <value>
                    <fullName>Credentialing Coordinator</fullName>
                </value>
                <value>
                    <fullName>Dir. Payer Relations</fullName>
                </value>
                <value>
                    <fullName>Director of Care Coordination</fullName>
                </value>
                <value>
                    <fullName>Director of Finance</fullName>
                </value>
                <value>
                    <fullName>Director of Patient Accounting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Roll_Down__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is created part of PPN-17862 to check weather the user has been selected roll down  option or not.</description>
        <label>Roll Down</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Affiliation Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Affiliations</label>
    <nameField>
        <displayFormat>A{0}</displayFormat>
        <label>Affiliation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <recordTypes>
        <fullName>Affiliation</fullName>
        <active>true</active>
        <label>Affiliation for PPW</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AffiliationTriggerHandler.cls
/**************************************************************************************************
Apex Class Name  : AffiliationTriggerHandler
Version          : 1.0  
Functionality    : 
Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Sreekanth Kalluru          06/11/2018             PPN-17862         
***************************************************************************************************/
public class AffiliationTriggerHandler 
{
    private string affCode                  =   'Medical Group Participant (MGP)';
    private List<Affiliations__c> affRollupsForInsert = new List<Affiliations__c>();
    private String ME_RecordType_Name       =   'Master_Entity_Account';
    private String Group_RecordType_Name    =   'Entity_Account';
    
    
     public void onBeforeInsert( List<Affiliations__c> newList )
    { 
        createAffiliations( newList );
    }
    
    public void onBeforeUpdate( List<Affiliations__c> newList , Map<id,Affiliations__c> oldMap )
    {
        ValidatePhoneFormat(newList);
        createAffiliations(newList);
    }
    
    public void ValidatePhoneFormat( List<Affiliations__c> newList ){
        
        for(Affiliations__c aff : newList){
            string phone = aff.Phone__c != NULL ? aff.Phone__c.replaceAll( '[^0-9]' , '' ) : NULL;
            string mobilePhone = aff.Mobile_Phone__c != NULL ? aff.Mobile_Phone__c.replaceAll( '[^0-9]' , '' ): NULL ;
            string fax = aff.Fax__c != NULL ? aff.Fax__c.replaceAll( '[^0-9]' , '' ) : NULL;
            
            if(phone != NULL && (!Phone.isNumeric() || phone.length() != 10)){
                aff.Phone__c.addError('Invalid Phone Number or Format');
            }
            if(mobilePhone != NULL && (!mobilePhone.isNumeric() || mobilePhone.length() != 10)){
                aff.Mobile_Phone__c.addError('Invalid Mobile Phone Number or Format');
            }
            if(fax != NULL && (!fax.isNumeric() || fax.length() != 10)){
                aff.Fax__c.addError('Invalid Fax Number or Format');
            }
        }
    }
    
    public void createAffiliations( List<Affiliations__c> newList )
    {
        Map<id,Affiliations__c> roldexAndProviderAcctIdMap  =   new Map<id,Affiliations__c>();
        List<Affiliations__c> refinedAffiliations           =   new List<Affiliations__c>();
        List<Affiliations__c> refinedMEAffiliations         =   new List<Affiliations__c>();
        Set<Id>     rolodexAcctIdSet            =   new Set<id>();
        Set<id>     providerAcctIdSet           =   new Set<Id>();
        Set<Id>     groupAccoutIdSet            =   new Set<Id>();
        Set<Id>     meAccountIdSet              =   new Set<Id>();
        
        for( Affiliations__c aff :  newList )
        {
           
            if(aff.Roll_Down__c == true)
            {
                roldexAndProviderAcctIdMap.put(aff.Account__c,aff);
                rolodexAcctIdSet.add( aff.CM_Affiliated_Provider_Name__c );
                providerAcctIdSet.add( aff.Account__c );
            }
        }
        System.debug('roldexAndProviderAcctIdMap===>>>'+roldexAndProviderAcctIdMap.keySet());
        if(!providerAcctIdSet.isEmpty())
        { 
            for(Account acct : [Select Id,RecordTypeId,RecordType.DeveloperName from Account Where Id IN:providerAcctIdSet])
            {
                if(acct.RecordType.DeveloperName == ME_RecordType_Name )
                {
                    System.debug('In side ME account'+acct.Id);
                    meAccountIdSet.add(acct.Id);
                }else if( acct.RecordType.DeveloperName == Group_RecordType_Name ){
                    System.debug('In side Group account'+acct.Id);
                   groupAccoutIdSet.add(acct.Id);
                }
            }
            
            
            if(!meAccountIdSet.isEmpty())
            {
                System.debug('meAccountIdSet===>>>'+meAccountIdSet);
                refinedAffiliations = [Select CM_Affiliated_Provider_Name__c,Account__c from Affiliations__c 
                                        where Account__c IN:meAccountIdSet ];
              
            }else If(!groupAccoutIdSet.isEmpty())
            {
               refinedAffiliations = [Select CM_Affiliated_Provider_Name__c,Account__c from Affiliations__c 
                                        where CM_Affiliated_Provider_Name__c IN:groupAccoutIdSet and CM_Affiliation_Code_Description__c=:affCode];
                
            }
              System.debug('refinedAffiliations===>>>>'+refinedAffiliations.size());
            if(!refinedAffiliations.isEmpty())
            {
                for( Affiliations__c affrec :  refinedAffiliations  )
                {
                      
                    if(    roldexAndProviderAcctIdMap.containsKey(affrec.CM_Affiliated_Provider_Name__c) )
                    {
                        // Code to create affiliations if selected account is either Entity / physician account
                        // creating affiliations for all asscoatied affiliations with affiliation description type MGP
                       Affiliations__c aff                  =   new Affiliations__c();
                        aff.Account__c                      =   affrec.Account__c;
                        aff.CM_Affiliated_Provider_Name__c  =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).CM_Affiliated_Provider_Name__c;
                        aff.CM_Corporate_Entity_Code__c     =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).CM_Corporate_Entity_Code__c;
                        aff.Start_Date__c                   =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).Start_Date__c;
                        aff.End_Date__c                     =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).End_Date__c;
                        aff.Status__c                       =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).Status__c;
                        aff.Role__c                         =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).Role__c;
                        aff.Phone__c                        =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).Phone__c;
                        aff.Mobile_Phone__c                 =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).Mobile_Phone__c;
                        aff.Fax__c                          =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).Fax__c;
                        aff.Email__c                        =   roldexAndProviderAcctIdMap.get(affrec.CM_Affiliated_Provider_Name__c).Email__c;
                        affRollupsForInsert.add( aff ); 
                    }else if( roldexAndProviderAcctIdMap.containsKey(affrec.Account__c) ) 
                    {
                        //PPN-19745
                        // Code to create affiliations if selected account is Master entity account
                        // If ME account gets seleted by the user , we are creating affiliations for all asscoatied affiliations with ME
                        Affiliations__c aff                 =   new Affiliations__c();
                        aff.Account__c                      =   affrec.CM_Affiliated_Provider_Name__c;
                        aff.CM_Affiliated_Provider_Name__c  =   roldexAndProviderAcctIdMap.get(affrec.Account__c).CM_Affiliated_Provider_Name__c;
                        aff.CM_Corporate_Entity_Code__c     =   roldexAndProviderAcctIdMap.get(affrec.Account__c).CM_Corporate_Entity_Code__c;
                        aff.Start_Date__c                   =   roldexAndProviderAcctIdMap.get(affrec.Account__c).Start_Date__c;
                        aff.End_Date__c                     =   roldexAndProviderAcctIdMap.get(affrec.Account__c).End_Date__c;
                        aff.Status__c                       =   roldexAndProviderAcctIdMap.get(affrec.Account__c).Status__c;
                        aff.Role__c                         =   roldexAndProviderAcctIdMap.get(affrec.Account__c).Role__c;
                        aff.Phone__c                        =   roldexAndProviderAcctIdMap.get(affrec.Account__c).Phone__c;
                        aff.Mobile_Phone__c                 =   roldexAndProviderAcctIdMap.get(affrec.Account__c).Mobile_Phone__c;
                        aff.Fax__c                          =   roldexAndProviderAcctIdMap.get(affrec.Account__c).Fax__c;
                        aff.Email__c                        =   roldexAndProviderAcctIdMap.get(affrec.Account__c).Email__c;
                        affRollupsForInsert.add( aff ); 
                    }                         
                } 
            }
           
        }
        System.debug('affRollupsForInsert===>>>>'+affRollupsForInsert);
        if(!affRollupsForInsert.isEmpty())
        {
            try{
                insert affRollupsForInsert;
            }catch(Exception e){
                System.debug('Message===>>>>'+e.getMessage());
            }
            
        }
    }
}