src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cred_Status__c</fullName>
        <description>This field created part of PPN-25402. This field will hold the group credentialing case status</description>
        <label>Cred Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PFIN__c</fullName>
        <externalId>true</externalId>
        <label>PFIN</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <externalId>true</externalId>
        <label>Prov ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Provider_Identification__c.object
<CustomObject>
    <description>Provider Identification Object contains the Issued Identification types and numbers of the provider like License,NPI, Medicare etc</description>
    <fields>
        <fullName>CM_Issu_Ident_Nmbr__c</fullName>
        <externalId>true</externalId>
        <label>Identification Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_PI_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Identification</relationshipLabel>
        <relationshipName>Provider_Identification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Prvdr_Iden_Typ_Cd__c</fullName>
        <label>Identification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NPI</fullName>
                </value>
                <value>
                    <fullName>Govt. ID</fullName>
                </value>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Identification</label>
    <nameField>
        <displayFormat>PI-{0}</displayFormat>
        <label>Provider Identification Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Identification</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Credentialing_record_types__c</fullName>
        <description>This field holds the credentialing record types and these record types are used when a crm case is a child for credentialing case it will bi pass the parent case status change.</description>
        <label>Credentialing record types</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <fields>
        <fullName>Contracting_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contracting Case</description>
        <label>Contracting Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Provider_Networks_Contracting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cred_Status__c</fullName>
        <label>Cred Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Needs Credentialing</fullName>
                </value>
                <value>
                    <fullName>No Credentialing Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Code_Name__c</fullName>
        <label>Network Code/Name</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Network_Load_Plan_Id__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PAR - Blue Traditional</fullName>
                </value>
                <value>
                    <fullName>PPO - Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>EPP - Blue Preferred</fullName>
                </value>
                <value>
                    <fullName>OPA - Blue Select PPO</fullName>
                </value>
                <value>
                    <fullName>SPN - Plan 65 Select</fullName>
                </value>
                <value>
                    <fullName>CAR - Caring Program</fullName>
                </value>
                <value>
                    <fullName>HMO - BlueLincs HMO</fullName>
                </value>
                <value>
                    <fullName>BVP - Blue Advantage PPO</fullName>
                </value>
                <value>
                    <fullName>ADV - Blue Advantage HMO</fullName>
                </value>
                <value>
                    <fullName>BAV - Blue Precision HMO</fullName>
                </value>
                <value>
                    <fullName>BAV - Blue Advantage HMO</fullName>
                </value>
                <value>
                    <fullName>BCA - BlueChoice PPO</fullName>
                </value>
                <value>
                    <fullName>BCE - Blue Choice PPO Preferred</fullName>
                </value>
                <value>
                    <fullName>BCO - Blue Choice Options</fullName>
                </value>
                <value>
                    <fullName>BCP - BlueChoice PPO (BH)</fullName>
                </value>
                <value>
                    <fullName>BCS - Professional Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>BDF - Blue Choice PPO Preferred Ancillary</fullName>
                </value>
                <value>
                    <fullName>BDS - Professional Designated Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>BFC - Blue Focus Care</fullName>
                </value>
                <value>
                    <fullName>BHD - Blue Care Direct</fullName>
                </value>
                <value>
                    <fullName>BLC - Blue Focus POS</fullName>
                </value>
                <value>
                    <fullName>CHP - CHIP (Medicaid)</fullName>
                </value>
                <value>
                    <fullName>CND - Blue Community HMO Dallas</fullName>
                </value>
                <value>
                    <fullName>CNN - Blue Community HMO Network</fullName>
                </value>
                <value>
                    <fullName>DCC - Facility - Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>DDC - Facility - Blue Choice Designated PPO</fullName>
                </value>
                <value>
                    <fullName>DEB - DNOA</fullName>
                </value>
                <value>
                    <fullName>DUE - Dual Eligible MMAI</fullName>
                </value>
                <value>
                    <fullName>EDF - Facility Blue Choice Designated PPO Preferred</fullName>
                </value>
                <value>
                    <fullName>EDS - Professional Designated Blue Choice PPO Preferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Name__c</fullName>
        <label>Network Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PFIN_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PFIN Case</description>
        <label>PFIN Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Provider_Networks_PFIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PFIN__c</fullName>
        <description>This field created to hold the PFIN data available on the Case object. 
US No: PPN-20704</description>
        <formula>Case_Number__r.MC_PFIN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PFIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PFIN_onBoarding__c</fullName>
        <label>PFIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paper_Cred_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paper Cred Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <description>Prov ID</description>
        <label>Prov ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <recordTypes>
        <fullName>Contracting_Onboarding</fullName>
        <active>true</active>
        <description>Contracting Onboarding</description>
        <label>Contracting Onboarding</label>
    </recordTypes>
    <recordTypes>
        <fullName>Credentialing</fullName>
        <active>true</active>
        <label>Credentialing</label>
    </recordTypes>
    <recordTypes>
        <fullName>Network</fullName>
        <active>true</active>
        <label>Network</label>
    </recordTypes>
    <recordTypes>
        <fullName>Onboarding</fullName>
        <active>true</active>
        <description>Onboarding</description>
        <label>Onboarding</label>
    </recordTypes>
    <recordTypes>
        <fullName>PFIN_Onboarding</fullName>
        <active>true</active>
        <description>PFIN Onboarding</description>
        <label>PFIN Onboarding</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QueueIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom setting is used to while updating plan id from child to Master and vise versa.

Query used to get the Queue Id and Developername.
SELECT DeveloperName,Id,Name,Type FROM Group WHERE Type = &apos;Queue&apos;</description>
    <fields>
        <fullName>PlanId__c</fullName>
        <label>PlanId</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueueId__c</fullName>
        <label>QueueId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Queue Ids</label>
</CustomObject>

src/objects/RoleAndPlanId_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom settings object created as a part of user story PPN-1645.
Use below query to create records for this custom settings object.</description>
    <fields>
        <fullName>PlanId__c</fullName>
        <label>PlanId</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Id__c</fullName>
        <label>Role Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RoleAndPlanId Settings</label>
</CustomObject>

src/classes/TestCaseTriggerHandler1.cls
/*******************************************
@Author Intake team (Andrew M)
@Date   10/19/17
@Description methods and properties related to test code coverage for CaseTriggerHandler
********************************************/
@isTest
private class TestCaseTriggerHandler1
{
    
    public static DataSupportForCaseTriggerHandler ds = new DataSupportForCaseTriggerHandler();
    
    @testSetup static void prepareData() {
        /*string strIndvCredRecTypeId  = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Provider_On_boarding_Credentialing').getRecordTypeId();

        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        gs.Credentialing_record_types__c = strIndvCredRecTypeId;
        insert gs; */
        
        TestDataFactory tdf = new TestDataFactory();
        tdf.InsertGlobalsetting();
        
        
        //do inserts to initalize custom settings
        ds.insertDataForCustomSettings();
        
        testclassdata.CreateCustomSettingData('case');
        testclassdata.CreateCustomSettingData('Provider_Networks__c');    
        
        List<case> casetList = new List<Case>();
        
        for(Integer i = 1; i <=5; i++){
            Case tCase = TestCaseUtil.CreateCase();
            casetList.add(tCase);
        }        
        insert casetList;
    }
    
    @isTest static void testMethod_1()
    {
        
        //Create supervisor test user
        List<User> userList    =   TestCaseUtil.createUser('PNC Profile','Illinois Supervisor',1);
        insert userList;
        System.runAs(userList[0]){        
            
            
            //insert new parent and child cases
            Case pc = ds.insertDataForParentCases();  
            Case cc = ds.insertDataForChildCases(pc);            
            
            List<Case> cl = new List<Case>();
            cl.add(pc);
            cl.add(cc);            
            
            Set<Id> parentCaseIdSet =  new Set<Id>();
            parentCaseIdSet.add(pc.id);
            parentCaseIdSet.add(cc.id);
            
            /*
* execute some stand alone methods
*/ 
            Test.StartTest();           
            CaseTriggerHandler.caseStatusUpdate(parentCaseIdSet);
            CaseTriggerHandler.UpdateCaseOwner(cl);
            //CaseTriggerHandler.validateUserRole(userList[0].id, 'IL1');
            //CaseTriggerHandler.validateUserRole(userList[0].id, 'OK1');
            CaseTriggerHandler.getChildCasesByParentStatus(parentCaseIdSet);
            CaseTriggerHandler.getChildCasesByParent(parentCaseIdSet);
            CaseTriggerHandler.casePriorityUpdate(parentCaseIdSet);  
               
            
            CaseComment casec = new CaseComment
                (
                    CommentBody = 'This is my test comment',
                    ParentId = pc.id,
                    IsPublished = true               
                );
            insert casec;            
            CaseTriggerHandler.getComments(pc,casec);
            ds.updateCase(cc,'status','Closed Processed');          
            ds.updateCase(pc, 'status', 'Closed Processed');
            ds.updateCase(cc, 'origin', 'Web On-boarding');
            ds.updateCase(pc, 'origin', 'Web On-boarding');   
            ds.updateCase(cc, 'ownerid', '0053C000000Fl9hQAC');
            ds.updateCase(pc, 'ownerid', '0053C000000Fl9hQAC');             
            ds.updateCase(pc, 'priority', 'High');
            Test.StopTest(); 
            
            //insert new parent and child cases
        }        
    }   
    
    static testmethod void createCase(){
        
        List<case> caseList = new List<Case>();
        List<User> userList    =   TestCaseUtil.createUser('System Administrator','Illinois Supervisor',1);
        insert userList;
       
        System.runAs(userList[0]){
        
            //for(Integer i = 1; i <=5; i++){
                Case curCase = TestCaseUtil.CreateCase();
                caseList.add(curCase);
            //}
            
            insert caseList;
            
            list<case> casetlist = new list<case>();
            casetList = [select id,status,plan_id__c from case];
            casetList[0].status = 'Closed Processed';
            casetList[1].status = 'Closed Rejected';
            casetList[2].plan_id__c = 'TX1';
            
            
            test.startTest();
            update casetList;
            test.stopTest();
        }        
    }
    
    @isTest static void testMethod_3()
    {
        list<case> casetlist = new list<case>();
        casetList = [select id,status,plan_id__c from case];
        casetList[0].status = 'Closed Processed';
        casetList[1].status = 'Closed Rejected';
        casetList[2].plan_id__c = 'TX1';
        
        List<User> userList    =   TestCaseUtil.createUser('System Administrator','Illinois Supervisor',1);
        insert userList;
        System.runAs(userList[0]){
            test.startTest();
            update casetList;
            test.stopTest();
        }        
    }
    
    @isTest static void testMethod_4()
    {
        List<case> caseList = new List<Case>();
        
        for(Integer i = 1; i <=2; i++){
            Case curCase = TestCaseUtil.CreateCase();
            caseList.add(curCase);      
        }
        insert caseList;
        caseList[0].parentId = caseList[1].Id;
        caseList[0].status = 'Closed Processed';
            test.startTest();
            update caseList;
            test.stopTest();
                
    }
    
    @isTest static void testMethod_5()
    {
        
        //Create supervisor test user
        List<User> userList    =   TestCaseUtil.createUser('Supervisor','Illinois Supervisor',1);
        insert userList;
        System.runAs(userList[0]){        
            
            
            //insert new parent and child cases
            Case pc = ds.insertDataForParentCases();  
            Case cc = ds.insertDataForChildCases(pc);            
            
            List<Case> cl = new List<Case>();
            cl.add(pc);
            cl.add(cc);
            
            Set<Id> parentCaseIdSet =  new Set<Id>();
            parentCaseIdSet.add(pc.id);
            parentCaseIdSet.add(cc.id);
            
            /*
* execute some stand alone methods
*/ 
            Test.StartTest();           
            CaseTriggerHandler.caseStatusUpdate(parentCaseIdSet);
            CaseTriggerHandler.UpdateCaseOwner(cl);
            //CaseTriggerHandler.validateUserRole(userList[0].id, 'IL1');
            //CaseTriggerHandler.validateUserRole(userList[0].id, 'OK1');
            CaseTriggerHandler.getChildCasesByParentStatus(parentCaseIdSet);
            CaseTriggerHandler.getChildCasesByParent(parentCaseIdSet);
            CaseTriggerHandler.casePriorityUpdate(parentCaseIdSet);    
            
            CaseComment casec = new CaseComment
                (
                    CommentBody = 'This is my test comment',
                    ParentId = pc.id,
                    IsPublished = true               
                );
            insert casec;            
            CaseTriggerHandler.getComments(pc,casec);
            ds.updateCase(cc,'status','Closed Processed');          
            ds.updateCase(pc, 'status', 'Closed Processed');
            ds.updateCase(cc, 'origin', 'Web On-boarding');
            ds.updateCase(pc, 'origin', 'Web On-boarding');   
            ds.updateCase(cc, 'ownerid', '0053C000000Fl9hQAC');
            ds.updateCase(pc, 'ownerid', '0053C000000Fl9hQAC');             
            ds.updateCase(pc, 'priority', 'High');
            Test.StopTest(); 
            
            //insert new parent and child cases
        }        
    }   
    
    static testmethod void updateMasterCaseForPedi()
    {
        /*string strIndvCredRecTypeId  = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Provider_On_boarding_Credentialing').getRecordTypeId();

        GlobalSettings__c gs  =  new GlobalSettings__c();
        gs.name         =  'PFFileRecieved';
        gs.PFFileRecieved__c  =  false;
        gs.Record_Type_Names__c  =  'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        gs.Credentialing_record_types__c = strIndvCredRecTypeId;
        insert gs; */
         TestDataFactory tdf = new TestDataFactory();
        tdf.InsertGlobalsetting();
        
        Account newAccount = TestCaseUtil.createAccount();  
        CM_Provider_Identification__c provIdentification = new CM_Provider_Identification__c();
        provIdentification.CM_PI_Prov__c = newAccount.Id;
        provIdentification.CM_Prvdr_Iden_Typ_Cd__c = 'License'; 
        provIdentification.CM_Issu_Ident_Nmbr__c = '12345';
        insert provIdentification; 
        List<Case> listOfCases = new List<Case>();
        Id groupContracting,groupOnboarding,groupCredentialing,groupNetworking,contractingRecType,countersignRecType;       
        for(RecordType newType:[Select Id,developerName from RecordType where (DeveloperName='Provider_Group_Onboarding_Contracting' OR DeveloperName='Provider_On_boarding' OR DeveloperName = 'Contracting_Provider_On_boarding' OR
                                                                               DeveloperName='Provider_Group_On_boarding_Credentialling' OR DeveloperName='Provider_Group_On_boarding_Network_Load' OR DeveloperName='Provider_On_boarding_Counter_Sign') AND SObjecttype='Case'])
        {
            if(newType.developerName=='Provider_Group_Onboarding_Contracting')
            {
                groupContracting=newType.Id;
            }
            if(newType.developerName=='Provider_On_boarding')
            {
                groupOnboarding=newType.Id;
            }
            if(newType.developerName=='Provider_Group_On_boarding_Credentialling')
            {
                groupCredentialing=newType.Id;
            }
            if(newType.developerName=='Provider_Group_On_boarding_Network_Load')
            {
                groupNetworking=newType.Id;
            }
            if(newType.developerName == 'Contracting_Provider_On_boarding'){
                contractingRecType = newType.Id;
            }
            if(newType.developerName=='Provider_On_boarding_Counter_Sign')
            {
                countersignRecType =newType.Id;
            }
        }
        Case parentCase = new Case();
        parentCase.Plan_ID__c='IL1';
        parentCase.RecordTypeId=groupOnboarding;
        parentCase.subject='Testing';
        parentCase.Description='Testing';
        parentCase.status='New';           
        parentCase.Email_Address_Submitter__c = 'test@hcsc.net';
        parentCase.origin   ='Web-Onboarding';
        parentCase.Completing_the_form_for__c='Group';
        parentCase.accountId = newAccount.Id;
        //parentCase.ownerId = userList[1].id;
        insert parentCase;
        
        
        
        Case counterCase = new Case();
        counterCase.Plan_ID__c='IL1';
        counterCase.Email_Address_Submitter__c = 'test@hcsc.net';
        counterCase.origin   ='Web On-boarding';
        counterCase.parentId=parentCase.Id;
        counterCase.status='New';
        counterCase.subject='Test';
        counterCase.Description='Test';
        counterCase.Network_Name__c ='a-b,b-c,c-d'; 
        counterCase.Completing_the_form_for__c='Group';        
        counterCase.RecordTypeId=groupContracting; 
        counterCase.accountId = newAccount.Id;
        
        insert counterCase;

        Case contractCase = new Case();
        contractCase.Plan_ID__c='IL1';
        contractCase.Email_Address_Submitter__c = 'test@hcsc.net';
        contractCase.origin   ='Web On-boarding';
        contractCase.parentId=parentCase.Id;
        contractCase.status='New';
        contractCase.subject='Test';
        contractCase.Description='Test';
        contractCase.Network_Name__c ='a-b,b-c,c-d'; 
        contractCase.Completing_the_form_for__c='Group';        
        contractCase.RecordTypeId=contractingRecType;
        contractCase.accountId=newAccount.Id;
        //contractCase.ownerId = userList[0].id;
        
        insert contractCase;
        
        contractCase.status = 'InProgress';
        update contractCase;
        Test.startTest();
       
        Provider_Networks__c newNetwork = new Provider_Networks__c();
        newNetwork.Contracting_Case__c= contractCase.Id;
        newNetwork.Prov_ID__c='5324525';
        newNetwork.Cred_Status__c='Needs Credentialing';
        //insert newNetwork;
        
       
        Provider_Networks__C newNetwork2 = new Provider_Networks__c();
        newNetwork2.Contracting_Case__c=contractCase.Id;
        newNetwork2.Prov_ID__c='5324525';
        newNetwork2.Cred_Status__c='No Credentialing Needed';
        //insert newNetwork2;       
        
        
        
        for(Integer count=0;count<1;count++)
        {
            Case newNetworking = new Case();
            newNetworking.Plan_ID__c='IL1';
            //newNetworking.Email_Address_Submitter__c = 'test@hcsc.net';
            newNetworking.origin   ='Web On-boarding';
            newNetworking.parentId=parentCase.Id;
            newNetworking.status='New';
            newNetworking.subject='Test';
            newNetworking.Description='Test';
            newNetworking.Network_Name__c ='a-b,b-c,c-d'; 
            newNetworking.Network_Effective_Date__c = system.today(); 
            newNetworking.Completing_the_form_for__c='Group';        
            newNetworking.RecordTypeId=groupCredentialing; 
            listOfCases.add(newNetworking);
        }
        insert listOfCases;
        Case newCase=[Select status from Case Where RecordTypeId=:groupCredentialing and ParentId=:parentCase.Id];
        newCase.status='Cred Approved';
        update newCase;
        
        List<case> caseList = [Select status from Case Where RecordTypeId=:groupNetworking and ParentId=:parentCase.Id];
        if(!caseList.isEmpty()){
           Case newNetworkCase = new Case(Id=caseList[0].Id) ;
            newNetworkCase.status='Closed Processed';
            newNetworkCase.Completing_the_form_for__c='Group';
            newNetworkCase.Network_name__c = 'Network1;Network2;Network3';
            newNetworkCase.External_Comments__c = 'External Comments';
            newNetworkCase.Contract_PFIN__c='test';
            newNetworkCase.accountId=newAccount.Id;
            newNetworkCase.Network_Effective_Date__c = Date.newInstance(2016, 12, 9);
            update newNetworkCase;  
        }
        
     Test.stopTest();   
    }
    
 static testmethod void updateMasterCaseForPedi1()
    {
       
        /*test.startTest();
        /*string strIndvCredRecTypeId  = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Provider_On_boarding_Credentialing').getRecordTypeId();

        GlobalSettings__c gs  =  new GlobalSettings__c();
        gs.name         =  'PFFileRecieved';
        gs.PFFileRecieved__c  =  false;
        gs.Record_Type_Names__c  =  'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        gs.Credentialing_record_types__c = strIndvCredRecTypeId;
        insert gs; 
         TestDataFactory tdf = new TestDataFactory();
        tdf.InsertGlobalsetting();
        Account newAccount = TestCaseUtil.createAccount();        
        List<Case> listOfCases = new List<Case>();
        Id groupOnboarding,groupOnboarding1,pfinProviderRectypeId, contProviderRecType ;       
        for(RecordType newType:[Select Id,developerName from RecordType where (DeveloperName='Provider_On_boarding'OR DeveloperName='Data_Entry_Group_Provider_On_boarding') AND SObjecttype='Case'])
        {
            
            if(newType.developerName=='Data_Entry_Group_Provider_On_boarding')
            {
                groupOnboarding1=newType.Id;
            }
            if(newType.developerName=='Provider_On_boarding')
            {
                groupOnboarding=newType.Id;
            }
           
        }
        for(RecordType newType:[Select Id,developerName from RecordType where (DeveloperName='PFIN_Onboarding' or DeveloperName = 'Contracting_Onboarding') AND SObjecttype='Provider_Networks__c'])
        {
        
          if(newType.developerName =='PFIN_Onboarding')
            {
                pfinProviderRectypeId =newType.Id;
            }
          else if(newType.developerName == 'Contracting_Onboarding'){
                contProviderRecType = newType.Id;
            }
        }
        Case parentCase = new Case();
        parentCase.Plan_ID__c='IL1';
        parentCase.RecordTypeId=groupOnboarding;
        parentCase.subject='Testing';
        parentCase.Description='Testing';
        parentCase.status='New';           
        parentCase.Email_Address_Submitter__c = 'test@hcsc.net';
        parentCase.origin   ='Web-Onboarding';
        parentCase.Completing_the_form_for__c='Group';
        parentCase.accountId = newAccount.Id;
        insert parentCase;
        
        Case pfinCase= new Case();
        pfinCase.Plan_ID__c='IL1';
        pfinCase.Email_Address_Submitter__c = 'test@hcsc.net';
        pfinCase.origin   ='Web On-boarding';
        pfinCase.parentId=parentCase.Id;
        pfinCase.status='New';
        pfinCase.subject='Test';
        pfinCase.Description='Test';
        pfinCase.Network_Name__c ='a-b,b-c,c-d'; 
        pfinCase.Completing_the_form_for__c='Group';        
        pfinCase.RecordTypeId=groupOnboarding1; 
        pfinCase.Billing_NPI_Number__c = '0123456789';
        pfinCase.Telephone_Number_Submitter__c ='(987) 456-1230';
        pfinCase.Tax_Id_Number__c ='012345689';
        pfinCase.Email_Address_Submitter__c ='test@gmail.com';
        pfinCase.Name_Submitter__c='testjohn';
        pfinCase.Title_Submitter__c='Mr';
        pfinCase.Plan_ID__c='012';
        pfinCase.accountId = newAccount.Id;        
        insert pfinCase;
        
        pfinCase.paper_cred_indicator__c = true;
        update pfinCase;
        
        Provider_Networks__C newNetwork1 = new Provider_Networks__c();
        newNetwork1.PFIN_Case__c=pfinCase.Id;
        newNetwork1.Prov_ID__c='5324525';
        newNetwork1.RecordTypeId=pfinProviderRectypeId;
        insert newNetwork1;
        
        pfinCase.status='Closed Processed';
        update pfinCase;
        
        List<Provider_Networks__c> provList = new List<Provider_Networks__c>();
        for(Provider_Networks__c pfinNet : [SELECT Id, Cred_Status__c, PFIN_onBoarding__c, Network_Code_Name__c, Prov_ID__c, PFIN__c FROM Provider_Networks__c WHERE contracting_Case__r.parentId =: parentCase.Id AND recordTypeId =: contProviderRecType]){
            Provider_Networks__c prov = new Provider_Networks__c(Id = pfinNet.Id);
            prov.PFIN_onBoarding__c = '1234';
            prov.Network_Code_Name__c = 'Network Name';
            prov.Cred_Status__c = 'No Credentialing Needed';
            provList.add(prov);
        }
        
        update provList;
        
        test.StopTest();
*/
      
    }
    
     @isTest static void testMethod_6()
    {
       
        
        RoleAndPlanId_Settings__c   Rp =   new RoleAndPlanId_Settings__c();
        Rp.Name = 'Illinois Supervisor';
        Rp.Role_Id__c =   '00E41000000bXVsEAM';
        Rp.PlanId__c =   'IL1';
        insert Rp;  
        
        QueueIds__c   Q =   new QueueIds__c();
        Q.Name = 'IL Queue';
        Q.QueueId__c = '00G41000001U0qKEAS';
        Q.PlanId__c =  'IL1';
        insert Q;    
        
        /*string strIndvCredRecTypeId  = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Provider_On_boarding_Credentialing').getRecordTypeId();

        GlobalSettings__c gs  =  new GlobalSettings__c();
        gs.name         =  'PFFileRecieved';
        gs.PFFileRecieved__c  =  false;
        gs.Record_Type_Names__c  =  'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        gs.Credentialing_record_types__c = strIndvCredRecTypeId;
        insert gs; */
         TestDataFactory tdf = new TestDataFactory();
        tdf.InsertGlobalsetting();
      
        
           List<Case> caseList = new List<Case>();
            Case curCase = TestCaseUtil.CreateCase();
            caseList.add(curCase);
            
            
            insert caseList;
            
            list<case> casetlist = new list<case>();
            casetList = [select id,status,plan_id__c,OwnerId from case];
            casetList[0].OwnerId = '00G41000001U0qKEAS';
            casetList[0].status = 'Closed Processed';
            casetList[1].status = 'Closed Rejected';
            casetList[1].ParentId= casetList[0].Id;
            casetList[1].plan_id__c= 'IL1';
            casetList[1].OwnerId = '00G41000001U0qKEAS';
            casetList[2].plan_id__c = 'IL1';
            
            
            test.startTest();
            update casetList;
            test.stopTest();
       
           }    
   
    
   
    
    
}