src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedFromMarketingCloud__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When an account is created from or for Marketing Cloud, this checkbox will be checked.</description>
        <label>Created From Marketing Cloud</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <externalId>true</externalId>
        <label>NPI</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CorporateEntityCode__c</fullName>
        <label>Corporate Entity Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>MarketingCloud</fullName>
        <active>true</active>
        <description>Campaigns specific to Marketing Cloud</description>
        <label>Marketing Cloud</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignActivity__c.object
<CustomObject>
    <description>This object stores the campaign activity when communications are sent from Marketing Cloud.</description>
    <fields>
        <fullName>AccountName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Activity History</relationshipLabel>
        <relationshipName>Campaign_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActivityDescription__c</fullName>
        <label>Activity Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignActivityLevel__c</fullName>
        <label>Campaign Activity Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Payee Location Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CampaignName__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The campaign this activity is a part of.</inlineHelpText>
        <label>Campaign Name</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Activities</relationshipLabel>
        <relationshipName>Campaign_Activity_History</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CorporateEntityCode__c</fullName>
        <label>Corporate Entity Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreateAtRolodexAcctwithSameEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag that a user will set during the Marketing Cloud Journey. If checked and a campaign activity is inserted into the database, the campaign activity will be cloned and attached to Rolodex accounts that share the &quot;Sent To&quot; email address.</description>
        <label>Create at Rolodex Acct with Same Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateAtServiceLocWithSameEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag that a user will set during the Marketing Cloud Journey. If checked and a campaign activity is inserted into the database, the campaign activity will be cloned and attached to Service locations that share the &quot;Sent To&quot; email address.</description>
        <label>Create at Service Loc with Same Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreatedFromMarketingCloud__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created From Marketing Cloud</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SentTo__c</fullName>
        <label>Sent To</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ServiceAndPayeeLocationAddress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service &amp; Payee Location Address</label>
        <referenceTo>CM_SPL_Addr__c</referenceTo>
        <relationshipLabel>Campaign Activity History</relationshipLabel>
        <relationshipName>Campaign_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Activity</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Activity Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CM_SPL_Addr__c.object
<CustomObject>
    <description>Service &amp; Payee Location Address Object based on PFIN Number</description>
    <fields>
        <fullName>Bill_PFIN__c</fullName>
        <description>Part of 40kpfin user stories.</description>
        <label>Bill PFIN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Addr_Type__c</fullName>
        <description>Provider Address Usage Type</description>
        <inlineHelpText>Provider Address Usage Type</inlineHelpText>
        <label>Address Usage Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Capitation</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Directory</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Credentialing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CM_SPL_Email__c</fullName>
        <description>Email</description>
        <inlineHelpText>Email</inlineHelpText>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_PFIN_No__c</fullName>
        <label>PFIN Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service &amp; Payee Location Address</relationshipLabel>
        <relationshipName>Account_Tax_Addresses_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service &amp; Payee Location Address</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Address Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service &amp; Payee Location Address</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CampaignActivityTriggerHandlerTest.cls
/**
 * This is the test class for the Campaign Activity Trigger and Handler
 * <p/><p/>
 * @author Travis Self
 */
@isTest
public class CampaignActivityTriggerHandlerTest {

	@testSetup static void createTestData() {
        
        TestDataFactory tdf = new TestDataFactory();
        TestDataFactory.prepareData();
        
        // Create a non-rolodex account
        Account testAccount = TestDataFactory.CreateAccount('IL1');
        
        // Create 3 service & payee locations
        List<CM_SPL_Addr__c> lstServiceAndPayee = new List<CM_SPL_Addr__c>();
        CM_SPL_Addr__c svp = new CM_SPL_Addr__c();
        svp.CM_Corporate_Entity_Code__c = 'IL1';
        svp.CM_SPL_PFIN_No__c = '0IL12345';
        svp.Bill_PFIN__c = '0IL12345';
        svp.CM_SPL_Prov__r = testAccount;
        svp.CM_SPL_Addr_Type__c = 'Service';
        svp.CM_SPL_Email__c = 'travis_self@bcbsok.com';
        lstServiceAndPayee.add(svp);
        lstServiceAndPayee.add(svp.clone());
        lstServiceAndPayee.add(svp.clone());
        insert lstServiceAndPayee;
        
        // Create a rolodex account
        Account rolodexAcc = new Account();
        rolodexAcc.LastName = 'Test';
        rolodexAcc.PersonEmail = 'travis_self@bcbsok.com';
        rolodexAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Rolodex').getRecordTypeId();
        rolodexAcc.Phone = '9185512503';
        rolodexAcc.Type = 'Individual';
        rolodexAcc.Tax_Id__c = '123456789';
        rolodexAcc.NPI__c = '0123456789';
        rolodexAcc.CM_Corporate_Entity_Code__c = 'IL1';
        insert rolodexAcc;
        
        // Create a campaign
        Campaign testCampaign = new Campaign();
        testCampaign.Name = 'IL Blue Review';
        testCampaign.Description = 'This is a test campaign.';
        testCampaign.CorporateEntityCode__c = 'IL1';
        testCampaign.IsActive = true;
        testCampaign.StartDate = Date.today();
        testCampaign.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('MarketingCloud').getRecordTypeId();
        insert testCampaign;
    }
    
    @isTest
    static void campaignActivityCloneTest() {
        
        List<CampaignActivity__c> lstCampaignActivities = createCampaignActivities(1);
        
        Test.startTest();
        
        	insert lstCampaignActivities;
        
        Test.stopTest();
        
        System.assertEquals(4, [SELECT count() FROM CampaignActivity__c]);
        
        delete lstCampaignActivities;
    }
    
    @isTest
    static void campaignActivityBulkTriggerTest() {
        
        List<CampaignActivity__c> lstCampaignActivities = createCampaignActivities(1000);
        
        Test.startTest();
        
        	insert lstCampaignActivities;
        
        Test.stopTest();
        
        System.assertEquals(1000, [SELECT count() FROM CampaignActivity__c WHERE CreatedFromMarketingCloud__c = true]);
    }
    
   /**
    * This method will start the creation of campaign history activities
    * 
    * @param numToCreate Number of campaign activities to create
    * @return List of campaign activities
    */ 
    static List<CampaignActivity__c> createCampaignActivities(Integer numToCreate) {
        
        Account testAccount = [SELECT Id FROM Account WHERE NOT(RecordType.DeveloperName = 'Rolodex') LIMIT 1];
        CM_SPL_Addr__c testServiceAndPayee = [SELECT Id FROM CM_SPL_Addr__c LIMIT 1];
        Campaign testCampaign = [SELECT Id FROM Campaign LIMIT 1];
        
        List<CampaignActivity__c> lstCampaignActivities = new List<CampaignActivity__c>();
        
        for(Integer i=0; i < numToCreate; i++) {
            CampaignActivity__c testCampaignActivity = new CampaignActivity__c();
            testCampaignActivity.ActivityDescription__c = 'Email Sent' + i;
            testCampaignActivity.CorporateEntityCode__c = 'IL1';
            testCampaignActivity.CampaignActivityLevel__c = 'Service & Payee Location Address';
            testCampaignActivity.CampaignName__c = testCampaign.Id;
            testCampaignActivity.Date__c = Date.today();
            testCampaignActivity.SentTo__c = 'travis_self@bcbsok.com';
            testCampaignActivity.CreateAtRolodexAcctwithSameEmail__c = true;
            testCampaignActivity.CreateAtServiceLocWithSameEmail__c = true;
            testCampaignActivity.CreatedFromMarketingCloud__c = true;
            testCampaignActivity.AccountName__c = testAccount.Id;
            testCampaignActivity.ServiceAndPayeeLocationAddress__c = testServiceAndPayee.Id;
            lstCampaignActivities.add(testCampaignActivity);
        }
        
        return lstCampaignActivities;
    }   
}