src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Entity_Account</fullName>
        <active>true</active>
        <description>Business Entities (not People).  Hospitals, Clinics, Groups, Locations, Facilities, etc</description>
        <label>Entity Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Person_Account</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Affiliations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name (Entity / Individual)</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Affiliated_Provider_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliated Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Affiliations</label>
    <nameField>
        <displayFormat>A{0}</displayFormat>
        <label>Affiliation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_size__c</fullName>
        <label>List size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/classes/TestEmbeddedHospitalAffiliations_Ext.cls
/**************************************************************************************************
Apex Class Name  : TestEmbeddedHospitalAffiliations_Ext 
Version          : 1.0  
Functionality    : 
Modification Log : 07/02/2018 Created by  SethuRaman
****************************************************************************************************/

@isTest
public class TestEmbeddedHospitalAffiliations_Ext{
public static List<Account> accountList;
    public static testmethod void createTestData()
    {
        GlobalSettings__c gs	=	new GlobalSettings__c();
        gs.name 				=	'PFFileRecieved';
        gs.PFFileRecieved__c	=	false;
        gs.List_size__c			=	10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c	=	'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;  
        
        Id entityRecTypeId = [SELECT Id, Name FROM RecordType WHERE developerName = 'Entity_Account' LIMIT 1].Id;
        Id physicianRecTypeId = [SELECT Id, Name FROM RecordType WHERE developerName = 'Person_Account' LIMIT 1].Id;
        
        accountList = new List<Account>();        
        Account entityAcct = new Account(name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'IL1', recordtypeid = entityRecTypeId ); //recordtypeid is for entity account 
        accountList.add(entityAcct);
        Account physicianAcct = new Account(name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'IL1',Class__c='P', recordtypeid = physicianRecTypeId); //recordtypeid is for person account 
        accountList.add(physicianAcct);        
        insert accountList;        
        
        List<Affiliations__c> affList = new List<Affiliations__c>();
        Affiliations__c aff1 = new Affiliations__c(CM_Affiliated_Provider_Name__c = entityAcct.Id, Account__c = physicianAcct.Id);
        affList.add(aff1);
        Affiliations__c aff2 = new Affiliations__c(CM_Affiliated_Provider_Name__c = physicianAcct.Id, Account__c = entityAcct.Id);
        affList.add(aff2);
        insert affList;
    }
    
    public static testmethod void defaultLoad(){
        
        GlobalSettings__c gs	=	new GlobalSettings__c();
        gs.name 				=	'PFFileRecieved';
        gs.PFFileRecieved__c	=	false;
        gs.List_size__c			=	10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c	=	'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;  
        
        createTestData();        
        ApexPages.StandardController sc = new ApexPages.StandardController(accountList[0]);
        EmbeddedHospitalAffiliations_Ext extension = new EmbeddedHospitalAffiliations_Ext(sc);        
        PageReference pageRef = Page.embeddedHospitalAffiliations;
        Test.setCurrentPage(pageRef);
        extension.getItems();
        extension.getType();
        extension.setType('All');
        extension.selectedTypeList();
    }
    
    public static testmethod void onchange(){
        GlobalSettings__c gs	=	new GlobalSettings__c();
        gs.name 				=	'PFFileRecieved';
        gs.PFFileRecieved__c	=	false;
        gs.List_size__c			=	10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c	=	'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;  
        createTestData();        
        ApexPages.StandardController sc = new ApexPages.StandardController(accountList[1]);
        EmbeddedHospitalAffiliations_Ext extension = new EmbeddedHospitalAffiliations_Ext(sc);        
        PageReference pageRef = Page.embeddedHospitalAffiliations;
        Test.setCurrentPage(pageRef);
        extension.getItems();
        extension.getType();
        extension.setType('Rolodex');
        extension.selectedTypeList();
    }
}