src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Entity_Account</fullName>
        <active>true</active>
        <description>Business Entities (not People).  Hospitals, Clinics, Groups, Locations, Facilities, etc</description>
        <label>Entity Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CaseLockStatus__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <externalId>true</externalId>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CaseLockStatus</label>
</CustomObject>

src/objects/CaseProfile__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ProfileName__c</fullName>
        <label>ProfileName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CaseProfile</label>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/RecordType_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <description>This field is to hold the record type developer name</description>
        <inlineHelpText>Record type developer name</inlineHelpText>
        <label>DeveloperName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>This field is to hold record type name</description>
        <inlineHelpText>Record type Name</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_type_Id__c</fullName>
        <description>This field is to hold the record type Id</description>
        <inlineHelpText>Record type Id</inlineHelpText>
        <label>Record type Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObject_Type__c</fullName>
        <description>This field is to hold the object name</description>
        <inlineHelpText>Object Name</inlineHelpText>
        <label>sObject Type</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordType settings</label>
</CustomObject>

src/classes/TestCaseCommentTriggerHandler.cls
@isTest
public class TestCaseCommentTriggerHandler{
    
    static user u;
    
    @testSetup static void prepareData() {
        
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        
        List<RecordType_settings__c> rtsList	=	 new List<RecordType_settings__c>();
        List<RecordType> recordTypeList	= [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType];
        for( RecordType recType : recordTypeList  )
        {
            RecordType_settings__c rts 	=	new RecordType_settings__c();
            rts.name					=	recType.Id;
            rts.DeveloperName__c	   	=	recType.DeveloperName;
            rts.Name__c					=	recType.Name;
            rts.Record_type_Id__c		=	recType.Id;
            rts.sObject_Type__c			=	recType.SobjectType;
            rtsList.add(rts);
        }
        insert rtsList;
        
        CaseProfile__c cp    =    new CaseProfile__c();
        cp.Name              =    'Supervisor';
        cp.ProfileName__c    =    'Supervisor';
        insert cp;
        
        CaseLockStatus__c cls     =    new CaseLockStatus__c();
        cls.Status__c             =    'Prod Verification';
        cls.Name                  =    'Prod Verification';
        insert cls;
    }
	 
    public static testMethod void test1_CaseCommentTriggerHandler() {      
        
        Account acc = new Account();
        acc.RecordTypeId = [SELECT Id, DeveloperName From RecordType WHERE RecordType.DeveloperName = 'Entity_Account'].Id;
        acc.Name = 'Test Entity';
        acc.CM_Corporate_Entity_Code__c = 'IL1';
        insert acc;
        
        Case  mCase = TestCaseUtil.CreateCase();
        mCase.Status = 'Prod Verification';
        mCase.RecordTypeId = [SELECT Id, DeveloperName FROM RecordType WHERE RecordType.DeveloperName = 'Email' and sobjectType='Case' limit 1].Id;
        mCase.Origin = 'Ancillary Gov Expansion';
        mCase.Case_Entity__c = acc.Id;
        mCase.AccountId = null;
        insert mCase;
        
        User u = [SELECT Id, Name FROM User WHERE UserRole.DeveloperName = 'Illinois_Supervisor' AND Profile.Name = 'Supervisor' AND isActive = true LIMIT 1];
        
        Test.startTest();
        
            System.runAs(u) {
                
                CaseComment cc = new CaseComment();
                cc.CommentBody = 'test';
                cc.ParentId = mCase.Id;
            
                insert cc;
                update cc;
                delete cc;
            }
        
        Test.stopTest();

    }
}