src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Acceptable_Plan_Ids__c</fullName>
        <label>Acceptable Plan Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>MCC trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/MCC_Data_Object__c.object
<CustomObject>
    <description>Intermediate object for Mass Case Creation and Death File.</description>
    <fields>
        <fullName>File_Count__c</fullName>
        <description>This field will hold the count the no rows processed within the mass file uploads ( Tx Recruitment, Il Roaster , Mass case closure and mass Cred status update)</description>
        <label>File Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>MCC_Data_Object</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Status__c</fullName>
        <label>Case Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Type__c</fullName>
        <label>Case Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Id__c</fullName>
        <label>File Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Type__c</fullName>
        <label>File Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Grouping_ID__c</fullName>
        <description>TX Specific</description>
        <label>Grouping ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Plan_ID__c</fullName>
        <description>For all loads</description>
        <label>Plan ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MCC_Project_Number__c</fullName>
        <description>TX Specific</description>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Prov_ID__c</fullName>
        <description>For Death and TX Data</description>
        <label>Provider ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Request_Type__c</fullName>
        <label>Request Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Mass Case Creation Record</label>
    <nameField>
        <displayFormat>MCC-{0000}</displayFormat>
        <label>MCC Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Case Creation Records</pluralLabel>
    <recordTypes>
        <fullName>Network_Recruitment</fullName>
        <active>true</active>
        <description>Network Recruitment</description>
        <label>Network Recruitment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Roster</fullName>
        <active>true</active>
        <description>Roster</description>
        <label>Roster</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MCC_Report_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>MCC success/failure reporting email recipients</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mass Case Creation Reporting Users</label>
</CustomObject>

src/objects/RecordType_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <description>This field is to hold the record type developer name</description>
        <inlineHelpText>Record type developer name</inlineHelpText>
        <label>DeveloperName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>This field is to hold record type name</description>
        <inlineHelpText>Record type Name</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_type_Id__c</fullName>
        <description>This field is to hold the record type Id</description>
        <inlineHelpText>Record type Id</inlineHelpText>
        <label>Record type Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObject_Type__c</fullName>
        <description>This field is to hold the object name</description>
        <inlineHelpText>Object Name</inlineHelpText>
        <label>sObject Type</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordType settings</label>
</CustomObject>

src/classes/MCCReportSenderBatchTest.cls
@isTest
public class MCCReportSenderBatchTest 
{
    @testSetup static void prepareData() {
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        List<RecordType_settings__c> rtsList    =    new List<RecordType_settings__c>();
        List<RecordType> recordTypeList = [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType];
        for( RecordType recType : recordTypeList  )
        {
            RecordType_settings__c rts  =   new RecordType_settings__c();
            rts.name                    =   recType.Id;
            rts.DeveloperName__c        =   recType.DeveloperName;
            rts.Name__c                 =   recType.Name;
            rts.Record_type_Id__c       =   recType.Id;
            rts.sObject_Type__c         =   recType.SobjectType;
            rtsList.add(rts);
        }
        insert rtsList;
    }
    
    static testmethod void finishMethod_NetworkRecruitment()
    {
        GlobalSettings__c gs = new GlobalSettings__c();
        gs.Name = 'PFFileRecieved';
        gs.Record_Type_Names__c = 'CRM;';
        gs.MCC_trigger_switch__c    =   false;
        gs.Acceptable_Plan_Ids__c   =   'IL1,MT1,NM1,OK1,TX1';    
        insert gs;
        
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'IL1'); 
        insert acct;  
        
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='TX1';
        insert cs; 
        
        MCC_Report_Users__c objreportUser=new MCC_Report_Users__c();           
        objreportUser.Email__c='test@bcbsil.com';
        objreportUser.name='test user';
        objreportUser.Plan_Id__c='TX1';
        insert objreportUser;          
        
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Network_recruitment'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test001';
        mcc.MCC_Grouping_ID__c = 'G001';
        mcc.MCC_Case_Type__c = 'CRM;';
        mcc.MCC_Request_Type__c = 'Network Recruitment';  
        mcc.MCC_Case_Status__c = 'New';   
        mcc.MCC_Plan_ID__c = 'TX1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File001'; 
        mcc.File_Count__c  = 1.0;
        mcc.MCC_Case_Id__c  =cs.id;               
        insert mcc;  
        
        Test.startTest();
            MCCReportSenderBatch bt = new MCCReportSenderBatch();
            Database.executeBatch( bt );
            System.Schedule('MCCreportSenderBatch', '0 0 * * * ?', new MCCReportSenderBatch());
       Test.stopTest(); 
    }
    
    
    
    static testmethod void finishMethod_RosterFile()
    {
        GlobalSettings__c gs = new GlobalSettings__c();
        gs.Name = 'PFFileRecieved';
        gs.Record_Type_Names__c = 'CRM;'; 
        gs.MCC_trigger_switch__c    =   false;
        gs.Acceptable_Plan_Ids__c   =   'IL1,MT1,NM1,OK1,TX1'; 
        insert gs;
        
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'IL1'); 
        insert acct;
        
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='IL1';
        insert cs;  
        
        MCC_Report_Users__c objreportUser=new MCC_Report_Users__c();           
        objreportUser.Email__c='test@bcbsil.com';
        objreportUser.name='test user';
        objreportUser.Plan_Id__c='IL1';
        insert objreportUser;            
        
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Roster'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test003';
        mcc.MCC_Grouping_ID__c = 'G003';
        mcc.MCC_Case_Type__c = 'CRM';
        mcc.MCC_File_Type__c = 'ILR';  
        mcc.MCC_Case_Status__c = 'New';   
        mcc.MCC_Plan_ID__c = 'IL1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File003';
        mcc.File_Count__c  = 1.0;
         mcc.MCC_Case_Id__c  =cs.id;                
        insert mcc;    
        
         
        Test.startTest();
            MCCReportSenderBatch bt = new MCCReportSenderBatch();
            Database.executeBatch( bt );
            System.Schedule('MCCreportSenderBatch', '0 0 * * * ?', new MCCReportSenderBatch());
       Test.stopTest(); 
        
   }
    static testmethod void finishMethod_masscaseCLose()
    {
        GlobalSettings__c gs = new GlobalSettings__c();
        gs.Name = 'PFFileRecieved';
        gs.Record_Type_Names__c = 'CRM;'; 
        gs.MCC_trigger_switch__c    =   false;
        gs.Acceptable_Plan_Ids__c   =   'IL1,MT1,NM1,OK1,TX1'; 
        insert gs;
        
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'TX1'); 
        insert acct;             
        
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='TX1';
        insert cs;
        
        MCC_Report_Users__c objreportUser=new MCC_Report_Users__c();           
        objreportUser.Email__c='test@bcbsil.com';
        objreportUser.name='test user';
        objreportUser.Plan_Id__c='TX1';
        insert objreportUser; 
        
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        //mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Roster'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test003';
        mcc.MCC_Grouping_ID__c = 'G003';
        mcc.MCC_Case_Type__c = 'CRM';
        mcc.MCC_File_Type__c = 'ADC Mass Status';  
        mcc.MCC_Case_Status__c = 'Closed Processed';   
        mcc.MCC_Plan_ID__c = 'TX1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File004';
        mcc.File_Count__c  = 1.0;
        mcc.MCC_Case_Id__c  =cs.id;              
        insert mcc;
        
         
        Test.startTest();
            MCCReportSenderBatch bt = new MCCReportSenderBatch();
            Database.executeBatch( bt );
            System.Schedule('MCCreportSenderBatch', '0 0 * * * ?', new MCCReportSenderBatch());
       Test.stopTest(); 
        
   }
    
    static testmethod void finishMethod_CredCase()
    {
        GlobalSettings__c gs = new GlobalSettings__c();
        gs.Name = 'PFFileRecieved';
        gs.Record_Type_Names__c = 'CRM;'; 
        gs.MCC_trigger_switch__c    =   false;
        gs.Acceptable_Plan_Ids__c   =   'IL1,MT1,NM1,OK1,TX1'; 
        insert gs;
        
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'IL1'); 
        insert acct;
        
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='IL1';
        insert cs;  
        
        MCC_Report_Users__c objreportUser=new MCC_Report_Users__c();           
        objreportUser.Email__c='test@bcbsil.com';
        objreportUser.name='test user';
        objreportUser.Plan_Id__c='IL1';
        insert objreportUser;            
        
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Roster'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test003';
        mcc.MCC_Grouping_ID__c = 'G003';
       mcc.MCC_File_Type__c = 'Onboarding Cred Mass Status Update';  
        mcc.MCC_Case_Status__c = 'Cred Denied'; 
        mcc.MCC_Case_Status__c = 'New';   
        mcc.MCC_Plan_ID__c = 'IL1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File003';
        mcc.File_Count__c  = 1.0;
         mcc.MCC_Case_Id__c  =cs.id;                
        insert mcc;    
        
         
        Test.startTest();
            MCCReportSenderBatch bt = new MCCReportSenderBatch();
            Database.executeBatch( bt );
            System.Schedule('MCCreportSenderBatch', '0 0 * * * ?', new MCCReportSenderBatch());
       Test.stopTest(); 
        
   }
   
   static testmethod void finishMethod_NetworkLoadMassStatus()
    {
        GlobalSettings__c gs = new GlobalSettings__c();
        gs.Name = 'PFFileRecieved';
        gs.Record_Type_Names__c = 'CRM;'; 
        gs.MCC_trigger_switch__c    =   false;
        gs.Acceptable_Plan_Ids__c   =   'IL1,MT1,NM1,OK1,TX1'; 
        insert gs;
        
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'IL1'); 
        insert acct;
        
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='IL1';
        insert cs;  
        
        MCC_Report_Users__c objreportUser=new MCC_Report_Users__c();           
        objreportUser.Email__c='test@bcbsil.com';
        objreportUser.name='test user';
        objreportUser.Plan_Id__c='IL1';
        insert objreportUser;            
        
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Roster'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test003';
        mcc.MCC_Grouping_ID__c = 'G003';
       mcc.MCC_File_Type__c = 'Network Load Mass Status';  
        mcc.MCC_Case_Status__c = 'Cred Denied'; 
        mcc.MCC_Case_Status__c = 'New';   
        mcc.MCC_Plan_ID__c = 'IL1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File003';
        mcc.File_Count__c  = 1.0;
         mcc.MCC_Case_Id__c  =cs.id;                
        insert mcc;    
        
         
        Test.startTest();
            MCCReportSenderBatch bt = new MCCReportSenderBatch();
            Database.executeBatch( bt );
            System.Schedule('MCCreportSenderBatch', '0 0 * * * ?', new MCCReportSenderBatch());
       Test.stopTest(); 
        
   }
   
   
   static testmethod void finishMethod_MassCRMCreation()
    {
        GlobalSettings__c gs = new GlobalSettings__c();
        gs.Name = 'PFFileRecieved';
        gs.Record_Type_Names__c = 'CRM;'; 
        gs.MCC_trigger_switch__c    =   false;
        gs.Acceptable_Plan_Ids__c   =   'IL1,MT1,NM1,OK1,TX1'; 
        insert gs;
        
        Account acct = new Account( name = 'Test Company Name', CM_Corporate_Entity_Code__c = 'IL1'); 
        insert acct;
        
        Case cs=new Case();
        cs.status='New';
        cs.Plan_ID__c='IL1';
        insert cs;  
        
        MCC_Report_Users__c objreportUser=new MCC_Report_Users__c();           
        objreportUser.Email__c='test@bcbsil.com';
        objreportUser.name='test user';
        objreportUser.Plan_Id__c='IL1';
        insert objreportUser;            
        
        MCC_Data_Object__c mcc = new MCC_Data_Object__c();
        mcc.recordTypeId = [Select RecordType.DeveloperName From RecordType  Where SobjectType = 'MCC_Data_Object__c' and DeveloperName =: 'Roster'].Id;
        mcc.MCC_Prov_ID__c = acct.Id;
        mcc.MCC_Project_Number__c = 'Test003';
        mcc.MCC_Grouping_ID__c = 'G003';
       mcc.MCC_File_Type__c = 'Mass CRM Creation';  
        mcc.MCC_Case_Status__c = 'Cred Denied'; 
        mcc.MCC_Case_Status__c = 'New';   
        mcc.MCC_Plan_ID__c = 'IL1';
        mcc.MCC_Priority__c = 'High'; 
        mcc.MCC_File_Id__c = 'File003';
        mcc.File_Count__c  = 1.0;
         mcc.MCC_Case_Id__c  =cs.id;                
        insert mcc;    
        
         
        Test.startTest();
            MCCReportSenderBatch bt = new MCCReportSenderBatch();
            Database.executeBatch( bt );
            System.Schedule('MCCreportSenderBatch', '0 0 * * * ?', new MCCReportSenderBatch());
       Test.stopTest(); 
        
   }
    
}