src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Affiliations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name (Entity / Individual)</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Affiliated_Provider_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliated Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Affiliation_Code_Description__c</fullName>
        <label>Affiliation Code Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Billing_PFIN__c</fullName>
        <label>Billing PFIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Affiliation End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Converted to multi-select picklist as part of PPN-18792</description>
        <label>Role(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Assistant</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Associate General Counsel</fullName>
                </value>
                <value>
                    <fullName>Biller</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Billing Clerk</fullName>
                </value>
                <value>
                    <fullName>Billing Manager</fullName>
                </value>
                <value>
                    <fullName>Billing Practice Manager</fullName>
                </value>
                <value>
                    <fullName>Billings Clinic</fullName>
                </value>
                <value>
                    <fullName>Business Manager</fullName>
                </value>
                <value>
                    <fullName>Business Office Manager</fullName>
                </value>
                <value>
                    <fullName>CAO</fullName>
                </value>
                <value>
                    <fullName>Case Management</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CEO interim</fullName>
                </value>
                <value>
                    <fullName>Chief Dev Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Medical Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Operating Officer</fullName>
                </value>
                <value>
                    <fullName>Clinic Biller</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Credentialing</fullName>
                </value>
                <value>
                    <fullName>Credentialing Coordinator</fullName>
                </value>
                <value>
                    <fullName>Dir. Payer Relations</fullName>
                </value>
                <value>
                    <fullName>Director of Care Coordination</fullName>
                </value>
                <value>
                    <fullName>Director of Finance</fullName>
                </value>
                <value>
                    <fullName>Director of Patient Accounting</fullName>
                </value>
                <value>
                    <fullName>Physician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Affiliation Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(NOT(CM_Affiliated_Provider_Name__r.IsPersonAccount), &apos;Entity&apos;, 
IF(AND(CM_Affiliated_Provider_Name__r.IsPersonAccount, ISPICKVAL(CM_Affiliated_Provider_Name__r.Class__c,&apos;P&apos;)),&apos;Physician&apos;, 
IF(AND(CM_Affiliated_Provider_Name__r.IsPersonAccount, CM_Affiliated_Provider_Name__r.RecordType.DeveloperName=&apos;Rolodex&apos;), 
&apos;Rolodex&apos;,&apos;&apos; 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Affiliations</label>
    <nameField>
        <displayFormat>A{0}</displayFormat>
        <label>Affiliation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EmbeddedHospitalAffiliations_Ext.cls
/**************************************************************************************************
Apex Class Name  : EmbeddedHospitalAffiliations_Ext 
Version          : 1.0  
Functionality    : 
Modification Log : 06/28/2018 Created by  SethuRaman
****************************************************************************************************/
public class EmbeddedHospitalAffiliations_Ext {
    String type;
    Public Boolean isEmptyList {get;set;}
    Public Boolean isOnchange {get;set;}
    Public Account acc {get;set;}
    Public List<Affiliations__c> affiliationList{get;set;}
    
    public embeddedHospitalAffiliations_Ext(ApexPages.StandardController controller) {
        this.acc = (Account)controller.getRecord();
        affiliationList = new List<Affiliations__c>();
        isEmptyList = false;
        isOnchange = false;
    }
    
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('All','All'));
        options.add(new SelectOption('Physician','Physician'));
        options.add(new SelectOption('Entity','Entity'));
        options.add(new SelectOption('Rolodex','Rolodex'));
        return options;
    }
    
    public String getType() {
        return type;
    }
 
    public void setType(String type) {
        this.type= type;
    }
    
    public void selectedTypeList(){
         system.debug('****** Inside selectedTypeList type *****' + type);   
         if(type != NULL){
             affiliationList = new List<Affiliations__c>();
             isOnchange = true;
             if(type == 'All')
             {
                 affiliationList = [SELECT Id, Name, Role__c, Account__c, CM_Affiliated_Provider_Name__c, Account__r.name, CM_Affiliated_Provider_Name__r.RecordType.Name ,Account__r.RecordType.Name, CM_Affiliated_Provider_Name__r.name, Start_Date__c, End_Date__c, CM_Billing_PFIN__c, Type__c, CM_Affiliation_Code_Description__c FROM Affiliations__c WHERE (CM_Affiliated_Provider_Name__c =: acc.Id OR Account__c =: acc.Id )];
             }
             else
             {
                 affiliationList = [SELECT Id, Name, Role__c, Account__c, CM_Affiliated_Provider_Name__c, Account__r.name, CM_Affiliated_Provider_Name__r.RecordType.Name, CM_Affiliated_Provider_Name__r.name, Account__r.RecordType.Name, Start_Date__c, End_Date__c, CM_Billing_PFIN__c, Type__c, CM_Affiliation_Code_Description__c FROM Affiliations__c WHERE Type__c =: type AND (CM_Affiliated_Provider_Name__c =: acc.Id OR Account__c =: acc.Id)];
             }
             system.debug('##### affiliationList size #####' + affiliationList.size());
             system.debug('##### affiliationList #####' + affiliationList);
             if(affiliationList.size() == 0){
                 isEmptyList  = true;
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'No records found.'));
             }
             else{
                 isEmptyList = false;
             }
             system.debug('##### isOnchange  #####' + isOnchange );
             system.debug('##### isEmptyList #####' + isEmptyList );
         }

    }

}