src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OMNI_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Case_Type_Name_Origin__c</fullName>
        <label>CaseType Name / Origin</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demographics</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>Govt Cases</fullName>
                </value>
                <value>
                    <fullName>Network Change</fullName>
                </value>
                <value>
                    <fullName>Other Provider Updates</fullName>
                </value>
                <value>
                    <fullName>Web On-boarding - Contracting</fullName>
                </value>
                <value>
                    <fullName>Web On-boarding - Data Entry</fullName>
                </value>
                <value>
                    <fullName>Ancillary Networks</fullName>
                </value>
                <value>
                    <fullName>Balance Billing</fullName>
                </value>
                <value>
                    <fullName>Delegated Credentialing</fullName>
                </value>
                <value>
                    <fullName>Fee Schedule Requests</fullName>
                </value>
                <value>
                    <fullName>Gov Netops Provider Update</fullName>
                </value>
                <value>
                    <fullName>Gov Providers</fullName>
                </value>
                <value>
                    <fullName>HCS-X6100</fullName>
                </value>
                <value>
                    <fullName>HMO Networks</fullName>
                </value>
                <value>
                    <fullName>Internal PNC Inquiries</fullName>
                </value>
                <value>
                    <fullName>Netops Provider Update</fullName>
                </value>
                <value>
                    <fullName>Network Roster Submission</fullName>
                </value>
                <value>
                    <fullName>OK Network Management</fullName>
                </value>
                <value>
                    <fullName>PNC NetOps Inquiries</fullName>
                </value>
                <value>
                    <fullName>PPN CorpusChristi</fullName>
                </value>
                <value>
                    <fullName>PPN EIPaso</fullName>
                </value>
                <value>
                    <fullName>PPN Lubbock-Amerillo</fullName>
                </value>
                <value>
                    <fullName>Professional Provider Network Dept</fullName>
                </value>
                <value>
                    <fullName>Provider Inquiry</fullName>
                </value>
                <value>
                    <fullName>Provider Relation DFW</fullName>
                </value>
                <value>
                    <fullName>Provider Relations Houston</fullName>
                </value>
                <value>
                    <fullName>Provider Relations Midland</fullName>
                </value>
                <value>
                    <fullName>Provider Relations South Texas</fullName>
                </value>
                <value>
                    <fullName>Provider Relations IL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type_s__c</fullName>
        <label>Request Type(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Change</fullName>
                </value>
                <value>
                    <fullName>Billing Address Change</fullName>
                </value>
                <value>
                    <fullName>Credentialing Change</fullName>
                </value>
                <value>
                    <fullName>NPI Tax Id Change</fullName>
                </value>
                <value>
                    <fullName>Name Change Request</fullName>
                </value>
                <value>
                    <fullName>Other Provider Updates</fullName>
                </value>
                <value>
                    <fullName>Physical Address Change</fullName>
                </value>
                <value>
                    <fullName>Remove Provider from Group/Location</fullName>
                </value>
                <value>
                    <fullName>nm_network_scripting@bcbsnm.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OMNI Queue</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OMNI Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OMNI_User_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>OMNI_Queue__c</referenceTo>
        <relationshipLabel>OMNI User Group</relationshipLabel>
        <relationshipName>User_Time_Table</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_User_Ids__c</fullName>
        <label>Selected User Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Users__c</fullName>
        <label>Selected Users</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Time_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Days__c</fullName>
        <label>Week Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OMNI User Group</label>
    <nameField>
        <displayFormat>OU-{0000}</displayFormat>
        <label>OMNI_User_Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMNI User Group</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmailToCaseOwnerUpdate.cls
public class EmailToCaseOwnerUpdate {
    
    @InvocableMethod(label='EmailToCaseOwnerUpdate' description='Returns the list of account names corresponding to the specified account IDs.')
    public static void updateEmailCaseOwner(list<Case> caseList)
    {
        System.debug('caseList in side Process builder===>>>'+caseList.size());
        list<OMNICriteriaTable> criteria = new list<OMNICriteriaTable>();
        Datetime GMTDate            =   system.now();
        String strConvertedDate     =   GMTDate.format('yyyy-MM-dd','America/Chicago');
        String strConvertedDate2    =   GMTDate.format('yyyy-MM-dd HH:mm:ss','America/Chicago');
        Datetime dttm               =   DateTIME.valueof(strConvertedDate2);
        Date dt                     =   Date.valueof(strConvertedDate);
        OMNICriteriaTable temp      =   new OMNICriteriaTable();
        
        list<OMNI_Queue__c> q       =   [select id,Ownerid,Case_Type__c,Plan_Id__c,Queue_Priority__c,Case_Type_Name_Origin__c,
                                         Request_Type_s__c from OMNI_Queue__c where Case_Type__c='Email'];
        list<OMNI_User_Group__c> UGlist = [select id,Group__c,Selected_User_Ids__c,Selected_Users__c,User__c from OMNI_User_Group__c 
                                           where Active__c = true and Start_Date__c <= :dt and End_Date__c >= :dt and 
                                           Week_Days__c includes (:dttm.format('EEEE'))];
        
        Map<id,OMNI_User_Group__c> userMap = new Map<id,OMNI_User_Group__c>();
        
        for(OMNI_User_Group__c g: UGlist)
        {       
            userMap.put(g.Group__c,g);
        }
       
        for(OMNI_Queue__c t : q) 
        {
            temp        =   new OMNICriteriaTable();
            temp.Queue  =   t;
            temp.UserGroup = userMap.get(t.id);
            criteria.add(temp);
        }    
        List<Case> casesToUpdate = new List<Case>();
        for( Case aCase : (List<Case>) caseList )
        {
            System.debug('Cases processed in Batch====>'+aCase.Subject);
            for( OMNI_Queue__c omniQueue : q )
            {
                Set<String> tempSet = new Set<String>();
               tempSet.addAll(String.valueOf( omniQueue.Case_Type_Name_Origin__c ).split(';')); 
                    if( tempSet.contains( aCase.Origin ) 
                       && omniQueue.Plan_Id__c == aCase.Plan_ID__c 
                      )
                    {
                           Case tempCase = new Case(Id=aCase.Id);
                           tempCase.ownerid = omniQueue.ownerid;
                           casesToUpdate.add(tempCase);
                           break;                           
                    }else{
                        System.debug('<<<==== No Cases for Update ====>>>');
                    }
             }
            /*for(OMNICriteriaTable t:criteria)
            {     
                    Set<String> tempSet = new Set<String>();
                    tempSet.addAll(String.valueOf(t.Queue.Case_Type_Name_Origin__c).split(';')); 
                    
                    if( tempSet.contains(aCase.Origin) 
                       && t.Queue.Plan_Id__c == aCase.Plan_ID__c 
                       && t.UserGroup != null
                      )
                    {
                           Case tempCase = new Case(Id=aCase.Id);
                           tempCase.ownerid = t.Queue.ownerid;
                           casesToUpdate.add(tempCase);
                           break;                           
                    }else{
                        System.debug('<<<==== No Cases for Update ====>>>');
                    }
                } */
            
            
        }
        System.debug('casesToUpdate===>'+casesToUpdate);
        if(!casesToUpdate.isEmpty())
        {
            try{
                update casesToUpdate;
            }catch(Exception e){
               System.debug('Error while updating Email -to Case owner update when OMNi custom queue found===>>>'+e.getMessage());
            }
            
        } 
    }
}