src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cred_Cycle__c</fullName>
        <label>Cred Cycle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cred_Status_Date__c</fullName>
        <description>Cred Status Date</description>
        <label>Cred Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cred_Status__c</fullName>
        <description>This field created part of PPN-25402. This field will hold the group credentialing case status</description>
        <label>Cred Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <externalId>true</externalId>
        <label>Prov ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MCC_Data_Object__c.object
<CustomObject>
    <description>Intermediate object for Mass Case Creation and Death File.</description>
    <fields>
        <fullName>Cred_Cycle__c</fullName>
        <label>Cred Cycle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cred_Status_Date__c</fullName>
        <label>Cred Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cred_Status__c</fullName>
        <label>Cred Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>MCC_Data_Object</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MCC_Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MCC_File_Id__c</fullName>
        <label>File Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Type__c</fullName>
        <label>File Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Grouping_ID__c</fullName>
        <description>TX Specific</description>
        <label>Grouping ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Plan_ID__c</fullName>
        <description>For all loads</description>
        <label>Plan ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Project_Number__c</fullName>
        <description>TX Specific</description>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Prov_ID__c</fullName>
        <description>For Death and TX Data</description>
        <label>Provider ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarding_Case_ID__c</fullName>
        <label>Onboarding Case ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mass Case Creation Record</label>
    <nameField>
        <displayFormat>MCC-{0000}</displayFormat>
        <label>MCC Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Case Creation Records</pluralLabel>
    <recordTypes>
        <fullName>Death_File</fullName>
        <active>true</active>
        <description>Death File</description>
        <label>Death File</label>
    </recordTypes>
    <recordTypes>
        <fullName>Roster</fullName>
        <active>true</active>
        <description>Roster</description>
        <label>Roster</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MCCTriggerHandler_Test.cls
/*
Apex Class Name  : To pass the values to the TestFactory class
Version          : 1.0  
Functionality    : To run the classes in bulk and in large volume
Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Ashok N                    11/19/2018             Test class to cover the MCCTriggerHandler 
 Saravana Bharathi           11/29/2018             Test Class to cover MCCTriggerHandler
******************************************************************************
*/

@Istest

public class MCCTriggerHandler_Test {
       
    static testMethod void credentialingMassUpdate()
    {
        TestDataFactory.prepareData();
        Account accountInsert= new Account();        
        accountInsert.FirstName='TEst';
        accountInsert.LastName='test';
        accountInsert.Prov_ID__c='Testing';
        accountInsert.CM_Corporate_Entity_Code__c='IL1';
        Id newId =Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Physician').getRecordTypeId();                
        accountInsert.RecordTypeId=newId;
        insert accountInsert;
        List<Case> caseList = new List<Case>();
        for(Integer check=0;check<10;check++)
        {
            Case newCase = new Case();
            newCase.accountId = accountInsert.Id;
            newCase.status = 'Opened';
            newCase.Origin='Web-Onboarding';
            caseList.add(newCase);
        }
        insert caseList;
        
        List<String> listOfCaseNumbers = new List<String>();
        for(Case newCase:[Select CaseNumber from Case where Id=:caseList])
        {
            listOfCaseNumbers.add(newCase.CaseNumber);
        }
        List<MCC_Data_Object__c> listOfMCCRecords = new List<MCC_Data_Object__c>();
        for(Integer check=0;check<10;check++)
        {
            MCC_Data_Object__c newObject = new MCC_Data_Object__c();
            newObject.MCC_File_Type__c='Onboarding Cred Mass Status Update';
            newObject.MCC_File_Id__c='Test1';
            newObject.MCC_Prov_ID__c='Testing';
            newObject.MCC_Plan_ID__c='IL1';
            newObject.Onboarding_Case_ID__c=listOfCaseNumbers[check];
            newObject.MCC_Comments__c='Testing';
            newObject.Cred_Cycle__c='I';
            newObject.Cred_Status__c='In Progress';
            newObject.MCC_Grouping_ID__c='Testing HCSC';
            newObject.Cred_Status_Date__c=System.today();
            listOfMCCRecords.add(newObject);
        }
        insert listOfMCCRecords;
        
        MCCTriggerHandler newTrigger = new MCCTriggerHandler();
        newTrigger.getProviderMap(new Set<String>{'Testing'});
        newTrigger.projectNumbers(listOfMCCRecords);
        
    }
    
    
     static testMethod void deathFileMassUpdate()
    {
        TestDataFactory.prepareData();
        Account accountInsert= new Account();        
        accountInsert.FirstName='TEst';
        accountInsert.LastName='test';
        accountInsert.Prov_ID__c='Testing';
        accountInsert.CM_Corporate_Entity_Code__c='IL1';
        Id newId =Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Physician').getRecordTypeId();                
        accountInsert.RecordTypeId=newId;
        insert accountInsert;
        
        List<Case> caseList = new List<Case>();
        
        for(Integer check=0;check<10;check++)
        {
            Case newCase = new Case();
            newCase.accountId = accountInsert.Id;
            newCase.status = 'Opened';
            newCase.Origin='Web-Onboarding';
            caseList.add(newCase);
        }
        
        insert caseList;
        List<String> listOfCaseNumbers = new List<String>();
        for(Case newCase:[Select CaseNumber from Case Where Id=:caseList ])
        {
            listOfCaseNumbers.add(newCase.CaseNumber);
        }
        List<MCC_Data_Object__c> listOfMCCRecords = new List<MCC_Data_Object__c>();
        Id deathFileId =Schema.SObjectType.MCC_Data_Object__c.getRecordTypeInfosByDeveloperName().get('Death_File').getRecordTypeId();  
        for(Integer check=0;check<10;check++)
        {
            MCC_Data_Object__c newObject = new MCC_Data_Object__c();
            newObject.MCC_File_Type__c='Mass CRM Creation';
            newObject.MCC_File_Id__c='Test1';
            newObject.MCC_Prov_ID__c='Testing';
            newObject.MCC_Plan_ID__c='IL1';
            newObject.Onboarding_Case_ID__c=listOfCaseNumbers[check];
            newObject.MCC_Comments__c='Testing';
            newObject.Cred_Cycle__c='I';
            newObject.Cred_Status__c='In Progress';
            newObject.Cred_Status_Date__c=System.today();
            newObject.MCC_Grouping_ID__c='Testing HCSC';
            newObject.RecordTypeId=deathFileId ;
            listOfMCCRecords.add(newObject);
        }
        insert listOfMCCRecords;
        
        MCCTriggerHandler newTrigger = new MCCTriggerHandler();
        newTrigger.getProviderMap(new Set<String>{'Testing'});
        newTrigger.projectNumbers(listOfMCCRecords);
        
    }
    
     static testMethod void networkLoadMassUpdate()
    {
        TestDataFactory.prepareData();
        Account accountInsert= new Account();        
        accountInsert.FirstName='TEst';
        accountInsert.LastName='test';
        accountInsert.Prov_ID__c='Testing';
        accountInsert.CM_Corporate_Entity_Code__c='IL1';
        Id newId =Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Physician').getRecordTypeId();                
        accountInsert.RecordTypeId=newId;
        insert accountInsert;
        
        List<Case> caseList = new List<Case>();
        
        for(Integer check=0;check<10;check++)
        {
            Case newCase = new Case();
            newCase.accountId = accountInsert.Id;
            newCase.status = 'Opened';
            newCase.Origin='Web-Onboarding';
            caseList.add(newCase);
        }
        
        insert caseList;
        List<String> listOfCaseNumbers = new List<String>();
        List<String> listOfCaseIds = new List<String>();
        for(Case newCase:[Select Id, CaseNumber from Case Where Id=:caseList ]) {
            listOfCaseNumbers.add(newCase.CaseNumber);
            listOfCaseIds.add(newCase.Id);
        }
        List<MCC_Data_Object__c> listOfMCCRecords = new List<MCC_Data_Object__c>();
        Id deathFileId =Schema.SObjectType.MCC_Data_Object__c.getRecordTypeInfosByDeveloperName().get('Death_File').getRecordTypeId();  
        for(Integer check=0;check<10;check++) {
            MCC_Data_Object__c newObject = new MCC_Data_Object__c();
            newObject.MCC_File_Type__c='Network Load Mass Status';
            newObject.MCC_File_Id__c='Test1';
            newObject.MCC_Prov_ID__c='Testing';
            newObject.MCC_Plan_ID__c='IL1';
            newObject.Onboarding_Case_ID__c=listOfCaseNumbers[check];
            newObject.MCC_Comments__c='Testing';
            newObject.Cred_Cycle__c='I';
            newObject.Cred_Status__c='In Progress';
            newObject.MCC_Grouping_ID__c='Testing HCSC';
            newObject.Cred_Status_Date__c=System.today();
            newObject.RecordTypeId=deathFileId ;
            listOfMCCRecords.add(newObject);
        }
        
        for(Integer check=0;check<10;check++) {
            MCC_Data_Object__c newObject = new MCC_Data_Object__c();
            newObject.MCC_File_Type__c='ADC Mass Status';
            newObject.MCC_File_Id__c='Test1';
            newObject.MCC_Prov_ID__c='Testing';
            newObject.MCC_Plan_ID__c='IL1';
            newObject.Onboarding_Case_ID__c=listOfCaseNumbers[check];
            newObject.MCC_Case_Id__c=listOfCaseIds[check];
            newObject.MCC_Comments__c='Testing';
            newObject.Cred_Cycle__c='I';
            newObject.Cred_Status__c='In Progress';
            newObject.MCC_Grouping_ID__c='Testing HCSC';
            newObject.Cred_Status_Date__c=System.today();
            newObject.RecordTypeId=deathFileId ;
            newObject.MCC_Project_Number__c = 'Testing';
            listOfMCCRecords.add(newObject);
        }
        
        for(Integer check=0;check<10;check++) {
            MCC_Data_Object__c newObject = new MCC_Data_Object__c();
            newObject.MCC_File_Type__c='CRM Mass Status';
            newObject.MCC_File_Id__c='Test1';
            newObject.MCC_Prov_ID__c='Testing';
            newObject.MCC_Plan_ID__c='IL1';
            newObject.Onboarding_Case_ID__c=listOfCaseNumbers[check];
            newObject.MCC_Case_Id__c=listOfCaseIds[check];
            newObject.MCC_Comments__c='Testing';
            newObject.Cred_Cycle__c='I';
            newObject.Cred_Status__c='In Progress';
            newObject.MCC_Grouping_ID__c='Testing HCSC';
            newObject.Cred_Status_Date__c=System.today();
            newObject.RecordTypeId=deathFileId ;
            newObject.MCC_Project_Number__c = 'Testing';
            listOfMCCRecords.add(newObject);
        }
        insert listOfMCCRecords;
        
        MCCTriggerHandler newTrigger = new MCCTriggerHandler();
        newTrigger.getProviderMap(new Set<String>{'Testing'});
        newTrigger.projectNumbers(listOfMCCRecords);
        
    }
    
    
    
     static testMethod void roseterLoadMassUpdate()
    {
        TestDataFactory.prepareData();
        Account accountInsert= new Account();        
        accountInsert.FirstName='TEst';
        accountInsert.LastName='test';
        accountInsert.Prov_ID__c='Testing';
        accountInsert.CM_Corporate_Entity_Code__c='IL1';
        Id newId =Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Physician').getRecordTypeId();                
        accountInsert.RecordTypeId=newId;
        insert accountInsert;
        
        List<MCC_Data_Object__c> listOfMCCRecords = new List<MCC_Data_Object__c>();
        Id deathFileId =Schema.SObjectType.MCC_Data_Object__c.getRecordTypeInfosByDeveloperName().get('Roster').getRecordTypeId();  
        for(Integer check=0;check<10;check++)
        {
            MCC_Data_Object__c newObject = new MCC_Data_Object__c();
            newObject.MCC_File_Type__c='ILR';
            newObject.MCC_File_Id__c='Test1';
            newObject.MCC_Prov_ID__c='Testing';
            newObject.MCC_Plan_ID__c='IL1';
            newObject.Onboarding_Case_ID__c=null;
            newObject.MCC_Comments__c='Testing';
            newObject.Cred_Cycle__c='I';
            newObject.Cred_Status__c='In Progress';
            newObject.MCC_Grouping_ID__c='Testing HCSC';
            newObject.Cred_Status_Date__c=System.today();
            newObject.RecordTypeId=deathFileId ;
            newObject.MCC_Project_Number__c = 'Testing';
            listOfMCCRecords.add(newObject);
        }
        insert listOfMCCRecords;
        
        MCCTriggerHandler newTrigger = new MCCTriggerHandler();
        newTrigger.getProviderMap(new Set<String>{'Testing'});
        newTrigger.projectNumbers(listOfMCCRecords);
        
    }
    
       static testMethod void acctCaseCredStatusLoadMassUpdate()
    {
        TestDataFactory.prepareData();
        Account accountInsert= new Account();        
        accountInsert.FirstName='TEst';
        accountInsert.LastName='test';
        accountInsert.Prov_ID__c='Testing';
        accountInsert.CM_Corporate_Entity_Code__c='IL1';
        Id newId =Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Physician').getRecordTypeId();                
        accountInsert.RecordTypeId=newId;
        insert accountInsert;
        
        List<MCC_Data_Object__c> listOfMCCRecords = new List<MCC_Data_Object__c>();
        Id deathFileId =Schema.SObjectType.MCC_Data_Object__c.getRecordTypeInfosByDeveloperName().get('Roster').getRecordTypeId();  
        for(Integer check=0;check<10;check++)
        {
            MCC_Data_Object__c newObject = new MCC_Data_Object__c();
            newObject.MCC_File_Type__c='Onboarding Cred Mass Status Update';
            newObject.MCC_File_Id__c='Test1';
            newObject.MCC_Prov_ID__c='Testing';
            newObject.MCC_Plan_ID__c='IL1';
            newObject.MCC_Comments__c='Testing';
            newObject.Cred_Cycle__c='I';
            newObject.Cred_Status__c='In Progress';
            newObject.MCC_Grouping_ID__c='Testing HCSC';
            newObject.Cred_Status_Date__c=System.today();
            newObject.RecordTypeId=deathFileId ;
            newObject.MCC_Project_Number__c = 'Testing';
            listOfMCCRecords.add(newObject);
        }
        
        insert listOfMCCRecords;
        
        MCCTriggerHandler newTrigger = new MCCTriggerHandler();
        newTrigger.getProviderMap(new Set<String>{'Testing'});
        newTrigger.projectNumbers(listOfMCCRecords);
        
    }
    
}