src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cred_Status__c</fullName>
        <description>This field created part of PPN-25402. This field will hold the group credentialing case status</description>
        <label>Cred Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <externalId>true</externalId>
        <label>Prov ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <fields>
        <fullName>Contracting_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contracting Case</description>
        <label>Contracting Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Provider_Networks_Contracting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CounterSign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CounterSign</description>
        <label>CounterSign</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Provider_Details_CounterSign</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cred_Status__c</fullName>
        <label>Cred Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Needs Credentialing</fullName>
                </value>
                <value>
                    <fullName>No Credentialing Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blue Advantage HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Advantage PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Care Direct</fullName>
                </value>
                <value>
                    <fullName>Blue Choice Options</fullName>
                </value>
                <value>
                    <fullName>BlueChoice PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>BlueChoice PPO (BH)</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO Preferred</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO Preferred Ancillary</fullName>
                </value>
                <value>
                    <fullName>Blue Community HMO Dallas</fullName>
                </value>
                <value>
                    <fullName>Blue Community HMO Network</fullName>
                </value>
                <value>
                    <fullName>Blue Cross Community Family Health Plan</fullName>
                </value>
                <value>
                    <fullName>Blue Essentials</fullName>
                </value>
                <value>
                    <fullName>Blue Focus Care</fullName>
                </value>
                <value>
                    <fullName>Blue Focus POS</fullName>
                </value>
                <value>
                    <fullName>BlueLincs HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Options</fullName>
                </value>
                <value>
                    <fullName>Blue Precision HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Preferred</fullName>
                </value>
                <value>
                    <fullName>Blue Premier HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Select PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Traditional</fullName>
                </value>
                <value>
                    <fullName>Caring Program</fullName>
                </value>
                <value>
                    <fullName>CHIP (Medicaid)</fullName>
                </value>
                <value>
                    <fullName>DNOA</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible MMAI</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible Special Needs Plan</fullName>
                </value>
                <value>
                    <fullName>Exclusive Provider Network</fullName>
                </value>
                <value>
                    <fullName>Facility - Blue Choice Designated PPO</fullName>
                </value>
                <value>
                    <fullName>Facility Blue Choice Designated PPO Preferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PFIN_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PFIN Case</description>
        <label>PFIN Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Provider_Networks_PFIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PFIN_onBoarding__c</fullName>
        <label>PFIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Panel_code__c</fullName>
        <label>Panel code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepting</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Existing Patients Only</fullName>
                </value>
                <value>
                    <fullName>Existing &amp; Family only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prior_Provider_Id__c</fullName>
        <label>Prior Provider Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <description>Prov ID</description>
        <label>Prov ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <recordTypes>
        <fullName>CounterSign</fullName>
        <active>true</active>
        <description>CounterSign</description>
        <label>CounterSign</label>
    </recordTypes>
    <recordTypes>
        <fullName>Credentialing</fullName>
        <active>true</active>
        <label>Credentialing</label>
    </recordTypes>
    <recordTypes>
        <fullName>Onboarding</fullName>
        <active>true</active>
        <description>Onboarding</description>
        <label>Onboarding</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RecordType_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <description>This field is to hold the record type developer name</description>
        <inlineHelpText>Record type developer name</inlineHelpText>
        <label>DeveloperName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>This field is to hold record type name</description>
        <inlineHelpText>Record type Name</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_type_Id__c</fullName>
        <description>This field is to hold the record type Id</description>
        <inlineHelpText>Record type Id</inlineHelpText>
        <label>Record type Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObject_Type__c</fullName>
        <description>This field is to hold the object name</description>
        <inlineHelpText>Object Name</inlineHelpText>
        <label>sObject Type</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordType settings</label>
</CustomObject>

src/classes/Test_ProviderDetailsTrigger.cls
/****************************************************************
@Author      : Provider Intake Salesforce team 
@Date        : 10/12/2018
@Description : Test class for Account Trigger
*******************************************************
SI.No       Author                Modification Comments
1          Sethu Raman                Created

******************************************************************/


@isTest
public class Test_ProviderDetailsTrigger{    

public static Id dataEntryRecordTypeId;
public static Id credRecordTypeId;
public static Id contractRecordTypeId;
public static Id counterSignRecordTypeId;
public static Id provCounterSignRecTypeId;
 
    public static testmethod void createCustomSettingRecords(){
          dataEntryRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Data_Entry_Provider_On_boarding').getRecordTypeId();
          credRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Provider_On_boarding_Credentialing').getRecordTypeId();
          contractRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Contracting_Provider_On_boarding').getRecordTypeId();
          counterSignRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Provider_Group_On_boarding_Counter_Sign').getRecordTypeId();
          provCounterSignRecTypeId = Schema.SObjectType.Provider_Networks__c.getRecordTypeInfosByDeveloperName().get('CounterSign').getRecordTypeId();
          
          List<RecordType_settings__c> recTypeList = new List<RecordType_settings__c>();
          
          RecordType_settings__c rType1 = new RecordType_settings__c();
          rType1.name = 'Provider On-boarding Data Entry';
          rType1.Name__c = 'Provider On-boarding Data Entry';
          rType1.developerName__c = 'Data_Entry_Provider_On_boarding';
          rType1.sObject_Type__c = 'Case';
          rType1.Record_type_Id__c = dataEntryRecordTypeId;
          recTypeList.add(rType1);
          
          RecordType_settings__c rType2 = new RecordType_settings__c();
          rType2.name = 'Provider On-boarding';
          rType2.Name__c = 'Provider On-boarding';
          rType2.developerName__c = 'Provider_On_boarding';
          rType2.sObject_Type__c = 'Case';
          rType2.Record_type_Id__c = dataEntryRecordTypeId;
          recTypeList.add(rType2);
          
          RecordType_settings__c rType3 = new RecordType_settings__c();
          rType3.name = 'Provider On_boarding Credentialing';
          rType3.Name__c = 'Provider On_boarding Credentialing';
          rType3.developerName__c = 'Provider_On_boarding_Credentialing';
          rType3.sObject_Type__c = 'Case';
          rType3.Record_type_Id__c = credRecordTypeId;
          recTypeList.add(rType3); 
          
          RecordType_settings__c rType4 = new RecordType_settings__c();
          rType4.name = 'Provider Group On_boarding Cred';
          rType4.Name__c = 'Provider Group On_boarding Credentialling';
          rType4.developerName__c = 'Provider_Group_On_boarding_Credentialling';
          rType4.sObject_Type__c = 'Case';
          rType4.Record_type_Id__c = credRecordTypeId;
          recTypeList.add(rType4);  
          
          RecordType_settings__c rType5 = new RecordType_settings__c();
          rType5.name = 'Provider Group Onboarding Master';
          rType5.Name__c = 'Provider Group Onboarding Master Entity';
          rType5.developerName__c = 'Provider_Group_Onboarding_Master_Entity';
          rType5.sObject_Type__c = 'Case';
          rType5.Record_type_Id__c = credRecordTypeId;
          recTypeList.add(rType5); 
          
          RecordType_settings__c rType6 = new RecordType_settings__c();
          rType6.name = 'Provider On-boarding Contracting';
          rType6.Name__c = 'Provider On-boarding Contracting';
          rType6.developerName__c = 'Contracting_Provider_On_boarding';
          rType6.sObject_Type__c = 'Case';
          rType6.Record_type_Id__c = contractRecordTypeId;
          recTypeList.add(rType6); 
          
          RecordType_settings__c rType7 = new RecordType_settings__c();
          rType7.name = 'Provider Group On-boarding Data';
          rType7.Name__c = 'Provider Group On-boarding DataEntry';
          rType7.developerName__c = 'Data_Entry_Group_Provider_On_boarding';
          rType7.sObject_Type__c = 'Case';
          rType7.Record_type_Id__c = contractRecordTypeId;
          recTypeList.add(rType7);
          
          RecordType_settings__c rType8 = new RecordType_settings__c();
          rType8.name = 'Provider Group On-boarding Contr';
          rType8.Name__c = 'Provider Group On-boarding Contracting';
          rType8.developerName__c = 'Provider_Group_Onboarding_Contracting';
          rType8.sObject_Type__c = 'Case';
          rType8.Record_type_Id__c = contractRecordTypeId;
          recTypeList.add(rType8); 
          
          insert recTypeList;          
          
          GlobalSettings__c gs = new GlobalSettings__c();
          gs.name = 'PFFileRecieved';
          gs.Record_Type_Names__c = 'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
          gs.PFFileRecieved__c = true;
          insert gs;
    }
    
    
    public static testmethod void createPFINProviderRecords(){         
          createCustomSettingRecords();
          Case newCase = TestCaseUtil.CreateCase();
          newCase.recordTypeId = dataEntryRecordTypeId;
          insert newCase;  
          Provider_Networks__c prov = new Provider_Networks__c(PFIN_Case__c = newCase.Id, PFIN_onBoarding__c ='1234', Prov_ID__c ='1234');
          insert prov;
    }
    
    public static testMethod void createContractProviderRecords(){
          createCustomSettingRecords();
          
          Case newCase = TestCaseUtil.CreateCase();
          newCase.recordTypeId = contractRecordTypeId;
          insert newCase;            
          Provider_Networks__c prov = new Provider_Networks__c(contracting_case__c = newCase.Id, PFIN_onBoarding__c ='1234', Prov_ID__c ='1234', Panel_code__c='aa', Cred_Status__c ='No Credentialing Needed');
          insert prov; 
          
          Case newCase2 = TestCaseUtil.CreateCase();
          newCase.recordTypeId = counterSignRecordTypeId;
          insert newCase2;       
          Provider_Networks__c prov2 = new Provider_Networks__c(counterSign__c= newCase2.Id, PFIN_onBoarding__c ='1234', Prov_ID__c ='1234', Panel_code__c='aa', prior_provider_Id__c = string.valueOf(prov.Id).substring(0,15));
          insert prov2;
                    
          prov.panel_code__c = 'ab';
          update prov;
    }
    
    public static testMethod void deleteProvNetworks(){
          createCustomSettingRecords();
          
          Case newCase = TestCaseUtil.CreateCase();
          newCase.recordTypeId = counterSignRecordTypeId;
          insert newCase;            
          Provider_Networks__c prov = new Provider_Networks__c(contracting_case__c = newCase.Id, PFIN_onBoarding__c ='1234', Prov_ID__c ='1234', Panel_code__c='aa', recordTypeId = provCounterSignRecTypeId);
          insert prov; 
          
          try{
              delete prov;
          }
          catch(Exception e){
          
          }
    }
}