src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CLM_AgreementPlanAutoPopulate.cls
public class CLM_AgreementPlanAutoPopulate {

    @InvocableMethod
    public static void StatePlan(List<Apttus__APTS_Agreement__c> agreementRecords){
        
        Set<Id> accountIds=new Set<Id>();
        for(Apttus__APTS_Agreement__c agreement:agreementRecords){
            if(agreement <> null && agreement.Apttus__Account__c <> null){
                accountIds.add(agreement.Apttus__Account__c);   
            }
        }
        
        Apttus__APTS_Agreement__c UpdatableAggrement;
        List<Apttus__APTS_Agreement__c> AgreementList=new List<Apttus__APTS_Agreement__c>();
        
        if(!AccountIds.isEmpty()){
            
            Map<Id,Account> AccountMap=new Map<Id,Account>([Select Id,CM_Corporate_Entity_Code__c FROM Account where Id IN:AccountIds]);

            for(Apttus__APTS_Agreement__c agreement:agreementRecords){
                
                if(AccountMap.containsKey(agreement.Apttus__Account__c)){
                    
                        UpdatableAggrement=new Apttus__APTS_Agreement__c(Id=agreement.Id);
                    if((AccountMap.get(agreement.Apttus__Account__c)).CM_Corporate_Entity_Code__c==Label.CLM_Plan_IL){
                        UpdatableAggrement.Plan__c='Illinois';
                    }else if((AccountMap.get(agreement.Apttus__Account__c)).CM_Corporate_Entity_Code__c==Label.CLM_Plan_NM){
                        UpdatableAggrement.Plan__c='New Mexico';
                        
                    }else if((AccountMap.get(agreement.Apttus__Account__c)).CM_Corporate_Entity_Code__c==Label.CLM_Plan_MT){
                        UpdatableAggrement.Plan__c='Montana';
                        
                    }else if((AccountMap.get(agreement.Apttus__Account__c)).CM_Corporate_Entity_Code__c==Label.CLM_Plan_OK){
                        
                        UpdatableAggrement.Plan__c='Oklahoma';
                    }else if((AccountMap.get(agreement.Apttus__Account__c)).CM_Corporate_Entity_Code__c==Label.CLM_Plan_TX){
                        
                        UpdatableAggrement.Plan__c='Texas';
                    }
                    
                    AgreementList.add(UpdatableAggrement);
                }
            }

        }
        
        if(!AgreementList.isEmpty()){
            try{
                update AgreementList;
            } Catch(Exception e){
                System.debug(e.getMessage());
            }
        }

    }

}