src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NPI__c</fullName>
        <externalId>true</externalId>
        <label>NPI</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Affiliations__c.object
<CustomObject>
    <label>Affiliations</label>
    <nameField>
        <displayFormat>A{0}</displayFormat>
        <label>Affiliation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Hours_of_Operation__c.object
<CustomObject>
    <label>Hours of Operation</label>
    <nameField>
        <displayFormat>HO-{0}</displayFormat>
        <label>Hours of Operation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hours of Operation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Network__c.object
<CustomObject>
    <fields>
        <fullName>CM_Network__c</fullName>
        <label>Network</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Network</label>
    <nameField>
        <displayFormat>NI-{0}</displayFormat>
        <label>Network Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Networks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Provider_Identification__c.object
<CustomObject>
    <description>Provider Identification Object contains the Issued Identification types and numbers of the provider like License,NPI, Medicare etc</description>
    <fields>
        <fullName>CM_PI_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Identification</relationshipLabel>
        <relationshipName>Provider_Identification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Prvdr_Iden_Typ_Cd__c</fullName>
        <label>Identification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NPI</fullName>
                </value>
                <value>
                    <fullName>Govt. ID</fullName>
                </value>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Identification</label>
    <nameField>
        <displayFormat>PI-{0}</displayFormat>
        <label>Provider Identification Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Identification</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Provider_Tax_Id__c.object
<CustomObject>
    <description>Provider Tax Identification Object  shows how and where billing is done.</description>
    <fields>
        <fullName>CM_PTI_Prov_Name_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Tax Identifications</relationshipLabel>
        <relationshipName>Provider_Tax_Identifications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider Tax Identification</label>
    <nameField>
        <displayFormat>PTI-{0}</displayFormat>
        <label>Prov Tax Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Tax Identifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Specialty__c.object
<CustomObject>
    <description>Speciality</description>
    <label>Specialty</label>
    <nameField>
        <displayFormat>SN-{0}</displayFormat>
        <label>Specialty Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specialty</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_SPL_Addr__c.object
<CustomObject>
    <description>Service &amp; Payee Location Address Object based on PFIN Number</description>
    <label>Service &amp; Payee Location Address</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Address Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service &amp; Payee Location Address</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_size__c</fullName>
        <label>List size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/classes/TestProviderDetails_Extended.cls
@isTest
public class TestProviderDetails_Extended
{
    @testSetup static void prepareData() {
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM;Provider Group Onboarding Data Entry;Provider On-boarding Data Entry;Provider On-boarding;Entity Account';
        insert gs;   
    }
    
    static testMethod void testPage() 
    {
        Test.startTest();
        List<Account> listofAccounts = new List<Account>();
        List<Id> listOfAccountIdIds = new List<Id>();
        
        Account acc1 = new Account();
        acc1 = TestClassData.CreateAccount();        
        listofAccounts.add(acc1);
        listOfAccountIdIds.add(acc1.Id);
        
        Account acc = new Account();
        acc = TestClassData.CreateAccount();
        listOfAccountIdIds.add(acc.Id);
       
        CM_Provider_Identification__c provIden = new CM_Provider_Identification__c();
        provIden = TestClassData.CreateProviderIdentification(acc.Id);        
        provIden.CM_PI_Prov__c = acc.Id;
        provIden.CM_Prvdr_Iden_Typ_Cd__c = 'NPI';
        
        CM_Provider_Tax_Id__c provTaxIden = new CM_Provider_Tax_Id__c();        
        provTaxIden = TestClassData.CreateProviderTaxIdentification(acc.Id);
        provTaxIden.CM_PTI_Prov_Name_From__c = acc.Id;
        provTaxIden.CM_PTI_Tax_Id__c = '123456789';
        update provTaxIden;
       
        provIden.CM_PI_Prov__c = provTaxIden.CM_PTI_Prov_Name_From__c;
        update provIden;
        
        CM_Provider_Identification__c provIden2 = new CM_Provider_Identification__c();
        provIden2 = TestClassData.CreateProviderIdentification(acc.Id);        
        provIden.CM_PI_Prov__c = acc.Id;
        provIden2.CM_Prvdr_Iden_Typ_Cd__c = 'NPI';
        provIden2.CM_PI_Prov__c = provTaxIden.CM_PTI_Prov_Name_From__c;
        update provIden2;
        
        
        listOfAccountIdIds.add(provTaxIden.CM_PTI_Prov_Name_From__c);
       
        Affiliations__c affi = new Affiliations__c();
        affi = TestClassData.CreateAffiliation(acc.Id);
        
        case c = new Case();
        c = TestClassData.CreateChildCase(acc.Id);
        c.RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByName().get('Provider Group Onboarding Data Entry').getRecordTypeId();
		c.Billing_NPI_Number__c = '1234567890';
        c.Tax_Id_Number__c = '123456789';
        c.Case_Entity__c = acc.Id;
        CM_SPL_Addr__c sploc = new CM_SPL_Addr__c();
        sploc = TestClassData.CreateServicePayeeLocationAddress(provTaxIden.Id);
        
        CM_Network__c net = new CM_Network__c();
        net = TestClassData.CreateNetwork(sploc.Id);
        
        CM_Specialty__c accspl = new CM_Specialty__c();        
        CM_Specialty__c netSpl = new CM_Specialty__c();        
        CM_Specialty__c spl2 = new CM_Specialty__c();
        accspl = TestClassData.CreateSpecialty(acc.Id,sploc.Id,net.Id);
        spl2 = TestClassData.CreateSpecialty(acc.Id,sploc.Id,net.Id);
        netspl = TestClassData.CreateSpecialty(acc.Id,sploc.Id,net.Id);
        
        CM_Hours_of_Operation__c hoo = new CM_Hours_of_Operation__c();
        hoo = TestClassData.CreateHoursofOperation(sploc.Id);
        
        
        pagereference pageref = page.providerdetails_extended;
        Test.setCurrentPage(pageRef);
        apexpages.currentpage().getparameters().put('id' , acc.Id);        
       
        providerdetails_extended controller = new providerdetails_extended();   
        CM_Provider_Tax_Id__c provTaxIden2 = new CM_Provider_Tax_Id__c();
        provTaxIden2 = TestClassData.CreateProviderTaxIdentificationForDelete(acc.Id);        
        delete provTaxIden2;
        
        CM_Provider_Identification__c pridenti = new CM_Provider_Identification__c();
        pridenti = TestClassData.CreateProviderIdentificationDelete(acc.Id);
        delete pridenti;
        
        Test.StopTest();
        
    }
    /*static testmethod void testing(){
        
        Account acc1 = new Account();
        acc1 = TestClassData.CreateAccount();
        acc1.Tax_Id__c='123456789';
        acc1.NPI__c='1234567890';
        update acc1;
        
        case c2 = new Case();
        c2 = TestClassData.CreateChildCase(acc1.Id);
        c2.RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByName().get('Provider Group Onboarding Data Entry').getRecordTypeId();
		c2.Billing_NPI_Number__c = '1234567890';
        c2.Tax_Id_Number__c = '123456789';
        c2.Case_Entity__c = acc1.Id;
        update c2;
        
        case c3 = new Case();
        c3 = TestClassData.CreateChildCase(acc1.Id);
        c3.RecordTypeId =Schema.SObjectType.Case.getRecordTypeInfosByName().get('Provider On-boarding').getRecordTypeId();
		c3.Billing_NPI_Number__c = '1234567890';
        c3.Tax_Id_Number__c = '123456789';
        c3.Case_Entity__c = acc1.Id;
        update c3;
    }*/
    
}