src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLM_Standard_or_Non_Standard_Base_Lan__c</fullName>
        <label>Standard or Non Standard Base Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Non-Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Networks__c</fullName>
        <label>Provider Networks</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL BlueCare Direct HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Select PPO Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Blue FocusCare HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Precision HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Broad PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL HMO of Illinois Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicaid Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL MMAI Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Focus Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Options Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Closed Plan Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT HealthLink Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Point of Service Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Traditional Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Community HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicaid Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PAR Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM POS Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PPO Provider Network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_size__c</fullName>
        <label>List size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <recordTypes>
        <fullName>Network</fullName>
        <active>true</active>
        <label>Network</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CLM_Texas_ReimbursementHandler_Test.cls
// Created by - Piyush Bhardwaj
//Test Class written to satisfy the code coverage for the CLM_Texas_ReimbursementHandler
@isTest
public class CLM_Texas_ReimbursementHandler_Test
{

// Method to satisfy the code coverage for defaulting the values for the fields mediation city, arbitration city, NPI type
// and termination without cause notice for professional Record Type and Medical Record Type
	static testMethod void testData() 
    {
  
       // Global Settings needed for using account object in test method advised by the contact team
       // This part needs to be uncommented out in SIT , UAT and Prod environments
       GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
      Account acc= new Account();
      acc.Name               = 'Test Account CLM_Plan_TX';  
      acc.CM_Corporate_Entity_Code__c   = 'TX1';
      acc.RecordTypeId          = [SELECT Id, Name FROM RecordType WHERE Name = 'Entity Account'].Id;
      insert acc;
        
      list<Apttus__APTS_Agreement__c> agrmtList=new list<Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> oldMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> newMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      
      //Finiding the appropriate user to create an agreement for Texas Plan based on the role
      user u=[select Id from user where userrole.Name in ('CLM Texas', 'Texas Supervisor' ) AND user.IsActive = true limit 1];
      
      //agrmt will be using professional record type which will test if the default values are getting populated
      Apttus__APTS_Agreement__c agrmt = new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c = acc.Id;
      agrmt.OwnerId = u.Id;
      agrmt.Plan__c = 'Texas';
      agrmt.recordtypeId = CLM_ReimbursementModel.professionalRecordTypeId ;
      agrmt.CLM_Standard_or_Non_Standard_Base_Lan__c = null;
      agrmtList.add(agrmt);
      
      // agrmt2 will be using medical record type which will test if the default values are getting removed 
      Apttus__APTS_Agreement__c agrmt2=new Apttus__APTS_Agreement__c();
      agrmt2.Apttus__Account__c=acc.Id;
      agrmt2.OwnerId=u.Id;
      agrmt2.Plan__c='Texas';       
      agrmt2.recordtypeId=CLM_ReimbursementModel.medicalRecordTypeId ;
      agrmt2.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Standard';
      agrmtList.add(agrmt2);
      
      // agrmt3 will be using medical record type which will test if the default values are getting populated
      Apttus__APTS_Agreement__c agrmt3=new Apttus__APTS_Agreement__c();
      agrmt3.Apttus__Account__c=acc.Id;
      agrmt3.OwnerId=u.Id;
      agrmt3.Plan__c='Texas';       
      agrmt3.recordtypeId=CLM_ReimbursementModel.medicalRecordTypeId ;
      agrmt3.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Non-Standard';
      agrmtList.add(agrmt3);
        
      // agrmt4 will be using professional record type which will test if the default values are getting removed 
      Apttus__APTS_Agreement__c agrmt4=new Apttus__APTS_Agreement__c();
      agrmt4.Apttus__Account__c=acc.Id;
      agrmt4.OwnerId=u.Id;
      agrmt4.Plan__c='Texas';       
      agrmt4.recordtypeId=CLM_ReimbursementModel.professionalRecordTypeId ;
      agrmt4.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Standard';
      agrmtList.add(agrmt4);
      insert agrmtList;
      
      // updating fields in the agreements created to test the desired changes
      agrmt.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Standard';
      update agrmt;
      agrmt2.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Non-Standard';
      update agrmt2;
      agrmt3.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Standard';
      update agrmt3;
      agrmt4.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Non-Standard';
      update agrmt4;
      
      //adding the agreements to the old map and new map
      oldMapAgrmt.put(agrmt4.Id,agrmt4);
      oldMapAgrmt.put(agrmt3.Id,agrmt3);
      oldMapAgrmt.put(agrmt2.Id,agrmt2);
      oldMapAgrmt.put(agrmt.Id,agrmt);
      newMapAgrmt.put(agrmt4.Id,agrmt4);
      newMapAgrmt.put(agrmt3.Id,agrmt3);
      newMapAgrmt.put(agrmt2.Id,agrmt2);
      newMapAgrmt.put(agrmt.Id,agrmt);
      
      //Running the test class with the target apex class
      Test.startTest();
      CLM_Texas_ReimbursementHandler.beforeUpdate(agrmtList,oldMapAgrmt,newMapAgrmt);
      Test.stopTest();
  }
    
    // the following test method covers the code coverage for the story PPN-48834 on the field Percentage of Medicaid fee schedule
    static testMethod void testData2() 
    {
  
       // Global Settings needed for using account object in test method advised by the contact team
       // This part needs to be uncommented out in SIT , UAT and Prod environments
       GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
      Account acc= new Account();
      acc.Name               = 'Test Account CLM_Plan_TX';  
      acc.CM_Corporate_Entity_Code__c   = 'TX1';
      acc.RecordTypeId          = [SELECT Id, Name FROM RecordType WHERE Name = 'Entity Account'].Id;
      insert acc;
        
      list<Apttus__APTS_Agreement__c> agrmtList=new list<Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> oldMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      Map<Id,Apttus__APTS_Agreement__c> newMapAgrmt=new Map<Id,Apttus__APTS_Agreement__c>();
      
      //Finiding the appropriate user to create an agreement for Texas Plan based on the role
      user u=[select Id from user where userrole.Name in ('CLM Texas', 'Texas Supervisor' ) AND user.IsActive = true limit 1];
      
      //agrmt will be using professional record type which will test if the default values are getting populated
      Apttus__APTS_Agreement__c agrmt = new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c = acc.Id;
      agrmt.OwnerId = u.Id;
      agrmt.Plan__c = 'Texas';
      agrmt.recordtypeId = CLM_ReimbursementModel.professionalRecordTypeId ;
      agrmt.Provider_Networks__c='CHIP Provider Network; STAR Kids Provider Network';
      agrmt.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Standard';
      agrmtList.add(agrmt);
      
      // agrmt2 will be using medical record type which will test if the default values are getting removed 
      Apttus__APTS_Agreement__c agrmt2=new Apttus__APTS_Agreement__c();
      agrmt2.Apttus__Account__c=acc.Id;
      agrmt2.OwnerId=u.Id;
      agrmt2.Plan__c='Texas';       
      agrmt2.recordtypeId=CLM_ReimbursementModel.medicalRecordTypeId ;
      agrmt2.Provider_Networks__c='CHIP Provider Network; STAR Kids Provider Network';
      agrmt2.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Standard';
      agrmtList.add(agrmt2);
      
      // agrmt3 will be using medical record type which will test if the default values are getting populated
      Apttus__APTS_Agreement__c agrmt3=new Apttus__APTS_Agreement__c();
      agrmt3.Apttus__Account__c=acc.Id;
      agrmt3.OwnerId=u.Id;
      agrmt3.Plan__c='Texas';       
      agrmt3.recordtypeId=CLM_ReimbursementModel.medicalRecordTypeId ;
      agrmt3.Provider_Networks__c='CHIP Provider Network; STAR Kids Provider Network';
      agrmt3.CLM_Standard_or_Non_Standard_Base_Lan__c = null;
      agrmtList.add(agrmt3);
        
      // agrmt4 will be using professional record type which will test if the default values are getting removed 
      Apttus__APTS_Agreement__c agrmt4=new Apttus__APTS_Agreement__c();
      agrmt4.Apttus__Account__c=acc.Id;
      agrmt4.OwnerId=u.Id;
      agrmt4.Plan__c='Texas';       
      agrmt4.recordtypeId=CLM_ReimbursementModel.professionalRecordTypeId ;
      agrmt4.Provider_Networks__c=null;
      agrmt4.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Standard';
      agrmtList.add(agrmt4);
      insert agrmtList;
      
      // updating fields in the agreements created to test the desired changes
      agrmt.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Non-Standard';
      agrmt.Provider_Networks__c=null;
      update agrmt;
      agrmt2.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Non-Standard';
      update agrmt2;
      agrmt3.CLM_Standard_or_Non_Standard_Base_Lan__c = 'Standard';
      update agrmt3;
      agrmt4.Provider_Networks__c='STAR Plus Provider Network';
      update agrmt4;
      
      //adding the agreements to the old map and new map
      oldMapAgrmt.put(agrmt4.Id,agrmt4);
      oldMapAgrmt.put(agrmt3.Id,agrmt3);
      oldMapAgrmt.put(agrmt2.Id,agrmt2);
      oldMapAgrmt.put(agrmt.Id,agrmt);
      newMapAgrmt.put(agrmt4.Id,agrmt4);
      newMapAgrmt.put(agrmt3.Id,agrmt3);
      newMapAgrmt.put(agrmt2.Id,agrmt2);
      newMapAgrmt.put(agrmt.Id,agrmt);
      
      //Running the test class with the target apex class
      Test.startTest();
      CLM_Texas_ReimbursementHandler.beforeUpdate(agrmtList,oldMapAgrmt,newMapAgrmt);
      Test.stopTest();
  }
    
    
}