src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedFromMarketingCloud__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When an account is created from or for Marketing Cloud, this checkbox will be checked.</description>
        <label>Created From Marketing Cloud</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CorporateEntityCode__c</fullName>
        <label>Corporate Entity Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignActivity__c.object
<CustomObject>
    <description>This object stores the campaign activity when communications are sent from Marketing Cloud.</description>
    <fields>
        <fullName>AccountName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Activity History</relationshipLabel>
        <relationshipName>Campaign_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CorporateEntityCode__c</fullName>
        <label>Corporate Entity Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreateAtRolodexAcctwithSameEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag that a user will set during the Marketing Cloud Journey. If checked and a campaign activity is inserted into the database, the campaign activity will be cloned and attached to Rolodex accounts that share the &quot;Sent To&quot; email address.</description>
        <label>Create at Rolodex Acct with Same Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateAtServiceLocWithSameEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag that a user will set during the Marketing Cloud Journey. If checked and a campaign activity is inserted into the database, the campaign activity will be cloned and attached to Service locations that share the &quot;Sent To&quot; email address.</description>
        <label>Create at Service Loc with Same Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreatedFromMarketingCloud__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created From Marketing Cloud</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SentTo__c</fullName>
        <label>Sent To</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ServiceAndPayeeLocationAddress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service &amp; Payee Location Address</label>
        <referenceTo>CM_SPL_Addr__c</referenceTo>
        <relationshipLabel>Campaign Activity History</relationshipLabel>
        <relationshipName>Campaign_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Activity</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Activity Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CM_SPL_Addr__c.object
<CustomObject>
    <description>Service &amp; Payee Location Address Object based on PFIN Number</description>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Addr_Type__c</fullName>
        <description>Provider Address Usage Type</description>
        <inlineHelpText>Provider Address Usage Type</inlineHelpText>
        <label>Address Usage Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Capitation</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Directory</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Credentialing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CM_SPL_Email__c</fullName>
        <description>Email</description>
        <inlineHelpText>Email</inlineHelpText>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service &amp; Payee Location Address</relationshipLabel>
        <relationshipName>Account_Tax_Addresses_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service &amp; Payee Location Address</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Address Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service &amp; Payee Location Address</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CampaignActivityTriggerHandler.cls
/**
 * This class serves as a Handler for the Campaign Activity Trigger.
 * <p/><p/>
 * @author Travis Self
 */
public with sharing class CampaignActivityTriggerHandler {
    
   /**
    * This method is used to handle the after insert event on the Campaign Activity Trigger.
    * 
    * @param lstCampaignActivitiesTriggerNew List of new campaign activites
    */ 
    public static void onAfterInsert(List<CampaignActivity__c> lstCampaignActivitiesTriggerNew) {
        
        List<String> lstEmails = new List<String>();
        List<String> lstPlanIds = new List<String>();
        List<Id> lstServiceAndPayeeLocationsToIgnore = new List<Id>();
        List<Id> lstAccountsToIgnore = new List<Id>();
        List<CM_SPL_Addr__c> lstServiceAndPayeeAddressesWithSharedEmail = new List<CM_SPL_Addr__c>();
        List<Account> lstRolodexAccountsWithSharedEmail = new List<Account>();
        List<CampaignActivity__c> lstNewCampaignActivities = new List<CampaignActivity__c>();
        
        for(CampaignActivity__c ca : lstCampaignActivitiesTriggerNew) {
            if(ca.CreatedFromMarketingCloud__c) {
                lstNewCampaignActivities.add(ca);
                lstPlanIds.add(ca.CorporateEntityCode__c);
                if(ca.SentTo__c != null) {
                    lstEmails.add(ca.SentTo__c);
                }
                if(ca.ServiceAndPayeeLocationAddress__c != null) {
                    lstServiceAndPayeeLocationsToIgnore.add(ca.ServiceAndPayeeLocationAddress__c);
                }
                if(ca.AccountName__c != null) {
                    lstAccountsToIgnore.add(ca.AccountName__c);
                }
            }
    	}
        
        if(!lstNewCampaignActivities.isEmpty()) {
            
            // Get all the Service & Payee Locations that share the same email address of the original email send.
            // Exclude the Service & Payee Locations where a new Campaign Activity was already created from Marketing Cloud.
            lstServiceAndPayeeAddressesWithSharedEmail = [SELECT Id, CM_SPL_Email__c, CM_SPL_Prov__c FROM CM_SPL_Addr__c 
                                                                WHERE CM_SPL_Email__c IN: lstEmails AND CM_SPL_Addr_Type__c = 'Service' AND CM_Corporate_Entity_Code__c IN: lstPlanIds AND Id NOT IN: lstServiceAndPayeeLocationsToIgnore];
         
            // Get all the Rolodex Account that share the same email address of the original email send. 
            // Exclude the Rolodex Accounts where a new Campaign Activity was already created from Marketing Cloud.
            lstRolodexAccountsWithSharedEmail = [SELECT Id, PersonEmail FROM Account WHERE PersonEmail IN: lstEmails AND RecordType.DeveloperName = 'Rolodex' AND CM_Corporate_Entity_Code__c IN: lstPlanIds AND Id NOT IN: lstAccountsToIgnore];
            
            if(!lstServiceAndPayeeAddressesWithSharedEmail.isEmpty()) {
                createCampaignActivitesOnAddressesWithSameEmail(lstNewCampaignActivities, lstServiceAndPayeeAddressesWithSharedEmail);
            }
            if(!lstRolodexAccountsWithSharedEmail.isEmpty()) {
                createCampaignActivitesOnAccountsWithSameEmail(lstNewCampaignActivities, lstRolodexAccountsWithSharedEmail);
            }
        }
    }

   /**
    * This method will create campaign history activities on service & payee location records that share the same email address as the original email send from Marketing Cloud.
    * 
    * @param lstActivities List of new campaign activites
    * @param lstServiceAndPayeeLocations List of service & payee location addresses
    */ 
    private static void createCampaignActivitesOnAddressesWithSameEmail (List<CampaignActivity__c> lstActivities, List<CM_SPL_Addr__c> lstServiceAndPayeeLocations) {
        
        List<CampaignActivity__c> lstActivitiesToInsert = new List<CampaignActivity__c>();
        
        for(CampaignActivity__c ca : lstActivities) {
            if(ca.CreateAtServiceLocWithSameEmail__c) {
                for(CM_SPL_Addr__c sAndP : lstServiceAndPayeeLocations) {
                    CampaignActivity__c newCampaignActivity = ca.clone();
                    newCampaignActivity.ServiceAndPayeeLocationAddress__c = sAndP.Id;
                    newCampaignActivity.AccountName__c = sAndP.CM_SPL_Prov__c;
                    newCampaignActivity.CreatedFromMarketingCloud__c = false;
                    lstActivitiesToInsert.add(newCampaignActivity);
                }
            }
        }
        
        Database.insert(lstActivitiesToInsert, false);
    }
    
   /**
    * This method will create campaign history activities on rolodex account records that share the same email address as the original email send from Marketing Cloud.
    * 
    * @param lstActivities List of new campaign activites
    * @param lstRolodexAccounts List of rolodex accounts
    */ 
    private static void createCampaignActivitesOnAccountsWithSameEmail (List<CampaignActivity__c> lstActivities, List<Account> lstRolodexAccounts ) {
        
        List<CampaignActivity__c> lstActivitiesToInsert = new List<CampaignActivity__c>();
        
        for(CampaignActivity__c ca : lstActivities) {
            if(ca.CreateAtRolodexAcctwithSameEmail__c) {
                for(Account acct : lstRolodexAccounts) {
                    CampaignActivity__c newCampaignActivity = ca.clone();
                    newCampaignActivity.ServiceAndPayeeLocationAddress__c = null;
                    newCampaignActivity.AccountName__c = acct.Id;
                    newCampaignActivity.CreatedFromMarketingCloud__c = false;
                    lstActivitiesToInsert.add(newCampaignActivity);
                }
            }
        }
        
        Database.insert(lstActivitiesToInsert, false);
    }
}