src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <externalId>true</externalId>
        <label>NPI</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <externalId>true</externalId>
        <label>Prov ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agreement_Provider_Locations__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Provider Locations</relationshipLabel>
        <relationshipName>Agreement_Provider_Locations_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLM_Address__c</fullName>
        <label>Address</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLM_SPL_Addr_Type__c</fullName>
        <label>Address Usage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Capitation</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Directory</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Credentialing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CLM_SPL_City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLM_SPL_NPI_Number__c</fullName>
        <label>NPI Number</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CLM_SPL_PFIN_No__c</fullName>
        <label>PFIN Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLM_SPL_Zip_CD__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Agreement Provider Location</label>
    <nameField>
        <displayFormat>APL-{00000}</displayFormat>
        <label>Agreement Provider Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Provider Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLM_NPI__c</fullName>
        <label>NPI</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CLM_Prov_Id_Search__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prov Id Search</relationshipLabel>
        <relationshipName>Prov_Id_Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Prov Id Search</relationshipLabel>
        <relationshipName>Prov_Id_Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLM_Prov_Id__c</fullName>
        <label>Prov Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Prov Id Search</label>
    <nameField>
        <label>Prov Id Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prov Id Search</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CM_Provider_Identification__c.object
<CustomObject>
    <description>Provider Identification Object contains the Issued Identification types and numbers of the provider like License,NPI, Medicare etc</description>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Issu_Ident_Nmbr__c</fullName>
        <externalId>true</externalId>
        <label>Identification Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_PI_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Identification</relationshipLabel>
        <relationshipName>Provider_Identification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Prvdr_Iden_Typ_Cd__c</fullName>
        <label>Identification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NPI</fullName>
                </value>
                <value>
                    <fullName>Govt. ID</fullName>
                </value>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Identification</label>
    <nameField>
        <displayFormat>PI-{0}</displayFormat>
        <label>Provider Identification Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Identification</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_SPL_Addr__c.object
<CustomObject>
    <description>Service &amp; Payee Location Address Object based on PFIN Number</description>
    <fields>
        <fullName>CLM_Address__c</fullName>
        <formula>CM_SPL_Addr_Line_1__c +&apos; &apos;+ CM_SPL_Add_Line_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLM_NPI__c</fullName>
        <label>NPI Number</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Addr_Type__c</fullName>
        <description>Provider Address Usage Type</description>
        <inlineHelpText>Provider Address Usage Type</inlineHelpText>
        <label>Address Usage Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Capitation</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Directory</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Credentialing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CM_SPL_City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_PFIN_No__c</fullName>
        <label>PFIN Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service &amp; Payee Location Address</relationshipLabel>
        <relationshipName>Account_Tax_Addresses_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Zip_CD__c</fullName>
        <description>Zip Code</description>
        <inlineHelpText>Zip Code</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_Id__c</fullName>
        <formula>CM_SPL_Prov__r.Prov_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prov Id</label>
        <type>Text</type>
    </fields>
    <label>Service &amp; Payee Location Address</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Address Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service &amp; Payee Location Address</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_size__c</fullName>
        <label>List size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/classes/CLM_LocatinSearchTest.cls
/******************************
Test class name     : CLM_LocatinSearchTest
Version             : 1.0
Function            : This is a test class for CLM_LocationSearchController apex class

Developer                  Date                                
------------------------------------------------------------------------------------- 
Chaitanya Motupalli        5/1/2019 
                     
******************************/


@isTest 
private class CLM_LocatinSearchTest{


/*The following "testData" method helpful to load test data for all objects such as Account,Agreement,Provider Identification
Service &payee location address, Agreement provider location. Here PFIN Search functionality has been checked. */

    static testMethod void testData()
    {
        
      
    	GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;

         RecordType rolodexType = [Select Id From RecordType Where sObjectType='Account' and DeveloperName='Rolodex'];

        Account acc= new Account();

        acc.lastName='rolodex Account';

        acc.Tax_Id__c='123456789';

        acc.NPI__c='1234567890';

        acc.RecordTypeId=rolodexType.Id;

        acc.CM_Corporate_Entity_Code__c = 'IL1';

        acc.Phone = '9185512503';
        acc.Prov_ID__c='708472251';

        acc.PersonEmail = 'testemail@email.com';

        insert acc;
       
      		user u=[select Id from user where userrole.Name in ('CLM Illinois', 'Illinois Supervisor') AND user.IsActive = true limit 1];
      		Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      		agrmt.Apttus__Account__c=acc.Id;
      		agrmt.Plan__c='illinois';
        	agrmt.OwnerId=u.Id;
      
      		insert agrmt;
      
      	  CLM_Prov_Id_Search__c IdSearch=new CLM_Prov_Id_Search__c();
          IdSearch.CLM_Prov_Id__c='708472251';
          IdSearch.Account__c=acc.Id;
          IdSearch.Agreement__c=agrmt.Id;
      
      	  insert IdSearch;
        
      	CM_Provider_Identification__c loc=new CM_Provider_Identification__c();
      	loc.CM_Prvdr_Iden_Typ_Cd__c='NPI';
      	loc.CM_Issu_Ident_Nmbr__c='1111';
      	loc.CM_PI_Prov__c=acc.Id;
      
      	insert loc;
      
          CM_Provider_Identification__c loc2=new CM_Provider_Identification__c();
          loc2.CM_Prvdr_Iden_Typ_Cd__c='Govt. Id';
          loc2.CM_Issu_Ident_Nmbr__c='1111';
          loc2.CM_PI_Prov__c=acc.Id;
          
      insert loc2;
      
      CM_Provider_Identification__c loc3=new CM_Provider_Identification__c();
      loc3.CM_Prvdr_Iden_Typ_Cd__c='Medicare';
      loc3.CM_Issu_Ident_Nmbr__c='1111';
      loc3.CM_PI_Prov__c=acc.Id;
      
      insert loc3;
      
      CM_SPL_Addr__c servLoc=new CM_SPL_Addr__c();
      servLoc.CLM_NPI__c='11111';
      
      servLoc.CM_SPL_City__c='CA';
      servLoc.CM_SPL_Zip_CD__c='11111';
      servLoc.CM_SPL_Prov__c=acc.Id;
      
      insert servLoc;
    
      Agreement_Provider_Locations__c  provLoc=new Agreement_Provider_Locations__c ();
      provLoc.CLM_SPL_City__c='CA';
      provLoc.CLM_SPL_Zip_CD__c='11111';
      provLoc.CLM_Address__c='CA';
      provLoc.CLM_SPL_NPI_Number__c='11111';
      
      insert provLoc;
      
      CLM_LocationSearchController.locationWrapper cmp = new CLM_LocationSearchController.locationWrapper();
      cmp.isSelected=true;
      
      Agreement_Provider_Locations__c agrtmLoc=new Agreement_Provider_Locations__c();
      agrtmLoc.Agreement__c=agrmt.Id;
      agrtmLoc.CLM_SPL_Addr_Type__c=servLoc.CM_SPL_Addr_Type__c;
      
      agrtmLoc.CLM_SPL_Zip_CD__c=servLoc.CM_SPL_Zip_CD__c;
      agrtmLoc.CLM_SPL_PFIN_No__c=servLoc.CM_SPL_PFIN_No__c;
      agrtmLoc.CLM_SPL_NPI_Number__c=servLoc.CLM_NPI__c;
      insert agrtmLoc;
      
      
      
      ApexPages.StandardController sc = new ApexPages.StandardController(agrmt);
      CLM_LocationSearchController ctrl= new CLM_LocationSearchController (sc);
    
    
      PageReference pageRef = Page.CLM_LocationSearch;
      pageRef.getParameters().put('id', String.valueOf(agrmt.Id));
      Test.setCurrentPage(pageRef);
        
      ctrl.PFIN=true;
      ctrl.searchText='708472251';
      ctrl.provIdSearchTxt='708472251';
      //ctrl.master=true;
      
        
      ctrl.smartsearch();
      ctrl.getsearchSites();
      ctrl.createLocations();
      ctrl.quickSave();
      ctrl.Cancel();
      ctrl.updteNPIDetails();
      ctrl.searchProvId();
      ctrl.removeProvId();
      ctrl.masterCheckBox();
      ctrl.removeLocation();
      ctrl.GetIsClassic();
      ctrl.Firstbtn();
      ctrl.prvbtn();
      ctrl.nxtbtn();
      ctrl.lstbtn();
      ctrl.getnxt();
      ctrl.getprv();
   
    }
   
   
   
   
   
   static testMethod void testData2() {
       
       
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
     RecordType rolodexType = [Select Id From RecordType Where sObjectType='Account' and DeveloperName='Rolodex'];

        Account acc= new Account();

        acc.lastName='rolodex Account';

        acc.Tax_Id__c='123456789';

        acc.NPI__c='1234567890';

        acc.RecordTypeId=rolodexType.Id;

        acc.CM_Corporate_Entity_Code__c = 'OK1';

        acc.Phone = '9185512503';

        acc.PersonEmail = 'testemail@email.com';

        insert acc;
      
     	 user u=[select Id from user where userrole.Name in ('CLM Oklahoma' ,'Oklahoma Supervisor') AND user.IsActive = true limit 1];
       
      	Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      	agrmt.Apttus__Account__c=acc.Id;
      	agrmt.Plan__c='Oklahoma';
       	agrmt.OwnerId=u.Id;
      	insert agrmt;
      
         CM_SPL_Addr__c servLoc=new CM_SPL_Addr__c();
          servLoc.CLM_NPI__c='11111';
          
          servLoc.CM_SPL_City__c='CA';
          servLoc.CM_SPL_Zip_CD__c='11111';
          servLoc.CM_SPL_Prov__c=acc.Id;
          
          insert servLoc;
    
      Agreement_Provider_Locations__c  provLoc=new Agreement_Provider_Locations__c ();
      provLoc.CLM_SPL_City__c='CA';
      provLoc.CLM_SPL_Zip_CD__c='11111';
      provLoc.CLM_Address__c='CA';
      provLoc.CLM_SPL_NPI_Number__c='11111';
      
      insert provLoc;
      
      CLM_LocationSearchController.locationWrapper cmp = new CLM_LocationSearchController.locationWrapper();
      cmp.isSelected=true;
      
      ApexPages.StandardController sc = new ApexPages.StandardController(agrmt);
      CLM_LocationSearchController ctrl= new CLM_LocationSearchController (sc);
    
      PageReference pageRef = Page.CLM_LocationSearch;
      pageRef.getParameters().put('id', String.valueOf(agrmt.Id));
      Test.setCurrentPage(pageRef);
      
      ctrl.PFIN=true;
      ctrl.provIdSearchTxt='33333';
      ctrl.master=true;
      
      ctrl.smartsearch();
      ctrl.getsearchSites();
      ctrl.createLocations();
      ctrl.quickSave();
      ctrl.Cancel();
      ctrl.updteNPIDetails();
      ctrl.searchProvId();
      ctrl.removeProvId();
      ctrl.masterCheckBox();
      ctrl.removeLocation();
      ctrl.GetIsClassic();
      ctrl.Firstbtn();
      ctrl.prvbtn();
      ctrl.nxtbtn();
      ctrl.lstbtn();
      ctrl.getnxt();
      ctrl.getprv();
       
       
    }
    
    
    //TaxID Search 
    
     static testMethod void testData3() {
     
      GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
     RecordType rolodexType = [Select Id From RecordType Where sObjectType='Account' and DeveloperName='Rolodex'];

        Account acc= new Account();

        acc.lastName='rolodex Account';

        acc.Tax_Id__c='123456789';

        acc.NPI__c='1234567890';

        acc.RecordTypeId=rolodexType.Id;

        acc.CM_Corporate_Entity_Code__c = 'TX1';

        acc.Phone = '9185512503';

        acc.PersonEmail = 'testemail@email.com';

        insert acc;
      
      user u=[select Id from user where userrole.Name in('CLM Texas', 'Texas Supervisor') AND user.IsActive = true limit 1];
      Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c=acc.Id;
      agrmt.Plan__c='Texas';
         agrmt.OwnerId=u.Id;
      insert agrmt;
      
      CM_SPL_Addr__c servLoc=new CM_SPL_Addr__c();
      servLoc.CLM_NPI__c='11111';
      
      servLoc.CM_SPL_City__c='CA';
      servLoc.CM_SPL_Zip_CD__c='11111';
      servLoc.CM_SPL_Prov__c=acc.Id;
      
      insert servLoc;
    
      Agreement_Provider_Locations__c  provLoc=new Agreement_Provider_Locations__c ();
      provLoc.CLM_SPL_City__c='CA';
      provLoc.CLM_SPL_Zip_CD__c='11111';
      provLoc.CLM_Address__c='CA';
      provLoc.CLM_SPL_NPI_Number__c='11111';
      
      insert provLoc;
      
      CLM_LocationSearchController.locationWrapper cmp = new CLM_LocationSearchController.locationWrapper();
      cmp.isSelected=true;
      
      ApexPages.StandardController sc = new ApexPages.StandardController(agrmt);
      CLM_LocationSearchController ctrl= new CLM_LocationSearchController (sc);
    
      PageReference pageRef = Page.CLM_LocationSearch;
      pageRef.getParameters().put('id', String.valueOf(agrmt.Id));
      Test.setCurrentPage(pageRef);
      
      ctrl.taxId=true;
      ctrl.searchText='11111';
        
      
      ctrl.smartsearch();
      ctrl.getsearchSites();
      ctrl.createLocations();
      ctrl.searchProvId();
      ctrl.Cancel();
      ctrl.updteNPIDetails();
      ctrl.Firstbtn();
      ctrl.prvbtn();
      ctrl.nxtbtn();
      ctrl.lstbtn();
      ctrl.getnxt();
      ctrl.getprv();
      
      
    }
    
    
    //NPI search
    
     static testMethod void testData4() {
    
     
           GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;      
       RecordType rolodexType = [Select Id From RecordType Where sObjectType='Account' and DeveloperName='Rolodex'];

        Account acc= new Account();

        acc.lastName='rolodex Account';

        acc.Tax_Id__c='123456789';

        acc.NPI__c='1234567890';

        acc.RecordTypeId=rolodexType.Id;

        acc.CM_Corporate_Entity_Code__c = 'MT1';

        acc.Phone = '9185512503';

        acc.PersonEmail = 'testemail@email.com';

        insert acc;
         
      user u=[select Id from user where userrole.Name in('CLM Montana','Montana Supervisor') AND user.IsActive = true limit 1];
      Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c=acc.Id;
         agrmt.OwnerId=u.Id;
      agrmt.Plan__c='Montana';
      
      insert agrmt;
      
      CM_SPL_Addr__c servLoc=new CM_SPL_Addr__c();
      servLoc.CLM_NPI__c='11111';
      
      servLoc.CM_SPL_City__c='CA';
      servLoc.CM_SPL_Zip_CD__c='11111';
      servLoc.CM_SPL_Prov__c=acc.Id;
      
      insert servLoc;
    
      Agreement_Provider_Locations__c  provLoc=new Agreement_Provider_Locations__c ();
      provLoc.CLM_SPL_City__c='CA';
      provLoc.CLM_SPL_Zip_CD__c='11111';
      provLoc.CLM_Address__c='CA';
      provLoc.CLM_SPL_NPI_Number__c='11111';
      
      insert provLoc;
      
      CLM_LocationSearchController.locationWrapper cmp = new CLM_LocationSearchController.locationWrapper();
      cmp.isSelected=true;
      
      ApexPages.StandardController sc = new ApexPages.StandardController(agrmt);
      CLM_LocationSearchController ctrl= new CLM_LocationSearchController (sc);
    
      PageReference pageRef = Page.CLM_LocationSearch;
      pageRef.getParameters().put('id', String.valueOf(agrmt.Id));
      Test.setCurrentPage(pageRef);
      
      ctrl.npi=true;
      ctrl.searchText='11111';
        
     
      ctrl.smartsearch();
      ctrl.getsearchSites();
      ctrl.createLocations();
      ctrl.searchProvId();
      ctrl.Cancel();
      ctrl.updteNPIDetails();
      ctrl.Firstbtn();
      ctrl.prvbtn();
      ctrl.nxtbtn();
      ctrl.lstbtn();
      ctrl.getnxt();
      ctrl.getprv();
     
       
    }
 
    
}