src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percent_of_Covered_Charges__c</fullName>
        <label>Percent of Covered Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Networks__c</fullName>
        <label>Provider Networks</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL BlueCare Direct HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Select PPO Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Blue FocusCare HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Precision HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Broad PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL HMO of Illinois Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicaid Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL MMAI Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Focus Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Options Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Closed Plan Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT HealthLink Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Point of Service Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Traditional Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Community HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicaid Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PAR Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM POS Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PPO Provider Network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_size__c</fullName>
        <label>List size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTSMD_CustomIterableAgreement_Test.cls
@istest

public class APTSMD_CustomIterableAgreement_Test{
  
  static testmethod void testData(){
      
      GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
  
      Account acc= new Account();
      acc.Name               = 'Test Account CLM_Plan_IL';  
      acc.CM_Corporate_Entity_Code__c   = 'IL1';
      acc.RecordTypeId          = [SELECT Id, Name FROM RecordType WHERE Name = 'Entity Account'].Id;
      insert acc;
      
      Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
      Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c=acc.Id;
      //agrmt.OwnerId=u.Id;
      //agrmt.Plan__c='Illinois';
      agrmt.Provider_Networks__c=  null;
      agrmt.recordtypeId=professionalRecordTypeId ;
      agrmt.Percent_of_Covered_Charges__c= 10;
      
      insert agrmt;
      APTSMD_AgreementWrapper wrap=new APTSMD_AgreementWrapper(agrmt,true);
      
     List<APTSMD_AgreementWrapper> lstAccWr=new List<APTSMD_AgreementWrapper>();
     APTSMD_CustomIterableAgreement ctrl=new APTSMD_CustomIterableAgreement(lstAccWr);
     ctrl.hasNext();
     ctrl.hasPrevious();
     ctrl.next();
     ctrl.previous();
  }
  
  static testmethod void testData2(){
      
      GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
  
      Account acc= new Account();
      acc.Name               = 'Test Account CLM_Plan_IL';  
      acc.CM_Corporate_Entity_Code__c   = 'IL1';
      acc.RecordTypeId          = [SELECT Id, Name FROM RecordType WHERE Name = 'Entity Account'].Id;
      insert acc;
      
      Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
      Apttus__APTS_Agreement__c agrmt=new Apttus__APTS_Agreement__c();
      agrmt.Apttus__Account__c=acc.Id;
      //agrmt.OwnerId=u.Id;
      //agrmt.Plan__c='Illinois';
      agrmt.Provider_Networks__c=  null;
      agrmt.recordtypeId=professionalRecordTypeId ;
      agrmt.Percent_of_Covered_Charges__c= 10;
      
      insert agrmt;
      APTSMD_AgreementWrapper wrap=new APTSMD_AgreementWrapper(agrmt,true);
      
     List<APTSMD_AgreementWrapper> lstAccWr=new List<APTSMD_AgreementWrapper>();
     APTSMD_CustomIterableAgreement ctrl=new APTSMD_CustomIterableAgreement(lstAccWr);
     ctrl.i=5;
     ctrl.setPageSize=2;
     ctrl.hasNext();
     ctrl.hasPrevious();
     ctrl.next();
     ctrl.previous();
  }
  
  
}