src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <externalId>true</externalId>
        <label>NPI</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <externalId>true</externalId>
        <label>Prov ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rolodex_Account_for__c</fullName>
        <description>PPN-20008</description>
        <label>Rolodex Account for</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Entity_Account</fullName>
        <active>true</active>
        <description>Business Entities (not People).  Hospitals, Clinics, Groups, Locations, Facilities, etc</description>
        <label>Entity Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Provider_Identification__c.object
<CustomObject>
    <description>Provider Identification Object contains the Issued Identification types and numbers of the provider like License,NPI, Medicare etc</description>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Issu_Ident_Nmbr__c</fullName>
        <externalId>true</externalId>
        <label>Identification Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_PI_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Identification</relationshipLabel>
        <relationshipName>Provider_Identification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Prvdr_Iden_Typ_Cd__c</fullName>
        <label>Identification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NPI</fullName>
                </value>
                <value>
                    <fullName>Govt. ID</fullName>
                </value>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Identification</label>
    <nameField>
        <displayFormat>PI-{0}</displayFormat>
        <label>Provider Identification Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Identification</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_Provider_Tax_Id__c.object
<CustomObject>
    <description>Provider Tax Identification Object  shows how and where billing is done.</description>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Prov_Name_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Tax Identifications</relationshipLabel>
        <relationshipName>Provider_Tax_Identifications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider Tax Identification</label>
    <nameField>
        <displayFormat>PTI-{0}</displayFormat>
        <label>Prov Tax Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Tax Identifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CM_SPL_Addr__c.object
<CustomObject>
    <description>Service &amp; Payee Location Address Object based on PFIN Number</description>
    <fields>
        <fullName>Bill_PFIN__c</fullName>
        <description>Part of 40kpfin user stories.</description>
        <label>Bill PFIN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Addr_Type__c</fullName>
        <description>Provider Address Usage Type</description>
        <inlineHelpText>Provider Address Usage Type</inlineHelpText>
        <label>Address Usage Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Capitation</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Directory</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Credentialing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CM_SPL_PFIN_No__c</fullName>
        <label>PFIN Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Prov_Tax_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Tax Identification</label>
        <referenceTo>CM_Provider_Tax_Id__c</referenceTo>
        <relationshipLabel>Service &amp; Payee Location Address</relationshipLabel>
        <relationshipName>Service_Payee_Location_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_SPL_Prov__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service &amp; Payee Location Address</relationshipLabel>
        <relationshipName>Account_Tax_Addresses_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prov_Id__c</fullName>
        <formula>CM_SPL_Prov__r.Prov_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prov Id</label>
        <type>Text</type>
    </fields>
    <label>Service &amp; Payee Location Address</label>
    <nameField>
        <displayFormat>PA-{0}</displayFormat>
        <label>Address Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service &amp; Payee Location Address</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_size__c</fullName>
        <label>List size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <fields>
        <fullName>PFIN_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PFIN Case</description>
        <label>PFIN Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Provider_Networks_PFIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <description>Prov ID</description>
        <label>Prov ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountTriggerHandler_Test.cls
/**
 * This is the test class for the Account Trigger and Handler
 * <p/><p/>
 * @author Travis Self
 */
@isTest
public class AccountTriggerHandler_Test  {
    
    @testSetup static void createTestData() {
        
        GlobalSettings__c gs = new GlobalSettings__c();
        gs.name = 'PFFileRecieved';
        gs.PFFileRecieved__c = false;
        gs.List_size__c = 10;
        gs.Account_trigger_switch__c = false;
        gs.Record_Type_Names__c = 'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        testclassdata.CreateCustomSettingData('Case');
        testclassdata.CreateCustomSettingData('Provider_Networks__c');
    
        Case netwkLoadCase = new Case();
        netwkLoadCase.recordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Provider_Group_On_boarding_Network_Load').getRecordTypeId();
        netwkLoadCase.Plan_ID__c = 'IL1';
        netwkLoadCase.Status = 'New';
        netwkLoadCase.Prov_ID__c = '985415357';
        insert netwkLoadCase;
        
        Account newPhysicianAccount = new Account();
        newPhysicianAccount.LastName = 'Physician Account';
        newPhysicianAccount.recordTypeId=  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Physician').getRecordTypeId();
        newPhysicianAccount.CM_Corporate_Entity_Code__c = 'IL1';
        newPhysicianAccount.Prov_ID__c = '985415357';
        newPhysicianAccount.Class__c = 'P';
        
        insert newphysicianAccount;
        
        CM_Provider_Tax_Id__c newTax = new CM_Provider_Tax_Id__c();
        newTax.CM_PTI_Tax_Id__c = '123456789';
        newTax.CM_Corporate_Entity_Code__c = 'IL1';
        newTax.CM_PTI_Prov_Name_From__c = newPhysicianAccount.Id;
        
        CM_Provider_Identification__c newNPI = new CM_Provider_Identification__c();
        newNPI.CM_Prvdr_Iden_Typ_Cd__c = 'NPI';
        newNPI.CM_Issu_Ident_Nmbr__c ='1234567890';
        newNPI.CM_Corporate_Entity_Code__c = 'IL1';
        newNPI.CM_PI_Prov__c = newPhysicianAccount.Id;
        
        CM_SPL_Addr__c serviceAndPayeAddr = new CM_SPL_Addr__c();
        serviceAndPayeAddr.CM_Corporate_Entity_Code__c = 'IL1';
        serviceAndPayeAddr.CM_SPL_Addr_Type__c = 'Service';
        serviceAndPayeAddr.CM_SPL_Prov_Tax_ID__c = newTax.Id;
        serviceAndPayeAddr.CM_SPL_PFIN_No__c = '0IL6647980';
        serviceAndPayeAddr.Bill_PFIN__c = '0IL6647980';
        serviceAndPayeAddr.CM_SPL_Prov__c = newPhysicianAccount.Id;
                
        insert newTax;
        insert newNPI;
        insert serviceAndPayeAddr;
        createCaseTestData(newPhysicianAccount);
    }

    @isTest
    static void insertAndUpdateNonRolodexAccountsTest() {
        
        List<User> integrationUser = TestCaseUtil.createUser('Integration', 'Business Admin', 1);
        integrationUser[0].Alias = 'prov';
        
        insert integrationUser[0];
        
        List<Account> lstAccountsToInsert = new List<Account>();
        
        Account newPhysicianAccount = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Physician' LIMIT 1];
        lstAccountsToInsert.add(newPhysicianAccount);
        
        Account newEntityAccount = new Account();
        newEntityAccount.Name = 'Entity Account';
        newEntityAccount.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Entity_Account').getRecordTypeId();
        newEntityAccount.CM_Corporate_Entity_Code__c = 'IL1';
        newEntityAccount.Prov_ID__c = '887744298';
        lstAccountsToInsert.add(newEntityAccount);
        
        Test.startTest();
        	System.runAs(integrationUser[0]) {
        		upsert lstAccountsToInsert;
    		}
        Test.stopTest();
    }
    
    @isTest
    static void insertAndUpdateRolodexAccountTest() {
        
        Account newRolodex = new Account();
        newRolodex.Rolodex_Account_for__c = 'Individual';
        newRolodex.FirstName = 'Rolodex';
        newRolodex.lastName = 'Account';
        newRolodex.Phone = '9185512503';
        newRolodex.PersonEmail = 'testemail@email.com';
        newRolodex.Tax_Id__c = '123456789';
        newRolodex.NPI__c = '1234567890';
        newRolodex.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Rolodex').getRecordTypeId();
        newRolodex.CM_Corporate_Entity_Code__c = 'IL1';
        
        Test.startTest();
        	insert newRolodex;
        	
        	try {
                // Give bad data to test phone validations
                newRolodex.Phone = '1';
                newRolodex.Fax = '1';
                newRolodex.PersonMobilePhone = '1';
                update newRolodex;
            } catch (DmlException e) {
                System.assert(e != null);
            }
		Test.stopTest();
    }
   
    static void createCaseTestData(Account accToLink) {
        
        List<Case> lstOtherCasesToInsert = new List<Case>();
        
        Case onBoardingParentCase = new Case();
        onBoardingParentCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Provider_On_boarding').getRecordTypeId();
        onBoardingParentCase.AccountId = accToLink.Id;
        onBoardingParentCase.Corporate_Received_Date_Time__c = System.now();
        insert onBoardingParentCase;
        
        Case onBoardingCase = new Case();
        onBoardingCase.Billing_NPI_Number__c = '1234567890';
        onBoardingCase.Tax_Id_Number__c = '123456789';
        onBoardingCase.recordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Data_Entry_Provider_On_boarding').getRecordTypeId();
        onBoardingCase.Plan_ID__c = 'IL1';
        onBoardingCase.ParentId = onBoardingParentCase.Id;
        onBoardingCase.AccountId = accToLink.Id;
        insert onBoardingCase;
        
        Provider_Networks__c prvDetail = new Provider_Networks__c();
        prvDetail.PFIN_Case__c = onBoardingCase.Id;
        prvDetail.Prov_ID__c = '985415357';
        prvDetail.Plan_Id__c = 'IL1';
        insert prvDetail;
        
        onBoardingCase.Status = 'Closed Processed';
        
        update onBoardingCase;
        
        Case contractingCase = new Case();
        contractingCase.Billing_NPI_Number__c = '1234567890';
        contractingCase.Tax_Id_Number__c = '123456789';
        contractingCase.recordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Contracting_Provider_On_boarding').getRecordTypeId();
        contractingCase.Plan_ID__c = 'IL1';
        contractingCase.ParentId = onBoardingParentCase.Id;
        contractingCase.AccountId = accToLink.Id;
        insert contractingCase;
        
    }
    
}