src/objects/Affiliations__c.object
<CustomObject>
    <label>Affiliations</label>
    <nameField>
        <displayFormat>A{0}</displayFormat>
        <label>Affiliation Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Affiliation_Trigger_Switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Affiliation Trigger Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/classes/TestAffiliationTrigger.cls
@isTest
public class TestAffiliationTrigger {
    
    @testSetup static void prepareData() {
        GlobalSettings__c gs				= new GlobalSettings__c();
        gs.name 							= 'PFFileRecieved';
        gs.PFFileRecieved__c				= false;
        gs.Affiliation_Trigger_Switch__c	= false;
        insert gs;
	}

    public static testmethod void testAffTrigger() {
        
        Affiliations__c aff1 = new Affiliations__c();
        
        Test.startTest();
        
        	insert aff1;
        
        	update aff1;
        
        	delete aff1;
        
        	undelete aff1;
        
        Test.stopTest();
        
    }
    
}