src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>BA_BP_IP_Hospital_Services_per_diem__c</fullName>
        <label>BA/BP IP Hospital Services per diem</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BA_BP_Residential_Treat_Srvcs_per_diem__c</fullName>
        <label>BA/BP Residential Treat. Srvcs per diem</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BA_IP_Max_Reimb_Allowance_Per_Diem__c</fullName>
        <label>BA IP Max Reimb. Allowance Per Diem</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BChoice_Max_Reimb_Allow_Resid_Treat_Srvc__c</fullName>
        <label>BChoice Max Reimb Allow-Resid Treat Srvc</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BPref_Max_Reimb_Allowed_Resid_Treat_Srvc__c</fullName>
        <label>BPref Max Reimb Allowed-Resid Treat Srvc</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BT_Network_Max_Reimbursement_Allowance__c</fullName>
        <label>BT Network Max Reimbursement Allowance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BlueLincs_HMO_Lab_Conversion_Factor__c</fullName>
        <label>BlueLincs HMO Lab Conversion Factor</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Blue_Advantage_PPO_Lab_Conversion_Factor__c</fullName>
        <label>Blue Advantage PPO Lab Conversion Factor</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Blue_Traditional_Lab_Conversion_Factor__c</fullName>
        <label>Blue Traditional Lab Conversion Factor</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_BlueLincsHmoLabConversionFact__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created to help us bypass the validation rule until the auto populated value is removed from the field</description>
        <label>CLM_Bypass_BlueLincsHmoLabConversionFac</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_BlueTraditionalLabConverFacto__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created to help us bypass the validation rule until the auto populated value is removed from the field</description>
        <label>CLM_Bypass_BlueTraditionalLabConverFac</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_MaHmoLesserOfCovered__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created to help us bypass the validation rule until the auto populated value is removed from the field</description>
        <label>CLM_Bypass_MaHmoLesserOf%OfCovered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_MaHmoLesserOfMedicAllo__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created to help us bypass the validation rule until the auto populated value is removed from the field</description>
        <label>CLM_Bypass_MaHmoLesserOf%OfMedicAllo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_MaPpoLesserOfCovered__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created to help us bypass the validation rule until the auto populated value is removed from the field</description>
        <label>CLM_Bypass_MaPpoLesserOf%OfCovered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_MaPpoLesserOfMedicareAl__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created to help us bypass the validation rule until the auto populated value is removed from the field</description>
        <label>CLM_Bypass_MaPpoLesserOf%OfMedicareAl</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_PercentCoveredCharges__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field Created to bypass the validation rule on percent covered charges field when we want to default the field value to 100</description>
        <label>CLM_Bypass_PercentCoveredCharges</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_PpoLabConversionFactor__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created to help us bypass the validation rule until the auto populated value is removed from the field</description>
        <label>CLM_Bypass_PpoLabConversionFactor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IP_Max_Reimbursement_Allowance_Per_Diem__c</fullName>
        <label>IP Max Reimbursement Allowance  Per Diem</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MA_HMO_lesser_of_of_Covered__c</fullName>
        <label>MA HMO lesser of % of Covered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MA_HMO_lesser_of_of_Medicare_allowed__c</fullName>
        <label>MA HMO lesser of % of Medicare allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MA_PPO_lesser_of_of_Covered__c</fullName>
        <label>MA PPO lesser of % of Covered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MA_PPO_lesser_of_of_Medicare_allowed__c</fullName>
        <label>MA PPO lesser of % of Medicare allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_of_Covered_Charges__c</fullName>
        <label>Percent of Covered Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Networks__c</fullName>
        <label>Provider Networks</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL BlueCare Direct HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Select PPO Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Blue FocusCare HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Precision HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Broad PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL HMO of Illinois Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicaid Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL MMAI Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Focus Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Options Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Closed Plan Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT HealthLink Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Point of Service Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Traditional Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Community HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicaid Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PAR Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM POS Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PPO Provider Network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Service_Type__c</fullName>
        <label>Provider Service Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dialysis</fullName>
                </value>
                <value>
                    <fullName>Home Health</fullName>
                </value>
                <value>
                    <fullName>Hospice</fullName>
                </value>
                <value>
                    <fullName>SNF</fullName>
                </value>
                <value>
                    <fullName>ASC</fullName>
                </value>
                <value>
                    <fullName>Air Ambulance</fullName>
                </value>
                <value>
                    <fullName>Autism Agency</fullName>
                </value>
                <value>
                    <fullName>Birthing Center</fullName>
                </value>
                <value>
                    <fullName>DME</fullName>
                </value>
                <value>
                    <fullName>DME w/ Power Mobility</fullName>
                </value>
                <value>
                    <fullName>DME w/o Power Mobility</fullName>
                </value>
                <value>
                    <fullName>Health Screening Vendor</fullName>
                </value>
                <value>
                    <fullName>Home Infusion</fullName>
                </value>
                <value>
                    <fullName>Lab and Imaging</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                </value>
                <value>
                    <fullName>Sleep Facility</fullName>
                </value>
                <value>
                    <fullName>Home Health and Hospice</fullName>
                </value>
                <value>
                    <fullName>Ambulance</fullName>
                </value>
                <value>
                    <fullName>Facility -Acute Care</fullName>
                </value>
                <value>
                    <fullName>Psych</fullName>
                </value>
                <value>
                    <fullName>RTC</fullName>
                </value>
                <value>
                    <fullName>Facility-Behavioral Health</fullName>
                </value>
                <value>
                    <fullName>Facility-Rehab</fullName>
                </value>
                <value>
                    <fullName>Facility-LTAC</fullName>
                </value>
                <value>
                    <fullName>MG-Anesthesia</fullName>
                </value>
                <value>
                    <fullName>MG-Behavioral</fullName>
                </value>
                <value>
                    <fullName>MG-Chiropractic</fullName>
                </value>
                <value>
                    <fullName>MG-PCP</fullName>
                </value>
                <value>
                    <fullName>Prof-Anesthesia</fullName>
                </value>
                <value>
                    <fullName>Prof-Behavioral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Facility</fullName>
        <active>true</active>
        <label>Facility</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CLM_Oklahoma_ReimbursementHandler.cls
public class CLM_Oklahoma_ReimbursementHandler {
	public static void beforeUpdate(List<Apttus__APTS_Agreement__c>agreementList ,Map<Id,Apttus__APTS_Agreement__c> agreementOldMap,Map<Id,Apttus__APTS_Agreement__c> agreementNewMap){ 
        List<Apttus__APTS_Agreement__c> oklahomaAgreementLis = new List<Apttus__APTS_Agreement__c>();
        for(Apttus__APTS_Agreement__c  agreementObj : agreementList){
           Apttus__APTS_Agreement__c agreementObjOld = agreementOldMap.get(agreementObj.Id);  
            
            
            if(agreementObj.Plan__c == CLM_ReimbursementModel.OKLAHOMA_PLAN){
              // Deafulting Percent of Covered Charges Field 
                if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))){
                    if(agreementObjOld.Provider_Networks__c == null || (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))){
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = false;
                           agreementObj.Percent_of_Covered_Charges__c = 100;
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = true;
                       }
                }     
                
              // Clear field values for Percent of Covered Charges Field
                   
                if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))){
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)                       
                       ||  (agreementObj.Provider_Networks__c != null && (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)){                         
                           agreementObj.Percent_of_Covered_Charges__c = null;
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = true;                          
                       }
                }
              // Common logic start
            
            if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Service_Type__c != null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId )){
                // HMO Advantage Start
                if(agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK)){
                    if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK))
                       || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && agreementObjOld.Provider_Service_Type__c == null)){
                           if (agreementObj.recordTypeId == CLM_ReimbursementModel.ANCRecordTypeId){
                                 agreementObj.CLM_Bypass_MaHmoLesserOfCovered__c = false;
                                 agreementObj.CLM_Bypass_MaHmoLesserOfMedicAllo__c = false;
                               }
                           agreementObj.MA_HMO_lesser_of_of_Medicare_allowed__c = 100;
                           agreementObj.MA_HMO_lesser_of_of_Covered__c = 100;
                       }
                }
                // HMO Advantage End
                
                // PPO Advantage Start
                if(agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)){
                    if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))
                       || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && agreementObjOld.Provider_Service_Type__c == null) ){
                           if (agreementObj.recordTypeId == CLM_ReimbursementModel.ANCRecordTypeId){
                                 agreementObj.CLM_Bypass_MaPpoLesserOfMedicareAl__c = false;
                                 agreementObj.CLM_Bypass_MaPpoLesserOfCovered__c = false;
                               }    
                           agreementObj.MA_PPO_lesser_of_of_Medicare_allowed__c = 100;                            
                           agreementObj.MA_PPO_lesser_of_of_Covered__c = 100;
                       }
                 }
             }
                // PPO Advantage End
             
            // 
            // Clear values
            // HMO Advantage Starts
              if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK)){
                  if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && ( agreementObjOld.Provider_Service_Type__c !=null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId)) 
                            ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)
                            || (agreementObj.Provider_Networks__c != null &&  !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c && ( agreementObjOld.Provider_Service_Type__c !=null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId))){
                                agreementObj.MA_HMO_lesser_of_of_Medicare_allowed__c = null;
                                agreementObj.MA_HMO_lesser_of_of_Covered__c = null;
                                if (agreementObj.recordTypeId == CLM_ReimbursementModel.ANCRecordTypeId){
                                 agreementObj.CLM_Bypass_MaHmoLesserOfCovered__c = true;
                                 agreementObj.CLM_Bypass_MaHmoLesserOfMedicAllo__c = true;
                               }      
                  }
              }
            // HMO Advantage ends
            
            // PPO Advantage Starts
                
               if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)){ 
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && ( agreementObjOld.Provider_Service_Type__c !=null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId)) 
                          ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c) 
                          ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c && ( agreementObjOld.Provider_Service_Type__c !=null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId ))){
                              agreementObj.MA_PPO_lesser_of_of_Medicare_allowed__c = null;
                              agreementObj.MA_PPO_lesser_of_of_Covered__c = null;
                              if (agreementObj.recordTypeId == CLM_ReimbursementModel.ANCRecordTypeId){
                                 agreementObj.CLM_Bypass_MaPpoLesserOfMedicareAl__c = true;
                                 agreementObj.CLM_Bypass_MaPpoLesserOfCovered__c = true;
                               }       
                       }
                     }
             // PPO Advantage Ends
                   
               // OK Facility Record type - Reimbursement start
              // 
                if(agreementObj.recordTypeId == CLM_ReimbursementModel.facilityRecordTypeId){
                    
                    // Facility - LTAC service type
                    // Facility - LTAC IP Max Reimbursement Allowance Per Diem FIELD
                     if(agreementObj.Provider_Service_Type__c != null &&  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_LTAC)){
                         
                          if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                          agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                          agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK))){
                              
                            if((agreementObjOld.Provider_Networks__c == null || (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) &&
                          !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) &&
                          !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK)))
                              || ((agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK)) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_LTAC)))){
                               agreementObj.IP_Max_Reimbursement_Allowance_Per_Diem__c  = 1350;
                               
                             }
                               
                          }
                        // Facility LTAC BA IP Max Reimb. Allowance Per Diem FIELD
                      if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK))
                              || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_LTAC))){
                                 agreementObj.BA_IP_Max_Reimb_Allowance_Per_Diem__c	 = 1250.00;
                            }
                        
                         }
                     }
                       
                        // Facility LTAC record type end
                    
                        
                   
                     
                        // Facility RTC record type start
                        // Blue Choice Network
                    if(agreementObj.Provider_Service_Type__c != null &&  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC)){
                         if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK))
                              || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK)  && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC)))){
                                 agreementObj.BChoice_Max_Reimb_Allow_Resid_Treat_Srvc__c = 364;                       
                            }           
                         }
                         
                        //Blue Preferred Network
                          if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK) )
                              || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK)  && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC)))){
                                 agreementObj.BPref_Max_Reimb_Allowed_Resid_Treat_Srvc__c = 309;
                                 
                            }
                        
                         }
                         
                           
                        // Facility RTC Traditional Network
                        if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK))
                              || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC)))){
                                 agreementObj.BT_Network_Max_Reimbursement_Allowance__c = 419;
                                 
                            }
                        
                         }
                    }
                        // Facility RTC record type end
                        
                       // Facility PSYCH record type start
                if(agreementObj.Provider_Service_Type__c != null &&  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_PSYCH)){
                         if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK))){
                            if((agreementObjOld.Provider_Service_Type__c == null || agreementObjOld.Provider_Networks__c == null || ((agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK)) && !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_PSYCH))) 
                               || (agreementObjOld.Provider_Service_Type__c == null || agreementObjOld.Provider_Networks__c == null || ((!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK)) && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_PSYCH)))){
                                 agreementObj.BA_BP_IP_Hospital_Services_per_diem__c = 554;
                                 agreementObj.BA_BP_Residential_Treat_Srvcs_per_diem__c = 362;
                            }
                         }
                        // Facility PSYCH record type end
                    }
                    
                      // Clear values for Facility LTAC - BA IP Max Reimb. Allowance Per Diem FIELD
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_LTAC)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_LTAC) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){           
                                   	agreementObj.BA_IP_Max_Reimb_Allowance_Per_Diem__c	 = null;           		 
                           }
                    }
                    
                    // Clear values for Fac LTAC - IP Max Reimbursement Allowance Per Diem FIELD
                    /*if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK))){
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c)
                       ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                       ||  (agreementObj.Provider_Networks__c != null && (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) &&
                          !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) &&
                          !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)){
                                   agreementObj.IP_Max_Reimbursement_Allowance_Per_Diem__c = null;
                            }
                    } */
                   if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK)) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_LTAC)){
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c)
                       ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                       ||  (agreementObj.Provider_Networks__c != null && (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) &&
                          !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) &&
                          !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                       ||(!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_LTAC) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                                   agreementObj.IP_Max_Reimbursement_Allowance_Per_Diem__c = null;
                            }
                    }
                    
                    // Clear values for Facility PSYCH 
                        if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK))&& agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_PSYCH)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_PSYCH) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                              
                                 agreementObj.BA_BP_IP_Hospital_Services_per_diem__c = null;
                                 agreementObj.BA_BP_Residential_Treat_Srvcs_per_diem__c = null;
                                     		 
                           }
                     }
                               
                    // Clear values for Facility RTC
                    // Blue choice clear values
                        if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK)  && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK)  && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                              
                                agreementObj.BChoice_Max_Reimb_Allow_Resid_Treat_Srvc__c = null;        		 
                           }
                     }
                    
                     // Blue choice preffered clear values
                        if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK)  && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK)  && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                              
                                agreementObj.BPref_Max_Reimb_Allowed_Resid_Treat_Srvc__c = null;            		 
                           }
                     }
                    
                      // Blue Traditional preffered clear values
                        if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK)  && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK)  && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_RTC) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                              
                                agreementObj.BT_Network_Max_Reimbursement_Allowance__c = null;             		 
                           }
                     }
                // OK Facility REcord type - Reimbursement end                                        
               }
                
                // OK ANC record type start
                if(agreementObj.recordTypeId == CLM_ReimbursementModel.ANCRecordTypeId){
                    
                    // In Agreement Detail page, 
                    // rest of the other Fields which is not part of Service Type and Provider Networks combination selected by user will not be Editable
                    //  i.e. if user tries to edit and then clicks on save button an error message
                    //   ‘For the Provider Service Type and Provider Networks selected this field cannot be edited’ is displayed next to the field
                   
                  // Defaulting Values  
                  // Oklahoma ANC Lab Starts
                    if(agreementObj.Provider_Service_Type__c != null &&  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB)){ 
                  // Oklahoma ANC Lab Blue Advantage PPO Lab Conversion Factor field starts
                    	if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK))
                              || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB))){
                                  agreementObj.CLM_Bypass_PpoLabConversionFactor__c	 = false;
                                  agreementObj.Blue_Advantage_PPO_Lab_Conversion_Factor__c	 = 'nineteen dollars and forty-eight cents ($19.48)';
                            }
                        
                         }
                   //Oklahoma ANC Lab Blue Advantage PPO Lab Conversion Factor field ends
                        
                   //Oklahoma ANC Lab BlueLincs HMO Lab Conversion Factor field starts
                   if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK))
                              || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB))){
                                  agreementObj.CLM_Bypass_BlueLincsHmoLabConversionFact__c = false;
                                  agreementObj.BlueLincs_HMO_Lab_Conversion_Factor__c = 'nineteen dollars and forty-eight cents ($19.48)';
                            }
                        
                         }
                   // Oklahoma ANC Lab BlueLincs HMO Lab Conversion Factor field ends
                   
                   // Oklahoma ANC Lab Blue Traditional Lab Conversion Factor field starts    
                   if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK))
                              || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB))){
                                 agreementObj.CLM_Bypass_BlueTraditionalLabConverFacto__c = false;
                                 agreementObj.Blue_Traditional_Lab_Conversion_Factor__c	 = 'twenty-five dollars and twenty-nine cents ($25.29)';
                            }
                        
                         }
                   // Oklahoma ANC Lab Blue Traditional Lab Conversion Factor field ends
                   
                   //Oklahoma ANC Lab BlueChoice PPO Lab Conversion Factor field starts
                   if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK))
                              || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB))){
                                 agreementObj.CLM_Bypass_BlueChoicePpoLabConversionFac__c = false;
                                 agreementObj.BlueChoice_PPO_Lab_Conversion_Factor__c = 'twenty-four dollars and seventy six cents ($24.76)';
                            }
                        
                         }
                   // Oklahoma ANC Lab BlueChoice PPO Lab Conversion Factor field ends
                   
                   // Oklahoma ANC Lab BluePreferred PPO Lab Conversion Factor Field starts
                   if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK))
                              || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB))){
                                 agreementObj.CLM_Bypass_BluePreferredPpoLabConverFac__c = false;
                                 agreementObj.BluePreferred_PPO_Lab_Conversion_Factor__c = 'twenty-three dollars and seventeen cents ($23.17)';
                            }
                        
                         }
                   // Oklahoma ANC Lab BluePreferred PPO Lab Conversion Factor Field ends
                   
                  // Oklahoma Anc Lab RBRVS Publication Location field starts
                  if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                          agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                          agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))){
                              
                            if((agreementObjOld.Provider_Networks__c == null || (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) &&
                          !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) &&
                          !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)))
                              || ((agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB)))){
                               agreementObj.CLM_Bypass_RbrvsPublicationLocation__c  = false;
                               agreementObj.RBRVS_Publication_Location__c  = 'Federal Register Volume 80 No. 220 (dated November 16, 2015)';
                             }   
                          }
                    }
                  // Oklahoma Anc Lab RBRVS Publication Location field ends
                  
                  // Oklahoma ANC DME fields starts
                 if(agreementObj.Provider_Service_Type__c != null &&  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME)){
                     if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                              agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                              agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))){
                                  
                                if((agreementObjOld.Provider_Networks__c == null || (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) &&
                              !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) &&
                              !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)))
                                  || ((agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                              agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                              agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME)))){
                                   agreementObj.CLM_Bypass_DmeRentalFeePreAuthCapAmoun__c  = false;
                                   agreementObj.CLM_Bypass_DmePurchasePreAuthCapAmount__c  = false;
                                   agreementObj.DME_Purchase_pre_auth_cap_amount__c  = 'four thousand dollars ($4,000.00)';
                                   agreementObj.DME_Rental_Fee_pre_auth_cap_amount__c  = 'four thousand dollars ($4,000.00)';
                                 }
                      }         
                   }
                // Oklahoma ANC DME Fields ends
                
                // Oklahoma ANC SNF Starts
                // Oklahoma ANC SNF BlueLincs HMO SNF Max Per Diem Field starts
               if(agreementObj.Provider_Service_Type__c != null &&  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF)){
                   if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK)){
                        if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK))
                           || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF))){
                               agreementObj.CLM_Bypass_BlueLincsHmoSnfMaxPerDiem__c = false;
                               agreementObj.BlueLincs_HMO_SNF_Max_Per_Diem__c = 'three hundred sixty-five dollars ($365.00)';
                           }
                     }
               }
                // Oklahoma ANC SNF BlueLincs HMO SNF Max Per Diem Field ends
                
                // Oklahoma ANC SNF BlueTrad,Choice,Pref SNF Max Per Diem Field Starts
                if(agreementObj.Provider_Service_Type__c != null &&  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF)){
                         if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK))){
                            if((agreementObjOld.Provider_Service_Type__c == null || agreementObjOld.Provider_Networks__c == null || ((agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK)) && !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF))) 
                               || (agreementObjOld.Provider_Service_Type__c == null || agreementObjOld.Provider_Networks__c == null || ((!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK)) && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF)))){
                                 agreementObj.CLM_Bypass_BlueTradChoicePrefSnfMaxPer__c = false;
                                 agreementObj.BlueTrad_Choice_Pref_SNF_Max_Per_Diem__c = 'four hundred twenty-five dollars ($425.00)';
                            }
                         }
                 }
                // Oklahoma ANC SNF BlueTrad,Choice,Pref SNF Max Per Diem Field Ends
                
                // Oklahoma ANC SNF Blue Advantage PPO SNF Max Per Diem Field Starts
                if(agreementObj.Provider_Service_Type__c != null &&  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF)){
                    if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK)){
                        if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK))
                           || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF))){
                               agreementObj.CLM_Bypass_BlueAdvantagePpoSnfMaxPerDiem__c = false;
                               agreementObj.Blue_Advantage_PPO_SNF_Max_Per_Diem__c= 'three hundred forty dollars ($340.00)';
                           }       
                    }
                }
                // Oklahoma ANC  Blue Advantage PPO SNF Max Per Diem Field Ends
                  
                  // clear values for Oklahoma Anc Sarts
                  // Clear values for Oklahoma Lab Starts
                  // clear value for Oklahoma ANC Lab Blue Advantage PPO Lab Conversion Factor field starts
                  if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                                  agreementObj.Blue_Advantage_PPO_Lab_Conversion_Factor__c = null;
                                  agreementObj.CLM_Bypass_PpoLabConversionFactor__c	 = true;   		 
                           }
                    }
                   // clear value for Oklahoma ANC Lab Blue Advantage PPO Lab Conversion Factor field ends
                   
                   // clear value for Oklahoma ANC Lab BlueLincs HMO Lab Conversion Factor field starts
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                                agreementObj.BlueLincs_HMO_Lab_Conversion_Factor__c = null;
                              	agreementObj.CLM_Bypass_BlueLincsHmoLabConversionFact__c = true;	 
                           }
                    }
                    // clear value for Oklahoma ANC Lab BlueLincs HMO Lab Conversion Factor field ends
                    
                    // Clear values for Oklahoma ANC Lab Blue Traditional Lab Conversion Factor field starts 
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                              agreementObj.Blue_Traditional_Lab_Conversion_Factor__c = null; 
                              agreementObj.CLM_Bypass_BlueTraditionalLabConverFacto__c = true;
                           }
                    }
                    // Clear values for Oklahoma ANC Lab Blue Traditional Lab Conversion Factor field ends
                    
                    // clear values for Oklahoma ANC Lab BlueChoice PPO Lab Conversion Factor field starts
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                      		   agreementObj.BlueChoice_PPO_Lab_Conversion_Factor__c = null;
                               agreementObj.CLM_Bypass_BlueChoicePpoLabConversionFac__c = true;
                           }
                    }
                    //clear values for Oklahoma ANC Lab BlueChoice PPO Lab Conversion Factor field ends
                    
                    // Clear values for Oklahoma ANC Lab BluePreferred PPO Lab Conversion Factor Field starts          
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                           agreementObj.BluePreferred_PPO_Lab_Conversion_Factor__c = null; 
                           agreementObj.CLM_Bypass_BluePreferredPpoLabConverFac__c = true;
                           }
                    }
                    //Clear values for Oklahoma ANC Lab BluePreferred PPO Lab Conversion Factor Field ends
                    
                    // Clear Values for Oklahoma Anc Lab RBRVS Publication Location field starts
                    if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.Lab)){
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c)
                       ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                       ||  (agreementObj.Provider_Networks__c != null && (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) &&
                          !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) &&
                          !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c) 
                      || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.Lab) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                               agreementObj.RBRVS_Publication_Location__c  = null;
                               agreementObj.CLM_Bypass_RbrvsPublicationLocation__c  = true;
                          }
                    } 
                    // Clear Values for Oklahoma Anc Lab RBRVS Publication Location field ends
                    // Clear Values for Oklahoma ANC Ends
                    
                    // Clear Value for OK - DME starts
                    if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) ||
                          agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME)){
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c)
                       ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                       ||  (agreementObj.Provider_Networks__c != null && (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) &&
                          !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK ) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK) &&
                          !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PLAN65_SELECT_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BCBS_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                       || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                               agreementObj.DME_Purchase_pre_auth_cap_amount__c  = null;
                               agreementObj.DME_Rental_Fee_pre_auth_cap_amount__c  = null;
                               agreementObj.CLM_Bypass_DmeRentalFeePreAuthCapAmoun__c  = true;
                               agreementObj.CLM_Bypass_DmePurchasePreAuthCapAmount__c  = true;
                          }
                    } 
                    // Clear Value for OK - DME ends
                    
                    // Clear Values for OK SNF BlueLincs HMO SNF Max Per Diem Field Starts
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUELINES_HMO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                           	   agreementObj.BlueLincs_HMO_SNF_Max_Per_Diem__c = null;
                               agreementObj.CLM_Bypass_BlueLincsHmoSnfMaxPerDiem__c = true;
                           }
                    }
                    // Clear Values for OK SNF BlueLincs HMO SNF Max Per Diem Ends
                    
                    // Clear Values for OK SNF BlueTrad,Choice,Pref SNF Max Per Diem Field Starts
                    if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK))&& agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUECHOICE_PPO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_PREFERRED_PPO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUETRADITIONAL_PROVIDER_NETWORK)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                               agreementObj.BlueTrad_Choice_Pref_SNF_Max_Per_Diem__c = null;  
                               agreementObj.CLM_Bypass_BlueTradChoicePrefSnfMaxPer__c = true;       		 
                           }
                     }
                    // Clear Values for OK SNF BlueTrad,Choice,Pref SNF Max Per Diem Field Ends
                    
                    // Clear Values for OK SNF Blue Advantage PPO SNF Max Per Diem Starts
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.OK_BLUE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                           	   agreementObj.Blue_Advantage_PPO_SNF_Max_Per_Diem__c= null; 
                               agreementObj.CLM_Bypass_BlueAdvantagePpoSnfMaxPerDiem__c = true;
                           }
                    }
                    // Clear Values for OK SNF Blue Advantage PPO SNF Max Per Diem Ends
                  
                    
                }
              // Oklahoma Plan end
            } 
            
        }
        
    }

}