src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent_of_Covered_Charges__c</fullName>
        <label>Percent of Covered Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Networks__c</fullName>
        <label>Provider Networks</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL BlueCare Direct HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Select PPO Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Blue FocusCare HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Precision HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Broad PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL HMO of Illinois Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicaid Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL MMAI Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Focus Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Options Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Closed Plan Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT HealthLink Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Point of Service Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Traditional Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Community HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicaid Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PAR Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM POS Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PPO Provider Network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Facility</fullName>
        <active>true</active>
        <label>Facility</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_DocuApi__DocuSignEnvelope__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Apttus_CMDSign__Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>DocuSignEnvelopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_DocuApi__EnvelopeId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Envelope Id from DocuSign</description>
        <externalId>true</externalId>
        <inlineHelpText>Envelope Id from DocuSign</inlineHelpText>
        <label>Envelope Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CLM_E_Signature_Status__c</fullName>
        <description>To display the status of the envelope in order to identify with whom the Docusign Envelope is pending for signatures</description>
        <label>E-Signature Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope</label>
    <nameField>
        <label>DocuSign Envelope Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c.object
<CustomObject>
    <description>Docusign envelope recipient status</description>
    <fields>
        <fullName>CLM_E_Signature_Status__c</fullName>
        <formula>if( Apttus_DocuApi__Status__c == &apos;completed&apos;,
if( Apttus_DocuApi__RoleName__c ==&apos;Signer 3&apos;,&apos;Fully Signed&apos;,
if(Apttus_DocuApi__RoleName__c ==&apos;Signer 2&apos;,&apos;For CounterSign&apos;,
if(Apttus_DocuApi__RoleName__c ==&apos;Signer 1&apos;,&apos;Provider Signed&apos;,&apos;With Provider&apos;))),
if(Apttus_DocuApi__Status__c != &apos;completed&apos;,if(Apttus_DocuApi__RoleName__c ==&apos;Signer 1&apos;,&apos;With Provider&apos;, &apos;&apos;),&apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>E-Signature Status</label>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope Recipient Status</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>DocuSignEnvelopeRecipientStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Envelope Recipient Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DocuSignEVPRecipientStatus_CLMTest.cls
@isTest
public class DocuSignEVPRecipientStatus_CLMTest 
{
  
     static testMethod void testData1()
   {
    GlobalSettings__c glbs=TestDataFactory_CLM.InsertGlobalsetting();
        

        account acc= TestDataFactory_CLM.CreateAccount('NM1');
        
       
       // Apttus__APTS_Agreement__c agrmt= TestDataFactory_CLM.CreateAgreement('Facility','New Mexico','CLM New Mexico');
        
       
        list<Apttus_DocuApi__DocuSignDefaultRecipient2__c>reclist= TestDataFactory_CLM.CreateDocusignRecipients();
        

       user u=[select Id from user where userrole.Name='Texas Supervisor' AND user.IsActive = true limit 1];
        Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
       //Apttus__APTS_Agreement__c agg= TestDataFactory_CLM.CreateAgreement('Facility','New Mexico','CLM New Mexico');
       Apttus__APTS_Agreement__c agg=new Apttus__APTS_Agreement__c();
      agg.Apttus__Account__c=acc.Id;
      agg.OwnerId=u.Id;
      //agrmt.Plan__c='Illinois';
      agg.Provider_Networks__c=  null;
      agg.recordtypeId=professionalRecordTypeId ;
      //agrmt.Percent_of_Covered_Charges__c= 10;
     insert agg;
       agg.Apttus__Status__c='Other Party Signatures';
       agg.Apttus__Status_Category__c='In Signatures';
       update agg;
       
       
        List< Apttus_DocuApi__DocuSignEnvelope__c> docuSEList= new List< Apttus_DocuApi__DocuSignEnvelope__c>();
        Apttus_DocuApi__DocuSignEnvelope__c docuSE= new Apttus_DocuApi__DocuSignEnvelope__c();
        //docuSE.CLM_E_Signature_Status__c='with provider';
        docuSE.Apttus_DocuApi__EnvelopeId__c='sssss';
        docuSE.Apttus_CMDSign__Agreement__c=agg.id;  
        docuSEList.add(docuSE);
        insert docuSEList;
      
       List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c> lstDocSRS= new list<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c>();
       Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c docuSERS= new Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c();
       docuSERS.Apttus_DocuApi__RoleName__c='Signer 1';
       docuSERS.Apttus_DocuApi__Status__c='sent';
       docuSERS.Apttus_DocuApi__DocuSignEnvelopeId__c=docuSE.id;
       docuSERS.Apttus_DocuApi__Email__c='chaitu863@gmail.com';
       lstDocSRS.add(docuSERS);
       insert lstDocSRS;
       
       Test.startTest();
       DocuSignEVPRecipientStatusHandler_CLM.UpdateEsignatureStatus(lstDocSRS);
       Test.stopTest(); 
   }
    
    
     static testMethod void testData2()
   {
    GlobalSettings__c glbs=TestDataFactory_CLM.InsertGlobalsetting();
        

        account acc= TestDataFactory_CLM.CreateAccount('NM1');
        
       
        //Apttus__APTS_Agreement__c agrmt= TestDataFactory_CLM.CreateAgreement('Facility','New Mexico','CLM New Mexico');
        
       
        list<Apttus_DocuApi__DocuSignDefaultRecipient2__c>reclist= TestDataFactory_CLM.CreateDocusignRecipients();
       // account acc= TestDataFactory_CLM.CreateAccount('NM1');
       user u=[select Id from user where userrole.Name='Texas Supervisor' AND user.IsActive = true limit 1];
        Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
       //Apttus__APTS_Agreement__c agg= TestDataFactory_CLM.CreateAgreement('Facility','New Mexico','CLM New Mexico');
       Apttus__APTS_Agreement__c agg=new Apttus__APTS_Agreement__c();
      agg.Apttus__Account__c=acc.Id;
      agg.OwnerId=u.Id;
      //agrmt.Plan__c='Illinois';
      agg.Provider_Networks__c=  null;
      agg.recordtypeId=professionalRecordTypeId ;
      //agrmt.Percent_of_Covered_Charges__c= 10;
     insert agg;

       agg.Apttus__Status__c='Other Party Signatures';
       agg.Apttus__Status_Category__c='In Signatures';
       update agg;
       
       
        List< Apttus_DocuApi__DocuSignEnvelope__c> docuSEList= new List< Apttus_DocuApi__DocuSignEnvelope__c>();
        Apttus_DocuApi__DocuSignEnvelope__c docuSE= new Apttus_DocuApi__DocuSignEnvelope__c();
        //docuSE.CLM_E_Signature_Status__c='with provider';
        docuSE.Apttus_DocuApi__EnvelopeId__c='sssss';
        docuSE.Apttus_CMDSign__Agreement__c=agg.id;  
        docuSEList.add(docuSE);
        insert docuSEList;
      
       List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c> lstDocSRS= new list<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c>();
       Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c docuSERS= new Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c();
       docuSERS.Apttus_DocuApi__RoleName__c='Signer 1';
       docuSERS.Apttus_DocuApi__Status__c='completed';
       docuSERS.Apttus_DocuApi__DocuSignEnvelopeId__c=docuSE.id;
       docuSERS.Apttus_DocuApi__Email__c='chaitu863@gmail.com';
       lstDocSRS.add(docuSERS);
       insert lstDocSRS;
       
       Test.startTest();
      DocuSignEVPRecipientStatusHandler_CLM.UpdateEsignatureStatus(lstDocSRS);
      Test.stopTest(); 
   }
    
     static testMethod void testData3()
   {
    GlobalSettings__c glbs=TestDataFactory_CLM.InsertGlobalsetting();
        

       // account acc= TestDataFactory_CLM.CreateAccount('NM1');
        
       
        //Apttus__APTS_Agreement__c agrmt= TestDataFactory_CLM.CreateAgreement('Facility','New Mexico','CLM New Mexico');
        
account acc= TestDataFactory_CLM.CreateAccount('NM1');
       user u=[select Id from user where userrole.Name='Texas Supervisor' AND user.IsActive = true limit 1];
        Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
       //Apttus__APTS_Agreement__c agg= TestDataFactory_CLM.CreateAgreement('Facility','New Mexico','CLM New Mexico');
       Apttus__APTS_Agreement__c agg=new Apttus__APTS_Agreement__c();
      agg.Apttus__Account__c=acc.Id;
      agg.OwnerId=u.Id;
      //agrmt.Plan__c='Illinois';
      agg.Provider_Networks__c=  null;
      agg.recordtypeId=professionalRecordTypeId ;
      //agrmt.Percent_of_Covered_Charges__c= 10;
     insert agg;       
        list<Apttus_DocuApi__DocuSignDefaultRecipient2__c>reclist= TestDataFactory_CLM.CreateDocusignRecipients();
        

       agg.Apttus__Status__c='Other Party Signatures';
       agg.Apttus__Status_Category__c='In Signatures';
       update agg;
       
       
        List< Apttus_DocuApi__DocuSignEnvelope__c> docuSEList= new List< Apttus_DocuApi__DocuSignEnvelope__c>();
        Apttus_DocuApi__DocuSignEnvelope__c docuSE= new Apttus_DocuApi__DocuSignEnvelope__c();
        //docuSE.CLM_E_Signature_Status__c='with provider';
        docuSE.Apttus_DocuApi__EnvelopeId__c='sssss';
        docuSE.Apttus_CMDSign__Agreement__c=agg.id;  
        docuSEList.add(docuSE);
        insert docuSEList;
      
       List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c> lstDocSRS= new list<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c>();
       Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c docuSERS= new Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c();
       docuSERS.Apttus_DocuApi__RoleName__c='Signer 2';
       docuSERS.Apttus_DocuApi__Status__c='completed';
       docuSERS.Apttus_DocuApi__DocuSignEnvelopeId__c=docuSE.id;
       docuSERS.Apttus_DocuApi__Email__c='chaitu863@gmail.com';
       lstDocSRS.add(docuSERS);
       insert lstDocSRS;
       
       Test.startTest();
      DocuSignEVPRecipientStatusHandler_CLM.UpdateEsignatureStatus(lstDocSRS);
      Test.stopTest();  
   }
    
     static testMethod void testData4()
   {
    GlobalSettings__c glbs=TestDataFactory_CLM.InsertGlobalsetting();
        

       // account acc= TestDataFactory_CLM.CreateAccount('NM1');
        
       
       // Apttus__APTS_Agreement__c agrmt= TestDataFactory_CLM.CreateAgreement('Facility','New Mexico','CLM New Mexico');
        
       account acc= TestDataFactory_CLM.CreateAccount('NM1');
       user u=[select Id from user where userrole.Name='Texas Supervisor' AND user.IsActive = true limit 1];
        Id professionalRecordTypeId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Professional').getRecordTypeId();
       //Apttus__APTS_Agreement__c agg= TestDataFactory_CLM.CreateAgreement('Facility','New Mexico','CLM New Mexico');
       Apttus__APTS_Agreement__c agg=new Apttus__APTS_Agreement__c();
      agg.Apttus__Account__c=acc.Id;
      agg.OwnerId=u.Id;
      //agrmt.Plan__c='Illinois';
      agg.Provider_Networks__c=  null;
      agg.recordtypeId=professionalRecordTypeId ;
      //agrmt.Percent_of_Covered_Charges__c= 10;
     insert agg;
        list<Apttus_DocuApi__DocuSignDefaultRecipient2__c>reclist= TestDataFactory_CLM.CreateDocusignRecipients();
        

       agg.Apttus__Status__c='Other Party Signatures';
       agg.Apttus__Status_Category__c='In Signatures';
       update agg;
       
       
        List< Apttus_DocuApi__DocuSignEnvelope__c> docuSEList= new List< Apttus_DocuApi__DocuSignEnvelope__c>();
        Apttus_DocuApi__DocuSignEnvelope__c docuSE= new Apttus_DocuApi__DocuSignEnvelope__c();
        //docuSE.CLM_E_Signature_Status__c='with provider';
        docuSE.Apttus_DocuApi__EnvelopeId__c='sssss';
        docuSE.Apttus_CMDSign__Agreement__c=agg.id;  
        docuSEList.add(docuSE);
        insert docuSEList;
      
       List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c> lstDocSRS= new list<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c>();
       Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c docuSERS= new Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c();
       docuSERS.Apttus_DocuApi__RoleName__c='Signer 3';
       docuSERS.Apttus_DocuApi__Status__c='completed';
       docuSERS.Apttus_DocuApi__DocuSignEnvelopeId__c=docuSE.id;
       docuSERS.Apttus_DocuApi__Email__c='chaitu863@gmail.com';
       lstDocSRS.add(docuSERS);
       insert lstDocSRS;
       
       Test.startTest();
       DocuSignEVPRecipientStatusHandler_CLM.UpdateEsignatureStatus(lstDocSRS);
       Test.stopTest(); 
   }
}