src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CLM_Agr_E_Signature_Status__c</fullName>
        <label>E-Signature Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_PercentCoveredCharges__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field Created to bypass the validation rule on percent covered charges field when we want to default the field value to 100</description>
        <label>CLM_Bypass_PercentCoveredCharges</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percent_of_Covered_Charges__c</fullName>
        <label>Percent of Covered Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Networks__c</fullName>
        <label>Provider Networks</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL BlueCare Direct HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Select PPO Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Blue FocusCare HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Precision HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Broad PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL HMO of Illinois Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicaid Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL MMAI Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Focus Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Options Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Closed Plan Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT HealthLink Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Point of Service Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Traditional Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Community HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicaid Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PAR Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM POS Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PPO Provider Network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CLM_Illinois_ReimbursementHandler.cls
/******************************
Apex Class Name     : CLM_Illinois_ReimbursementHandler
Version             : 1.0
Function            : This is a handler class for CLM_Reimbursement trigger which handles the defaulting and removal
                      of default values in the reimbursement section when the conditions meet and when they are no longer
                      satisfied respectively


Developer                  Date                                
------------------------------------------------------------------------------------- 
Piyush Bhardwaj           6/26/2019  

******************************/

public class CLM_Illinois_ReimbursementHandler 
{   
    //Method that takes in a list of agreements and Agreements old Map and Agreements new map
    public static void beforeUpdate(List<Apttus__APTS_Agreement__c>agreementList ,Map<Id,Apttus__APTS_Agreement__c> agreementOldMap,Map<Id,Apttus__APTS_Agreement__c> agreementNewMap)
    { 
        List<Apttus__APTS_Agreement__c> illinoisAgreementLis = new List<Apttus__APTS_Agreement__c>();
        //Running the loop to go through all the agreements
        for(Apttus__APTS_Agreement__c  agreementObj : agreementList)
        {
            Apttus__APTS_Agreement__c agreementObjOld = agreementOldMap.get(agreementObj.Id);
            
            //Checking if agreement plan belongs to Illiinois
            if(agreementObj.Plan__c == CLM_ReimbursementModel.Illinois_PLAN)
            {
                // Logic to Default the value for Percent of Covered Charge Field
                if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.IL_Medicare_Advantage_HMO_Provider_Network) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.IL_Medicare_Advantage_PPO_Provider_Network)))
                {
                    if(agreementObjOld.Provider_Networks__c == null || (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.IL_Medicare_Advantage_HMO_Provider_Network) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.IL_Medicare_Advantage_PPO_Provider_Network)))
                    {
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = false;
                           agreementObj.Percent_of_Covered_Charges__c = 100;
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = true;
                    }
                }
            
            
                // Logic to Clear field values for Percent of Covered Charges Field  
                if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.IL_Medicare_Advantage_HMO_Provider_Network) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.IL_Medicare_Advantage_PPO_Provider_Network)))
                {
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)                       
                       ||  (agreementObj.Provider_Networks__c != null && (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.IL_Medicare_Advantage_HMO_Provider_Network) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.IL_Medicare_Advantage_PPO_Provider_Network)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c))
                    {                         
                           agreementObj.Percent_of_Covered_Charges__c = null;
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = true;                          
                    }
                }    
            }

 /*********************************************
 Function            : This part of the code updated the Agreement E-signature status based on recall eSignature

Developer                  Date                                
------------------------------------------------------------------------------------- 
Chaitanya Motupalli        08/20/2019 
**********************************************/                
             if(agreementObj.Apttus__Status__c!='Other Party Signatures') 
            {
                agreementObj.CLM_Agr_E_Signature_Status__c=null;
            }    
		}
    }
}