src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Acute_Inpatient_Rehab_Per_Diem__c</fullName>
        <label>Acute Inpatient Rehab Per Diem</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Blue_Salud__c</fullName>
        <label>Blue Salud/Blue SCI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CLM_Bypass_PercentCoveredCharges__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field Created to bypass the validation rule on percent covered charges field when we want to default the field value to 100</description>
        <label>CLM_Bypass_PercentCoveredCharges</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charge_Master_Max_Increase_percent__c</fullName>
        <label>Charge Master Max Increase percent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>one percent (1%)</fullName>
                </value>
                <value>
                    <fullName>two percent (2%)</fullName>
                </value>
                <value>
                    <fullName>three percent (3%)</fullName>
                </value>
                <value>
                    <fullName>four percent (4%)</fullName>
                </value>
                <value>
                    <fullName>five percent (5%)</fullName>
                </value>
                <value>
                    <fullName>six percent (6%)</fullName>
                </value>
                <value>
                    <fullName>seven percent (7%)</fullName>
                </value>
                <value>
                    <fullName>eight percent (8%)</fullName>
                </value>
                <value>
                    <fullName>nine percent (9%)</fullName>
                </value>
                <value>
                    <fullName>ten percent (10%)</fullName>
                </value>
                <value>
                    <fullName>zero percent (0%)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Excluded_Services_Per_Treatment_Amount__c</fullName>
        <label>Excluded Services Per Treatment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ICR__c</fullName>
        <label>ICR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MA_HMO_lesser_of_of_Covered__c</fullName>
        <label>MA HMO lesser of % of Covered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MA_HMO_lesser_of_of_Medicare_allowed__c</fullName>
        <label>MA HMO lesser of % of Medicare allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MA_PPO_lesser_of_of_Covered__c</fullName>
        <label>MA PPO lesser of % of Covered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MA_PPO_lesser_of_of_Medicare_allowed__c</fullName>
        <label>MA PPO lesser of % of Medicare allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_of_Covered_Charges__c</fullName>
        <label>Percent of Covered Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Networks__c</fullName>
        <label>Provider Networks</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL BlueCare Direct HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Select PPO Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Blue FocusCare HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Precision HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Broad PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL HMO of Illinois Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicaid Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL MMAI Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Focus Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Options Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Closed Plan Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT HealthLink Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Point of Service Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Traditional Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Community HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicaid Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PAR Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM POS Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PPO Provider Network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Service_Type__c</fullName>
        <label>Provider Service Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dialysis</fullName>
                </value>
                <value>
                    <fullName>Home Health</fullName>
                </value>
                <value>
                    <fullName>Hospice</fullName>
                </value>
                <value>
                    <fullName>SNF</fullName>
                </value>
                <value>
                    <fullName>ASC</fullName>
                </value>
                <value>
                    <fullName>Air Ambulance</fullName>
                </value>
                <value>
                    <fullName>Autism Agency</fullName>
                </value>
                <value>
                    <fullName>Birthing Center</fullName>
                </value>
                <value>
                    <fullName>DME</fullName>
                </value>
                <value>
                    <fullName>DME w/ Power Mobility</fullName>
                </value>
                <value>
                    <fullName>DME w/o Power Mobility</fullName>
                </value>
                <value>
                    <fullName>Health Screening Vendor</fullName>
                </value>
                <value>
                    <fullName>Home Infusion</fullName>
                </value>
                <value>
                    <fullName>Lab and Imaging</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                </value>
                <value>
                    <fullName>Sleep Facility</fullName>
                </value>
                <value>
                    <fullName>Home Health and Hospice</fullName>
                </value>
                <value>
                    <fullName>Ambulance</fullName>
                </value>
                <value>
                    <fullName>Facility -Acute Care</fullName>
                </value>
                <value>
                    <fullName>Psych</fullName>
                </value>
                <value>
                    <fullName>RTC</fullName>
                </value>
                <value>
                    <fullName>Facility-Behavioral Health</fullName>
                </value>
                <value>
                    <fullName>Facility-Rehab</fullName>
                </value>
                <value>
                    <fullName>Facility-LTAC</fullName>
                </value>
                <value>
                    <fullName>MG-Anesthesia</fullName>
                </value>
                <value>
                    <fullName>MG-Behavioral</fullName>
                </value>
                <value>
                    <fullName>MG-Chiropractic</fullName>
                </value>
                <value>
                    <fullName>MG-PCP</fullName>
                </value>
                <value>
                    <fullName>Prof-Anesthesia</fullName>
                </value>
                <value>
                    <fullName>Prof-Behavioral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Single_Outpatient_Rehab_per_unit__c</fullName>
        <label>Single Outpatient Rehab per unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stoploss_Reimbursement_Rate__c</fullName>
        <label>Stoploss Reimbursement Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Stoploss_Threshold__c</fullName>
        <label>Stoploss Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>of_Medicaid_fee_schedule__c</fullName>
        <label>% of Medicaid fee schedule</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>ASC</fullName>
        <active>true</active>
        <label>ASC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Facility</fullName>
        <active>true</active>
        <label>Facility</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professional</fullName>
        <active>true</active>
        <label>Professional</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CLM_NewMexico_ReimbursementHandler.cls
public class CLM_NewMexico_ReimbursementHandler {
    
    
    
    public static void beforeUpdate(List<Apttus__APTS_Agreement__c>agreementList ,Map<Id,Apttus__APTS_Agreement__c> agreementOldMap,Map<Id,Apttus__APTS_Agreement__c> agreementNewMap){ 
        List<Apttus__APTS_Agreement__c> mexicoAgreementLis = new List<Apttus__APTS_Agreement__c>();
        for(Apttus__APTS_Agreement__c  agreementObj : agreementList){
           Apttus__APTS_Agreement__c agreementObjOld = agreementOldMap.get(agreementObj.Id);
            
          if(agreementObj.Plan__c == CLM_ReimbursementModel.NEW_MEXICO_PLAN){
            if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Service_Type__c != null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId )){
                // HMO Advantage Start
                if(agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK)){
                    if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK))
                       || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && agreementObjOld.Provider_Service_Type__c == null)){
                           agreementObj.MA_HMO_lesser_of_of_Medicare_allowed__c = 100;
                           agreementObj.MA_HMO_lesser_of_of_Covered__c = 100;
                       }
                }
                // HMO Advantage End
                
                // PPO Advantage Start
                if(agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)){
                    if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))
                       || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && agreementObjOld.Provider_Service_Type__c == null) ){   
                           agreementObj.MA_PPO_lesser_of_of_Medicare_allowed__c = 100;                            
                           agreementObj.MA_PPO_lesser_of_of_Covered__c = 100;
                       }
                 }
             }
                // PPO Advantage End
             
            // 
            // Clear values
            // HMO Advantage Starts
              if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK)){
                  if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && ( agreementObjOld.Provider_Service_Type__c !=null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId)) 
                            ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)
                            || (agreementObj.Provider_Networks__c != null &&  !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c && ( agreementObjOld.Provider_Service_Type__c !=null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId))){
                                agreementObj.MA_HMO_lesser_of_of_Medicare_allowed__c = null;
                                agreementObj.MA_HMO_lesser_of_of_Covered__c = null;      
                  }
              }
            // HMO Advantage ends
            
            // PPO Advantage Starts
                
               if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)){ 
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && ( agreementObjOld.Provider_Service_Type__c !=null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId)) 
                          ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c) 
                          ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c && ( agreementObjOld.Provider_Service_Type__c !=null || agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId ))){
                              agreementObj.MA_PPO_lesser_of_of_Medicare_allowed__c = null;
                              agreementObj.MA_PPO_lesser_of_of_Covered__c = null;       
                       }
                     }
             // PPO Advantage Ends
          }              
            
            //  Common logic end
            
            // Specific to New Mexicon plan
            if(agreementObj.Plan__c == CLM_ReimbursementModel.NEW_MEXICO_PLAN){
                
              // Deafulting Percent of Covered Charges List  
                if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))){
                    if(agreementObjOld.Provider_Networks__c == null || (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))){
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = false;
                           agreementObj.Percent_of_Covered_Charges__c = 100;
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = true;
                       }
                } 
                
               // Clear field values for Percent of Covered Charges Field  
                if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK))){
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)                       
                       ||  (agreementObj.Provider_Networks__c != null && (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_HMO_PROVIDER_NETWORK) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICARE_ADVANTAGE_PPO_PROVIDER_NETWORK)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)){                         
                           agreementObj.Percent_of_Covered_Charges__c = null;
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = true;                          
                       }
                }
                
                // Common logic for 
                if(agreementObj.recordTypeId == CLM_ReimbursementModel.facilityRecordTypeId){
                    
                            
                            
                    // Medicaid Start - Rehab
                    if( agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObj.Provider_Service_Type__c != null && agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_REHAB)){
                        if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK))
                           || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_REHAB))) ){
                               // Reimbursement section start
                               //if(agreementObj.Acute_Inpatient_Rehab_Per_Diem__c == null)
                               agreementObj.Acute_Inpatient_Rehab_Per_Diem__c = 785.00;
                               // Payment section start
                               //if(agreementObj.Excluded_Services_Per_Treatment_Amount__c  == null)
                               agreementObj.Excluded_Services_Per_Treatment_Amount__c = 375.00;
                               //if(agreementObj.Single_Outpatient_Rehab_per_unit__c == null)     
                               agreementObj.Single_Outpatient_Rehab_per_unit__c = 20.9;
                           }
                    }
                    // Medicaid End - Rehab
                      
                   
                   // Medicaid Start - Facility Acute care 
                    if(agreementObj.Provider_Service_Type__c != null &&  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_ACUTE_CARE)){
                        if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.startsWith('NM')){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.startsWith('NM') )
                              || agreementObjOld.Provider_Networks__c.startsWith('NM') && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_ACUTE_CARE))){
                         // Reimbursement section start for all the facility provider networks of New Mexico
                         		//if(agreementObj.Charge_Master_Max_Increase_percent__c  == null)
                                	agreementObj.Charge_Master_Max_Increase_percent__c = 'five percent (5%)';
                            }
  
                        }
                        
                        if(agreementObj.Provider_Networks__c != null && agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK)){
                            if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK))
                              || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_ACUTE_CARE))){
                             // Reimbursement section start 
                             	
                                	agreementObj.Stoploss_Reimbursement_Rate__c = 41;
                             // Payment section start 
                          
                                	agreementObj.Stoploss_Threshold__c = 100000;
                          
                                	agreementObj.Blue_Salud__c = 3313.59;
                            
                                    agreementObj.ICR__c = 1872.13;
                            }
                        
                        }
                        
                    }
                   
                    //  Medicaid End - Facility Acute care 
                    
                    // Clear values for rehab
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_REHAB)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_REHAB) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                              
                               
                                        agreementObj.Acute_Inpatient_Rehab_Per_Diem__c = null;
                                        agreementObj.Excluded_Services_Per_Treatment_Amount__c = null;
                                        agreementObj.Single_Outpatient_Rehab_per_unit__c = null;
                           }
                    }
                    
                  // Clear values for Acute
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_ACUTE_CARE)){
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           || (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_ACUTE_CARE) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                              
                               
                              
                                   			agreementObj.Stoploss_Reimbursement_Rate__c = null;
                                     		agreementObj.Stoploss_Threshold__c = null;
                                            agreementObj.Blue_Salud__c = null;
                                            agreementObj.ICR__c = null;  
                           }
                    }
                    
				/*if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.startsWith('NM')){
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c)
                       ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                       ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.startsWith('NM') && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)){
                                    agreementObj.Charge_Master_Max_Increase_percent__c = null;

                    }
                }*/
 
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.startsWith('NM') && agreementObjOld.Provider_Service_Type__c != null && agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_ACUTE_CARE)){
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c)
                       ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                       ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.startsWith('NM') && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                       ||  (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.FACILITY_ACUTE_CARE) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                                    agreementObj.Charge_Master_Max_Increase_percent__c = null;

                    }
                }
                }
                
                // Non-ASC Ancillary Record type - Reimbursement
                if(agreementObj.recordTypeId == CLM_ReimbursementModel.ANCRecordTypeId){
                    if(agreementObj.Provider_Service_Type__c != null &&
                            (agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.BIRTHING_CENTER)
                             || agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME_W_POWER_MOBILITY)
                             || agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME_WO_POWER_MOBILITY)
                             || agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB)
                             /* 
                             ( agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DIALYSIS) 
                                  ||  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.HOME_HEALTH)
                                  ||  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.HOSPICE)
                                  ||  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.SNF)
                                  ||  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.HOME_INFUSION)
                                  ||  agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.HOME_HEALTH_AND_HOSPICE))*/
                            )){
                                 
                         if(agreementObj.Provider_Networks__c != null){
                            
                         
                            // ANC - Medicaid Start
                            if(agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK)){
                                if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK))
                                  || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && (agreementObjOld.Provider_Service_Type__c == null || (!agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.BIRTHING_CENTER) && !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME_W_POWER_MOBILITY) && !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME_WO_POWER_MOBILITY) && !agreementObjOld.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB))   )) {
                            // Reimbursement section start
                                 
                                    agreementObj.of_Medicaid_fee_schedule__c = 100;
                                
                                }
                            }
                             
                           // ANC - Medicaid End
                                 
                         }
                      }              
                    
                        
                     // Clear values
                     // 
                   if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK)){  
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c ) 
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)
                           ||  (!agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.BIRTHING_CENTER) && !agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME_W_POWER_MOBILITY) && !agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.DME_WO_POWER_MOBILITY) && !agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.LAB) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c)){
                                     agreementObj.of_Medicaid_fee_schedule__c = null;
    
                        }
                   }      
                 
               
                       
            }
                
                // ASC Record type - Reimbursement
                if(agreementObj.recordTypeId == CLM_ReimbursementModel.ASCRecordTypeId){
                                                
                     
                           
                        
                    
                }
                
                // MG Record type - Reimbursement
                if(agreementObj.recordTypeId == CLM_ReimbursementModel.medicalRecordTypeId){
                    if(agreementObj.Provider_Service_Type__c != null &&  
                            (agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.MG_ANESTHESIA) 
                             || agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.MG_BEHAVIORAL) 
                             || agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.MG_CHIROPRACTIC) 
                             || agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.MG_PCP))){
                          
                         if(agreementObj.Provider_Networks__c != null){
                            // MG - Medicaid Start
                            if(agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK)){
                                if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK))
                                  || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c && agreementObjOld.Provider_Service_Type__c == null) ){
                                 // Reimbursement section start
                                // if(agreementObj.of_Medicaid_fee_schedule__c == null)
                                    	agreementObj.of_Medicaid_fee_schedule__c = 100;
                                
                                }
                            }
                             
                           // MG - Medicaid End
                            
                         }
                                 
                      }  
                                 
               
                    
                     // Clear values
                     // 
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK)){  
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c ) 
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)){
                                     agreementObj.of_Medicaid_fee_schedule__c = null;
    
                        } 
                    }
                   
                 
                    
                }
                
                // Professional Record type - Reimbursement
                if(agreementObj.recordTypeId == CLM_ReimbursementModel.professionalRecordTypeId ){
                         if(agreementObj.Provider_Service_Type__c != null &&  
                            (agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.PROF_ANESTHESIA) 
                             || agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.PROF_BEHAVIORAL) 
                             || agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.PROF_CHIROPRACTIC) 
                             || agreementObj.Provider_Service_Type__c.contains(CLM_ReimbursementModel.PROF_PCP))){
                          
                         if(agreementObj.Provider_Networks__c != null){
                            
                           // Professional - Medicaid Start
                            if(agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK)){
                                if((agreementObjOld.Provider_Networks__c == null || !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK))
                                  || (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c) && agreementObjOld.Provider_Service_Type__c == null){
                                 // Reimbursement section start0
                                 // if(agreementObj.of_Medicaid_fee_schedule__c == null)
                                    	agreementObj.of_Medicaid_fee_schedule__c = 100;
                                
                                }
                            }
                             
                           // Professional - Medicaid End
                            
                        }
                        
                                 
                     }
                    
                     // Clear values
                    if(agreementObjOld.Provider_Networks__c <> null && agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK)){ 
                        if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c ) 
                           ||  (agreementObj.Provider_Service_Type__c == null && agreementObjOld.Provider_Service_Type__c <> agreementObj.Provider_Service_Type__c ) 
                           ||  (agreementObj.Provider_Networks__c != null && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.NM_MEDICAID_PROVIDER_NETWORK) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)){
                                     agreementObj.of_Medicaid_fee_schedule__c = null;
     
                        } 
                    }
                    
                }
        } 
            // Oklahoma Plan start
            
            
                    

            }
        }
}