src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CLM_Agr_E_Signature_Status__c</fullName>
        <label>E-Signature Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_DocuApi__DocuSignEnvelope__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Agreement_status_CLM__c</fullName>
        <formula>TEXT(Apttus_CMDSign__Agreement__r.Apttus__Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agreement status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_CMDSign__Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>DocuSignEnvelopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLM_E_Signature_Status__c</fullName>
        <description>To display the status of the envelope in order to identify with whom the Docusign Envelope is pending for signatures</description>
        <label>E-Signature Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope</label>
    <nameField>
        <label>DocuSign Envelope Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DocusignEnvelopeHandler_CLM.cls
/**************************************************************************************************
Apex Class Name  : DocusignEnvelopeHandler_CLM
Version          : 1.0  
Functionality    : This class serves as a Handler class for "DocusignEnvelopeTrigger_CLM" Trigger.
Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Chaitanya Motupalli        08/19/2019              PPN-54084,PPN-51538                       
***************************************************************************************************/
public class DocusignEnvelopeHandler_CLM 
{
    /****
    * @input: List of DocuSignEnvelope object records
    * @output: Map of Agreement records updated
    * Business Purpose: update the fields on Agreement object based on DocuSignEnvelope object.
    * Story Number : PPN-54084,PPN-51538  
    * param : lstDocsignEnv
    ****/
    public static void UpdateAgreementEsignatureStatus(List<Apttus_DocuApi__DocuSignEnvelope__c >lstDocsignEnv)
    {  
        Map<ID, Apttus__APTS_Agreement__c> mapAgreements = new Map<ID, Apttus__APTS_Agreement__c>(); 
        set<Id> setIds = new set<Id>();
        for (Apttus_DocuApi__DocuSignEnvelope__c DocsEnv: lstDocsignEnv) 
        {
            setIds.add(DocsEnv.Apttus_CMDSign__Agreement__c);
        }
        if(!setIds.isEmpty())
        {
        mapAgreements = new Map<Id,Apttus__APTS_Agreement__c >([SELECT id,Apttus__Status__c,Apttus__Status_Category__c,name,CLM_Agr_E_Signature_Status__c FROM
                                                                Apttus__APTS_Agreement__c WHERE 
                                                                ID IN :setIds]);
        }
        for (Apttus_DocuApi__DocuSignEnvelope__c DocsEnv: lstDocsignEnv)
        {
            Apttus__APTS_Agreement__c agr = mapAgreements.get(DocsEnv.Apttus_CMDSign__Agreement__c);
            agr.CLM_Agr_E_Signature_Status__c=DocsEnv.CLM_E_Signature_Status__c;
        }
        if(!mapAgreements.isEmpty())
        {
          update mapAgreements.values();    
        }
    }
    public static void ClearAgreementEsignatureStatus(List<Apttus_DocuApi__DocuSignEnvelope__c >lstDocusigneve)
    {   
        for(Apttus_DocuApi__DocuSignEnvelope__c docu :lstDocusigneve)
        {
            if(docu.Agreement_status_CLM__c!='Other Party Signatures')
            {
                docu.CLM_E_Signature_Status__c=null;
            }
        }
    }
}