src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Perpetual__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether agreement has an end date specified</description>
        <label>Perpetual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Arbitration_City__c</fullName>
        <label>Arbitration City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chicago, IL</fullName>
                </value>
                <value>
                    <fullName>Helena, MT</fullName>
                </value>
                <value>
                    <fullName>Albuquerque, NM</fullName>
                </value>
                <value>
                    <fullName>Tulsa, OK</fullName>
                </value>
                <value>
                    <fullName>Oklahoma City, OK</fullName>
                </value>
                <value>
                    <fullName>Abilene, TX</fullName>
                </value>
                <value>
                    <fullName>Amarillo, TX</fullName>
                </value>
                <value>
                    <fullName>Austin, TX</fullName>
                </value>
                <value>
                    <fullName>Corpus Christi, TX</fullName>
                </value>
                <value>
                    <fullName>Dallas, TX</fullName>
                </value>
                <value>
                    <fullName>El Paso, TX</fullName>
                </value>
                <value>
                    <fullName>Houston, TX</fullName>
                </value>
                <value>
                    <fullName>Lubbock, TX</fullName>
                </value>
                <value>
                    <fullName>Midland, TX</fullName>
                </value>
                <value>
                    <fullName>Odessa, TX</fullName>
                </value>
                <value>
                    <fullName>San Angelo, TX</fullName>
                </value>
                <value>
                    <fullName>San Antonio, TX</fullName>
                </value>
                <value>
                    <fullName>Texarkana, TX</fullName>
                </value>
                <value>
                    <fullName>Waco, TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CLM_Bypass_PercentofMedicaidFeeSchedule__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created in order for the CLM_Reimburement trigger to default the value before the condition for the validation rule on the field % of medicaid fee schedule is met</description>
        <label>CLM_Bypass_PercentofMedicaidFeeSchedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLM_NPI_List_Type__c</fullName>
        <label>NPI Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type 1</fullName>
                </value>
                <value>
                    <fullName>Type 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CLM_Standard_or_Non_Standard_Base_Lan__c</fullName>
        <label>Standard or Non Standard Base Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Non-Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CLM_Tx_City_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is just created to be used in the apex class CLM_Texas_ReimbursementHandler in order to default the values of mediation city and arbitration city in TX plan</description>
        <label>CLM_Tx_City_Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mediation_City__c</fullName>
        <label>Mediation City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chicago, IL</fullName>
                </value>
                <value>
                    <fullName>Helena, MT</fullName>
                </value>
                <value>
                    <fullName>Albuquerque, NM</fullName>
                </value>
                <value>
                    <fullName>Tulsa, OK</fullName>
                </value>
                <value>
                    <fullName>Oklahoma City, OK</fullName>
                </value>
                <value>
                    <fullName>Abilene, TX</fullName>
                </value>
                <value>
                    <fullName>Amarillo, TX</fullName>
                </value>
                <value>
                    <fullName>Austin, TX</fullName>
                </value>
                <value>
                    <fullName>Corpus Christi, TX</fullName>
                </value>
                <value>
                    <fullName>Dallas, TX</fullName>
                </value>
                <value>
                    <fullName>El Paso, TX</fullName>
                </value>
                <value>
                    <fullName>Houston, TX</fullName>
                </value>
                <value>
                    <fullName>Lubbock, TX</fullName>
                </value>
                <value>
                    <fullName>Midland, TX</fullName>
                </value>
                <value>
                    <fullName>Odessa, TX</fullName>
                </value>
                <value>
                    <fullName>San Angelo, TX</fullName>
                </value>
                <value>
                    <fullName>San Antonio, TX</fullName>
                </value>
                <value>
                    <fullName>Texarkana, TX</fullName>
                </value>
                <value>
                    <fullName>Waco, TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Credentialed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Provider Credentialed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Networks__c</fullName>
        <label>Provider Networks</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL BlueCare Direct HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Select PPO Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Blue FocusCare HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Precision HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Broad PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL HMO of Illinois Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicaid Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL MMAI Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Focus Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Options Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Closed Plan Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT HealthLink Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Point of Service Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Traditional Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Community HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicaid Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PAR Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM POS Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PPO Provider Network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Without_Cause_Notice__c</fullName>
        <label>Termination Without Cause Notice</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>sixty (60) calendar days</fullName>
                </value>
                <value>
                    <fullName>ninety (90) calendar days</fullName>
                </value>
                <value>
                    <fullName>one hundred eighty (180) calendar days</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Medicaid_fee_schedule__c</fullName>
        <label>% of Medicaid fee schedule</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <recordTypes>
        <fullName>Onboarding</fullName>
        <active>true</active>
        <description>Onboarding</description>
        <label>Onboarding</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CLM_Texas_ReimbursementHandler.cls
/******************************
Apex Class Name     : CLM_Texas_ReimbursementHandler
Version             : 1.0
Function            : The following texas handler has been written in order to default the values for custom fields like Mediation city
 					  and Arbitration city. It also defaults and removes the default values for reimbursement field when a particular 
					  criteria is met and when that criteria is no longer being satisfied

Developer                  Date                                
------------------------------------------------------------------------------------- 
Piyush Bhardwaj           7/17/2019  
Sri Ram Adusumilli        8/21/2019 (PPN-52076)

*****************************/

public class CLM_Texas_ReimbursementHandler 
{
    // Method is invoked in the trigger for Reiumbursement where it intakes an agreement list, 
    // agreement old map and agreement new map
    public static void beforeUpdate(List<Apttus__APTS_Agreement__c>agreementList ,Map<Id,Apttus__APTS_Agreement__c> agreementOldMap,Map<Id,Apttus__APTS_Agreement__c> agreementNewMap)
    { 
        List<Apttus__APTS_Agreement__c> oklahomaAgreementLis = new List<Apttus__APTS_Agreement__c>();
        for(Apttus__APTS_Agreement__c  agreementObj : agreementList)
        {
           Apttus__APTS_Agreement__c agreementObjOld = agreementOldMap.get(agreementObj.Id);  
            // Testing to see if the agreement generated is for Texas Plan
           if(agreementObj.Plan__c == CLM_ReimbursementModel.Texas_PLAN)
           {
               // Logic for Populating the default values for the fields Arbitration City & Mediation City
               if(agreementObj.CLM_Tx_City_Check__c == false)
               {
                   agreementObj.Arbitration_City__c = 'Dallas, TX';
                   agreementObj.Mediation_City__c = 'Dallas, TX';
                   agreementObj.CLM_Tx_City_Check__c = true;
               }
               
               //Logic for Populating the default value for the field NPI Type,Termination Without Cause Notice & Perpetual
               if(agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c == 'Standard')
               {
                   if(agreementObjOld.CLM_Standard_or_Non_Standard_Base_Lan__c == null || agreementObjOld.CLM_Standard_or_Non_Standard_Base_Lan__c != 'Standard')
                   {
                       if(agreementObj.recordTypeId == CLM_ReimbursementModel.professionalRecordTypeId)
                       {
                           agreementObj.CLM_NPI_List_Type__c = 'Type 1';
                           agreementObj.Termination_Without_Cause_Notice__c = 'ninety (90) calendar days';
                           agreementObj.Apttus__Perpetual__c = true;
                       }
                
                       if(agreementObj.recordTypeId == CLM_ReimbursementModel.medicalRecordTypeId)
                       {
                           agreementObj.CLM_NPI_List_Type__c = 'Type 2';
                           agreementObj.Termination_Without_Cause_Notice__c = 'ninety (90) calendar days';
                           agreementObj.Apttus__Perpetual__c = true;
                           
                       }
                   }
               }
               
               //Logic for removing the default value for the field NPI Type,Termination without cause notice & Perpetual
               if(agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c == null || agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c != 'Standard')
               {
                   if(agreementObjOld.CLM_Standard_or_Non_Standard_Base_Lan__c == 'Standard')
                   {
                       if(agreementObj.recordTypeId == CLM_ReimbursementModel.professionalRecordTypeId)
                       {
                           agreementObj.CLM_NPI_List_Type__c = null;
                           agreementObj.Termination_Without_Cause_Notice__c = null;
                           agreementObj.Apttus__Perpetual__c = false;
                          
                       }
                       if(agreementObj.recordTypeId == CLM_ReimbursementModel.medicalRecordTypeId)
                       {
                           agreementObj.CLM_NPI_List_Type__c = null;
                           agreementObj.Termination_Without_Cause_Notice__c = null;
                           agreementObj.Apttus__Perpetual__c = false;
                       }
                   }
               }
               
               // Populating the default value for the field % of Medicaid Fee schedule field
              if(agreementObj.recordTypeId == CLM_ReimbursementModel.professionalRecordTypeId || agreementObj.recordTypeId == CLM_ReimbursementModel.medicalRecordTypeId)
               {
                   //Logic for defaulting the value for the field
                   //1st scenerio standard was selected but networks were missing
                   //2nd scenerio networks were there but standard was missing
                   if((agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c <> null && agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c == 'Standard' &&
                        ((agreementObj.Provider_Networks__c<> null &&(agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_CHIP_Provider_Network) || 
                        agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Kids_Provider_Network)  ||
                        agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Medicaid_Provider_Network)  ||
                        agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Plus_Provider_Network))) &&
                        (agreementObjOld.Provider_Networks__c == null || (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_CHIP_Provider_Network) && 
                        !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Kids_Provider_Network)  &&
                        !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Medicaid_Provider_Network)  &&
                        !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Plus_Provider_Network))))) ||   // 1st scenerio ends
                        ((agreementObjOld.CLM_Standard_or_Non_Standard_Base_Lan__c == null || agreementObjOld.CLM_Standard_or_Non_Standard_Base_Lan__c != 'Standard') &&
                        agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c == 'Standard' &&
                        (agreementObj.Provider_Networks__c<> null &&(agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_CHIP_Provider_Network) || 
                        agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Kids_Provider_Network)  ||
                        agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Medicaid_Provider_Network)  ||
                        agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Plus_Provider_Network)))))         // 2nd scenerio ends
                      {
                          agreementObj.CLM_Bypass_PercentofMedicaidFeeSchedule__c = false;
                          agreementObj.of_Medicaid_fee_schedule__c = 100;
                          agreementObj.CLM_Bypass_PercentofMedicaidFeeSchedule__c = true;
                      }
                   
                   
                   //Logic for removing the default value for the field % of medicaid fee schedule
                   //1st scenerio changed from standard but still has networks
                   //2nd scenerio standard but networks are removed 
                   //3rd scenerio both are removed
                   if(((agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c == null || agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c != 'Standard') 
                        && agreementObjOld.CLM_Standard_or_Non_Standard_Base_Lan__c <> null && agreementObjOld.CLM_Standard_or_Non_Standard_Base_Lan__c == 'Standard' &&
                        (agreementObj.Provider_Networks__c <> null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_CHIP_Provider_Network) || 
                        agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Kids_Provider_Network)  ||
                        agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Medicaid_Provider_Network)  ||
                        agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Plus_Provider_Network)))) || //1st scenerio ends
                        ((agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c <> null && agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c == 'Standard') &&
                        (agreementObjOld.Provider_Networks__c <>null &&(agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_CHIP_Provider_Network) || 
                        agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Kids_Provider_Network)  ||
                        agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Medicaid_Provider_Network)  ||
                        agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Plus_Provider_Network))) && 
                        (agreementObj.Provider_Networks__c == null || (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_CHIP_Provider_Network) && 
                        !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Kids_Provider_Network)  &&
                        !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Medicaid_Provider_Network)  &&
                        !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Plus_Provider_Network)))) || //2nd scenerio ends
                        (agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c == null || agreementObj.CLM_Standard_or_Non_Standard_Base_Lan__c != 'Standard') 
                        && agreementObjOld.CLM_Standard_or_Non_Standard_Base_Lan__c <> null && agreementObjOld.CLM_Standard_or_Non_Standard_Base_Lan__c == 'Standard' &&
                        ((agreementObjOld.Provider_Networks__c <>null &&(agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_CHIP_Provider_Network) || 
                        agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Kids_Provider_Network)  ||
                        agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Medicaid_Provider_Network)  ||
                        agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Plus_Provider_Network))) && 
                        (agreementObj.Provider_Networks__c == null || (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_CHIP_Provider_Network) && 
                        !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Kids_Provider_Network)  &&
                        !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Medicaid_Provider_Network)  &&
                        !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.TX_STAR_Plus_Provider_Network)))))  // 3rd Scenerio Ends
                   {
                       agreementObj.CLM_Bypass_PercentofMedicaidFeeSchedule__c = true;
                       agreementObj.of_Medicaid_fee_schedule__c = null;
                   }  
               }
               
/******************************
				Function            : Code added to auto check the provider credentialed field according to specific 
                                      status values of associated provider onboarding individual case
                Story No.           : PPN-50822
				Developer                  Date                                
				------------------------------------------------------------------------------------- 
				Piyush Bhardwaj           8/19/2019  

*****************************/
               // Checking if the status of the associated contracting on-boarding individual case is one of the
               // status for which we need to check the checkbox of the field provider credentialed
              /* if(agreementObj.CLM_Credentialing_Case_Status__c != agreementObjOld.CLM_Credentialing_Case_Status__c)
               {
                   if(agreementObj.CLM_Credentialing_Case_Status__c == 'Cred Approved' || agreementObj.CLM_Credentialing_Case_Status__c == 'Delegated' || agreementObj.CLM_Credentialing_Case_Status__c == 'Provisionally Approved')
                   {
                       if((agreementObj.CLM_Credentialing_Case_Status__c == 'Cred Approved' && (agreementObjOld.CLM_Credentialing_Case_Status__c == 'Delegated' || agreementObjOld.CLM_Credentialing_Case_Status__c == 'Provisionally Approved')) ||
                          (agreementObj.CLM_Credentialing_Case_Status__c == 'Provisionally Approved' && (agreementObjOld.CLM_Credentialing_Case_Status__c == 'Delegated' || agreementObjOld.CLM_Credentialing_Case_Status__c == 'Cred Approved')) || 
                          (agreementObj.CLM_Credentialing_Case_Status__c == 'Delegated' && (agreementObjOld.CLM_Credentialing_Case_Status__c == 'Cred Approved' || agreementObjOld.CLM_Credentialing_Case_Status__c == 'Provisionally Approved')) ||
                          (agreementObjOld.CLM_Credentialing_Case_Status__c != 'Cred Approved' && agreementObjOld.CLM_Credentialing_Case_Status__c != 'Delegated' && agreementObj.CLM_Credentialing_Case_Status__c != 'Provisionally Approved'))
                       {
                           agreementObj.Provider_Credentialed__c= true;
                       }
                   }
               }
               
               // Checking if the status of the associated contracting on-boarding individual case is one of the
               // status for which the checkbox of the field provider credentialed is not checked
               if(agreementObj.CLM_Credentialing_Case_Status__c != agreementObjOld.CLM_Credentialing_Case_Status__c)
               {
                   if(agreementObj.CLM_Credentialing_Case_Status__c != 'Cred Approved' && agreementObj.CLM_Credentialing_Case_Status__c != 'Delegated' && agreementObj.CLM_Credentialing_Case_Status__c != 'Provisionally Approved')
                   {
                       if(agreementObjOld.CLM_Credentialing_Case_Status__c == 'Cred Approved' || agreementObjOld.CLM_Credentialing_Case_Status__c == 'Delegated' || agreementObjOld.CLM_Credentialing_Case_Status__c == 'Provisionally Approved')

                       agreementObj.Provider_Credentialed__c= false;
                   }
               }*/
           }
        }
    }                       
}