src/objects/Apttus_DocuApi__DocuSignEnvelope__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Apttus_DocuApi__Status__c</fullName>
        <description>Envelope status from DocuSign</description>
        <inlineHelpText>Envelope status from DocuSign</inlineHelpText>
        <label>Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLM_E_Signature_Status__c</fullName>
        <description>To display the status of the envelope in order to identify with whom the Docusign Envelope is pending for signatures</description>
        <label>E-Signature Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope</label>
    <nameField>
        <label>DocuSign Envelope Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c.object
<CustomObject>
    <description>Docusign envelope recipient status</description>
    <fields>
        <fullName>Apttus_DocuApi__DocuSignEnvelopeId__c</fullName>
        <description>DocuSign Envelope Id master record id (SFDC ID)</description>
        <inlineHelpText>DocuSign Envelope Id master record id (SFDC ID)</inlineHelpText>
        <label>DocuSign Envelope Id</label>
        <referenceTo>Apttus_DocuApi__DocuSignEnvelope__c</referenceTo>
        <relationshipLabel>DocuSign Envelope Recipient Status</relationshipLabel>
        <relationshipName>DocuSignEnvelopeRecipientStatus</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_DocuApi__RoleName__c</fullName>
        <description>Recipient Role Name</description>
        <inlineHelpText>Recipient Role Name</inlineHelpText>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_DocuApi__Status__c</fullName>
        <description>Envelope Recipient Status</description>
        <inlineHelpText>Envelope Recipient Status</inlineHelpText>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLM_E_Signature_Status__c</fullName>
        <formula>if( Apttus_DocuApi__Status__c == &apos;completed&apos;,
if( Apttus_DocuApi__RoleName__c ==&apos;Signer 3&apos;,&apos;Fully Signed&apos;,
if(Apttus_DocuApi__RoleName__c ==&apos;Signer 2&apos;,&apos;For CounterSign&apos;,
if(Apttus_DocuApi__RoleName__c ==&apos;Signer 1&apos;,&apos;Provider Signed&apos;,&apos;With Provider&apos;))),
if(Apttus_DocuApi__Status__c != &apos;completed&apos;,if(Apttus_DocuApi__RoleName__c ==&apos;Signer 1&apos;,&apos;With Provider&apos;, &apos;&apos;),&apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>E-Signature Status</label>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope Recipient Status</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>DocuSignEnvelopeRecipientStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Envelope Recipient Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DocuSignEVPRecipientStatusHandler_CLM.cls
/**************************************************************************************************
Apex Class Name  : DocuSignEVPRecipientStatusHandler_CLM
Version          : 1.0  
Functionality    : This class serves as a Handler class for "DocuSignEVPRecipientStatusTrigger_CLM" Trigger.
Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Chaitanya Motupalli        08/19/2019              PPN-54085,PPN-53513                     
***************************************************************************************************/
public class DocuSignEVPRecipientStatusHandler_CLM
{
    
    /****
    * @input: List of DocuSignEnvelopeRecipientStatus object records
    * @output: Map of DocuSignEnvelope records updated
    * Business Purpose: update the fields on DocuSignEnvelope object based on DocuSignEnvelopeRecipientStatus object.
    * Story Number : PPN-54085,PPN-53513 
    * param : lstDocSRS
    ****/
    public static void UpdateEsignatureStatus(List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c >lstDocSRS)
    {     
        Map<ID, Apttus_DocuApi__DocuSignEnvelope__c> mapDocuSEVP = new Map<ID, Apttus_DocuApi__DocuSignEnvelope__c>(); 
        set<Id> setIds = new set<Id>();
        for (Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c relRec: lstDocSRS) 
        {
            setIds.add(relRec.Apttus_DocuApi__DocuSignEnvelopeId__c);
        }
        if(!setIds.isEmpty())
        {
            mapDocuSEVP = new Map<Id, Apttus_DocuApi__DocuSignEnvelope__c>([SELECT id,name,Apttus_DocuApi__Status__c,CLM_E_Signature_Status__c FROM
                                                                            Apttus_DocuApi__DocuSignEnvelope__c WHERE
                                                                            ID IN :setIds]);
        }
        for (Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c DocSRS: lstDocSRS)
        {
           Apttus_DocuApi__DocuSignEnvelope__c docusEVP = mapDocuSEVP.get(DocSRS.Apttus_DocuApi__DocuSignEnvelopeId__c);
           if(DocSRS.Apttus_DocuApi__RoleName__c=='Signer 3' && DocSRS.Apttus_DocuApi__Status__c=='completed')
            {
                docusEVP.CLM_E_Signature_Status__c=DocSRS.CLM_E_Signature_Status__c;
            }else if(DocSRS.Apttus_DocuApi__RoleName__c=='Signer 2' && DocSRS.Apttus_DocuApi__Status__c=='completed')
            {
                docusEVP.CLM_E_Signature_Status__c=DocSRS.CLM_E_Signature_Status__c;
            }
            else if(DocSRS.Apttus_DocuApi__RoleName__c=='Signer 1' && DocSRS.Apttus_DocuApi__Status__c=='completed')
            {
                docusEVP.CLM_E_Signature_Status__c=DocSRS.CLM_E_Signature_Status__c;
            }else if(DocSRS.Apttus_DocuApi__RoleName__c=='Signer 1' && DocSRS.Apttus_DocuApi__Status__c=='sent')
            {
                docusEVP.CLM_E_Signature_Status__c=DocSRS.CLM_E_Signature_Status__c;
            }  
         }
        if(!mapDocuSEVP.isEmpty())
        {
           update mapDocuSEVP.values();
        }
    }
}