src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>CLM_Bypass_PercentCoveredCharges__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field Created to bypass the validation rule on percent covered charges field when we want to default the field value to 100</description>
        <label>CLM_Bypass_PercentCoveredCharges</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percent_of_Covered_Charges__c</fullName>
        <label>Percent of Covered Charges</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Networks__c</fullName>
        <label>Provider Networks</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Plan__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL BlueCare Direct HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Choice Select PPO Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Blue FocusCare HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Blue Precision HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Broad PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL HMO of Illinois Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicaid Provider Networks</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>IL MMAI Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Focus Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Blue Options Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Closed Plan Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT HealthLink Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Point of Service Provider Network</fullName>
                </value>
                <value>
                    <fullName>MT Traditional Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Community HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Blue Preferred PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicaid Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage HMO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM Medicare Advantage PPO Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PAR Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM POS Provider Network</fullName>
                </value>
                <value>
                    <fullName>NM PPO Provider Network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CLM_Montana_ReimbursementHandler.cls
public class CLM_Montana_ReimbursementHandler {
    public static void beforeUpdate(List<Apttus__APTS_Agreement__c>agreementList ,Map<Id,Apttus__APTS_Agreement__c> agreementOldMap,Map<Id,Apttus__APTS_Agreement__c> agreementNewMap){ 
        List<Apttus__APTS_Agreement__c> montanaAgreementLis = new List<Apttus__APTS_Agreement__c>();
        for(Apttus__APTS_Agreement__c  agreementObj : agreementList){
           Apttus__APTS_Agreement__c agreementObjOld = agreementOldMap.get(agreementObj.Id);  
            
            // Defaulting the value for Percent of covered charge field
            if(agreementObj.Plan__c == CLM_ReimbursementModel.Montana_PLAN){
                if(agreementObj.Provider_Networks__c != null && (agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.MT_Medicare_Advantage_HMO_Provider_Network) || agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.MT_Medicare_Advantage_PPO_Provider_Network))){
                    if(agreementObjOld.Provider_Networks__c == null || (!agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.MT_Medicare_Advantage_HMO_Provider_Network) && !agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.MT_Medicare_Advantage_PPO_Provider_Network))){
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = false;
                           agreementObj.Percent_of_Covered_Charges__c = 100;
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = true;
                       }
                }
            
            
                     // Clear field values for Percent of Covered Charges Field  
                if(agreementObjOld.Provider_Networks__c <> null && (agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.MT_Medicare_Advantage_HMO_Provider_Network) || agreementObjOld.Provider_Networks__c.contains(CLM_ReimbursementModel.MT_Medicare_Advantage_PPO_Provider_Network))){
                    if((agreementObj.Provider_Networks__c == null && agreementObjOld.Provider_Networks__c <> agreementObj.Provider_Networks__c && agreementObjOld.Provider_Networks__c <> null)                       
                       ||  (agreementObj.Provider_Networks__c != null && (!agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.MT_Medicare_Advantage_HMO_Provider_Network) && !agreementObj.Provider_Networks__c.contains(CLM_ReimbursementModel.MT_Medicare_Advantage_PPO_Provider_Network)) && agreementObj.Provider_Networks__c <> agreementObjOld.Provider_Networks__c)){                         
                           agreementObj.Percent_of_Covered_Charges__c = null;
                           agreementObj.CLM_Bypass_PercentCoveredCharges__c = true;                          
                       }
                }
            }

		}
    }
}