src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Amended_Terms__c</fullName>
        <description>Insert Amended Terms into here</description>
        <inlineHelpText>Insert Amended Terms into here</inlineHelpText>
        <label>Amended Terms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Apttus__Agreement_Category__c</fullName>
        <description>Used to categorize agreement types.  When setting up a new agreement type make sure to seect approrpiate values for that agreement type and to set the right default</description>
        <label>Agreement Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>ASC</fullName>
        <active>true</active>
        <label>ASC</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Template__c.object
<CustomObject>
    <description>Contract language templates available in the system. These templates specify guidance, language, local setitngs, and include Word attachment templates representing the bulk of actual contracts that can be used when creating a first draft . Templates can include standard and non-standard language.</description>
    <fields>
        <fullName>Use_for_MassAmend__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use for MassAmend</label>
        <type>Checkbox</type>
    </fields>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__ComplySystemProperties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Comply System properties</description>
    <label>Comply System Properties</label>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Account_trigger_switch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field added as a part of PPN-23504 . This fields help to turn on and off the Case Trigger</description>
        <label>Account trigger switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_size__c</fullName>
        <label>List size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/classes/APTSCU_MassAmendmentAngularCtlr_Test.cls
/**
 * Test class for APTSCU_MassAmendmentAngularController.
 * Created By - Kushal Bhalodiya
 * Created Date - 16th Oct, 2018
 * Modified By - 
 * Modified Date - 
 */
@isTest
private class APTSCU_MassAmendmentAngularCtlr_Test {

    @testSetup 
    static void setup() 
    {
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        Apttus__ComplySystemProperties__c sysProp = APTS_CLMTestUtility.createComplySystemProp();
        insert sysProp; 
        Account accSO = APTS_CLMTestUtility.createAccount();
        accSO.Name = Label.APTS_Mass_Amend_Agreement;
        insert accSO;
        Contact conSO = APTS_CLMTestUtility.createContact();
        insert conSO;
        
        List<Apttus__APTS_Agreement__c> agreementList = APTS_CLMTestUtility.createAgreement(conSO.ID, accSO.ID, 1);
        insert agreementList;
        List<Attachment> attachList = APTS_CLMTestUtility.createAttachmentWithBody(agreementList, 'ASC - Agreement - BCBS');
        insert attachList;
        
        Apttus__APTS_Template__c templateSO = APTS_CLMTestUtility.createTemplate();
        templateSO.Use_for_MassAmend__c = TRUE;
        insert templateSO;
        Attachment templateAtt = APTS_CLMTestUtility.createTemplateAttachmentWithBody(templateSO.ID, 'Amendment Template');
        insert templateAtt;
        
    }
    
    private static testMethod void testSetConstructor()
    {
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        Account accSO = [Select ID from Account];
	    Contact conSO = [Select ID from Contact];
	    
        List<Apttus__APTS_Agreement__c> agreementSOList = APTS_CLMTestUtility.createAgreement(conSO.ID, accSO.ID, 1);
        insert agreementSOList;
        Test.startTest();
        PageReference pageRef = Page.APTSCU_MassAmendmentAngular;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', agreementSOList[0].ID);
        ApexPages.currentPage().getHeaders().put('Referer',''+System.Url.getSalesforceBaseUrl().toExternalForm());
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(agreementSOList);
        sc.setSelected(agreementSOList);
        APTSCU_MassAmendmentAngularController controller = new APTSCU_MassAmendmentAngularController(sc);
        sc = new ApexPages.StandardSetController(agreementSOList);
        APTSCU_MassAmendmentAngularController controller1 = new APTSCU_MassAmendmentAngularController(sc);
        controller1.doMassAmend();
        Test.stopTest();
    }
    
    private static testMethod void testConstructor()
    {
        
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        Account accSO = [Select ID from Account];
	    Contact conSO = [Select ID from Contact];
	    
        List<Apttus__APTS_Agreement__c> agreementSOList = APTS_CLMTestUtility.createAgreement(conSO.ID, accSO.ID, 1);
        insert agreementSOList;
        Test.startTest();
        PageReference pageRef = Page.APTSCU_MassAmendmentAngular;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', agreementSOList[0].ID);
        ApexPages.StandardController sc = new ApexPages.StandardController(agreementSOList[0]);
        APTSCU_MassAmendmentAngularController controller = new APTSCU_MassAmendmentAngularController(sc);
        controller.onClickAmend();
        Test.stopTest();
    }
    
    private static testMethod void testdeleteAgreement()
    {
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        Account accSO = [Select ID from Account];
	    Contact conSO = [Select ID from Contact];
	    
        List<Apttus__APTS_Agreement__c> agreementSOList = APTS_CLMTestUtility.createAgreement(conSO.ID, accSO.ID, 1);
        agreementSOList[0].Selected__c = true;
        insert agreementSOList;
        Test.startTest();
        PageReference pageRef = Page.APTSCU_MassAmendmentAngular;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', agreementSOList[0].ID);
        ApexPages.currentPage().getParameters().put('myParam',JSON.serialize(agreementSOList));
        ApexPages.currentPage().getHeaders().put('Referer',''+System.Url.getSalesforceBaseUrl().toExternalForm());
        ApexPages.StandardController sc = new ApexPages.StandardController(agreementSOList[0]);
        APTSCU_MassAmendmentAngularController controller = new APTSCU_MassAmendmentAngularController(sc);
        controller.deleteAgreement();
        
        Test.stopTest();
    }
    
    private static testMethod void testdoMassAmend()
    {
       
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        Account accSO = [Select ID from Account];
	    Contact conSO = [Select ID from Contact];
	    
        List<Apttus__APTS_Agreement__c> agreementSOList = APTS_CLMTestUtility.createAgreement(conSO.ID, accSO.ID, 1);
        insert agreementSOList;
        Test.startTest();
        PageReference pageRef = Page.APTSCU_MassAmendmentAngular;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('id', agreementSOList[0].ID);
        ApexPages.currentPage().getParameters().put('myEffectiveDate', '2018-10-10');
        ApexPages.currentPage().getParameters().put('myAgmtName', 'ASC - Agreement - BCBS');
        ApexPages.currentPage().getParameters().put('myDesc', 'Desc');
        ApexPages.currentPage().getHeaders().put('Referer',''+System.Url.getSalesforceBaseUrl().toExternalForm());
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(agreementSOList);
        sc.setSelected(agreementSOList);
        APTSCU_MassAmendmentAngularController controller = new APTSCU_MassAmendmentAngularController(sc);
        controller.doMassAmend();
        Test.stopTest();
    }
    
    private static testMethod void testpopulateNewAgreementList()
    {
        
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        Account accSO = [Select ID from Account];
	    Contact conSO = [Select ID from Contact];
	    
        List<Apttus__APTS_Agreement__c> agreementSOList = APTS_CLMTestUtility.createAgreement(conSO.ID, accSO.ID, 1);
        agreementSOList[0].Amended_Terms__c = 'Amended Terms';
        insert agreementSOList;
        Test.startTest();
        PageReference pageRef = Page.APTSCU_MassAmendmentAngular;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(agreementSOList[0]);
        APTSCU_MassAmendmentAngularController controller = new APTSCU_MassAmendmentAngularController(sc);
        controller.finalDisplayIds.add(agreementSOList[0].ID);
        controller.populateNewAgreementList();
        controller.agreementIdsToGenerate.add(agreementSOList[0].ID);
        controller.contactSet.add(conSO.ID);
        controller.agreementNames.add(agreementSOList[0].Name);
        controller.doGenerate();
        Test.stopTest();
    }
    
    private static testMethod void testgetObjectFields()
    {
        
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        Test.startTest();
        
        APTSCU_MassAmendmentAngularController.getObjectFields('Apttus__APTS_Agreement__c');
        
        Test.stopTest();
    }
    private static testMethod void testgetPicklistValues()
    {
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.List_size__c         =   10;
        gs.Account_trigger_switch__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        Test.startTest();
        
        APTSCU_MassAmendmentAngularController.getPicklistValues('Apttus__APTS_Agreement__c', 'Apttus__Agreement_Category__c');
        APTSCU_MassAmendmentAngularController.getReferenceRecords('Apttus__APTS_Agreement__c');
        APTSCU_MassAmendmentAngularController.getAgmtsAsPerCondition('ID != null', [Select ID from Apttus__APTS_Agreement__c LIMIT 1].ID);
        Test.stopTest();
    }

}