src/objects/CaseLockStatus__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <externalId>true</externalId>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CaseLockStatus</label>
</CustomObject>

src/objects/CaseProfile__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ProfileName__c</fullName>
        <label>ProfileName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CaseProfile</label>
</CustomObject>

src/classes/DataSupportForBypassValidation.cls
public class DataSupportForBypassValidation {
            
    public void insertDataForCustomSettings(){

        insertClosedCaseStatuses();
        insertClosedCaseBypass();
        
        
    }    
            
    public void insertClosedCaseStatuses(){
        
                    insert
                  ( 
                        new CaseLockStatus__c
                        (                                
                            Name='ClosedCaseStatuses' , Status__c = 'Closed,Closed Processed,Closed Rejected'
                        )
                  ); 
        
    }
    
    public void insertClosedCaseBypass(){
        
                    insert
                  ( 
                        new CaseProfile__c
                        (                                
                            Name= 'ClosedCaseBypass' , ProfileName__c = 'Supervisor,Montana Supervisor,PNC Profile'
                        )
                  ); 
        
    }    
    
    
}