src/objects/CaseLockStatus__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <externalId>true</externalId>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CaseLockStatus</label>
</CustomObject>

src/objects/CaseOwnerUpdate__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Profile__c</fullName>
        <label>Profile</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CaseOwnerUpdate</label>
</CustomObject>

src/objects/CaseProfile__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ProfileName__c</fullName>
        <label>ProfileName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CaseProfile</label>
</CustomObject>

src/objects/Email_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email Settings</label>
</CustomObject>

src/objects/QueueIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom setting is used to while updating plan id from child to Master and vise versa.

Query used to get the Queue Id and Developername.
SELECT DeveloperName,Id,Name,Type FROM Group WHERE Type = &apos;Queue&apos;</description>
    <fields>
        <fullName>PlanId__c</fullName>
        <label>PlanId</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueueId__c</fullName>
        <label>QueueId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Queue Ids</label>
</CustomObject>

src/objects/RoleAndPlanId_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom settings object created as a part of user story PPN-1645.
Use below query to create records for this custom settings object.</description>
    <fields>
        <fullName>PlanId__c</fullName>
        <label>PlanId</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Id__c</fullName>
        <label>Role Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RoleAndPlanId Settings</label>
</CustomObject>

src/classes/DataSupportForCaseTriggerHandler.cls
public class DataSupportForCaseTriggerHandler {
    
    public Case insertDataForParentCases(){
        
        //Create a Case to initialize the Extension constructor
        Case parentCase = TestCaseUtil.CreateCase();   
        parentCase.Email_Address_Submitter__c = 'test@test.com';
        parentCase.Govt_Programs__c = true;
        insert parentCase;
        AvoidRecursion.runAfter = false;
        return parentCase;
        
    }
    
    public Case insertDataForChildCases(Case parentCase){
        
        Case childCase = TestCaseUtil.CreateCase();   
        childCase.ParentId = parentCase.id;        
        childCase.Email_Address_Submitter__c = 'test3@test.com';
        childCase.Govt_Programs__c = true;
        insert childCase;       
        AvoidRecursion.runAfter = false;
        return childCase;
    }    
    
    
    public void updateCase(Case uCase, String fieldname, String value){
        
        uCase.put(fieldname, value);  
        try{
        update uCase;
        }catch(Exception e){
           
        }
        AvoidRecursion.runAfter = false;
        
    }     
    public void insertDataForCustomSettings(){
        
        
       insert
      ( 
          	new CaseLockStatus__c
        	(
            	name='Closed Processed', status__c = 'Closed Processed'
            )
        );
                
        
        
        insert
        (
            new CaseProfile__c
        	(
            	name='System Administator', ProfileName__c = 'System Administrator'
            )                      
        );
        
        insert
        (    
           new CaseProfile__c
        	(
            	
                name='ClosedCaseBypass', ProfileName__c = 'Supervisor,Montana Supervisor'
            )  
        );
        
        insert
        (
            new CaseLockStatus__c
            (
                 name='ClosedCaseStatuses', status__c = 'Closed,Closed Processed,Closed Rejected'                
                //name='ClosedCaseStatuses', status__c = 'Closed,Closed Processed,Closed Rejected'                
            )
         );   
        
        
        insert
        (
            new Email_Settings__c
            (
                 name='URL', state__c = 'http://prodevmer-hcscproviderintake.cs71.force.com'                              
            )
         );           
        
        insert
        (
            new Email_Settings__c
            (
                 name='IL', state__c = 'Netops_Provider_Update@bcbsil.com'                              
            )
         );   


        List<RoleAndPlanId_Settings__c> lst = new List<RoleAndPlanId_Settings__c>();
        
        RoleAndPlanId_Settings__c rp	=	new RoleAndPlanId_Settings__c( Name='Illinois_Supervisor',PlanId__c='IL1',Role_Id__c='00E41000000bXVsEAM' );
        lst.add(rp);
        RoleAndPlanId_Settings__c rp1	=	new RoleAndPlanId_Settings__c( Name='Montana_Supervisor',PlanId__c='MT1',Role_Id__c='00E41000000bXVtEAM' );
        lst.add(rp1);
        RoleAndPlanId_Settings__c rp2	=	new RoleAndPlanId_Settings__c( Name='New_Mexico_Supervisor',PlanId__c='NM1',Role_Id__c='00E41000000bXVuEAM' );
        lst.add(rp2);
        RoleAndPlanId_Settings__c rp3	=	new RoleAndPlanId_Settings__c( Name='Oklahoma_Supervisor',PlanId__c='OK1',Role_Id__c='00E41000000bXVvEAM' );
        lst.add(rp3);
        RoleAndPlanId_Settings__c rp4	=	new RoleAndPlanId_Settings__c( Name='Texas_Supervisor',PlanId__c='TX1',Role_Id__c='00E41000000bXW1EAM' );
        lst.add(rp4);
                               
        insert lst;
        
          List<QueueIds__c>	 queueIdsLst	   = new List<QueueIds__c>();
          QueueIds__c qid1		=	new QueueIds__c(name='IL Contracting Queue',PlanId__c='IL1',QueueId__c='a084D000000Jz9eQAC');
          queueIdsLst.add(qid1);
          QueueIds__c qid2		=	new QueueIds__c(name='Montana Queue',PlanId__c='MT1',QueueId__c='a084D000000Jz9jQAC');
          queueIdsLst.add(qid2);
          QueueIds__c qid3		=	new QueueIds__c(name='Illinois Queue',PlanId__c='IL1',QueueId__c='a084D000000Jz9ZQAS');
          queueIdsLst.add(qid3);
          
          insert queueIdsLst;

        List<CaseOwnerUpdate__c> ownerlst = new List<CaseOwnerUpdate__c>();
        CaseOwnerUpdate__c ownerrp1	=	new CaseOwnerUpdate__c( Name='Montana Supervisor',Profile__c='Montana Supervisor');
        ownerlst.add(ownerrp1);
        CaseOwnerUpdate__c ownerrp2=	new CaseOwnerUpdate__c( Name='Supervisor',Profile__c='Supervisor');
        ownerlst.add(ownerrp2);
        insert ownerlst;
    
    }    
    
    
    
    
}