src/objects/CM_Provider_Tax_Id__c.object
<CustomObject>
    <description>Provider Tax Identification Object  shows how and where billing is done.</description>
    <fields>
        <fullName>CM_PTI_Prov_Name_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Tax Identifications</relationshipLabel>
        <relationshipName>Provider_Tax_Identifications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_PTI_Tax_Id__c</fullName>
        <externalId>true</externalId>
        <label>Tax Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider Tax Identification</label>
    <nameField>
        <displayFormat>PTI-{0}</displayFormat>
        <label>Prov Tax Info</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Tax Identifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TaxIdReport.cls
public with sharing class TaxIdReport {
	public transient List<Account> accounts	{ get; set; }
	public string taxId	{ get; set; }    
    public TaxIdReport(){

    }
    
    public  void getAccounts(){
        system.debug('taxId'+taxId);
		
         /* Use the below Query to get the cases for the Account which has one of the entered Tax IDs, This is suitable for CRM Cases where they Tax_ID_Number__c is not always mandatory 
       			*/
         if(taxId!=''){
   
        Accounts = [SELECT Name, 
                    (SELECT Id, AccountId, CaseNumber,Origin,Reason,Case_Entity__c,Description,Subject,OwnerId FROM Cases),
                    (SELECT Id, AccountId, CaseNumber,Origin,Reason,Case_Entity__c,Description,Subject,OwnerId FROM Cases__r) 
                    FROM Account 
                    WHERE Id IN (SELECT CM_PTI_Prov_Name_From__c FROM CM_Provider_Tax_Id__c where CM_PTI_Tax_Id__c =:taxId) LIMIT 1000];
   		 
        
        /* Use the below Query to get the cases for the entered Tax ID for an account. For this to always return values , Tax_ID_Number__c field should be mandatory in all the Case Page Layouts 
        */
        /*Accounts = [SELECT Name, 
        			(SELECT Id, AccountId, CaseNumber,Origin,Reason,Case_Entity__c,Description,Subject,OwnerId FROM Cases where Tax_ID_Number__c=:taxId), 
					(SELECT Id, AccountId, CaseNumber,Origin,Reason,Case_Entity__c,Description,Subject,OwnerId FROM Cases__r where Tax_ID_Number__c=:taxId)  
					FROM Account 
					WHERE Id IN (SELECT CM_PTI_Prov_Name_From__c FROM CM_Provider_Tax_Id__c where CM_PTI_Tax_Id__c =:taxId)];
    */
          
                 
              system.debug('Accounts'+Accounts);
         }
        
           else
               
               Accounts = null;
}  
    
    public pagereference downloadReport(){
        
         PageReference report= new PageReference('/apex/TaxIdReportPDF'); 
        
        return report;
    }
}