src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Network Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Network_Support_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comp_Grid_Code__c</fullName>
        <label>Comp Grid Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Designation_Code__c</fullName>
        <label>Designation Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prior_Provider_Id__c</fullName>
        <label>Prior Provider Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProviderDetailsTrigger_Test.cls
@isTest
public class ProviderDetailsTrigger_Test {
    
      @isTest
        static void test_caseOwnerChange(){
        GlobalSettings__c gs    =   new GlobalSettings__c();
        gs.name                 =   'PFFileRecieved';
        gs.PFFileRecieved__c    =   false;
        gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        
        testclassdata.CreateCustomSettingData('Case');
        testclassdata.CreateCustomSettingData('Provider_Networks__c');
        
        
            List<RecordType> recType =  [SELECT DeveloperName,Id,Name FROM RecordType WHERE DeveloperName In ('Master_Provider_Case_data','Network_Load')];
            Case parentCase          =  TestCaseUtil.CreateCase();   
            parentCase.Email_Address_Submitter__c   =   'test@test.com';
            parentCase.RecordTypeId =   recType[0].id;
            parentCase.Plan_ID__c   =   'IL1';
            parentCase.Status       =   'New';
            parentCase.Subject     =   'Test Email';
            parentCase.Origin      =   'PNC NetOps Inquiries';
            
            insert parentCase;
            
            Case childCase          =   TestCaseUtil.CreateCase();   
            childCase.ParentId      =   parentCase.id; 
            childCase.Email_Address_Submitter__c    =   'test3@test.com';
            childCase.RecordTypeId  =   recType[1].id;
            childCase.Govt_Programs__c              =   true;
            childCase.Plan_ID__c                    =   'IL1';
            childCase.Status                        =   'New';  
            childCase.Completing_the_form_for__c = 'Individual';
            
            insert childCase;
      
   
       // Integer MAX_QUERY = Limits.getLimitQueries(); 
       // Integer NUM_QUERY = MAX_QUERY - 1; 
           
            List<Provider_Networks__c> pns = new List<Provider_Networks__c>();       
            pns = testDataFactory.ProviderNetworkCreation(1,'IL1','01241000001h1Bw');         
            pns[0].Case_Number__c = childCase.Id;
            pns[0].Designation_Code__c = 'test';
            pns[0].Prior_Provider_Id__c = string.valueof(pns[0].Id).substring(0,15);
             Test.StartTest();
             // System.assertNotEquals(NUM_QUERY, Limits.getQueries()); 
           //update pns[0];
            pns[0].Comp_Grid_Code__c = 'test';          
             //update pns[0];
           delete pns[0];
          //  System.assertEquals(NUM_QUERY, Limits.getQueries()); 
         Test.StopTest();     
    }
}