src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/OMNI_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type_s__c</fullName>
        <label>Request Type(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Change</fullName>
                </value>
                <value>
                    <fullName>Billing Address Change</fullName>
                </value>
                <value>
                    <fullName>Credentialing Change</fullName>
                </value>
                <value>
                    <fullName>NPI Tax Id Change</fullName>
                </value>
                <value>
                    <fullName>Name Change Request</fullName>
                </value>
                <value>
                    <fullName>Other Provider Updates</fullName>
                </value>
                <value>
                    <fullName>Physical Address Change</fullName>
                </value>
                <value>
                    <fullName>Remove Provider from Group/Location</fullName>
                </value>
                <value>
                    <fullName>nm_network_scripting@bcbsnm.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OMNI Queue</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OMNI Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blue Advantage HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Advantage PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Care Direct</fullName>
                </value>
                <value>
                    <fullName>Blue Choice Options</fullName>
                </value>
                <value>
                    <fullName>BlueChoice PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>BlueChoice PPO (BH)</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO Preferred</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO Preferred Ancillary</fullName>
                </value>
                <value>
                    <fullName>Blue Community HMO Dallas</fullName>
                </value>
                <value>
                    <fullName>Blue Community HMO Network</fullName>
                </value>
                <value>
                    <fullName>Blue Cross Community Family Health Plan</fullName>
                </value>
                <value>
                    <fullName>Blue Essentials</fullName>
                </value>
                <value>
                    <fullName>Blue Focus Care</fullName>
                </value>
                <value>
                    <fullName>Blue Focus POS</fullName>
                </value>
                <value>
                    <fullName>BlueLincs HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Options</fullName>
                </value>
                <value>
                    <fullName>Blue Precision HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Preferred</fullName>
                </value>
                <value>
                    <fullName>Blue Premier HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Select PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Traditional</fullName>
                </value>
                <value>
                    <fullName>Caring Program</fullName>
                </value>
                <value>
                    <fullName>CHIP (Medicaid)</fullName>
                </value>
                <value>
                    <fullName>DNOA</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible MMAI</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible Special Needs Plan</fullName>
                </value>
                <value>
                    <fullName>Exclusive Provider Network</fullName>
                </value>
                <value>
                    <fullName>Facility - Blue Choice Designated PPO</fullName>
                </value>
                <value>
                    <fullName>Facility Blue Choice Designated PPO Preferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RecordType_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <description>This field is to hold the record type developer name</description>
        <inlineHelpText>Record type developer name</inlineHelpText>
        <label>DeveloperName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>This field is to hold record type name</description>
        <inlineHelpText>Record type Name</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_type_Id__c</fullName>
        <description>This field is to hold the record type Id</description>
        <inlineHelpText>Record type Id</inlineHelpText>
        <label>Record type Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObject_Type__c</fullName>
        <description>This field is to hold the object name</description>
        <inlineHelpText>Object Name</inlineHelpText>
        <label>sObject Type</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordType settings</label>
</CustomObject>

src/classes/updateExistingCasesTest.cls
@isTest
public class updateExistingCasesTest {
   
    
    @testSetup static void prepareData() {
	   
        List<RecordType_settings__c> rtsList	=	 new List<RecordType_settings__c>();
        List<RecordType> recordTypeList	= [SELECT DeveloperName,Id,Name,SobjectType FROM RecordType];
        for( RecordType recType : recordTypeList  )
        {
            RecordType_settings__c rts 	=	new RecordType_settings__c();
            rts.name					=	recType.Id;
            rts.DeveloperName__c	   	=	recType.DeveloperName;
            rts.Name__c					=	recType.Name;
            rts.Record_type_Id__c		=	recType.Id;
            rts.sObject_Type__c			=	recType.SobjectType;
            rtsList.add(rts);
        }
        insert rtsList;
    }
    @isTest
    static void test_updateExistingCases(){
        
        system.debug('1Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
        
        List<User>  userList    =   TestCaseUtil.createUser('Supervisor','Illinois Supervisor',1);
        insert userList;
        
        system.debug('2Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
        List<User>  dataRepUserlist =   TestCaseUtil.createUser('Provider Data Rep','Provider Data Rep- IL',1);
        insert dataRepUserlist;
        system.debug('3Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
        
        System.runAs(new User(Id = UserInfo.getUserId())){
            //testclassdata.CreateCustomSettingData('case');
        	//testclassdata.CreateCustomSettingData('Provider_Networks__c');
            GlobalSettings__c gs    =   new GlobalSettings__c();
            gs.name                 =   'PFFileRecieved';
            gs.PFFileRecieved__c    =   false;
            gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
            insert gs;
            system.debug('4Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            List<RecordType> recType =  [SELECT DeveloperName,Id,Name FROM RecordType WHERE Name In ('Master Provider Case data','Name Change Request')];
            Case parentCase          =  TestCaseUtil.CreateCase();   
            parentCase.Email_Address_Submitter__c   =   'test@test.com';
            parentCase.RecordTypeId =   recType[0].id;
            parentCase.Plan_ID__c   =   'IL1';
            parentCase.Status       =   'New';
            parentCase.Subject     =   'Test Email';
            parentCase.Origin      =   'PNC NetOps Inquiries';
            insert parentCase;
            system.debug('5Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            
            Case childCase          =   TestCaseUtil.CreateCase();   
            childCase.ParentId      =   parentCase.id; 
            childCase.Email_Address_Submitter__c    =   'test3@test.com';
            childCase.RecordTypeId  =   recType[1].id;
            childCase.Govt_Programs__c              =   true;
            childCase.Plan_ID__c                    =   'IL1';
            childCase.Status                        =   'New';
            List<case> flist    = new List<case>();
            flist.add(childCase);
            insert flist;
            system.debug('6Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            
            
            List<id> idList = new List<id>();
            idList.add(userList[0].Id);
            idList.add(dataRepUserlist[0].Id);
            
            User usr                =   [Select Id,Name from User where Id =:userList[0].Id];
            Group testGroup = new Group(Name='Illinois Queue1', Type='Queue');
            insert testGroup;
            
            system.debug('Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            QueuesObject testQueue = new QueueSObject(QueueID = testGroup.id, SObjectType = 'Case');
            insert testQueue;
            system.debug('7Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            QueuesObject testQueue1 = new QueueSObject(QueueID = testGroup.id, SObjectType = 'Omni_Queue__C');
            insert testQueue1;
            
            system.debug('8Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            omni_queue__C queueRec            =    new omni_queue__C();        
            queueRec.Case_Type__c              =   'Demographics';
            queueRec.Request_Type_s__c         =   'NPI Tax Id Change; Administrative Change';
            queueRec.Plan_Id__c                =   'IL1';
            queueRec.Queue_Priority__c         =   '5';
            queueRec.Name                       =   'Test queue uewyrewr';
            insert queueRec; 
			
            list<RecordType_settings__c> rs = new list<RecordType_settings__c>();
            RecordType_settings__c temprs = new RecordType_settings__c();
            //Add values to Custom Setting Record Type Settings
            /*for(recordtype r:[select id,sobjecttype,DeveloperName,name from recordtype where isactive = true]){
                	temprs = new RecordType_settings__c();	
                	temprs.Name 				= r.Id;
                    temprs.DeveloperName__c 	= r.DeveloperName;
                    temprs.Name__c				= r.Name;
                    temprs.Record_type_Id__c	= r.Id;
                    temprs.sObject_Type__c		= 'Case';
                	rs.add(temprs);
            }
            insert rs; */
            system.debug('9Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            system.debug('10Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            Test.startTest();
            system.debug('1***Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            System.enqueueJob(new updateExistingCases(idList,testGroup.Id,queueRec.Id,flist));
            system.debug('2***Limits ' + Limits.getDmlStatements() + ' --- ' + Limits.getQueries() + '---' + Limits.getQueueableJobs());
            Test.stopTest();
        }
        
    }
}