src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Global Settings</label>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <recordTypes>
        <fullName>Credentialing</fullName>
        <active>true</active>
        <label>Credentialing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReportConfig__mdt.object
<CustomObject>
    <description>This is the support object for the report described in PPN-21988</description>
    <fields>
        <fullName>CaseStatusValues__c</fullName>
        <description>Case status values which are to be pulled for the report are to be added here, i.e New;In Progress; etc.....make sure there are no spaces between the values in the values separated by the semi colons.</description>
        <label>Case Status Values</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailSubject__c</fullName>
        <description>This is the subject line of the email</description>
        <label>Subject of Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Failures_Report_Recipents__c</fullName>
        <label>Failures_Report_Recipents</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FileName__c</fullName>
        <description>This is the name of the file as it will appear to whomever receives the report</description>
        <label>File Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HeaderListing__c</fullName>
        <description>Column header list for CSV report</description>
        <label>Header Listing</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MainQuery2__c</fullName>
        <label>MainQuery2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MainQuery__c</fullName>
        <description>This is the main query for generating the report</description>
        <label>Main Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecipientEmailList__c</fullName>
        <description>This is semi-colon separated list of email addresses to whom the report will be sent.</description>
        <label>Recipient Email List</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Record_Types__c</fullName>
        <description>This is the value of the Case Record Type you want to use to build your report</description>
        <label>Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_types2__c</fullName>
        <label>Record Types2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>body__c</fullName>
        <description>This is the body of the email message to whomever receives the report..</description>
        <label>body</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>ReportConfig</label>
    <pluralLabel>ReportConfigs</pluralLabel>
</CustomObject>

src/classes/CredentialingReport_Test.cls
/*
* This is the test class to covor the code coverage for the class CredentialingReport.apxc  
* Developer : Sreekanth Kalluru
* Date      : 02/03/2019
*/
@isTest
public class CredentialingReport_Test {
    
    @testSetup
    public static void prepareData() 
    {
        
        TestDataFactory tdf             =   new TestDataFactory();
        List<GlobalSettings__c> glbalsettingsList   =   tdf.InsertGlobalsetting();
        
       
        
        ReportConfig__mdt rc            =   new ReportConfig__mdt();
        rc                              =   [select MasterLabel,body__c,CaseStatusValues__c,FileName__c,HeaderListing__c,
                                             MainQuery__c,MainQuery2__c,RecipientEmailList__c,Record_Types__c,Record_types2__c,
                                             EmailSubject__c,Failures_Report_Recipents__c from ReportConfig__mdt limit 1];
       
        
        Id rectypefornet                =   Schema.SObjectType.Provider_Networks__c.getRecordTypeInfosByDeveloperName().get('Credentialing').getRecordTypeId();
        Id groupCredentialingCaserecId  =   Schema.SObjectType.case.getRecordTypeInfosByDeveloperName().get('Provider_Group_On_boarding_Credentialling').getRecordTypeId();
        Id individualCredCase           =   Schema.SObjectType.case.getRecordTypeInfosByDeveloperName().get('Provider_On_boarding_Credentialing').getRecordTypeId();
        
        List<Provider_Networks__c> pn   =   new List<Provider_Networks__c>();
        pn                              =   TestDataFactory.ProviderNetworkCreation(1,'IL1',recTypefornet);
        List<case> credCaseGroup        =   new list<case>();
        credCaseGroup                   =   TestDataFactory.CredCaseCreation(pn,'IL1','Ind',groupCredentialingCaserecId);
        
        List<Provider_Networks__c> pn1  =   new List<Provider_Networks__c>();
        pn1                             =   TestDataFactory.ProviderNetworkCreation(1,'IL1',recTypefornet);
        List<Case> credCaseIndividual   =   new List<Case>();
        credCaseIndividual              =   TestDataFactory.CredCaseCreation(pn1,'IL1','Ind',individualCredCase);
       
    }
    
    
     public static testMethod void test_CredentialingReport()
     {

        // start the test execution context
        Test.startTest();        
            CredentialingReport cr = new CredentialingReport();
            cr.initFromMetaData('ReportConfig__mdt.Credentialing_Report');       
            try{
                cr.callReport();
            } catch(Exception e) {
                System.debug('The following exception occured when sending credentialing report email: ' + e);
            }        
            // stop the test
        Test.stopTest();        
    }    
}