src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Acceptable_Plan_Ids__c</fullName>
        <label>Acceptable Plan Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Case_Status_fields__c</fullName>
        <label>CRM Case Status fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CRM_Case_record_Type_Id__c</fullName>
        <label>CRM_Case_record_Type_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_Master_Record_Type_Id__c</fullName>
        <label>CRM Master Record Type Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_record_type_id__c</fullName>
        <label>Entity record type id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fake_Email__c</fullName>
        <label>Fake Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Profile_Id__c</fullName>
        <label>Integration Profile Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Origin__c</fullName>
        <label>MCC Case Origin</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physician_record_id__c</fullName>
        <label>Physician record id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/classes/TestCreateChildCase.cls
@isTest
public class TestCreateChildCase {
    
    @testSetup static void prepareData() {
        GlobalSettings__c gs			=	 new GlobalSettings__c();
        gs.name 						=	'PFFileRecieved';
        gs.PFFileRecieved__c			=	 false;
        gs.CRM_Case_Status_fields__c 	= 	'New,In Progress,Waiting for Internal Response,Waiting for External Response,Closed';
        gs.Record_Type_Names__c			=	'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        gs.Acceptable_Plan_Ids__c		= 	'IL1,MT1,NM1,OK1,TX1';
        gs.Physician_record_id__c		= 	[SELECT Id, Name, SObjectType FROM RecordType WHERE SObjectType='Account' AND Name = 'Physician'].Id;
        gs.Entity_record_type_id__c		= 	[SELECT Id, Name, SObjectType FROM RecordType WHERE SObjectType='Account' AND Name = 'Entity Account'].Id;
        gs.CRM_Master_Record_Type_Id__c	= 	[SELECT Id, Name, SObjectType FROM RecordType WHERE SObjectType='Case' AND Name like 'Master CRM%'].Id;
        gs.CRM_Case_record_Type_Id__c	= 	[SELECT Id, Name, SObjectType FROM RecordType WHERE SObjectType='Case' AND Name = 'CRM'].Id;
        gs.Integration_Profile_Id__c	= 	[SELECT Id, Name FROM Profile WHERE Name = 'Integration'].Id;
        gs.Fake_Email__c				= 	'fakeemail@bcbsil.com';
        gs.MCC_Case_Origin__c			= 	'Mass Case Creation';
        insert gs;
    }
    
    static testMethod void testCases() {    
        
        List<case> testChild = new List<case>();  
        
        Case  mCase = TestCaseUtil.CreateCase();
        
        //insert mCase;
        
        testChild.add(mCase);
        
        Test.startTest();
        
        	CreateChildCase.createChildCaseMethod(testChild);
        
        Test.stopTest();
        
        //System.assertEquals(0,[SELECT count() FROM Case]);
        
    }  
}