src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/OMNI_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Case_Type_Name_Origin__c</fullName>
        <label>CaseType Name / Origin</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demographics</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>Govt Cases</fullName>
                </value>
                <value>
                    <fullName>Network Change</fullName>
                </value>
                <value>
                    <fullName>Other Provider Updates</fullName>
                </value>
                <value>
                    <fullName>Web On-boarding - Contracting</fullName>
                </value>
                <value>
                    <fullName>Web On-boarding - Data Entry</fullName>
                </value>
                <value>
                    <fullName>Ancillary Networks</fullName>
                </value>
                <value>
                    <fullName>Balance Billing</fullName>
                </value>
                <value>
                    <fullName>Delegated Credentialing</fullName>
                </value>
                <value>
                    <fullName>Fee Schedule Requests</fullName>
                </value>
                <value>
                    <fullName>Gov Netops Provider Update</fullName>
                </value>
                <value>
                    <fullName>Gov Providers</fullName>
                </value>
                <value>
                    <fullName>HCS-X6100</fullName>
                </value>
                <value>
                    <fullName>HMO Networks</fullName>
                </value>
                <value>
                    <fullName>Internal PNC Inquiries</fullName>
                </value>
                <value>
                    <fullName>Netops Provider Update</fullName>
                </value>
                <value>
                    <fullName>Network Roster Submission</fullName>
                </value>
                <value>
                    <fullName>OK Network Management</fullName>
                </value>
                <value>
                    <fullName>PNC NetOps Inquiries</fullName>
                </value>
                <value>
                    <fullName>PPN CorpusChristi</fullName>
                </value>
                <value>
                    <fullName>PPN EIPaso</fullName>
                </value>
                <value>
                    <fullName>PPN Lubbock-Amerillo</fullName>
                </value>
                <value>
                    <fullName>Professional Provider Network Dept</fullName>
                </value>
                <value>
                    <fullName>Provider Inquiry</fullName>
                </value>
                <value>
                    <fullName>Provider Relation DFW</fullName>
                </value>
                <value>
                    <fullName>Provider Relations Houston</fullName>
                </value>
                <value>
                    <fullName>Provider Relations Midland</fullName>
                </value>
                <value>
                    <fullName>Provider Relations South Texas</fullName>
                </value>
                <value>
                    <fullName>Provider Relations IL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type_s__c</fullName>
        <label>Request Type(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Change</fullName>
                </value>
                <value>
                    <fullName>Billing Address Change</fullName>
                </value>
                <value>
                    <fullName>Credentialing Change</fullName>
                </value>
                <value>
                    <fullName>NPI Tax Id Change</fullName>
                </value>
                <value>
                    <fullName>Name Change Request</fullName>
                </value>
                <value>
                    <fullName>Other Provider Updates</fullName>
                </value>
                <value>
                    <fullName>Physical Address Change</fullName>
                </value>
                <value>
                    <fullName>Remove Provider from Group/Location</fullName>
                </value>
                <value>
                    <fullName>nm_network_scripting@bcbsnm.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OMNI Queue</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OMNI Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OMNI_User_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_User_Ids__c</fullName>
        <label>Selected User Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Users__c</fullName>
        <label>Selected Users</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week_Days__c</fullName>
        <label>Week Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OMNI User Group</label>
    <nameField>
        <displayFormat>OU-{0000}</displayFormat>
        <label>OMNI_User_Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMNI User Group</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Request_Types__mdt.object
<CustomObject>
    <fields>
        <fullName>CaseType_Name_Origin__c</fullName>
        <label>CaseType Name / Origin</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseType__c</fullName>
        <label>CaseType</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Ids__c</fullName>
        <label>Plan Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Request_Name__c</fullName>
        <label>Request Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Request Types</label>
    <pluralLabel>Request Types</pluralLabel>
</CustomObject>

src/classes/OMNIQueueManagementTest1.cls
@isTest
private class OMNIQueueManagementTest1 {
@TestSetup
    public static void insertTestData()
    {
    	GlobalSettings__c gs  =  new GlobalSettings__c();
        gs.name         =  'PFFileRecieved';
        gs.PFFileRecieved__c  =  false;
        gs.Record_Type_Names__c  =  'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
    }
    static testMethod void test_DemographicCase(){
        List<User>  userList  =  TestCaseUtil.createUser('Supervisor','Illinois Supervisor',3);
        insert userList;
        System.runAs(new User (Id=UserInfo.getUserId()))
        {
        	insertTestData();
        }
        Set<Id>   userId    =  new Set<Id>();
        userId.add(userList[0].Id);
        userId.add(userList[1].Id); 
        userId.add(userList[2].Id);
        List<User> usrListTemp        =  [Select Id,Name from User where Id IN:userId];
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption(usrListTemp[0].Id,usrListTemp[0].Name));
        options.add(new SelectOption(usrListTemp[1].Id,usrListTemp[1].Name));
        options.add(new SelectOption(usrListTemp[2].Id,usrListTemp[2].Name));
        
        System.runAs(new User(Id = UserInfo.getUserId())){
            
            OMNIQueueManagementCls cls = new OMNIQueueManagementCls();
            PageReference pageRef = Page.OMNIQueueManagementPage;
            Test.setCurrentPage(pageRef);
            cls.requestTypeList        =  TestContextMetaDataSupportCls.requestTypes('IL1');
            cls.selectedProcessors = options;
            cls.updateProcessors();
            cls.selectedCaseType='Demographics';
            cls.planId='IL1';
            cls.rowToDelete=1;
            cls.displayCaseReqtypes();
            cls.displayProcessors();
            cls.doSave();
            cls.deleteCurrentRow();
            cls.doDisplayQueuerecords();
            cls.refreshPage();
            cls.openPage();
            cls.omniQueuePrev = new OMNI_Queue__c();
            cls.omniQueue = new OMNI_Queue__c();
            cls.omniQueuePrev.request_Type_s__c = 'CRM;Email;';
            cls.omniQueue.request_Type_S__c = 'CRM;';
            cls.handleEditRule();
            cls.omniQueuePrev.request_Type_s__c='CRM;';
            cls.omniQueue.request_Type_s__c='CRM;';
            cls.omniqueuePrev.case_Type__c='Email';
            cls.omniQueue.case_Type__c='Demographics';
            cls.handleEditRule();
            cls.omniQueuePrev.request_Type_s__c='CRM;';
            cls.omniQueue.request_Type_s__c='CRM;';
            cls.omniqueuePrev.case_Type__c='Demographics';
            cls.omniQueue.case_Type__c='Email';
            cls.handleEditRule();
            cls.omniQueuePrev.request_Type_s__c='CRM;';
            cls.omniQueue.request_Type_s__c='CRM1;';
            cls.omniqueuePrev.case_Type__c='Demographics';
            cls.omniQueue.case_Type__c='Email';
            cls.handleEditRule(); 
            cls.omniQueuePrev.request_Type_s__c='CRM;';
            cls.omniQueue.request_Type_s__c='CRM;';
            cls.omniqueuePrev.case_Type__c='Demographics';
            cls.omniQueue.case_Type__c='Demographics';
            cls.handleEditRule();
            cls.omniQueuePrev.request_Type_s__c='CRM;';
            cls.omniQueue.request_Type_s__c='Mass Case;';
            cls.omniqueuePrev.case_Type__c='Email';
            cls.omniQueue.case_Type__c='Email';
            cls.handleEditRule(); 
            cls.omniQueuePrev.request_Type_s__c='CRM;';
            cls.omniQueue.request_Type_s__c='Mass Case;';
            cls.omniqueuePrev.case_Type__c='Demographics';
            cls.omniQueue.case_Type__c='Demographics';
            cls.handleEditRule();
            
            cls.updateLeftOptions(new Set<String>());
            OMNI_Queue__c newQueue = new OMNI_Queue__c();
            newQueue.name='Testing';
            newQueue.Case_Type__c='CRM';
            newqueue.Case_Type_Name_Origin__c='Roster;CRM';
            newQueue.Request_Type_s__c='Roster;CRM';
            insert newQueue;

            ApexPages.currentPage().getParameters().put('oId',newQueue.Id);
            cls = new OMNIQueueManagementCls();
            cls.caseTypeWithrequestMap = new Map<String,List<String>>();
            cls.caseTypeWithrequestMap.put('Mass Case',new String[]{'ILRoster','Roster'});
            cls.caseTypeWithrequestMap.put('CRM',new String[]{'Roster'});
            cls.displayCaseReqtypes();
        }
    }
    
    static testMethod void test_DoSave()
    {
        List<User>  userList  =  TestCaseUtil.createUser('Supervisor','Illinois Supervisor',3);
        insert userList;
		System.runAs(new User(Id=UserInfo.getUserId()))
		{
    		insertTestData();
		}
        Set<Id>   userId    =  new Set<Id>();
        userId.add(userList[0].Id);
        userId.add(userList[1].Id); 
        userId.add(userList[2].Id);
        List<User> usrListTemp        =  [Select Id,Name from User where Id IN:userId];
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption(usrListTemp[0].Id,usrListTemp[0].Name));
        options.add(new SelectOption(usrListTemp[1].Id,usrListTemp[1].Name));
        options.add(new SelectOption(usrListTemp[2].Id,usrListTemp[2].Name));
        
        List<RecordType> recType =[SELECT DeveloperName,Id,Name FROM RecordType WHERE Name = 'Email'];

        System.runAs(new User(Id = UserInfo.getUserId())){
            
            Test.startTest();
            OMNIQueueManagementCls cls  =  new OMNIQueueManagementCls();
            PageReference pageRef     =  Page.OMNIQueueManagementPage;
            Test.setCurrentPage(pageRef);
            cls.requestTypeList        =  TestContextMetaDataSupportCls.requestTypes('IL1');
            
            Map<String,List<String>>     caseTypeWithrequestMapTemp  =   new Map<String,List<String>>();
            Map<String,String> caseTypeAndOrigMap                =   new Map<String,String>();
            
            for( Request_Types__mdt requestType :  cls.requestTypeList  )
            {
                caseTypeAndOrigMap.put(requestType.Request_Name__c, requestType.CaseType_Name_Origin__c);
                String planIds   =   requestType.Plan_Ids__c;
                if(caseTypeWithrequestMapTemp.containsKey( requestType.CaseType__c))
                {
                    caseTypeWithrequestMapTemp.get(requestType.CaseType__c).add(requestType.Request_Name__c);
                }else{
                    List<String> reqList = new List<String>();
                    reqList.add(requestType.Request_Name__c);
                    caseTypeWithrequestMapTemp.put(requestType.CaseType__c, reqList);
                }       
            } 
            cls.caseTypeWithrequestMap  =  caseTypeWithrequestMapTemp;
            cls.selectedProcessors = options;
            cls.updateProcessors();
            cls.selectedCaseType    =  'Demographics';
            cls.isEditPage        =  false;
            cls.planId          =  'IL1';
            
            cls.selectedRequests.add(new SelectOption('Administrative Change','Administrative Change'));
            cls.omniQueueObj.Case_Type__c              =   'Demographics';
            cls.omniQueueObj.Request_Type_s__c         =   'NPI Tax Id Change; Administrative Change';
            cls.omniQueueObj.Plan_Id__c                =   'IL1';
            cls.omniQueueObj.Queue_Priority__c         =   '5';
            cls.omniQueueObj.Name            =  'kjfhdkjsafhkjsdah';
            
            OMNI_User_Group__c usrGrouprec1        =   new OMNI_User_Group__c();
            usrGrouprec1.Start_Date__c         =   date.today();
            usrGrouprec1.End_Date__c           =   Date.Today().addDays(15);
            usrGrouprec1.Plan_Id__c            =   'IL1';
            usrGrouprec1.Active__c             =   true;
            usrGrouprec1.Week_Days__c          =   'Monday; Tuesday; Wednesday; Thursday; Friday; Saturday; Sunday';
            usrGrouprec1.Selected_User_Ids__c  =   usrListTemp[0].Id;
            usrGrouprec1.Selected_Users__c     =   usrListTemp[0].Name;
            cls.omniUserGrpList.add(usrGrouprec1);
            cls.doSave();
            
            List<QueuesObject> qSobjectList   =  new List<QueuesObject>();
            QueuesObject  qSobject         =  new QueuesObject (SobjectType ='Case', QueueId=cls.g.id);
            qSobjectList.add(qSobject);
            QueuesObject  qSobject2       =  new QueuesObject (SobjectType ='OMNI_Queue__c', QueueId=cls.g.id);
            qSobjectList.add(qSobject2);     
            insert qSobjectList;  
            OMNI_Queue__c o = [select id,ownerid from OMNI_Queue__c where id = :cls.omniQueue.id];
            o.ownerid = cls.g.id;
            update o;
      
            OMNIQueueManagementCls cls2  =  new OMNIQueueManagementCls(); 
            cls2.requestTypeList        =  TestContextMetaDataSupportCls.requestTypes('IL1');
             Map<String,List<String>>     caseTypeWithrequestMapTemp1    =   new Map<String,List<String>>();
             Map<String,String> caseTypeAndOrigMap1                    =   new Map<String,String>();
            
            for( Request_Types__mdt requestType :  cls2.requestTypeList  )
            {
                caseTypeAndOrigMap1.put(requestType.Request_Name__c, requestType.CaseType_Name_Origin__c);
                String planIds   =   requestType.Plan_Ids__c;
                if(caseTypeWithrequestMapTemp1.containsKey( requestType.CaseType__c))
                {
                    caseTypeWithrequestMapTemp1.get(requestType.CaseType__c).add(requestType.Request_Name__c);
                }else{
                    List<String> reqList = new List<String>();
                    reqList.add(requestType.Request_Name__c);
                    caseTypeWithrequestMapTemp1.put(requestType.CaseType__c, reqList);
                }       
            } 
            cls2.caseTypeWithrequestMap  =  caseTypeWithrequestMapTemp1;
            
            PageReference pageRef2       =  Page.OMNIQueueManagementPage;
            Test.setCurrentPageReference(pageRef2); 
            System.currentPageReference().getParameters().put('oId', cls.omniQueue.Id);   

            cls2.selectedCaseType    =  'Demographics';
            cls2.openPage();
            cls2.isDeleteMode         = false;
            cls2.isEditPage        =  true;
           
            cls2.processorsWrap.clear();
            cls2.userList          = usrListTemp;
            cls2.displayProcessors();
            cls2.doDisplayQueuerecords();
            cls2.omniQueueObj.Request_Type_s__c         =   'Billing Address Change';
            cls2.doSave(); 
            Test.stopTest();
        }
    }
    static testMethod void test_EditAndDoSave(){
        List<User>  userList  =  TestCaseUtil.createUser('Supervisor','Illinois Supervisor',3);
        insert userList;
		System.runAs(new User(Id=UserInfo.getUserId()))
		{
    		insertTestData();
		}
        Set<Id>   userId    =  new Set<Id>();
        userId.add(userList[0].Id);
        userId.add(userList[1].Id); 
        userId.add(userList[2].Id);
        List<User> usrListTemp        =  [Select Id,Name from User where Id IN:userId];
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption(usrListTemp[0].Id,usrListTemp[0].Name));
        options.add(new SelectOption(usrListTemp[1].Id,usrListTemp[1].Name));
        options.add(new SelectOption(usrListTemp[2].Id,usrListTemp[2].Name));
        
        List<RecordType> recType =[SELECT DeveloperName,Id,Name FROM RecordType WHERE Name = 'Email'];

        System.runAs(new User(Id = UserInfo.getUserId())){
            
            OMNIQueueManagementCls cls  =  new OMNIQueueManagementCls();
            PageReference pageRef     =  Page.OMNIQueueManagementPage;
            Test.setCurrentPage(pageRef);
            cls.requestTypeList        =  TestContextMetaDataSupportCls.requestTypes('IL1');
            
            Map<String,List<String>>     caseTypeWithrequestMapTemp  =   new Map<String,List<String>>();
            Map<String,String> caseTypeAndOrigMap                =   new Map<String,String>();
            
            for( Request_Types__mdt requestType :  cls.requestTypeList  )
            {
                caseTypeAndOrigMap.put(requestType.Request_Name__c, requestType.CaseType_Name_Origin__c);
                String planIds   =   requestType.Plan_Ids__c;
                if(caseTypeWithrequestMapTemp.containsKey( requestType.CaseType__c))
                {
                    caseTypeWithrequestMapTemp.get(requestType.CaseType__c).add(requestType.Request_Name__c);
                }else{
                    List<String> reqList = new List<String>();
                    reqList.add(requestType.Request_Name__c);
                    caseTypeWithrequestMapTemp.put(requestType.CaseType__c, reqList);
                }       
            } 
            cls.caseTypeWithrequestMap  =  caseTypeWithrequestMapTemp;
            cls.selectedProcessors = options;
            cls.updateProcessors();
            cls.selectedCaseType    =  'Demographics';
            cls.isEditPage        =  false;
            cls.planId          =  'IL1';
            
            cls.selectedRequests.add(new SelectOption('Administrative Change','Administrative Change'));
            cls.omniQueueObj.Case_Type__c              =   'Demographics';
            cls.omniQueueObj.Request_Type_s__c         =   'NPI Tax Id Change; Administrative Change';
            cls.omniQueueObj.Plan_Id__c                =   'IL1';
            cls.omniQueueObj.Queue_Priority__c         =   '5';
            cls.omniQueueObj.Name            =  'kjfhdkjsafhkjsdah';
                     
            OMNI_User_Group__c usrGrouprec1        =   new OMNI_User_Group__c();
            usrGrouprec1.Start_Date__c         =   date.today();
            usrGrouprec1.End_Date__c           =   Date.Today().addDays(15);
            usrGrouprec1.Plan_Id__c            =   'IL1';
            usrGrouprec1.Active__c             =   true;
            usrGrouprec1.Week_Days__c          =   'Monday; Tuesday; Wednesday; Thursday; Friday; Saturday; Sunday';
            usrGrouprec1.Selected_User_Ids__c  =   usrListTemp[0].Id;
            usrGrouprec1.Selected_Users__c     =   usrListTemp[0].Name;
            cls.omniUserGrpList.add(usrGrouprec1);
            cls.doSave();
            cls.omniUserGrpList[0].Start_Date__c=Date.Today().addDays(16);
            cls.omniUserGrpList[0].End_Date__c=Date.Today().addDays(15);
            cls.doSave();
            cls.omniUserGrpList[0].start_Date__c=Date.Today();
            cls.omniUserGrpList[0].End_Date__c=Date.Today().addDays(15);            
            cls.omniUserGrpList[0].Selected_Users__c=NULL;
            cls.doSave();
            cls.omniUserGrpList[0].selected_Users__c=usrListTemp[0].Name;
            cls.omniUserGrpList[0].start_Date__c=Date.Today();
            cls.omniUserGrpList[0].End_Date__c=Date.Today().addDays(15);             
            cls.isEditPage=true;
            cls.dosave();
            
            List<QueuesObject> qSobjectList   =  new List<QueuesObject>();
            QueuesObject  qSobject         =  new QueuesObject (SobjectType ='Case', QueueId=cls.g.id);
            qSobjectList.add(qSobject);
            QueuesObject  qSobject2       =  new QueuesObject (SobjectType ='OMNI_Queue__c', QueueId=cls.g.id);
            qSobjectList.add(qSobject2);     
            insert qSobjectList;  
            OMNI_Queue__c o = [select id,ownerid from OMNI_Queue__c where id = :cls.omniQueue.id];
            o.ownerid = cls.g.id;
            update o;
            cls.selectedCaseType='Demographics';
            cls.isEditPage=true;
            OMNI_Queue__c newqueue = [Select Id From OMNI_Queue__c Limit 1];
            ApexPages.currentPage().getParameters().put('oId',newQueue.Id);
            cls = new OMNIQueueManagementCls();
            cls.displayCaseReqtypes();
        } 
    }
}