src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/OMNI_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Case_Type_Name_Origin__c</fullName>
        <label>CaseType Name / Origin</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demographics</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>Govt Cases</fullName>
                </value>
                <value>
                    <fullName>Network Change</fullName>
                </value>
                <value>
                    <fullName>Other Provider Updates</fullName>
                </value>
                <value>
                    <fullName>Web On-boarding - Contracting</fullName>
                </value>
                <value>
                    <fullName>Web On-boarding - Data Entry</fullName>
                </value>
                <value>
                    <fullName>Ancillary Networks</fullName>
                </value>
                <value>
                    <fullName>Balance Billing</fullName>
                </value>
                <value>
                    <fullName>Delegated Credentialing</fullName>
                </value>
                <value>
                    <fullName>Fee Schedule Requests</fullName>
                </value>
                <value>
                    <fullName>Gov Netops Provider Update</fullName>
                </value>
                <value>
                    <fullName>Gov Providers</fullName>
                </value>
                <value>
                    <fullName>HCS-X6100</fullName>
                </value>
                <value>
                    <fullName>HMO Networks</fullName>
                </value>
                <value>
                    <fullName>Internal PNC Inquiries</fullName>
                </value>
                <value>
                    <fullName>Netops Provider Update</fullName>
                </value>
                <value>
                    <fullName>Network Roster Submission</fullName>
                </value>
                <value>
                    <fullName>OK Network Management</fullName>
                </value>
                <value>
                    <fullName>PNC NetOps Inquiries</fullName>
                </value>
                <value>
                    <fullName>PPN CorpusChristi</fullName>
                </value>
                <value>
                    <fullName>PPN EIPaso</fullName>
                </value>
                <value>
                    <fullName>PPN Lubbock-Amerillo</fullName>
                </value>
                <value>
                    <fullName>Professional Provider Network Dept</fullName>
                </value>
                <value>
                    <fullName>Provider Inquiry</fullName>
                </value>
                <value>
                    <fullName>Provider Relation DFW</fullName>
                </value>
                <value>
                    <fullName>Provider Relations Houston</fullName>
                </value>
                <value>
                    <fullName>Provider Relations Midland</fullName>
                </value>
                <value>
                    <fullName>Provider Relations South Texas</fullName>
                </value>
                <value>
                    <fullName>Provider Relations IL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type_s__c</fullName>
        <label>Request Type(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Change</fullName>
                </value>
                <value>
                    <fullName>Billing Address Change</fullName>
                </value>
                <value>
                    <fullName>Credentialing Change</fullName>
                </value>
                <value>
                    <fullName>NPI Tax Id Change</fullName>
                </value>
                <value>
                    <fullName>Name Change Request</fullName>
                </value>
                <value>
                    <fullName>Other Provider Updates</fullName>
                </value>
                <value>
                    <fullName>Physical Address Change</fullName>
                </value>
                <value>
                    <fullName>Remove Provider from Group/Location</fullName>
                </value>
                <value>
                    <fullName>nm_network_scripting@bcbsnm.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OMNI Queue</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OMNI Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OMNI_User_Group__c.object
<CustomObject>
    <label>OMNI User Group</label>
    <nameField>
        <displayFormat>OU-{0000}</displayFormat>
        <label>OMNI_User_Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMNI User Group</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAddSobjectTypeToQueue.cls
@isTest
public class TestAddSobjectTypeToQueue 
{
	public static testmethod void testQueueable()
    {
        Group newGroup = new Group();
        newGroup.Name='Test Queue';
        newGroup.Type='Queue';
        insert newGroup;
        Test.startTest();
        GlobalSettings__c gs  =  new GlobalSettings__c();
        gs.name         =  'PFFileRecieved';
        gs.PFFileRecieved__c  =  false;
        gs.Record_Type_Names__c  =  'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
        insert gs;
        Case newCase = new Case();
        newCase.subject = 'Test';
        newCase.Status='New';
        newCase.Origin='Web';
        //newCase.Request_type__c=Case.sObjectType.Request_Type__c.getDescribe().getPicklistValues()[0].getLabel();
        newCase.RecordTypeId=[Select Id From RecordType where sObjectType='Case' and Name='CRM' Limit 1].Id;
        insert newCase;
        List<Case> listOfCase = new List<Case>();
        listOfCase.add(newCase);
        OMNI_Queue__c newQueue = new OMNI_Queue__c();
        newQueue.name='Testing';
        newQueue.Case_Type__c='CRM';
        newqueue.Case_Type_Name_Origin__c='Roster;CRM';
        newQueue.Request_Type_s__c='Roster;CRM';
        insert newQueue;
        List<Id> listOfIds = new List<Id>();
        listOfIds.add(Userinfo.getUserId());
        addSobjectTypeToQueue queueableMethod = new addSobjectTypeToQueue(listOfIds,newGroup.Id,newQueue.id,listOfCase);
        System.enqueueJob(queueableMethod);
        OMNICriteriaTable newTable = new OMNICriteriaTable();
        newTable.queue = new OMNI_Queue__c();
        newTable.userGroup = new OMNI_User_Group__c();
        Test.stopTest();
    }
}