src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PFFileRecieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PFFileRecieved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Names__c</fullName>
        <description>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</description>
        <inlineHelpText>This field values are utilized in Apex class  &apos;OMNIQueueRecaluclation&apos; to eliminate the Case record types while querying the records</inlineHelpText>
        <label>Record Type Names</label>
        <type>TextArea</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/OMNI_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type_s__c</fullName>
        <label>Request Type(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Change</fullName>
                </value>
                <value>
                    <fullName>Billing Address Change</fullName>
                </value>
                <value>
                    <fullName>Credentialing Change</fullName>
                </value>
                <value>
                    <fullName>NPI Tax Id Change</fullName>
                </value>
                <value>
                    <fullName>Name Change Request</fullName>
                </value>
                <value>
                    <fullName>Other Provider Updates</fullName>
                </value>
                <value>
                    <fullName>Physical Address Change</fullName>
                </value>
                <value>
                    <fullName>Remove Provider from Group/Location</fullName>
                </value>
                <value>
                    <fullName>nm_network_scripting@bcbsnm.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OMNI Queue</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OMNI Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OMNI_User_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>OMNI_Queue__c</referenceTo>
        <relationshipLabel>OMNI User Group</relationshipLabel>
        <relationshipName>User_Time_Table</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_User_Ids__c</fullName>
        <label>Selected User Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Users__c</fullName>
        <label>Selected Users</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week_Days__c</fullName>
        <label>Week Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OMNI User Group</label>
    <nameField>
        <displayFormat>OU-{0000}</displayFormat>
        <label>OMNI_User_Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMNI User Group</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OMNIUserRecalculationtest.cls
@isTest
private class OMNIUserRecalculationtest {

    static testMethod void test_userrecaluclation() {
    List<User>  userList    =   TestCaseUtil.createUser('Supervisor','Illinois Supervisor',1);
        insert userList;
       System.runAs(new User(Id = UserInfo.getUserId())){
        OMNI_Queue__c queueRec              =   new OMNI_Queue__c();
         queueRec.Case_Type__c              =   'Demographics';
         queueRec.Request_Type_s__c         =   'Credentialing Change; Name Change Request';
         queueRec.Plan_Id__c                =   'IL1';
         queueRec.Queue_Priority__c         =   '5';
         insert queueRec;
         
         OMNI_User_Group__c usrGrouprec     =   new OMNI_User_Group__c();
         usrGrouprec.Group__c               =   queueRec.Id;
         usrGrouprec.Start_Date__c          =   date.today();
         usrGrouprec.End_Date__c            =   date.today();
         usrGrouprec.Plan_Id__c             =   'IL1';
         usrGrouprec.Active__c              =   true;
         usrGrouprec.Week_Days__c           =   'Monday; Tuesday; Wednesday; Thursday; Friday; Saturday; Sunday';
         usrGrouprec.Selected_User_Ids__c   =   userList[0].Id;
         usrGrouprec.Selected_Users__c      =   userList[0].Name;
         insert usrGrouprec;
             
         OMNI_User_Group__c usrGrouprec1        =   new OMNI_User_Group__c();
         usrGrouprec1.Group__c              =   queueRec.Id;
         usrGrouprec1.Start_Date__c         =   date.today();
         usrGrouprec1.End_Date__c           =   Date.Today().addDays(15);
         usrGrouprec1.Plan_Id__c            =   'IL1';
         usrGrouprec1.Active__c             =   true;
         usrGrouprec1.Week_Days__c          =   'Monday; Tuesday; Wednesday; Thursday; Friday; Saturday; Sunday';
         usrGrouprec1.Selected_User_Ids__c  =   userList[0].Id;
         usrGrouprec1.Selected_Users__c     =   userList[0].Name;
         insert usrGrouprec1;
           GlobalSettings__c gs    =   new GlobalSettings__c();
           gs.name                 =   'PFFileRecieved';
           gs.PFFileRecieved__c    =   false;
           gs.Record_Type_Names__c =   'Master_Provider_Case_data;Provider_On_boarding;PDM;CRM';
           insert gs;        
           Test.startTest();
            OMNIUserRecalculation bt = new OMNIUserRecalculation();
            Database.executeBatch( bt );
            System.Schedule('OMNIUserreCalc', '0 00 3 * * ?', new OMNIUserRecalculationScheduler());
            Test.stopTest(); 
       }
    }
}