src/objects/MCC_Data_Object__c.object
<CustomObject>
    <description>Intermediate object for Mass Case Creation and Death File.</description>
    <fields>
        <fullName>File_Count__c</fullName>
        <description>This field will hold the count the no rows processed within the mass file uploads ( Tx Recruitment, Il Roaster , Mass case closure and mass Cred status update)</description>
        <label>File Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>MCC_Data_Object</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MCC_Case_Status__c</fullName>
        <label>Case Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Id__c</fullName>
        <label>File Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_File_Type__c</fullName>
        <label>File Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Load_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Load Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MCC_Plan_ID__c</fullName>
        <description>For all loads</description>
        <label>Plan ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCC_Request_Type__c</fullName>
        <label>Request Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed_for_reporting__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field used to validate whether success and report has been processed for this record or not</description>
        <label>Processed for reporting</label>
        <type>Checkbox</type>
    </fields>
    <label>Mass Case Creation Record</label>
    <nameField>
        <displayFormat>MCC-{0000}</displayFormat>
        <label>MCC Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Case Creation Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MCCProcessFlagUpdateBatch.cls
/**************************************************************************************************
Apex Class Name  : MCCProcessFlagUpdateBatch
Version          : 1.0  
Functionality    : This batch class is used for to update processed records 
Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Sreekanth Kalluru           10/10/2018               
*******************************************************************************************************/
global class MCCProcessFlagUpdateBatch implements Database.Batchable<sobject>
{
    Set<String> mccRecordNameSetNew        =   new Set<String>();

    public MCCProcessFlagUpdateBatch( Set<String> mccRecordNameSet )
    {
        mccRecordNameSetNew.addAll( mccRecordNameSet );
    }
    
    global Database.QueryLocator start( Database.BatchableContext BC ) 
    {
        return DataBase.getQueryLocator([ SELECT Id,Name,RecordType.Name,MCC_Load_Status__c,Processed_for_reporting__c,MCC_File_Type__c,
                                         MCC_Case_Id__r.Plan_Id__c,MCC_Case_Id__c,MCC_Request_Type__c,MCC_File_Id__c,MCC_Plan_Id__c,mcc_case_status__c,
                                         File_Count__c FROM MCC_Data_Object__c where Name IN : mccRecordNameSetNew] ); 
    }
    
    
    global void execute( Database.BatchableContext BC,List<MCC_Data_Object__c> mccList ) 
    {
        List<MCC_Data_Object__c> mccRecordsProcessedForreporting		=	new List<MCC_Data_Object__c>();
        
        if( !mccList.isEmpty() )
        {
            for( MCC_Data_Object__c networkMCcRecord : mccList  )
            {
                MCC_Data_Object__c tempMCCNetworkRec 			=	new MCC_Data_Object__c( Id = networkMCcRecord.Id );
                tempMCCNetworkRec.Processed_for_reporting__c	=	true;
                mccRecordsProcessedForreporting.add( tempMCCNetworkRec ); 
            }
        }
        if(!mccRecordsProcessedForreporting.isEmpty())
        {
            update mccRecordsProcessedForreporting;
        }
    }
    
    global void finish( Database.BatchableContext BC )
    {
    }
}