src/objects/Network__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <label>Network</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Network_OLD_DO_NOT_USE</label>
    <nameField>
        <displayFormat>NId{0}</displayFormat>
        <label>NId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Networks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blue Advantage HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Advantage PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Care Direct</fullName>
                </value>
                <value>
                    <fullName>Blue Choice Options</fullName>
                </value>
                <value>
                    <fullName>BlueChoice PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>BlueChoice PPO (BH)</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO Preferred</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO Preferred Ancillary</fullName>
                </value>
                <value>
                    <fullName>Blue Community HMO Dallas</fullName>
                </value>
                <value>
                    <fullName>Blue Community HMO Network</fullName>
                </value>
                <value>
                    <fullName>Blue Cross Community Family Health Plan</fullName>
                </value>
                <value>
                    <fullName>Blue Essentials</fullName>
                </value>
                <value>
                    <fullName>Blue Focus Care</fullName>
                </value>
                <value>
                    <fullName>Blue Focus POS</fullName>
                </value>
                <value>
                    <fullName>BlueLincs HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Options</fullName>
                </value>
                <value>
                    <fullName>Blue Precision HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Preferred</fullName>
                </value>
                <value>
                    <fullName>Blue Premier HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Select PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Traditional</fullName>
                </value>
                <value>
                    <fullName>Caring Program</fullName>
                </value>
                <value>
                    <fullName>CHIP (Medicaid)</fullName>
                </value>
                <value>
                    <fullName>DNOA</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible MMAI</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible Special Needs Plan</fullName>
                </value>
                <value>
                    <fullName>Exclusive Provider Network</fullName>
                </value>
                <value>
                    <fullName>Facility - Blue Choice Designated PPO</fullName>
                </value>
                <value>
                    <fullName>Facility Blue Choice Designated PPO Preferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <label>Network</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Name__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ADV</fullName>
                </value>
                <value>
                    <fullName>BAV</fullName>
                </value>
                <value>
                    <fullName>BCA</fullName>
                </value>
                <value>
                    <fullName>BCE</fullName>
                </value>
                <value>
                    <fullName>BCO</fullName>
                </value>
                <value>
                    <fullName>BCP</fullName>
                </value>
                <value>
                    <fullName>BCS</fullName>
                </value>
                <value>
                    <fullName>BDF</fullName>
                </value>
                <value>
                    <fullName>BDS</fullName>
                </value>
                <value>
                    <fullName>BFC</fullName>
                </value>
                <value>
                    <fullName>BHD</fullName>
                </value>
                <value>
                    <fullName>BLC</fullName>
                </value>
                <value>
                    <fullName>BVP</fullName>
                </value>
                <value>
                    <fullName>CAR</fullName>
                </value>
                <value>
                    <fullName>CHP</fullName>
                </value>
                <value>
                    <fullName>CND</fullName>
                </value>
                <value>
                    <fullName>CNN</fullName>
                </value>
                <value>
                    <fullName>DCC</fullName>
                </value>
                <value>
                    <fullName>DDC</fullName>
                </value>
                <value>
                    <fullName>DEB</fullName>
                </value>
                <value>
                    <fullName>DUE</fullName>
                </value>
                <value>
                    <fullName>EDF</fullName>
                </value>
                <value>
                    <fullName>EDS</fullName>
                </value>
                <value>
                    <fullName>EPN</fullName>
                </value>
                <value>
                    <fullName>EPP</fullName>
                </value>
                <value>
                    <fullName>FEA</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HGT</fullName>
                </value>
                <value>
                    <fullName>HME</fullName>
                </value>
                <value>
                    <fullName>HMH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProviderNetworkCls_Test.cls
@isTest
public class ProviderNetworkCls_Test
{
    public static testmethod void saveMethod()
    {
        PageReference pageRef = Page.ProviderNetworkPage; 
        pageRef.getParameters().put('planId', 'IL1');            
        pageRef.getParameters().put('mode', 'create');            
        System.test.setCurrentPage(pageRef);
        ApexPages.standardController newController = new ApexPages.standardController(new Provider_Networks__c());
        ProviderNetworkCls newClass = new ProviderNetworkCls(newController);
        newClass.providerNetwork.Name__c='Test';
        newClass.providerNetwork.Network__c='Testing';
        newClass.saveAction();
        
		newClass.providerNetwork = [Select Id From Provider_Networks__c Limit 1];
		newClass.providerNetwork.Name__c='Test';
        newClass.providerNetwork.Network__c='Testing';        
        update newClass.providerNetwork;
        pageRef = Page.ProviderNetworkPage; 
        pageRef.getParameters().put('planId', 'IL1');            
        pageRef.getParameters().put('networkId', newClass.providerNetwork.Id);            
        pageRef.getParameters().put('mode', 'edit');            
        System.test.setCurrentPage(pageRef);
        newController = new ApexPages.standardController(new Provider_Networks__c());
        newClass = new ProviderNetworkCls(newController);
        newClass.displayNetworkNames();
        newClass.networkName='Testing';
        newClass.displayNetworkNames();
        newClass.displayNetworks();
        newClass.saveAction();
        newClass.saveAndNewAction();
        newClass.backToCase();
    }
}