src/objects/Network__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <label>Network</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Network_OLD_DO_NOT_USE</label>
    <nameField>
        <displayFormat>NId{0}</displayFormat>
        <label>NId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Networks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Networks_With_Codes__mdt.object
<CustomObject>
    <fields>
        <fullName>Network_Code__c</fullName>
        <label>Network Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Network_Name__c</fullName>
        <label>Network Name</label>
        <length>160</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                    <default>true</default>
                    <label>IL1</label>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Networks &amp; Codes</label>
    <pluralLabel>Networks &amp; Codes</pluralLabel>
</CustomObject>

src/objects/Provider_Networks__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Network Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Network_Support_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comp_Grid_Code__c</fullName>
        <label>Comp Grid Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Designation_Code__c</fullName>
        <label>Designation Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blue Advantage HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Advantage PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Care Direct</fullName>
                </value>
                <value>
                    <fullName>Blue Choice Options</fullName>
                </value>
                <value>
                    <fullName>BlueChoice PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>BlueChoice PPO (BH)</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO Preferred</fullName>
                </value>
                <value>
                    <fullName>Blue Choice PPO Preferred Ancillary</fullName>
                </value>
                <value>
                    <fullName>Blue Community HMO Dallas</fullName>
                </value>
                <value>
                    <fullName>Blue Community HMO Network</fullName>
                </value>
                <value>
                    <fullName>Blue Cross Community Family Health Plan</fullName>
                </value>
                <value>
                    <fullName>Blue Essentials</fullName>
                </value>
                <value>
                    <fullName>Blue Focus Care</fullName>
                </value>
                <value>
                    <fullName>Blue Focus POS</fullName>
                </value>
                <value>
                    <fullName>BlueLincs HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Options</fullName>
                </value>
                <value>
                    <fullName>Blue Precision HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Preferred</fullName>
                </value>
                <value>
                    <fullName>Blue Premier HMO</fullName>
                </value>
                <value>
                    <fullName>Blue Select PPO</fullName>
                </value>
                <value>
                    <fullName>Blue Traditional</fullName>
                </value>
                <value>
                    <fullName>Caring Program</fullName>
                </value>
                <value>
                    <fullName>CHIP (Medicaid)</fullName>
                </value>
                <value>
                    <fullName>DNOA</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible MMAI</fullName>
                </value>
                <value>
                    <fullName>Dual Eligible Special Needs Plan</fullName>
                </value>
                <value>
                    <fullName>Exclusive Provider Network</fullName>
                </value>
                <value>
                    <fullName>Facility - Blue Choice Designated PPO</fullName>
                </value>
                <value>
                    <fullName>Facility Blue Choice Designated PPO Preferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Name__c</fullName>
        <label>Network Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <label>Network</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Name__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ADV</fullName>
                </value>
                <value>
                    <fullName>BAV</fullName>
                </value>
                <value>
                    <fullName>BCA</fullName>
                </value>
                <value>
                    <fullName>BCE</fullName>
                </value>
                <value>
                    <fullName>BCO</fullName>
                </value>
                <value>
                    <fullName>BCP</fullName>
                </value>
                <value>
                    <fullName>BCS</fullName>
                </value>
                <value>
                    <fullName>BDF</fullName>
                </value>
                <value>
                    <fullName>BDS</fullName>
                </value>
                <value>
                    <fullName>BFC</fullName>
                </value>
                <value>
                    <fullName>BHD</fullName>
                </value>
                <value>
                    <fullName>BLC</fullName>
                </value>
                <value>
                    <fullName>BVP</fullName>
                </value>
                <value>
                    <fullName>CAR</fullName>
                </value>
                <value>
                    <fullName>CHP</fullName>
                </value>
                <value>
                    <fullName>CND</fullName>
                </value>
                <value>
                    <fullName>CNN</fullName>
                </value>
                <value>
                    <fullName>DCC</fullName>
                </value>
                <value>
                    <fullName>DDC</fullName>
                </value>
                <value>
                    <fullName>DEB</fullName>
                </value>
                <value>
                    <fullName>DUE</fullName>
                </value>
                <value>
                    <fullName>EDF</fullName>
                </value>
                <value>
                    <fullName>EDS</fullName>
                </value>
                <value>
                    <fullName>EPN</fullName>
                </value>
                <value>
                    <fullName>EPP</fullName>
                </value>
                <value>
                    <fullName>FEA</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HGT</fullName>
                </value>
                <value>
                    <fullName>HME</fullName>
                </value>
                <value>
                    <fullName>HMH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Networks_Effective_Date__c</fullName>
        <label>Network Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Panel_code__c</fullName>
        <label>Panel code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepting</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Existing Patients Only</fullName>
                </value>
                <value>
                    <fullName>Existing &amp; Family only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roles_Code__c</fullName>
        <label>Role Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PCP</fullName>
                </value>
                <value>
                    <fullName>PSP</fullName>
                </value>
                <value>
                    <fullName>PCP/PSP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <recordTypes>
        <fullName>Network</fullName>
        <active>true</active>
        <label>Network</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProviderNetworkCls.cls
public class ProviderNetworkCls 
{

    public List<SelectOption> 			networks     			{ set; get; }
    public List<SelectOption> 			networkNames 			{ set; get; }
    public Provider_Networks__c 		providerNetwork         { get; set; } 
    public String						network					{ get; set; }
    public String						networkName				{ get; set; }
    
    private String		returnUrl	=	'';
	private String 		planId;
    Private Id 			caseId;
    private Id 			providerNetworkId;
    private String		pageMode;
    private Map<String,String> networkMap 		=	 new Map<String,String>();
    private Map<String,String> networkNameMap 	=	 new Map<String,String>();
    
    public ProviderNetworkCls(ApexPages.StandardController std)
    {
        networkNames		=	new List<SelectOption>();
        networks			=	new List<SelectOption>();
        providerNetwork		=	new Provider_Networks__c();
        network				=	'';
        networkName			=	'';
        
        
        planId 				=	ApexPages.currentPage().getParameters().get('planId');
        caseId 				=	ApexPages.currentPage().getParameters().get('caseId');
        pageMode			=	ApexPages.currentPage().getParameters().get('mode');
        if(pageMode == 'edit')
        {
            providerNetworkId	=	ApexPages.currentPage().getParameters().get('networkId');
        }

        if( String.isNotEmpty( planId ) && pageMode == 'create')
        {
            System.debug('planId===>>>'+planId);
            for ( Networks_With_Codes__mdt network : [ Select Network_Code__c,Network_Name__c,Plan_Id__c from Networks_With_Codes__mdt where Plan_Id__c =: planId] )
            {
                networkNames.add( new SelectOption( network.Network_Name__c , network.Network_Name__c));
                networks.add( new SelectOption( network.Network_Code__c , network.Network_Code__c));
                networkMap.put( network.Network_Code__c, network.Network_Name__c );
                NetworkNameMap.put( network.Network_Name__c, network.Network_Code__c );
            }
          providerNetwork.Plan_Id__c		=	planId;
          providerNetwork.Case_Number__c	=	caseId;
        }else If(String.isNotEmpty( planId ) 
                 && pageMode == 'edit'
                ){
            
            providerNetwork = [ Select Id,Plan_Id__c,Case_Number__c,Comp_Grid_Code__c,Designation_Code__c,Network__c,
                                Networks_Effective_Date__c,Name__c,Panel_code__c,Roles_Code__c from Provider_Networks__c 
                                where Id =:providerNetworkId ];
            networkNames.add( new SelectOption( providerNetwork.Name__c , providerNetwork.Name__c));
            networks.add( new SelectOption( providerNetwork.Network__c , providerNetwork.Network__c));
        }
    }
    
    public PageReference  saveAction()
    {            
         returnUrl =  saveNetwork(true);
        return ( new PageReference ( returnUrl ).setRedirect(true) );
    }
    
    public PageReference saveAndNewAction()
    {            
         returnUrl =  saveNetwork(false);
        System.debug('returnUrl=====>>>>'+returnUrl);
        return ( new PageReference ( returnUrl ).setRedirect(true) ); 
    }
    
    public String saveNetwork( Boolean isSave )
    {
        String retPageURl                				=   '';
        List<Provider_Networks__c> networksForInsert	=   new List<Provider_Networks__c>();
        Provider_Networks__c	networkRec;
        
        if( providerNetwork != null ) 
        {
            If(pageMode=='edit')
            {
               networkRec	=	new Provider_Networks__c(id=providerNetworkId); 
            }else{ networkRec	=	new Provider_Networks__c(); }
                
           
            networkRec.Case_Number__c		  	=	caseId;
            networkRec.Plan_Id__c				=	planId;
            networkRec.Name__c					=	networkName;
            networkRec.Network__c				=	network;
            networkRec.Comp_Grid_Code__c		=	providerNetwork.Comp_Grid_Code__c;
            networkRec.RecordTypeId				=   utils.GetRecordTypeId('Provider_Networks__c','Network');
            networkRec.Panel_code__c			=	providerNetwork.Panel_code__c;
            networkRec.Roles_Code__c		 	=	providerNetwork.Roles_Code__c;
            networkRec.Designation_Code__c		=	providerNetWork.Designation_Code__c;
            networkRec.Networks_Effective_Date__c	=	providerNetwork.Networks_Effective_Date__c;
            networksForInsert.add( networkRec );
        }
        
        if(!networksForInsert.isEmpty()){
            upsert networksForInsert;
        }
        
        if( isSave == true )
        {
           retPageURl   =   '/' + networksForInsert[0].Id;    
        }else{retPageURl = ApexPages.currentPage().getUrl();}
        
        return retPageURl;
    }
    
    public PageReference displayNetworkNames()
    {
        if( String.isNotEmpty( network ) && networkMap.containsKey(network))
        {
            networkNames.clear();
            networkNames.add( new SelectOption(networkMap.get(network),networkMap.get(network)));
        }
        System.debug('networkNames===>>>>'+networkNames);
        return null;
    }
    
    public PageReference displayNetworks()
    {
        System.debug('networkName===>>>>'+networkName);
        if( String.isNotEmpty( networkName ) && networkNameMap.containsKey( networkName ))
        {
            networks.clear();
            networks.add( new SelectOption( networkNameMap.get(networkName),networkNameMap.get(networkName) ));
        }
        System.debug('networks===>>>>'+networks);
        return null;
    }
    
    public PageReference backToCase()
    {
         return ( new PageReference ( '/'+caseId ).setRedirect(true) );
    }
    
}