src/objects/OMNI_Queue__c.object
<CustomObject>
    <label>OMNI Queue</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OMNI Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OMNI_User_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>OMNI_Queue__c</referenceTo>
        <relationshipLabel>OMNI User Group</relationshipLabel>
        <relationshipName>User_Time_Table</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Selected_User_Ids__c</fullName>
        <label>Selected User Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week_Days__c</fullName>
        <label>Week Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OMNI User Group</label>
    <nameField>
        <displayFormat>OU-{0000}</displayFormat>
        <label>OMNI_User_Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMNI User Group</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OMNIUserRecalculation.cls
/**************************************************************************************************
Apex Class Name  : OMNIUserRecalculation
Version          : 1.0  
Functionality    : Daily job to go through the users for OMNI rules available on OMNI_Queue__c object
and assign them to corresponding Queues
Modification Log :
-----------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Laxman Vattam              Sep 8, 2017            Code Logic For PPN-5272
* Sreekanth Kalluru(i364191) March 21, 2019         PPN - 29304
***************************************************************************************************/
//Batch Job for Processing the Records
global class OMNIUserRecalculation implements Database.Batchable<sobject>
{
        global String [] email          =       new String[] {'ProviderIntakeDev@bcbstx.com'};//Add here your email address here
        public Map<Id,User> userMap     =       new Map<Id,User>();
        
        public OMNIUserRecalculation()
        {
            for(User userRecord : [Select Id,isActive,Name from User where isActive=true])
            {
                userMap.put(userRecord.id, userRecord);
            }
        }
        
        //Start Method
        global Database.Querylocator start (Database.BatchableContext BC) 
       {
            return Database.getQueryLocator('select id,OwnerId from OMNI_Queue__c');
       }
    
    //Execute method
    global void execute (Database.BatchableContext BC, List<sobject> scope) 
    {
        list<OMNI_Queue__c> OMNIq   =   (list<OMNI_Queue__c>)scope;        
        list<OMNI_Queue__c> qlist   =   [select id,OwnerId from OMNI_Queue__c where Id in :OMNIq];  
        set<id> qids                =   new set<id>();
        
        for(OMNI_Queue__c o: qlist)
        {
            qids.add(o.ownerid);
        }  
        list<Group> queueIds        =   [select id from Group where id in :qids];
        /*set<Id> dids              =   new set<Id>();
        
        for(Group g: DeleteQueue)
        {
            dids.add(g.id);
        } */
        list<GroupMember> queueMembers  =   [select id from GroupMember where GroupId IN :queueIds]; 
        try{
            system.debug('About to be deleted: queueMembers:' + queueMembers);
            Delete queueMembers;  
        }catch(exception e){
            system.debug('Exception:' + e);
        }
        
        String[] splitvalue;
        List<OMNI_User_Group__c> OMNIg      =   new List<OMNI_User_Group__c>();
        Datetime GMTDate                    =   system.now();
        String strConvertedDate             =   GMTDate.format('yyyy-MM-dd','America/Chicago');
        String strConvertedDate2            =   GMTDate.format('yyyy-MM-dd HH:mm:ss','America/Chicago');
        Datetime dttm                       =   DateTIME.valueof(strConvertedDate2);
        Date dt                             =   Date.valueof(strConvertedDate);
        List<GroupMember> memToBeAdded      =   new List<GroupMember>();
        GroupMember tempmem                 =   new GroupMember();
        
        system.debug('OMNIq:' + OMNIq);
        for(OMNI_Queue__c q: OMNIq)
        {
            OMNIg       =   new list<OMNI_User_Group__c>();
            OMNIg       =   [Select id, Selected_User_Ids__c From OMNI_User_Group__c where  Group__c = :q.id and Active__c = true 
                             and Start_Date__c <= :dt and End_Date__c >= :dt and Week_Days__c includes (:dttm.format('EEEE'))]; 
            system.debug('q.id:' + q.id);
            system.debug('OMNIg:' + OMNIg);
            for(OMNI_User_Group__c g:OMNIg)
            {
                splitvalue      =   g.Selected_User_Ids__c.split(','); 
                system.debug('splitvalue:' + splitvalue);
                for(string s:splitvalue)
                {
                    id userId               =   (id)s;
                    if(userMap.containsKey( userId ) && userMap.get(userId).isActive )
                    {
                        System.debug(userId+'<<<===id===>>>'+s);
                        tempmem                 =   new GroupMember();
                        tempmem.UserOrGroupId   =   userId;
                        tempmem.GroupId         =   q.ownerid;
                        memToBeAdded.add( tempmem );   
                        system.debug('memToBeAdded:' + memToBeAdded);
                    }
                }
            }
        }
        try{
            system.debug('about to be inserted' + memToBeAdded);
            insert memToBeAdded;            
        } catch(exception e){
            system.debug('Exception:' + e);
        }
        
        
        
    }
    
    //Finish Method
    global void finish(Database.BatchableContext BC){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        //Below code will fetch the job Id
        AsyncApexJob a = [Select a.TotalJobItems, a.Status, a.NumberOfErrors, a.JobType, a.JobItemsProcessed, a.ExtendedStatus, a.CreatedById, a.CompletedDate From AsyncApexJob a WHERE id = :BC.getJobId()];//get the job Id
        System.debug('$$$ Jobid is'+BC.getJobId());
        
        //below code will send an email to User about the status
        mail.setToAddresses(email);
        mail.setReplyTo('laxman_rao_vattam@bcbsil.com');//Add here your email address
        mail.setSenderDisplayName('Apex Batch Processing Module');
        mail.setSubject('UAT : OMNI Batch Processing '+a.Status);
        mail.setPlainTextBody('The Batch Apex job processed  '+a.TotalJobItems+' batches with  '+a.NumberOfErrors+' failures '+'Job Item processed are '+a.JobItemsProcessed);
        Messaging.sendEmail(new Messaging.Singleemailmessage [] {mail});
    }
}