src/objects/Provider_Networks__c.object
<CustomObject>
    <fields>
        <fullName>Network_Code_Name_Detail__c</fullName>
        <label>Network Code/Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Network_Load_Plan_Id__c</fullName>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestProvNetworkLoadController.cls
@isTest
public class TestProvNetworkLoadController {
    
    @testSetup static void setup() {
        Provider_Networks__c p = new Provider_Networks__c();
        p.Network_Load_Plan_Id__c = 'IL1';
        p.Network_Code_Name_Detail__c = 'ADV - Blue Advantage HMO';
        insert p;
    }
    
    static testMethod void testProviderNetworkLoadEditPageController() {
        
        Provider_Networks__c testProviderDetail = [SELECT Id FROM Provider_Networks__c LIMIT 1];
        
        Provider_Networks__c pn = new Provider_Networks__c();
        PageReference pageRef = Page.ProviderNetworkLoadEditPage;
        pageRef.getParameters().put('Id', testProviderDetail.id );
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc 					= new ApexPages.StandardController(pn);
        ProviderNetworkLoadEditPageController controller 	= new ProviderNetworkLoadEditPageController(sc);
        
        Test.startTest();
        
        	controller.save();
        
        	controller.cancel();
        
        Test.stopTest();
    }

}