src/objects/Provider_Networks__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Network Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Network_Support_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comp_Grid_Code__c</fullName>
        <label>Comp Grid Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contracting_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contracting Case</description>
        <label>Contracting Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Provider_Networks_Contracting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Designation_Code__c</fullName>
        <label>Designation Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Network_Code_Name_Detail__c</fullName>
        <label>Network Code/Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Network_Code_Name__c</fullName>
        <label>Network Code/Name</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Network_Load_Plan_Id__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PAR - Blue Traditional</fullName>
                </value>
                <value>
                    <fullName>PPO - Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>EPP - Blue Preferred</fullName>
                </value>
                <value>
                    <fullName>OPA - Blue Select PPO</fullName>
                </value>
                <value>
                    <fullName>SPN - Plan 65 Select</fullName>
                </value>
                <value>
                    <fullName>CAR - Caring Program</fullName>
                </value>
                <value>
                    <fullName>HMO - BlueLincs HMO</fullName>
                </value>
                <value>
                    <fullName>BVP - Blue Advantage PPO</fullName>
                </value>
                <value>
                    <fullName>ADV - Blue Advantage HMO</fullName>
                </value>
                <value>
                    <fullName>BAV - Blue Precision HMO</fullName>
                </value>
                <value>
                    <fullName>BAV - Blue Advantage HMO</fullName>
                </value>
                <value>
                    <fullName>BCA - BlueChoice PPO</fullName>
                </value>
                <value>
                    <fullName>BCE - Blue Choice PPO Preferred</fullName>
                </value>
                <value>
                    <fullName>BCO - Blue Choice Options</fullName>
                </value>
                <value>
                    <fullName>BCP - BlueChoice PPO (BH)</fullName>
                </value>
                <value>
                    <fullName>BCS - Professional Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>BDF - Blue Choice PPO Preferred Ancillary</fullName>
                </value>
                <value>
                    <fullName>BDS - Professional Designated Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>BFC - Blue Focus Care</fullName>
                </value>
                <value>
                    <fullName>BHD - Blue Care Direct</fullName>
                </value>
                <value>
                    <fullName>BLC - Blue Focus POS</fullName>
                </value>
                <value>
                    <fullName>CHP - CHIP (Medicaid)</fullName>
                </value>
                <value>
                    <fullName>CND - Blue Community HMO Dallas</fullName>
                </value>
                <value>
                    <fullName>CNN - Blue Community HMO Network</fullName>
                </value>
                <value>
                    <fullName>DCC - Facility - Blue Choice PPO</fullName>
                </value>
                <value>
                    <fullName>DDC - Facility - Blue Choice Designated PPO</fullName>
                </value>
                <value>
                    <fullName>DEB - DNOA</fullName>
                </value>
                <value>
                    <fullName>DUE - Dual Eligible MMAI</fullName>
                </value>
                <value>
                    <fullName>EDF - Facility Blue Choice Designated PPO Preferred</fullName>
                </value>
                <value>
                    <fullName>EDS - Professional Designated Blue Choice PPO Preferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Load_Plan_Id__c</fullName>
        <label>Plan Id</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL1</fullName>
                </value>
                <value>
                    <fullName>MT1</fullName>
                </value>
                <value>
                    <fullName>NM1</fullName>
                </value>
                <value>
                    <fullName>OK1</fullName>
                </value>
                <value>
                    <fullName>TX1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Networks_Effective_Date__c</fullName>
        <label>Network Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PFIN_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PFIN Case</description>
        <label>PFIN Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Provider Details</relationshipLabel>
        <relationshipName>Provider_Networks_PFIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PFIN_onBoarding__c</fullName>
        <label>PFIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Panel_code__c</fullName>
        <label>Panel code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepting</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Existing Patients Only</fullName>
                </value>
                <value>
                    <fullName>Existing &amp; Family only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prov_ID__c</fullName>
        <description>Prov ID</description>
        <label>Prov ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderName__c</fullName>
        <label>Provider Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roles_Code__c</fullName>
        <label>Role Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PCP</fullName>
                </value>
                <value>
                    <fullName>PSP</fullName>
                </value>
                <value>
                    <fullName>PCP/PSP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Details</label>
    <nameField>
        <displayFormat>PN-{0}</displayFormat>
        <label>Provider Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Details</pluralLabel>
    <recordTypes>
        <fullName>Network</fullName>
        <active>true</active>
        <label>Network</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProviderNetworkLoadEditPageController.cls
/*
 * This controller is used with ProviderNetworkLoadEditPage.vfp
 * which is a custom edit page on the Network Load page layout
 * in the provider details related list
 * 10/16/2018
*/ 
public class ProviderNetworkLoadEditPageController {
    
    public Provider_Networks__c provNetObj      {get; set;}
    public String str ='';
    String providerNetworkId = '';
    
    public ProviderNetworkLoadEditPageController(ApexPages.StandardController controller) {
        
        providerNetworkId = ApexPages.currentPage().getParameters().get('Id');
        
        provNetObj = new Provider_Networks__c();
        
        provNetObj = [SELECT Id, Name, Case_Number__c, Plan_Id__c,PFIN_Case__c, ProviderName__c, Contracting_Case__c, Network_Code_Name__c, Prov_ID__c, PFIN_onBoarding__c, Network_Load_Plan_Id__c, Network_Code_Name_Detail__c, Networks_Effective_Date__c, Designation_Code__c, Comp_Grid_Code__c, Panel_code__c, Roles_Code__c
                     FROM Provider_Networks__c WHERE Id= :providerNetworkId LIMIT 1];
        
        provNetObj.Plan_Id__c = provNetObj.Network_Load_Plan_Id__c;          
        
        //provNetObj.Network_Code_Name_Detail__c = provNetObj.Network_Code_Name__c ;
        
       
    }
    
    public PageReference save() {
        
            if(provNetObj.Network_Code_Name__c != NULL){                
                    for(String s : provNetObj.Network_Code_Name__c.split(';')){
                        str = str != NULL ? str + '\r\n' + s: s;
                    }
                }
        provNetObj.Network_Code_Name_Detail__c = str;
        
        update provNetObj;
        
        return (new PageReference ( '/' + providerNetworkId ).setRedirect(true) );
    }
    
    public PageReference cancel() {
        
        return (new PageReference ( '/' + providerNetworkId ).setRedirect(true) );
    }
    
}