src/objects/SFHealthTechIssueLog__c.object
<CustomObject>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Role</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ImpactedAreas__c</fullName>
        <label>Impacted Areas</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Apttus</fullName>
                </value>
                <value>
                    <fullName>Availity PDM</fullName>
                </value>
                <value>
                    <fullName>Email to case</fullName>
                </value>
                <value>
                    <fullName>eVips/Vistar</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Manual ADC/CRM</fullName>
                </value>
                <value>
                    <fullName>Manual On boarding</fullName>
                </value>
                <value>
                    <fullName>Mass Case closure</fullName>
                </value>
                <value>
                    <fullName>Mass Credentialing update</fullName>
                </value>
                <value>
                    <fullName>Mass CRM Case creation</fullName>
                </value>
                <value>
                    <fullName>Mass IL Roster</fullName>
                </value>
                <value>
                    <fullName>Provider Account Data</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
                <value>
                    <fullName>RightFax</fullName>
                </value>
                <value>
                    <fullName>UCR</fullName>
                </value>
                <value>
                    <fullName>Voicemail</fullName>
                </value>
                <value>
                    <fullName>Web Demographic case</fullName>
                </value>
                <value>
                    <fullName>Web On boarding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IssueSummary__c</fullName>
        <label>Issue Summary</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IssueType__c</fullName>
        <label>Issue Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Data Errors</fullName>
                </value>
                <value>
                    <fullName>Defect</fullName>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Outage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JiraURL__c</fullName>
        <label>Jira URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ReportedState__c</fullName>
        <defaultValue>IF(CONTAINS($UserRole.Name, &quot;Illinois&quot;) || $UserRole.Name = &quot;Provider Data Rep- IL&quot; , &quot;Illinois&quot;, 
			IF(CONTAINS($UserRole.Name, &quot;Montana&quot;) || $UserRole.Name = &quot;Provider Data Rep- MT&quot; , &quot;Montana&quot;, 
			IF(CONTAINS($UserRole.Name, &quot;New Mexico&quot;) || $UserRole.Name = &quot;Provider Data Rep- NM&quot; , &quot;New Mexico&quot;, 
			IF(CONTAINS($UserRole.Name, &quot;Oklahoma&quot;) || $UserRole.Name = &quot;Provider Data Rep- OK&quot; , &quot;Oklahoma&quot;, 
			IF(CONTAINS($UserRole.Name, &quot;Texas&quot;) || $UserRole.Name = &quot;Provider Data Rep- TX&quot; , &quot;Texas&quot;, 
			&quot;&quot;)))))</defaultValue>
        <label>Reported State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HCSC_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SF Health Tech Issue Log</label>
    <nameField>
        <displayFormat>IS-{00000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF Health Tech Issue Logs</pluralLabel>
    <recordTypes>
        <fullName>SFHealthTechIssueLog</fullName>
        <active>true</active>
        <label>SF Health Tech Issue Log</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFHealthTechIssueLogHistory__c.object
<CustomObject>
    <description>Contains the history for SF Health Tech Issue Logs&apos; Issue Summaries</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewValue__c</fullName>
        <description>Contains the new value for Issue Summary</description>
        <label>New Value</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OriginalValue__c</fullName>
        <description>Contains the old value for the Issue Summary.</description>
        <label>Original Value</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SFHealthTechIssueLog__c</fullName>
        <label>SF Health Tech Issue Log</label>
        <referenceTo>SFHealthTechIssueLog__c</referenceTo>
        <relationshipLabel>SF Health Tech Issue Log History</relationshipLabel>
        <relationshipName>SFHealthTechIssueLogHistory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SF_Health_Tech_Issue_Log_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SF Health Tech Issue Log History</label>
    <nameField>
        <label>SF Health Tech Issue Log History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SF Health Tech Issue Log History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/HCSC_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>New Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Oklahoma</fullName>
    </customValue>
    <customValue>
        <fullName>Texas</fullName>
    </customValue>
    <description>The states covered by HCSC</description>
    <masterLabel>HCSC States</masterLabel>
</GlobalValueSet>

src/classes/SFHealthTechIssueLogTriggerHandler.cls
/**
* Handles trigger logic for SFHealthTechIssueLog__c.
* <p /><p />
* @author Josh McGhee
*/
public with sharing class SFHealthTechIssueLogTriggerHandler {
    
    /**
	* Method is used to handle the Before Insert event on SFHealthTechIssueLog Trigger.
	* Finds the ID for the SFHealthTechIssueLog Queue and assigns ownership of the record 
	* to that queue.
	*
	* @param lstInsertedLog indicates the Trigger.New list from the trigger
	*/
    public static void beforeInsert(List<SFHealthTechIssueLog__c> lstInsertedLog) {

        Id idQueue = [SELECT DeveloperName,Id,Name,Type FROM Group WHERE 
                                 Type = 'Queue' and DeveloperName = 'SFHealthTechIssueLog' LIMIT 1].Id;
     
        for (SFHealthTechIssueLog__c objNewLog : lstInsertedLog) {
            objNewLog.OwnerId = idQueue;
        }
    }    

    /**
	* Method is used to handle the Before Update event on SFHealthTechIssueLog Trigger.
	* Creates new SFHealthTechIssueLogHistory records for each update to the Issue 
	* Summary field, and prevents changes to fields without proper permissions.
	*
	* @param lstUpdatedLog and mapTrigger indicate the Trigger.New list and Trigger.oldMap map
	* from the trigger, respectively.
	*/
    public static void beforeUpdate(List<SFHealthTechIssueLog__c> lstUpdatedLog, Map<Id, SFHealthTechIssueLog__c> mapTrigger) {
        
        String strRecordTypeDeveloperName;
        String strProfileName = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1].Name;
        String strPermissionError = 'You do not have permission to change this field.';
        List<SFHealthTechIssueLogHistory__c> lstHistoryToInsert = new List<SFHealthTechIssueLogHistory__c>();
        Map<ID, Schema.RecordTypeInfo> mapRecordType = Schema.SObjectType.SFHealthTechIssueLog__c.getRecordTypeInfosById();
        
        //Loops through the list of updated Issue Logs passed to the method.
        for (SFHealthTechIssueLog__c objNewLog : lstUpdatedLog) {
            
            //Access the "old" record by its ID in mapTrigger.
            SFHealthTechIssueLog__c objOldLog = mapTrigger.get(objNewLog.Id);
            
            //Gets the Record Type Name of the current Issue Log. 
            strRecordTypeDeveloperName = mapRecordType.get(objNewLog.RecordTypeId).getDeveloperName();
            
            //Checks that the Record Type Name is correct and that the old record exists.
            if(strRecordTypeDeveloperName == 'SFHealthTechIssueLog' && objOldLog != null) {
                
                //Only runs the following block of code if the user is neither SysAdmin nor Integration.
                if (strProfileName != 'System Administrator' && strProfileName != 'Integration') {
                    
                    //Checks whether the user attempted to change any fields for which they lack permissions.
                    if(objOldLog.IssueType__c != objNewLog.IssueType__c) {
                        objNewLog.IssueType__c.addError(strPermissionError);
                    }
                    if(objOldLog.OwnerId != objNewLog.OwnerId) {
                        objNewLog.OwnerId.addError(strPermissionError);
                    }
                    if(objOldLog.ReportedState__c != objNewLog.ReportedState__c) {
                        objNewLog.ReportedState__c.addError(strPermissionError);
                    }
                    if(objOldLog.ImpactedAreas__c != objNewLog.ImpactedAreas__c) {
                        objNewLog.ImpactedAreas__c.addError(strPermissionError);
                    }
                    if(objOldLog.Status__c != objNewLog.Status__c) {
                        objNewLog.Status__c.addError(strPermissionError);
                    }
                    if(objOldLog.JiraURL__c != objNewLog.JiraURL__c) {
                        objNewLog.JiraURL__c.addError(strPermissionError);
                    }
                    if(objOldLog.RecordTypeId != objNewLog.RecordTypeId) {
                        objNewLog.RecordTypeId.addError(strPermissionError);
                    }
                    if(objOldLog.Impact__c != objNewLog.Impact__c) {
                        objNewLog.Impact__c.addError(strPermissionError);
                    }
                }
                
                //If the new Issue Summary contents do not match the old contents, a history is created
                if(objOldLog.IssueSummary__c != objNewLog.IssueSummary__c){
                    SFHealthTechIssueLogHistory__c objHistory = new SFHealthTechIssueLogHistory__c();
                    
                    objHistory.Name = objNewLog.Name;
                    objHistory.Date__c = System.now();
                    objHistory.Field__c = 'Issue Summary';
                    objHistory.User__c = UserInfo.getUserId();
                    objHistory.OriginalValue__c = objOldLog.IssueSummary__c;
                    objHistory.NewValue__c = objNewLog.IssueSummary__c;
                    objHistory.SFHealthTechIssueLog__c = objNewLog.Id;
                    
                    lstHistoryToInsert.add(objHistory);
                }
            }
        }
        
        //Inserts SF Health Tech Issue Log History object if available.
        if(!lstHistoryToInsert.isEmpty()) {
            insert lstHistoryToInsert;
        }
    }
}