src/objects/SFHealthTechIssueLog__c.object
<CustomObject>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Role</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ImpactedAreas__c</fullName>
        <label>Impacted Areas</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Apttus</fullName>
                </value>
                <value>
                    <fullName>Availity PDM</fullName>
                </value>
                <value>
                    <fullName>Email to case</fullName>
                </value>
                <value>
                    <fullName>eVips/Vistar</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Manual ADC/CRM</fullName>
                </value>
                <value>
                    <fullName>Manual On boarding</fullName>
                </value>
                <value>
                    <fullName>Mass Case closure</fullName>
                </value>
                <value>
                    <fullName>Mass Credentialing update</fullName>
                </value>
                <value>
                    <fullName>Mass CRM Case creation</fullName>
                </value>
                <value>
                    <fullName>Mass IL Roster</fullName>
                </value>
                <value>
                    <fullName>Provider Account Data</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
                <value>
                    <fullName>RightFax</fullName>
                </value>
                <value>
                    <fullName>UCR</fullName>
                </value>
                <value>
                    <fullName>Voicemail</fullName>
                </value>
                <value>
                    <fullName>Web Demographic case</fullName>
                </value>
                <value>
                    <fullName>Web On boarding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IssueSummary__c</fullName>
        <label>Issue Summary</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IssueType__c</fullName>
        <label>Issue Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Data Errors</fullName>
                </value>
                <value>
                    <fullName>Defect</fullName>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Outage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JiraURL__c</fullName>
        <label>Jira URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ReportedState__c</fullName>
        <defaultValue>IF(CONTAINS($UserRole.Name, &quot;Illinois&quot;) || $UserRole.Name = &quot;Provider Data Rep- IL&quot; , &quot;Illinois&quot;, 
			IF(CONTAINS($UserRole.Name, &quot;Montana&quot;) || $UserRole.Name = &quot;Provider Data Rep- MT&quot; , &quot;Montana&quot;, 
			IF(CONTAINS($UserRole.Name, &quot;New Mexico&quot;) || $UserRole.Name = &quot;Provider Data Rep- NM&quot; , &quot;New Mexico&quot;, 
			IF(CONTAINS($UserRole.Name, &quot;Oklahoma&quot;) || $UserRole.Name = &quot;Provider Data Rep- OK&quot; , &quot;Oklahoma&quot;, 
			IF(CONTAINS($UserRole.Name, &quot;Texas&quot;) || $UserRole.Name = &quot;Provider Data Rep- TX&quot; , &quot;Texas&quot;, 
			&quot;&quot;)))))</defaultValue>
        <label>Reported State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HCSC_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SF Health Tech Issue Log</label>
    <nameField>
        <displayFormat>IS-{00000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF Health Tech Issue Logs</pluralLabel>
    <recordTypes>
        <fullName>SFHealthTechIssueLog</fullName>
        <active>true</active>
        <label>SF Health Tech Issue Log</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFHealthTechIssueLogHistory__c.object
<CustomObject>
    <description>Contains the history for SF Health Tech Issue Logs&apos; Issue Summaries</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewValue__c</fullName>
        <description>Contains the new value for Issue Summary</description>
        <label>New Value</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OriginalValue__c</fullName>
        <description>Contains the old value for the Issue Summary.</description>
        <label>Original Value</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SFHealthTechIssueLog__c</fullName>
        <label>SF Health Tech Issue Log</label>
        <referenceTo>SFHealthTechIssueLog__c</referenceTo>
        <relationshipLabel>SF Health Tech Issue Log History</relationshipLabel>
        <relationshipName>SFHealthTechIssueLogHistory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SF_Health_Tech_Issue_Log_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SF Health Tech Issue Log History</label>
    <nameField>
        <label>SF Health Tech Issue Log History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SF Health Tech Issue Log History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/HCSC_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>New Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Oklahoma</fullName>
    </customValue>
    <customValue>
        <fullName>Texas</fullName>
    </customValue>
    <description>The states covered by HCSC</description>
    <masterLabel>HCSC States</masterLabel>
</GlobalValueSet>

src/classes/SFHealthTechIssueLogTriggerTest.cls
/**
* Tests the trigger and trigger handler for SFHealthTechIssueLog__c.
* <p /><p />
* @author Josh McGhee
*/
@isTest(SeeAllData = false)
private class SFHealthTechIssueLogTriggerTest {
    
    /**
	* Method is used to test the Before Insert and Before Update events on 
	* SFHealthTechIssueLog Trigger. Creates new SFHealthTechIssueLog record 
	* for insertion, then changes the fields and user for the update attempt.
	* Creates SFHealthTechIssueLogHistory record for update.
	*/
    @isTest
    static void testSFHealthTechIssueLogTrigger() {
        
        Id idRecordType = Schema.SObjectType.SFHealthTechIssueLog__c.getRecordTypeInfosByDeveloperName().get('SFHealthTechIssueLog').getRecordTypeId(); 
        PermissionSet objPs = [SELECT Id FROM PermissionSet WHERE Name = 'SFHealthTechIssueLogPermission' LIMIT 1];
        SFHealthTechIssueLog__c objSfIssueLogRecord = new SFHealthTechIssueLog__c();
        SFHealthTechIssueLogHistory__c objHistoryTest = new SFHealthTechIssueLogHistory__c();
        List<User> lstIllinoisUser = TestCaseUtil.createUser('Supervisor', 'Illinois Supervisor', 2);
        
        //Creates two users and assigns the SFHealthTechIssueLogPermission set to them.
        insert lstIllinoisUser;
        insert new PermissionSetAssignment(AssigneeId = lstIllinoisUser[0].id, PermissionSetId = objPs.Id);
        
        //Runs test as the first of the two users.
        
            Test.startTest();
            System.runAs(lstIllinoisUser[0]){ 
            	//Fills all the fields that have permission checks, except OwnerId,
            	//which is filled by the handler method automatically. 
            	objSfIssueLogRecord.IssueType__c = 'Defect';
            	objSfIssueLogRecord.ReportedState__c = 'Illinois';
            	objSfIssueLogRecord.ImpactedAreas__c = 'Apttus';
            	objSfIssueLogRecord.Status__c = 'New';
            	objSfIssueLogRecord.JiraURL__c = 'https://www.google.com';
            	objSfIssueLogRecord.Impact__c = 'Role';
            	objSfIssueLogRecord.IssueSummary__c = 'Old';
            	objSfIssueLogRecord.RecordTypeId = idRecordType;
            
            	//Inserts the new record.
            	insert objSfIssueLogRecord;
            
            	//Attempts to change all the fields with permission checks.
            	objSfIssueLogRecord.IssueType__c = 'Data Errors';
            	objSfIssueLogRecord.OwnerId = lstIllinoisUser[1].Id;
            	objSfIssueLogRecord.ReportedState__c = 'New Mexico';
            	objSfIssueLogRecord.ImpactedAreas__c = 'Integration';
            	objSfIssueLogRecord.Status__c = 'In Progress';
            	objSfIssueLogRecord.JiraURL__c = 'https://google.com';
            	objSfIssueLogRecord.Impact__c = 'Value';
            	objSfIssueLogRecord.IssueSummary__c = 'New';
            	objSfIssueLogRecord.RecordTypeId = null;
            	
            	//Fills out a history record for the Issue Summary field change.
            	objHistoryTest.Name = 'IS-00001';
            	objHistoryTest.Date__c = System.now();
            	objHistoryTest.Field__c = 'Issue Summary';
            	objHistoryTest.User__c = lstIllinoisUser[1].id;
            	objHistoryTest.OriginalValue__c = 'Old';
            	objHistoryTest.NewValue__c = 'New';
            	objHistoryTest.SFHealthTechIssueLog__c = objSfIssueLogRecord.Id;
            
            //Attempts to update the Issue Log record, but should fail and return an
            //error message.
            try {
                update objSfIssueLogRecord;
            } catch (DmlException e) {
                System.assert(e.getMessage() != null);
            } catch (Exception e) {
                System.assert(e.getMessage() != null);
            }
            //Inserts the history record.
            insert objHistoryTest;}
            Test.stopTest();
        
    }
}